### ISSUE TITLE
Add 'addaccount' functionality to m_hostchange, similar to 'addnick'

### ISSUE THREAD

**Issue by shaynejellesma** [inspircd/inspircd#1001]
Add a 'addaccount' functionality to m_hostchange, similar to how 'addnick' works. If the account hasn't been identified, revert back to using 'addnick'. Use case is users connecting via a tor relay using a .onion address. I require tor clients using my relay to authenticate via SASL before they are allowed to connect. Would be nice to add the account they have identified to to their hostname to distinguish them, similar to how freenode does it. 'addnick' does work, but it uses the nick they connect with and not necassarily the account they have identified to.

**Comment by SaberUK** [comment]
:+1:

**Comment by GLolol** [comment]
:+1

**Comment by Sheogorath-SI** [comment]
shoudln't https://github.com/inspircd/inspircd-extras/blob/master/2.0/m_accounthost.cpp fix that?

**Comment by GLolol** [comment]
@Sheogorath-SI From what I read, m_accounthost applies it globally, while m_hostchange only does it for certain, defined IP blocks (which is what I'm looking for).
