### ISSUE TITLE
[2.0] mssql module has not worked since SQLv2 was removed five years ago.

### ISSUE THREAD

**Issue by SaberUK** [inspircd/inspircd#1006]
It was apparently never converted to SQLv3 in March 2010 when SQLv2 was removed. It also appears to be written against an old version of FreeTDS as neither the version in APT on Ubuntu 14.04 or in Homebrew on OSX have a `tds.h` header.

This means that **every single version of 2.0** has shipped with an uncompilable extras module. How the hell have we not had some kind of report about this in almost five years? I'm guessing nobody uses InspIRCd with Microsoft's SQL Server? Posting this so we can get feedback from Windows users.

---

FWIW I am in favour of killing the module on insp20 and migrating entirely to use ODBC for SQL in master. That way we won't have to maintain code for something which is already a solved problem.

**Comment by kaniini** [comment]
unixodbc for example is kind of unpleasant to code against, are you sure this is a good plan for all modules?

**Comment by SaberUK** [comment]
@kaniini I was thinking we could use a C++ wrapper around it like we do with LDAP in master.

**Comment by attilamolnar** [comment]
Removed from master. There's no harm done with it being in 2.0, it might even be in use with a third party module forward ported from an older branch when m_mssql was working.

**Comment by SaberUK** [comment]
>There's no harm done with it being in 2.0

Other than confusing people who expect us to ship code that works and then wonder why it doesn't even build?

>it might even be in use with a third party module forward ported from an older branch where m_mssql was working.

It won't be because m_mssql doesn't even compile under any modern version of InspIRCd *or* FreeTDS.
