### ISSUE TITLE
server version

### ISSUE THREAD

**Issue by layer3** [inspircd/inspircd#1010]
what file i need to edit if i want hide server version!

thx

**Comment by Heufneutje** [comment]
The full version number should already be hidden by default to anyone who's not an oper.

**Comment by layer3** [comment]
hmmm you get server version on connect! like " your host blaa running version InspIRCd-2.0"

**Comment by Heufneutje** [comment]
That's part of the RFC and should be there. It shows the least significant part of the version to anyone. The patch number is hidden.

For reference:
> 004    RPL_MYINFO
   "<servername> <version> <available user modes>
   <available channel modes>"
From https://tools.ietf.org/html/rfc2812#section-5.1

**Comment by SaberUK** [comment]
Why do you want to hide the version?

**Comment by attilamolnar** [comment]
Hiding the server version is not supported.
