### ISSUE TITLE
~ and ^ not treated as equivalent despite CASEMAPPING=rfc1459

### ISSUE THREAD

**Issue by aleth** [inspircd/inspircd#1017]
When ISUPPORT CASEMAPPING=rfc1459, the character ~ should be treated as the lowercase of ^ (otherwise, it would be strict-rfc1459, see http://www.irc.org/tech_docs/005.html).

However, if one tries to retrieve WHOIS for Nick^ with "WHOIS nick~", this fails with a 401 response.

**Comment by clokep** [comment]
(If you want a more formal document...this is also what http://tools.ietf.org/html/draft-brocklesby-irc-isupport-03#section-3.1 and http://tools.ietf.org/html/draft-hardy-irc-isupport-00#section-4.1 say.)

**Comment by kaniini** [comment]
I disagree, because `^` is a valid nick prefix char and `~` is not, thusly they are not really equivilant.  This is another pitfall of RFC1459.

**Comment by clokep** [comment]
Sorry, but I'm not really following how that's related, can you expand a bit? I'm unsure how this is related to prefixes, the example we saw "in the wild" was with a nick who used `^` at the end of a nick. (Additionally, it seems unfortunate if a character is valid both inside of a nick and as a prefix...)

To be clear, the suggestion is that the ISUPPORT token should be returning `strict-rfc1459`, if `^` and `~` and not equal in a case-insensitive manner.

**Comment by Adam-** [comment]
I think a change like this is insp20 may be a bit too much. In master sure, but I would rather see it just changed to use ascii like Unreal (or configurable?, but default to ascii). Would have to support both anyway still in master for backwards compat linking.

**Comment by SaberUK** [comment]
>I think a change like this in insp20 may be a bit too much.

We could probably just change ISUPPORT in 2.0.

>I would rather see it just changed to use ascii like Unreal

:+1:

**Comment by SaberUK** [comment]
@attilamolnar What do you think about changing ISUPPORT in 2.0 for this? Doesn't seem like it would be too invasive.

**Comment by attilamolnar** [comment]
I tried changing the ISUPPORT token to "strict-rfc1459" when this issue was opened but experienced compatibility problems with some clients (unfortunately can't remember which), so unless things have improved in the meantime I don't see changing ISUPPORT in 2.0 as a viable solution.

**Comment by kaniini** [comment]
I think it's better to just move to true unicode casefolding, per rfc7700 / ircv3/ircv3-specifications#259.

**Comment by SaberUK** [comment]
@kaniini Whilst I agree with adding support for proper unicode nicks I don't think it should be the default for now.

We don't even support super common stuff like TLS and server linking without the user enabling a module

**Comment by kaniini** [comment]
Yeah of course not for now, some transitional period would likely be required, as well as support of services and other middleware.  What I mean here is that dealing with `rfc1459` vs `strict-rfc1459` ultimately doesn't really matter, it's good enough less edge cases, and if you wanted to solve it, it would be better to transition to `ascii` casemapping anyway which would simplify a transitional path to a unicode casefolding later.

**Comment by SaberUK** [comment]
@kaniini Yeah, I think for 2.2 our plan is to transition to `ascii`. I looked into it yesterday and 2.0 compat is a bit icky though.

**Comment by kaniini** [comment]
A solution would be to disallow `~]^` characters on the 2.2 side while 2.0 servers are linked to the network (configuration option so that desyncs can be avoided).  This is how we plan to handle that step in the transition with Charybdis.

**Comment by jwheare** [comment]
`m_ascii` was added as an extra module in inspircd/inspircd-extras#92 so that should ease transition.

**Comment by SaberUK** [comment]
As of 51a47e7d757df63370168ab5000d13ca9c349ecd ASCII casemapping is the default. The old broken casemapping is supported in order to enable linking with legacy servers.

**Comment by SaberUK** [comment]
CASEMAPPING=rfc1459 will be removed in 3.0+1 so i'm marking this as blocked until that happens.
