### ISSUE TITLE
Make the description and/or function of m_messageflood more clear

### ISSUE THREAD

**Issue by B00mX0r** [inspircd/inspircd#1019]
Kind of related (a false bug due to a MOD_RES_DENY): https://github.com/inspircd/inspircd/issues/1013

The kick message and description of m_messageflood both define it as setting a limit. The documentation even states: "When a user types more than 'lines' lines in 'sec' seconds, kick them." However, the true function of 'lines' is a trigger. If a user types 'lines' lines, the module kicks them, which doesn't apply to the definition of limit ("a point or level beyond which something does not or may not extend or pass"). 

I'm worried that this misleading description may confuse some users. This could use discussion, but my personal suggestion is changing everywhere where it says 'limit'. If the actual function of the module were changed, chanops would need to change their flood modes, leading to unexpected behavior on channels where the chanops didn't get confused by the description.

 	irc.server kicked B00mX0r from the channel (Channel flood triggered (limit is 7 lines in 5 secs))

**Comment by SaberUK** [comment]
>However, the true function of 'lines' is a trigger. If a user types 'lines' lines, the module kicks them, which doesn't apply to the definition of limit ("a point or level beyond which something does not or may not extend or pass").

It's the number of lines which the user is allowed to send to the channel before being kicked. In other words, it's a limit.

>I'm worried that this misleading description may confuse some users.

You are literally the first person I have seen be confused by this.

**Comment by B00mX0r** [comment]
I'm not confused by it, but the definition of limit is the maximum, not where you go over the maximum.

**Comment by SaberUK** [comment]
Is there any point bikeshedding over this?

**Comment by B00mX0r** [comment]
Given that the wiki clearly defines the module's parameters, I'm surprised this hasn't already been brought up.

**Comment by attilamolnar** [comment]
@B00mX0r is technically right, this is a doc issue for 2.0.

**Comment by attilamolnar** [comment]
The helpop says:

    f [*]<lines>:<sec> Kicks on text flood equal to or above the
                       specified rate. With *, the user is banned

The comments near the <module> tag don't get into specifics.
Is there anything else to update besides the kick message (will happen in master) and the wiki?
