### ISSUE TITLE
Support for IPv6 DNSBL

### ISSUE THREAD

**Issue by HeavyMetal-ASoTnet** [inspircd/inspircd#1020]
The current m_dnsbl does not support IPv6 DNSBL as a result IPv6 hosts that is listed in the DNSBL is not being blocked. 

As more and more hosts are now using IPv6 it is likely more attacks will also be over IPv6 m_dnsbl should be upgraded now rather than later to mitigate this high probability.

**Comment by attilamolnar** [comment]
Can you tell us a few ipv6 dnsbls which should work?

**Comment by HeavyMetal-ASoTnet** [comment]
dnsbl.fireirc.co with ::2 and dnsbl.aseriesoftubez.com with ::2

**Comment by attilamolnar** [comment]
Implemented by @Adam- in #1028.
