### ISSUE TITLE
[Proposal] Strip colour from quit messages in cmd_quit

### ISSUE THREAD

**Issue by Renegade334** [inspircd/inspircd#1022]
Some ircd's such as charybdis strip colour from user-provided QUIT messages as core behaviour. There are several conceivable arguments in favour of this:
- A quitting user is not a particularly noteworthy event, and it should not draw attention away from surrounding channel activity.
- Coloured quit messages will break through user modes/channel modes/extbans that block or strip colour messages when they are displayed within an active channel or query by the client, which is an annoyance to the user.
- Quit messages cannot be modified by event handlers within InspIRCd. To implement any kind of filtering of quit messages would require direct changes to the core `cmd_quit` module.

As such, I'd be interested to see what feelings are with regards implementing this behaviour.

**Comment by SaberUK** [comment]
>Quit messages cannot be modified by event handlers within InspIRCd.

There's no reason we couldn't add a prehook in UserManager::QuitUser or make the message parameter of `OnUserQuit` non-const.

>As such, I'd be interested to see what feelings are with regards implementing this behaviour.

:+1: as a module. :-1: as a core feature.

**Comment by Shawn-Smith** [comment]
I think it should be stripped if the quitting user is in any channel that either blocks or strips color for it's users, that should be part of the block/strip color module though.

A new module or option could be made for stripping it no matter what.

**Comment by SaberUK** [comment]
@Shawn-Smith Doing it anything other than globally seems like it would be confusing. Also, we don't have the hooks for doing variable quit messages and it would probably be too intensive to add.
