### ISSUE TITLE
[Proposal] Add a new extban to m_gecosban to match n!u@h+gecos

### ISSUE THREAD

**Issue by Renegade334** [inspircd/inspircd#1023]
Currently, `m_gecosban` exports the `r:` extban for globmatching against gecos. However, there is no way to fine-tune this matching behaviour by mask. The ability to narrow down a gecos extban by mask might be useful in circumstances where the target gecos pattern is a common one, and therefore this crude matching against all users is not desirable.

One way this could be implemented is with an additional extban in `m_gecosban` that takes a string containing both n!u@h and a gecos globmask. For example, `a:*!*@*.abusive.host+*bot*` might match users matching both the `*!*@*.abusive.host` mask and the `*bot*` gecos pattern.

Thoughts welcome!

**Comment by Renegade334** [comment]
Example implementation at https://github.com/inspircd/inspircd/compare/master...Renegade334:ext-gecosban.

**Comment by SaberUK** [comment]
:+1:

You should probably file a pull request.

**Comment by maxteufel** [comment]
Can't this be consistent with Charybdis' `$x:nick!user@host#realname` (at least the # instead of +)?

**Comment by SaberUK** [comment]
@maxteufel I imagine that might cause conflicts with `m_banredirect`.
