### ISSUE TITLE
Problem Compiling on ARM Ubuntu 14.04.02 latest after upgrade today

### ISSUE THREAD

**Issue by doctorwhoisthis** [inspircd/inspircd#1025]
It worked before I upgraded. Wonder if there are new specs/etc in latest compiler.

Ubuntu 14.04.2 LTS

Linux odroid 3.10.72-76 #1 SMP PREEMPT Thu Mar 19 16:40:31 BRT 2015 armv7l armv7l armv7l GNU/Linux
armv7l
*************************************
*       BUILDING INSPIRCD           *
*                                   *
*   This will take a *long* time.   *
*     Why not read our wiki at      *
*     http://wiki.inspircd.org      *
*  while you wait for make to run?  *
*************************************
        BUILD:              bancache.cpp
An error occured when executing: g++ -o obj/bancache.o -pipe -fPIC -DPIC -pedantic -Woverloaded-virtual -Wshadow -Wformat=2 -Wmissing-format-attribute -Wall -O2 -g1 -Iinclude -c /root/insptaller/inspircd-2.0.18/src/bancache.cpp
In file included from /usr/include/arm-linux-gnueabihf/bits/errno.h:24:0,
                 from /usr/include/errno.h:35,
                 from /usr/include/c++/4.9/cerrno:41,
                 from include/socket.h:47,
                 from include/users.h:28,
                 from include/inspircd.h:83,
                 from /root/insptaller/inspircd-2.0.18/src/bancache.cpp:23:
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
 ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 ^
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
In file included from include/socket.h:141:0,
                 from include/users.h:28,
                 from include/inspircd.h:83,
                 from /root/insptaller/inspircd-2.0.18/src/bancache.cpp:23:
include/socketengine.h: In static member function ‘static bool SocketEngine::IgnoreError()’:
include/socketengine.h:509:16: error: ‘EAGAIN’ was not declared in this scope
  if ((errno == EAGAIN) || (errno == EWOULDBLOCK))
                ^
include/socketengine.h:509:37: error: ‘EWOULDBLOCK’ was not declared in this scope
  if ((errno == EAGAIN) || (errno == EWOULDBLOCK))
                                     ^
make[1]: *** [obj/bancache.o] Error 1
make: *** [target] Error 2

**Comment by SaberUK** [comment]
Hi,

Can you edit your comment to surround your compiler log in a [fenced code block](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks). It's a bit hard to read as-is.

**Comment by doctorwhoisthis** [comment]
Nevermind, can you please delete this. I guess it required a reboot.

**Comment by doctorwhoisthis** [comment]
Oops, nope. It's still got the issue. I was leaping when I saw it pausing for more than it did before.
How do you code block. Please don't delete.

**Comment by doctorwhoisthis** [comment]
*************************************
```
*       BUILDING INSPIRCD           *
*                                   *
*   This will take a *long* time.   *
*     Why not read our wiki at      *
*     http://wiki.inspircd.org      *
*  while you wait for make to run?  *
*************************************
        BUILD:              bancache.cpp
An error occured when executing: g++ -o obj/bancache.o -pipe -fPIC -DPIC -pedantic -Woverloaded-virtual -Wshadow -Wformat=2 -Wmissing-format-attribute -Wall -O2 -g1 -Iinclude -c /root/insptaller/inspircd-2.0.18/src/bancache.cpp
In file included from /usr/include/arm-linux-gnueabihf/bits/errno.h:24:0,
                 from /usr/include/errno.h:35,
                 from /usr/include/c++/4.9/cerrno:41,
                 from include/socket.h:47,
                 from include/users.h:28,
                 from include/inspircd.h:83,
                 from /root/insptaller/inspircd-2.0.18/src/bancache.cpp:23:
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
 ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 ^
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
In file included from include/socket.h:141:0,
                 from include/users.h:28,
                 from include/inspircd.h:83,
                 from /root/insptaller/inspircd-2.0.18/src/bancache.cpp:23:
include/socketengine.h: In static member function ‘static bool SocketEngine::IgnoreError()’:
include/socketengine.h:509:16: error: ‘EAGAIN’ was not declared in this scope
  if ((errno == EAGAIN) || (errno == EWOULDBLOCK))
                ^
include/socketengine.h:509:37: error: ‘EWOULDBLOCK’ was not declared in this scope
  if ((errno == EAGAIN) || (errno == EWOULDBLOCK))
                                     ^
make[1]: *** [obj/bancache.o] Error 1
make: *** [target] Error 2
*************************************
*       BUILDING INSPIRCD           *
*                                   *
*   This will take a *long* time.   *
*     Why not read our wiki at      *
*     http://wiki.inspircd.org      *
*  while you wait for make to run?  *
*************************************
        BUILD:              bancache.cpp
An error occured when executing: g++ -o obj/bancache.o -pipe -fPIC -DPIC -pedantic -Woverloaded-virtual -Wshadow -Wformat=2 -Wmissing-format-attribute -Wall -O2 -g1 -Iinclude -c /root/insptaller/inspircd-2.0.18/src/bancache.cpp
In file included from /usr/include/arm-linux-gnueabihf/bits/errno.h:24:0,
                 from /usr/include/errno.h:35,
                 from /usr/include/c++/4.9/cerrno:41,
                 from include/socket.h:47,
                 from include/users.h:28,
                 from include/inspircd.h:83,
                 from /root/insptaller/inspircd-2.0.18/src/bancache.cpp:23:
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
 ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 ^
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
In file included from include/socket.h:141:0,
                 from include/users.h:28,
                 from include/inspircd.h:83,
                 from /root/insptaller/inspircd-2.0.18/src/bancache.cpp:23:
include/socketengine.h: In static member function ‘static bool SocketEngine::IgnoreError()’:
include/socketengine.h:509:16: error: ‘EAGAIN’ was not declared in this scope
  if ((errno == EAGAIN) || (errno == EWOULDBLOCK))
                ^
include/socketengine.h:509:37: error: ‘EWOULDBLOCK’ was not declared in this scope
  if ((errno == EAGAIN) || (errno == EWOULDBLOCK))
                                     ^
make[1]: *** [obj/bancache.o] Error 1
make: *** [target] Error 2
```

**Comment by SaberUK** [comment]
Surround it in three tildes like this:

   \`\`\`
   log goes here
   \`\`\`

**Comment by SaberUK** [comment]
>/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program

It looks like there is a problem with your system headers. Try running `apt-get update && apt-get dist-upgrade` and seeing if it builds then.

**Comment by doctorwhoisthis** [comment]
I did as you said. No go. Thanks for your swift input. Latest kernel, latest software, latest libraries and dependencies for inspircd 2.0.18

**Comment by SaberUK** [comment]
You will probably need to contact your OS vendor as the problem is with your system headers (in this case errno.h):

```
/usr/include/linux/errno.h:1:1: error: stray ‘\377’ in program
 ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 ^
```

**Comment by doctorwhoisthis** [comment]
Copied errno.h from another working ARM system, and now ti works. I thank you kindly for your time and support.

**Comment by kaniini** [comment]
This is probably actually a locales issue, I suspect the first bytes of your errno.h are a byte-order mark.  Removing the first few bytes of errno.h should fix the issue.  Sometimes `dpkg` mangles files in this way, I am not sure why.
