### ISSUE TITLE
Nicks which begin with numbers?

### ISSUE THREAD

**Issue by flotwig** [inspircd/inspircd#1027]
No modern IRCd allows a user to use a nick beginning with a number. This is in accordance with the [RFC](http://tools.ietf.org/html/rfc2812#section-2.3.1):

```
nickname   =  ( letter / special ) *8( letter / digit / special / "-" )
```

Is this an actual technical limitation? Could this restriction be removed without any issues? 

@ElementalAlchemist suggested that the reason is so that inspircd can guarantee that a user will be able to change nick to their UID in the event of a nick collision. If the restriction was changed so that users could not change their nick to a nick in UID format but they COULD change nick to a nick beginning with a digit, would this cause any issues?

Here is a log of the discussion in #inspircd: http://pastebin.com/ysvimnmW

**Comment by Shawn-Smith** [comment]
The reason you can't allow nicks to begin with numbers and also forbid UID format nicks is because any nick that begins with a number would be a valid UID.

`0SOMENICK` for example is a valid UID.

**Comment by flotwig** [comment]
Thanks Shawn. Correct me if I'm wrong with the following paragraph, I'm not too familiar with the inner machinations of inspircd.

The string 0AA (for example) is a valid UID which would never be generated by inspircd's default configuration. Because we know that inspircd will only generate UIDs which are alphanumeric and of a certain length, what would be the issue with only stopping users from using those specific nicks while allowing all other number-started nicks?

Another question: Is there a specific reason why inspircd changes the nick to a UID in the event of a collision? Would it be horribly inefficient to check if the nick is in use before forcing the user to change nick? I suppose that there are a finite number of valid nicks to switch to, but in reality, the full nick namespace could never be saturated.

**Comment by kaniini** [comment]
The string `0AA` is also a valid SID, which could be used by middleware.

**Comment by aFreshMelon** [comment]
Maybe all these ID's should have stricter format definitions since usernames with digits as the first characters are not particularly uncommon.

**Comment by flotwig** [comment]
@kaniini Let's also assume that the username restrictions can take things like that into account. In a real-world scenario, we would know all of the software running on the network at any given time, so we can take things like that in to account realistically.

**Comment by kaniini** [comment]
I think, reasonably, *assuming* that middleware is properly written in the inspircd-specific case, that you could allow nicknames beginning with numbers provided that nicknames of length 3 and 9 are reserved.

I do not recommend such a configuration for production networks though without extensive testing.

**Comment by aFreshMelon** [comment]
I agree with @kaniini here, partially. It was my suggestion to have much stricter formats for ID's since they can reasonably be in a very specific format and to only have usernames matching the exact format blocked.

Whether just length is enough here is another thing.

**Comment by Shawn-Smith** [comment]
>The string 0AA (for example) is a valid UID which would never be generated by inspircd's default configuration. Because we know that inspircd will only generate UIDs which are alphanumeric and of a certain length, what would be the issue with only stopping users from using those specific nicks while allowing all other number-started nicks?

I suppose you COULD do this, but it would have a hackish feel to it, and if the UID length ever changed it could cause issues.

>Another question: Is there a specific reason why inspircd changes the nick to a UID in the event of a collision? Would it be horribly inefficient to check if the nick is in use before forcing the user to change nick? I suppose that there are a finite number of valid nicks to switch to, but in reality, the full nick namespace could never be saturated.

It's more efficient to force someone to a UID that is guaranteed to be unique than it is to generate a random nick, check to see if someone is using it, and then change someone's nick to that or continue looping until a not-in-use nick is found.

**Comment by Adam-** [comment]
If you were to force uids in the protocol (as opposed to allowing nicks or ids) you could do it without any of these limitations. P10 has had numnicks that are valid nicknames for decades. But it doesn't allow nicknames to begin with numbers, due to the rfc limitations.

**Comment by Adam-** [comment]
Except that wouldn't work correct with SAVE since it has to know the other side's nick will always be free, I think.

**Comment by SaberUK** [comment]
The string 0AA (for example) is a valid UID which would never be generated by inspircd's default configuration.

I believe that the early UIDs are not generated to make things easier for services.

>Another question: Is there a specific reason why inspircd changes the nick to a UID in the event of a collision? Would it be horribly inefficient to check if the nick is in use before forcing the user to change nick? I suppose that there are a finite number of valid nicks to switch to, but in reality, the full nick namespace could never be saturated.

Why bother when the user already has a guaranteed unique identifier?

**Comment by voidzero** [comment]
If I remember correctly, the reason for the rule that nicknames mustn't start with a digit, is that SIDs (Server IDs) are supposed to start with a digit. In other words: digit-first is reserved for servers.

**Comment by kaniini** [comment]
SIDs came way after RFC1459.   That SIDs traditionally start with a digit in a TS6-like link protocol is simply due to taking advantage of RFC1459's restriction instead of making SID/UID explicit as in P10.

**Comment by SaberUK** [comment]
As mentioned previously this would be a RFC 1459 violation and cause problems with UIDs so i'm going to close this.
