### ISSUE TITLE
openssl: Turning off sslv3 shouldn't require setting customcontextoptions

### ISSUE THREAD

**Issue by docwhat** [inspircd/inspircd#1031]
For the `m_ssl_openssl` module, it seems confusing that turning off SSLv3 (`sslv3="off"`) should require setting `customcontextoptions` to `on`.

This took me a lot of time to figure out, especially since the wiki page is down now and the wayback machine doesn't have a recent enough copy of the openssl module page.

Looking at the code in `SetContextOptions()` it seems benign enough that I don't see what the harm would be to just always run it for server and client (e.g. no longer check for `customcontextoptions`, assume it's true).

**Comment by Mikaela** [comment]
I personally think that InspIRCd shouldn't even have SSLv3 by default. I believe that Charybdis has disabled it and as far as I am aware other server software like nginx (at least on Ubuntu) disables it by default.

**Comment by Adam-** [comment]
It looks to me like this was done to preserve backwards compatibility in 2.0.x, which is important to us. Master doesn't have it. I think it should be documented in modules.conf (along with all of the other modules that are too "complex"), since the wiki has always been spotty at best.

**Comment by docwhat** [comment]
We did discover that some clients only speak SSLv3.  But I agree that it should be off by default.

**Comment by SaberUK** [comment]
Compatibility is king. Users would not be happy if their servers suddenly stopped "working" after a minor upgrade.

**Comment by attilamolnar** [comment]
Hello,

> For the m_ssl_openssl module, it seems confusing that turning off SSLv3 (sslv3="off") should require setting customcontextoptions to on.

This works as documented. The wiki being down is another issue which should not cause us to make code changes. I'd rather do as @Adam- suggested and expand the example configuration of the modules which do not have a proper one.

**Comment by attilamolnar** [comment]
I can confirm `customcontextoptions` is not required on master as mentioned earlier.

**Comment by docwhat** [comment]
Ah. I'm not using master. I'm using the latest release.
