### ISSUE TITLE
allow m_messageflood to do something more useful than kick users

### ISSUE THREAD

**Issue by kaniini** [inspircd/inspircd#1032]
So I use an inspircd network and sometimes the server kicks me because of flooding, which then has a painful intersection with `+J` (or as I lovingly call it "twat mode").

It seems to be a common pain point, so I was thinking, instead of kicking people for flooding which is intrusive anyway... why not just block their messages after the configured threshold?  Most intersections with `+f` are not from bots, but legitimate participants, _especially if it's misconfigured_.

@SaberUK was talking about this the other day, I think.  Also I noticed #499 but it seems like a dead issue, so I opened this one up.

**Comment by Shawn-Smith** [comment]
Pull #471 allows for blocking instead of kick(ban)ing. I know we discussed that on IRC, just referencing it here for anyone reading this issue.
