### ISSUE TITLE
Multiple-character fantasy prefixes supported in m_alias

### ISSUE THREAD

**Issue by MandL27** [inspircd/inspircd#1036]
Could it be possible to set prefixes in a <fantasy> tag to be longer than just a single character? According to SaberUK, the current build makes a prefix definition of "!s@me7h1nG" get interpreted as simply "!".

**Comment by attilamolnar** [comment]
@MandL27 @SaberUK Can you provide use cases for this feature request?

**Comment by MandL27** [comment]
@attilamolnar I've seen a few bots that respond to "!(two-letter_prefix) (command)" so if fantasy prefixes built into insp could behave similarly, it'd keep one namespace across the network.

**Comment by attilamolnar** [comment]
Implemented by @SaberUK in #1044.
