### ISSUE TITLE
GCC Error on New Version

### ISSUE THREAD

**Issue by TuSuNaMi** [inspircd/inspircd#1040]
BUILD:              modules/m_regex_stdlib.cpp
An error occured when executing: g++ -o modules/m_regex_stdlib.so -pipe -fPIC -DPIC -pedantic -Woverloaded-virtual -Wshadow -Wformat=2 -Wmissing-format-attribute -Wall -O2 -g1 -Iinclude -std=c++11 -DMODNAME=m_regex_stdlib.so -fPIC -shared -rdynamic /home/ircodam/inspircd-2.0.19/src/modules/m_regex_stdlib.cpp
cc1plus: error: unrecognized command line option "-std=c++11"
make[1]: *** [modules/m_regex_stdlib.so] Error 1
make: *** [target] Error 2

**Comment by Googolplexed** [comment]
m_regex_stdlib is a module from extras that requires a C++11 capable compiler to use

Many distros don't ship C++11 capable compilers, and it is disabled by default for that reason. (All modules in extras have dependancies beyond InspIRCd's normal requirements)

Until the distro that you are running ships a C++11 capable version of GCC, you cannot use the module.

**Comment by TuSuNaMi** [comment]
I removed module thank you
