### ISSUE TITLE
Connecting via browser makes you connect to network (but you fail to register)

### ISSUE THREAD

**Issue by Agent-Isai** [inspircd/inspircd#1047]
Hi, is it normal to see 
:irc.mynetwork.net NOTICE Auth :*** Looking up your hostname...
:irc.my network.net NOTICE Auth :*** Could not resolve your hostname: Domain name not found; using your IP address (<IP>) instead.
ERROR :Closing link: (unknown@<IP>) [Registration timeout]
When connecting to any port that is used for InspIRCd via a web browser (e.g. https://bender.chatspike.net:6697)

**Comment by WindowsUser** [comment]
"is it normal?" Yes, because IRC != HTTP.

**Comment by Mikaela** [comment]
I believe you get that with every IRCd as long as you use browser which doesn't block traditional IRC ports.

**Comment by SaberUK** [comment]
If you want to kill off HTTP connections straight away then consider using `m_autodrop` from `inspircd-extras` (run `./modulemanager install m_autodrop` and rebuild).

**Comment by attilamolnar** [comment]
Yes, this is normal.

**Comment by AlexandraBryantKS** [comment]
Hi, I'm having this same issue with port 6500, which works perfectly fine with UnrealIRC on the backend (but UnrealIRC doesn't have as good Windows Service support as you guys!) normally it goes http:// -> request to upgrade to ws:// 

Does InspIRCd support this upgrade requesting?

**Comment by SaberUK** [comment]
There is no upgrading from a normal IRC port to websockets.If you want a WebSocket listener then you have to load the websocket module and set hook="websocket" in your `<bind>` tag.
