### ISSUE TITLE
Want user modes for SSL connection, and Authenticated connection

### ISSUE THREAD

**Issue by daleghent** [inspircd/inspircd#1052]
I am in a situation where I need to enforce 2 things for every user who accesses the server:

1. Ensure that they have a SSL/TLS connection, and
2. Before they are allowed to join any channel, ensure they have authenticated. A mechanism needs to exist where UNauthenticated users should not be allowed to join any "protected" channel and, optionally, be disconnected by the server if they have not auth'd after *N* seconds transpires from their initial connection.

Could this be accomplished by the SSL and auth modules setting a user mode signifying these states, and an additional module which can block access to channels if the user modes aren't present?

**Comment by Googolplexed** [comment]
If you only want SSL/TLS users on your server, the simplest way would be to simply not listen on any plaintext ports, or to set your connect blocks to deny all users that attempt to connect over plaintext

Allowing users to connect, but requiring authentication before joining a channel can be done simply by using the m_services_account module and ensuring that the channels are set to +R

**Comment by SaberUK** [comment]
>Allowing users to connect, but requiring authentication before joining a channel can be done simply by using the m_services_account module and ensuring that the channels are set to +R

This is splitrideable. A better alternative would be to require all clients to be authed via SASL using `<connect:requireaccount>` and `<connect:registered>` before they can connect to the server.
