### ISSUE TITLE
PID file not writable with --system option on 2.0 branch

### ISSUE THREAD

**Issue by hameerabbasi** [inspircd/inspircd#1065]
I get the following error with InspIRCd 2.0 and --system:

    Failed to write PID-file '/var/run/inspircd.pid', exiting.

A temporary fix I applied was to create an empty `/var/run/inspircd.pid` and `chown` it to the user InspIRCd runs as.

Edit: Let me be clear, the configuration was sane. The error was due to an un-writable PID file, and as I noted, was fixed by creating and `chown`-ing it.

**Comment by attilamolnar** [comment]
Why is this an inspircd issue? The pid file is supposed to be writable. If it isn't you should configure a new location for it.

**Comment by attilamolnar** [comment]
Relevant config section: https://github.com/inspircd/inspircd/blob/insp20/docs/conf/inspircd.conf.example#L465-475

**Comment by hameerabbasi** [comment]
With the --system configuration, the PID file should be stored in the system directory for PID files. Since this is /var/run on most *nix systems, this should be supported for system-wide installs.

Like I said... When first starting the IRCd, the file should be created and chowned as root...

**Comment by SaberUK** [comment]
That wouldn't work because even if you're installed system-wide you may not be starting as root (there is no legitimate reason to start as root). This is why `--system` defaults to having the pid file in `/var/inspircd/inspircd.pid` which at build time is set to the user which the IRCd is going to run as (e.g. `irc` on Debian-derived systems).

**Comment by hameerabbasi** [comment]
Okay, looks like I'll have to settle for a non-standard location, then. Thanks. :-)

**Comment by hameerabbasi** [comment]
I just tried with a fresh install of InspIRCd... Looks like `/var/inspircd` is not owned by the correct user either. I had to manually `chown` that, too.

**Comment by SaberUK** [comment]
What version of InspIRCd are you trying to build? There is an issue related to that which was fixed in commit 2ad8a6791bbc548dee4156eaf661612bea3d310f.

**Comment by hameerabbasi** [comment]
I got the sources from master yesterday, so it was definitely after that commit.

**Comment by hameerabbasi** [comment]
Excuse me, insp20.

**Comment by SaberUK** [comment]
Can you provide the exact commands you used to build and install InspIRCd?

**Comment by hameerabbasi** [comment]
Perhaps it's because I had a left-over folder from a previous installation? In that case, I think the directory should be `chown`-ed even if it exists to fix the issue.

And to answer your question, I used your Debian package script with GnuTLS and insp20 in the recommended way.

**Comment by SaberUK** [comment]
Try running `apt-get purge inspircd` and then making sure the directories have been deleted and then installing again.

**Comment by attilamolnar** [comment]
@hameerabbasi Please comment if the issue persists.
