### ISSUE TITLE
[Proposal] Split the receivers of a message from the target in the S2S protocol.

### ISSUE THREAD

**Issue by SaberUK** [inspircd/inspircd#1073]
Currently the syntax for sending a message (in this case a `NOTICE` but the syntax is the same for a `PRIVMSG`) to a channel in spanningtree is:

:&lt;source uuid&gt; NOTICE &lt;channel name&gt; :&lt;message&gt;

I propose that this is amended an optional second parameter which specifies the target of the message.

:&lt;source uuid&gt; NOTICE &lt;channel name&gt; &lt;comma delimited list of uuids to receive this message&gt; :&lt;message&gt;

When the IRCd receives a message with this extra parameter it should iterate over the list of UUIDs and send the message to each user as if it had been sent to the channel. If the parameter is missing then it should just follow normal behaviour and send the message to all users in the channel.

One such use for this is that it would allow for services packages such as Anope (Adam has said that he liked this idea) to send entry messages to a specific user whilst keeping them in the client's channel window. This prevents the problem of if you join 30 channels each with their own entry message your client exploding with new PM windows or flooding the active window depending on your client configuration.

Another use is that it would allow you to configure a log channel (e.g. m_chanlog) and only have specific privileged users in that channel be to receive log messages.

**Comment by del6597** [comment]
Would this strictly be for server-server communications or would a client be able to invoke a message like this as well? It could be beneficial, since there are users who have bots that do this type of entry message greeting.  It seems similar to STATUSMSG except that individuals are specified.  Unfortunately I have yet to be a part of a channel where everyone understands what a STATUSMSG is, so it only causes confusion.

**Comment by SaberUK** [comment]
@del6597 As mentioned in the topic this would be for the S2S protocol only.

**Comment by attilamolnar** [comment]
This is a complicated solution when Anope could use PUSH to accomplish something similar. Are there any other use cases?

**Comment by attilamolnar** [comment]
For m_chanlog, you can use multiple log channels with different types, members and restrictions.
