### ISSUE TITLE
[2.0] Server somehow still remembers and enforces a previously removed <badchan> block

### ISSUE THREAD

**Issue by Techman-** [inspircd/inspircd#1078]
I had `#*brony*` as a badchan block previously, and then I decided to remove it as it was no longer needed. Did this to modules.conf and replaced it on all servers, then did `/rehash *`. Every server except one worked fine; a lone server somehow refuses to allow users into a previously-restricted channel. This server is on the latest commit from 2.0, and the others are just a few commits behind (so all are on 2.0). Reloading the module on that server has no effect, nor does doing it globally. If I `/gunloadmodule m_denychans.so`, everything works fine again but then I lose other  <badchan> blocks which I really do rely on. Perhaps I'll just use Anope's `/os forbid` in the meantime.

**Comment by attilamolnar** [comment]
Please paste the entire configuration of the affected server.

**Comment by Sheogorath-SI** [comment]
Your badchan blocks are added to xline.db and after removing the blocks they stay in xline.db so they'll stay.

you also have to remove it by /cban

**Comment by attilamolnar** [comment]
Closing after no reply for nearly 3 weeks. Feel free to comment with new info and I'll reopen.
