### ISSUE TITLE
charset problem

### ISSUE THREAD

**Issue by TuSuNaMi** [inspircd/inspircd#1083]
Hello;

< module name="m_nationalchars.so" >
< nationalchars file="/home/xxxx/inspircd/locales/tr_TR.iso88599_braces" >

I use this config for Turkish Charset but some IRC clients made problem with this charset. Any chance to use double charset in config file or another way. 

Thank You

**Comment by antoniocostacf** [comment]
what about try use UTF-8?

**Comment by TuSuNaMi** [comment]
I cant see UTF-8 file in locales directory

**Comment by Sheogorath-SI** [comment]
It's because it's not there. And it's not really a server Problem. Your Problem-Clients are using the wrong charset talk to those users to use iso88599 and not utf-8. that should solve your problem. (Yes, there are really good reasons for using ascii for nicknames and all serverside things)

**Comment by TuSuNaMi** [comment]
I need iso8859-9 for Turkish nicknames but its made problem with the mobile client

http://m.sohbetodam.org

**Comment by SaberUK** [comment]
You can only use one nationalchars map for the entire server. This is not something we can change as it would cause name conflicts.

**Comment by attilamolnar** [comment]
@TuSuNaMi Please use our IRC channel for support and questions, this is an issue tracker used to report bugs.

What you are talking about has something to do with clients not the server, the server can only use one casemapping.
