### ISSUE TITLE
Problems with Aliases

### ISSUE THREAD

**Issue by SGColdSun** [inspircd/inspircd#1087]
It seems that the alias module isn't handling multiple words in the replacements on our current installation, or it's quite possible I'm simply missing something obvious.

Our goal is to create aliases that will mirror the basic functionality of GameSurge's srvx services with our anope installation.

First example that we tried:

`
<alias text="users" usercommand="no" channelcommand="yes" replace="PRIVMSG ChanServ access $chan list" requires="ChanServ" uline="yes">`
    

It unfortunately only sent chanserv the following "access #channel-here".

Next, I tried the following, just as a test
`
<alias text="Test" replace="PRIVMSG ColdSun this is a test alias">
` 
and I only received the following privmsg:
"this"

**Comment by Sheogorath-SI** [comment]
You have to use the IRC Syntax: `PRIVMSG ColdSun :this is a test alias`

**Comment by SGColdSun** [comment]
Ah, thank you ;)

**Comment by SGColdSun** [comment]
That would seem to resolve my issue. Thanks :)
