### ISSUE TITLE
Modules/2.0/conn join port based autojoin

### ISSUE THREAD

**Issue by TuSuNaMi** [inspircd/inspircd#1088]
Hello;

Any way possible port based autojoin channels ?

Thanks

**Comment by Sheogorath-SI** [comment]
You can define an `autojoin` parameter in your connect class where you also can specify a port.
as example:
```
<connect 
    allow="*" 
    port="6667"
    autojoin="#channnel"
    parent="main"
>
```

**Comment by TuSuNaMi** [comment]
Ok last question

I use different idents for web logins any chance to use ident for allow section 

example allow="*!Test@*"

**Comment by attilamolnar** [comment]
This is an issue tracker, use our IRC channel for questions.
