### ISSUE TITLE
Cleared/unset topic misleading behavior

### ISSUE THREAD

**Issue by Robby-** [inspircd/inspircd#1091]
When one sets a topic on a channel and clears/unsets it again, the ircd sends you an empty topic upon rejoining the channel. I found this out while testing if this was a (caching) bug in an IRC client or not.

This is misleading behavior because when you do a `/TOPIC #channel` you get a "331 No topic set." message, yet upon joining such channels you always get served this empty topic:
`:<server> 332 Robby #Test3 :` (and the numeric 333 message that goes with it).

Either this should never be sent to the client upon joining in the first place when the topic is empty, or `/TOPIC #channel` should also return this empty topic. I'm for the former, I never liked the latter implementation.

If I remember correctly it is UnrealIRCd that has (or had) the latter behavior, because in this way it was visible who had last unset the topic, when asked about this behavior.

**Comment by SaberUK** [comment]
What:

1. Version of InspIRCd are you using?
2. Client and client version are you using?
3. Are you using any proxy software like ZNC? If so, what and what version?

**Comment by attilamolnar** [comment]
I've marked this as an enhancement for 2.2 because it brings us closer to other implementations. No changes will occur to 2.0 because what we do right now is not RFC incompliant.
