### ISSUE TITLE
double whowas output for "whois nick nick"

### ISSUE THREAD

**Issue by darix** [inspircd/inspircd#1097]
irssi has a default alias ```wii whois $0 $0```. if you do it for an online user, who get the expected one reply. for an offline user, you get 2 whowas answers. This seems inconsistent.

**Comment by attilamolnar** [comment]
Please attach a debug log.

**Comment by darix** [comment]
will have to do that for a testing instance later.

**Comment by attilamolnar** [comment]
It's enough to get a raw log from a client.

**Comment by attilamolnar** [comment]
I suspect what you are seeing is normal behavior: one nick can have more whowas entries stored (if it left more than once) and doing a single /WHOWAS will cause all of them to be sent to the querying client. Raw logs are necessary to see the actual numerics to confirm this, but it's highly likely.

You can set the number of entries to store per nick with [`<whowas groupsize>`](https://github.com/inspircd/inspircd/blob/insp20/docs/conf/inspircd.conf.example#L847-L849).

**Comment by attilamolnar** [comment]
Reply if the above does not explain the situation and I'll reopen

**Comment by darix** [comment]
yes couldnt reproduce it anymore.
