### ISSUE TITLE
Italics not stripped by chanmode S

### ISSUE THREAD

**Issue by uecasm** [inspircd/inspircd#1100]
On a server running InspIRCd-2.0 (I'm not a server op, so I'm not sure exactly what version), I noticed that the +S channel mode does not strip the italics control character (0x1D, apparently, though I've read that 0x16 is also sometimes used for italics or inverse -- I'm not sure which of these HexChat sends).

Although it *does* strip the "normal text" one (0x0F), so someone trying to send only one word in italics will get italics until the end of the line, unless they use the italics control again instead of "normal text".

**Comment by AppleDash** [comment]
+1, can confirm this happens. The stripcontrol module should probably be augmented to strip italics too, even though it's not an mIRC color code.

**Comment by Heufneutje** [comment]
I think that's because italics are not a standardized control character and not every client support it. Still, I do agree that it should probably be stripped (and subsequently blocked by chanmode c)

**Comment by SaberUK** [comment]
:+1:

**Comment by phy1729** [comment]
I think the most future proof solution would be to just block all control characters except for a beginning and ending \001 for CTCP. That way when some client adds a blink control code it'a already blocked,

**Comment by AppleDash** [comment]
But what do we define as a "control character"?

**Comment by phy1729** [comment]
if (!(*i & 0xE0)) or if (*i < 0x20)

**Comment by NikosPapakonstantinou** [comment]
Italics looks like utf8 chars which are not affected by S.
Plus could be an issue for no caps module because you can write text with utf8 small caps to bypass it.

**Comment by attilamolnar** [comment]
Fixed.

**Comment by Robby-** [comment]
Any chance to get this backported to 2.0 as well?
