### ISSUE TITLE
+B extban blocks strings other than ALLCAPS

### ISSUE THREAD

**Issue by Tjololo12** [inspircd/inspircd#1102]
Discovered in a channel today that blocking a user using an extban of +B:nick!*@* is blocking strings that contain only periods and spaces, for example:

.                              .                                         .

Found by accident. You can see a log of testing chat here: http://pastebin.com/idK3qPNu I tried out a bunch of test cases, even tried voicing the user. The second half of the pastebin is the same, but with all spaces converted to * symbols so you can more easily count them.

I brought it up in #help on irc.snoonet.org, and they suggested filing it as a bug, so here you go! If you need any more info, let me know.

**Comment by Adam-** [comment]
I can't reproduce this. Get client or server debug logs, and m_blockcaps configuration.

**Comment by Tjololo12** [comment]
I can't get anything other than client logs, here's my client's raw log:

[11:46:38] << PRIVMSG #testingtesting :a      s
[11:46:38] >> :corellia.snoonet.org 404 Tjololo #testingtesting :Your message cannot contain more than 75% capital letters if it's longer than 5 characters

I'm not sure how to get anything other than that. That was pulled from my client, instead of kiwiirc.

I've alerted the admins of the server (irc.snoonet.org), hopefully they can get some more information.

**Comment by Adam-** [comment]
I think they configured a bunch of lowercase letters into the capsmap.

**Comment by flotwig** [comment]
This is our blockcaps configuration.

    <blockcaps percent="75"
               minlen="5"
               capsmap="ABCDEFGHIJKLMNOPQRSTUVWXYZ! ">

**Comment by Adam-** [comment]
I can't reproduce it on snoonet either.

**Comment by Tjololo12** [comment]
I'm able to consistently.

1. Join a channel to test (I've been using #testingtesting)
2. Send command "/mode #testingtesting +b B:yournick!*@*"
3. Send text ".      ." (period 6 spaces period)
4. Text does not send

**Comment by Adam-** [comment]
Oh 6 spaces? The spaces are considered caps, see above.

**Comment by Tjololo12** [comment]
Yes, I think that's what's going on, after looking at the caps config. I guess it's not a bug then
