### ISSUE TITLE
Make m_cloaking output chars configurable

### ISSUE THREAD

**Issue by del6597** [inspircd/inspircd#1107]
Is there a specific reasoning that the base32 variable in m_cloaking _has_ to be lower-case?  When a cloak appears as all lowercase characters it looks odd when compared to Unreal.  As far as I can tell the case of the letters doesn't impact the algorithm.
I edit this variable to be all upper case like `static const char base32[] = "0123456789ABCDEFGHIJKLMNOPQRSTUV";` when compiling, but it would be much better if it could be specified in the config files.
Can this be made configurable so a user may specify a value for this variable or even just upper/lower case?

**Comment by attilamolnar** [comment]
It can be made configurable, but I don't understand the reasoning. InspIRCd is not Unreal, why make it look like it?

**Comment by Heufneutje** [comment]
In fact, there's probably more IRCds that DON'T use uppercase for cloaks than ones that do.

**Comment by del6597** [comment]
Even without comparing it to other IRCds there's a difference between uppercase and lowercase in terms of usability for reading. Lower case _is_ easier to differentiate the letters, but in terms of IRC cloaks I would argue that all upper case looks more appealing when people join/part/quit, since the common portion of the cloak (half vs. full) will be uniform for everyone instead of mixed letter heights.
For instance `ahbqdp` is less appealing than `AHBQDP`.

It's a preference I thought I'd bring up and maybe others feel the same way.  Currently a recompile of the module is required for anyone to change it to their liking which is inconvenient.
