### ISSUE TITLE
Consider adding support for mbedTLS

### ISSUE THREAD

**Issue by kaniini** [inspircd/inspircd#1111]
Hello,

There is another TLS library that is growing in popularity, mbedTLS.  It has the advantages of being cleanly implemented and has been security audited.

It may be advantageous to offer it as a TLS backend for InspIRCd users, especially given the generally bad situation with OpenSSL and the poor maintenance of GNUTLS lately.

**Comment by SaberUK** [comment]
This was already rejected in #100.

**Comment by attilamolnar** [comment]
Hello, I think this is a good idea if we don't have to bundle the mbedTLS code (which was the issue raised in #100).

**Comment by kaniini** [comment]
mbedTLS supports being built as shared library now and is included in most mainstream distributions

**Comment by SaberUK** [comment]
I personally don't think this is worth the effort of maintaining *another* TLS module.

**Comment by blitmap** [comment]
Maybe we need a...
( •_•)
( •_•)>⌐■-■
(⌐■_■)
...TLSEngine.cpp

**Comment by attilamolnar** [comment]
mbedTLS support has been implemented.
