### ISSUE TITLE
what kind of md5 hashing does md5 and sha256 implement?

### ISSUE THREAD

**Issue by fboerman** [inspircd/inspircd#1113]
I am using it with the sqlauth module but when i examine the query that it sends to my mariadb server it inserts a hash that does not correspond with the traditional md5 or sha256. I read the source code but didnt understand it. Can someone shed light on this?

**Comment by attilamolnar** [comment]
Hello, please note that this is an issue tracker, general support is provided over IRC. All hashing modules implement the standard hashes. If you see otherwise provide /mkpasswd output showing hashes that are incorrect.
