### ISSUE TITLE
sqlauth not inserting sha256 or plain text password

### ISSUE THREAD

**Issue by fboerman** [inspircd/inspircd#1114]
the sqlauth module inserts a space when i try to have it insert sha256 hash, eventhough i have the sha256 module enabled. It does the same for the $pass variable. Does anybody know why, and how to fix this? I have the latest stable version on latest debian jessie

**Comment by attilamolnar** [comment]
Please submit your configuration and debug logs (run `./inspircd debug`) showing the issue.

**Comment by attilamolnar** [comment]
Please reply if you think this is still an InspIRCd bug.
