### ISSUE TITLE
Cannot give relative path as config file

### ISSUE THREAD

**Issue by ProgVal** [inspircd/inspircd#1115]
```
$ inspircd --nofork --config ./inspircd.conf
ERROR: Cannot open config file: /home/progval/.local/conf/./inspircd.conf
Exiting...
$ ls inspircd.conf 
inspircd.conf
```

Expected behavior: local `inspircd.conf` is used instead of trying (and failing) to use a file relative to the prefix.

Version: ac861f854ccee2515c191068cc2274e5d1a92fa8 (Git master at the time I am writing this)

**Comment by SaberUK** [comment]
It seems like `FileSystem::ExpandPath` needs to be expanded to handle relative paths. I'll look into it some time.

**Comment by SaberUK** [comment]
I finall got chance to look into this and it seems like we shouldn't even be using PrependConfig here.

I've got a local fix and I will push it (and close this issue) when I have tested it.

**Comment by ProgVal** [comment]
thanks!
