### ISSUE TITLE
Neither RPL_NOTOPIC or RPL_TOPIC after joining a channel

### ISSUE THREAD

**Issue by ProgVal** [inspircd/inspircd#1116]
Session log:

```
1450662475.043 1: connects to server.
1450662475.043 1 -> S: NICK foo
1450662475.043 1 -> S: USER username * * :Realname
1450662475.043 S -> 1: :irc.example.com NOTICE * :*** Skipping host resolution (disabled by server administrator)
1450662476.044 S -> 1: :irc.example.com 001 foo :Welcome to the Network IRC Network foo!username@127.0.0.1
1450662476.044 1 -> S: PING foo
1450662476.045 S -> 1: :irc.example.com 002 foo :Your host is irc.example.com, running version InspIRCd-2.2
1450662476.045 S -> 1: :irc.example.com 003 foo :This server was created 21:58:05 Dec 19 2015
1450662476.045 S -> 1: :irc.example.com 004 foo irc.example.com InspIRCd-2.2 iosw biklmnopstv bklov
1450662476.045 S -> 1: :irc.example.com 005 foo AWAYLEN=200 CASEMAPPING=rfc1459 CHANMODES=b,k,l,imnpst CHANNELLEN=64 CHANTYPES=# ELIST=MU FNC KICKLEN=255 MAXBANS=64 MAXCHANNELS=20 MAXTARGETS=20 MODES=20 :are supported by this server
1450662476.045 S -> 1: :irc.example.com 005 foo NAMESX NETWORK=Network NICKLEN=32 PREFIX=(ov)@+ STATUSMSG=@+ TOPICLEN=307 VBANLIST :are supported by this server
1450662476.045 S -> 1: :irc.example.com 251 foo :There are 1 users and 0 invisible on 1 servers
1450662476.045 S -> 1: :irc.example.com 254 foo 0 :channels formed
1450662476.045 S -> 1: :irc.example.com 255 foo :I have 1 clients and 0 servers
1450662476.045 S -> 1: :irc.example.com 265 foo :Current local users: 1  Max: 1
1450662476.045 S -> 1: :irc.example.com 266 foo :Current global users: 1  Max: 1
1450662476.045 S -> 1: :irc.example.com 422 foo :Message of the day file is missing.
1450662476.045 S -> 1: :irc.example.com PONG irc.example.com :foo
1450662476.045 1 -> S: JOIN #chan
1450662476.083 S -> 1: :foo!username@127.0.0.1 JOIN :#chan
1450662476.084 S -> 1: :irc.example.com 353 foo = #chan :@foo
1450662476.084 S -> 1: :irc.example.com 366 foo #chan :End of /NAMES list.
```

Expected result: get an extra `RPL_NOTOPIC` or `RPL_TOPIC`, as defined by RFC 1149 [section 4.2.1](https://tools.ietf.org/html/rfc1459#section-4.2.1): “If a JOIN is successful, the user is then sent the channel's topic (using RPL_TOPIC) and […]”, as well as RFC 2812 [section 3.2.1](https://tools.ietf.org/html/rfc2812#section-3.2.1)

Version: ac861f854ccee2515c191068cc2274e5d1a92fa8 (Git master at the time I am writing this)

Configuration:

```
<bind address="{hostname}" port="{port}" type="clients">
<module name="cap">
<module name="ircv3">
<module name="ircv3_capnotify">
<module name="namesx">
<connect allow="*" resolvehostnames="no">
```

**Comment by MattIrv** [comment]
This is caused by not sending a RPL_NOTOPIC reply when joining a channel for which the topic is not set.

However, reading the RFC, I think this is the expected behavior. RFC 1149 and RFC 2812 allow only RPL_TOPIC as a reply to join messages, while they explicitly allow both RPL_TOPIC and RPL_NOTOPIC as replies to topic messages.

A quick look at a couple other IRCDs shows that their behavior is the same as the current behavior.

**Comment by ProgVal** [comment]
The RFCs do not “only allow”, because they do not state nothing else should be sent.

**Comment by Adam-** [comment]
We aren't trying to deviate from the behavior of other IRCds just because the RFC can be ambiguous/interpreted differently than how it is currently implemented. There has to be a reason why changing this would be beneficial, and I don't see one.

**Comment by ProgVal** [comment]
> There has to be a reason why changing this would be beneficial, and I don't see one.

To make it possible for clients to know there is no topic without sending TOPIC or hardcoding a timeout.

**Comment by Adam-** [comment]
Topic is always sent prior to /names, and /names are always sent.

**Comment by ProgVal** [comment]
Is that documented somewhere?
