### ISSUE TITLE
“CAP LIST” instead of “CAP LIST :” as a reply

### ISSUE THREAD

**Issue by ProgVal** [inspircd/inspircd#1120]
```
1450915220.264 1 -> S: CAP LIST
1450915220.264 S -> 1: :irc.example.com NOTICE * :*** Skipping host resolution (disabled by server administrator)
1450915220.264 S -> 1: :irc.example.com CAP * LIST 
```

Expected behavior: the server sends `CAP * LIST :`

[IRCv3.1 capability negotiation](http://ircv3.net/specs/core/capability-negotiation-3.1.html#the-cap-list-subcommand):
> If no capabilities are active, an empty parameter must be sent.

**Comment by DanielOaks** [comment]
From what's pasted there, it seems like there is a trailing space after the server's `LIST`, ie this is the full reply from the server: `":irc.example.com CAP * LIST "`

If this is the case then there is an empty parameter (due to that trailing space).

**Comment by ProgVal** [comment]
According to RFC 1459, the grammar for lines is:

```
<params>   ::= <SPACE> [ ':' <trailing> | <middle> <params> ]

<middle>   ::= <Any *non-empty* sequence of octets not including SPACE
               or NUL or CR or LF, the first of which may not be ':'>
<trailing> ::= <Any, possibly *empty*, sequence of octets not including
                 NUL or CR or LF>
```

So, as `<middle>` is not allowed to be empty, only `<trailing>` may.

**Comment by SaberUK** [comment]
I think this is a recent breakage with @attilamolnar's new CAP stuff because 2.0 doesn't do this.

**Comment by attilamolnar** [comment]
Correct, before fixing this I need to learn more about a supposed mIRC bug with regards to a trailing space in the cap list. @DanielOaks can you elaborate?

**Comment by ProgVal** [comment]
As far as I know, Charybdis and Mammon append a space to capability lists in LS to that mIRC splits the list appropriately.
InspIRCd does not do this for LS, so I guess the policy in InspIRCd is to ignore that mIRC does not follow the spec

**Comment by attilamolnar** [comment]
Yes I understand that much, but I wonder what happens without the trailing space. Does it fail to recognize the last cap in the list or fail completely?

**Comment by attilamolnar** [comment]
Fixed, thanks.
