### ISSUE TITLE
Implement channel shun (cshun)

### ISSUE THREAD

**Issue by emagaliff** [inspircd/inspircd#1129]
A channel-level shun command (/cshun) would add another helpful moderation tool available to channel ops and half-ops in addition to the current ban + extbans. While it is currently possible to mute a user in a channel, this can be seen by all and the user is notified when they try to speak.

As it stands now, trolls frequently change hosts/nicks/idents upon noticing a ban put into place. Adding the ability for OPs to invisibly silence users will reduce extban evasion and potentially reduce the frequency of ban evasion.

**Comment by Robby-** [comment]
This is somewhat related to #1096. I still need to forward-port that to 2.2 though. It doesn't add channel shuns but does address the issue that users get notified when trying to speak, and allows for those notifications to be disabled.

**Comment by SaberUK** [comment]
Add the b mode to `<options:hidemodes>`.

https://github.com/inspircd/inspircd/blob/insp20/docs/conf/inspircd.conf.example#L669-L672

**Comment by emagaliff** [comment]
@Robby- Thanks. My main concern with removing notifications from muteban is that the ban list can still be viewed by anyone in the channel, as well as ```user sets mode +b *!*@*``` appears in the channel.

@SaberUK I considered that as an option. With the mode notification for +b appearing in the channel, hiding the banlist doesn't solve the issue of trolls/evaders seeing that they were banned. /cshun should not provide any mode notification or warning to the user, except possible a notice visible only to other ops.

**Comment by SaberUK** [comment]
>With the mode notification for +b appearing in the channel, hiding the banlist doesn't solve the issue of trolls/evaders seeing that they were banned.

We could add an option to m_hidelist to hide the list mode change from unprivileged clients. Would that work for you?

**Comment by MuffinMedic** [comment]
That could work if it was paired with the ability to disable any "You are not authorized to speak in this channel" messages, or anything that would indicate to the user they've been moderated.

**Comment by SaberUK** [comment]
In v3 you can hide the setting of the ban mode from unprivileged users which I think covers the issue reported here.
