### ISSUE TITLE
GnuTLS not working on windows in 2.0.21

### ISSUE THREAD

**Issue by eremini** [inspircd/inspircd#1137]
Hey,

Just updated my windows box from .20 to .21 and not able to start anymore. Logs show:

Fri Feb 19 00:33:01 2016: Unable to load m_ssl_gnutls.so: A dynamic link library (DLL) initialization routine failed.
Fri Feb 19 00:33:01 2016: Unable to load m_ssl_gnutls.so: A dynamic link library (DLL) initialization routine failed.

Let me know what other info you might need.

Regards,
Ilya

**Comment by Adam-** [comment]
What OS?

**Comment by eremini** [comment]
2012 R2 Standard

**Comment by Adam-** [comment]
Maybe load the dll into dependency walker and see if it is missing any dependencies. I am able to run the installer and load m_ssl_gnutls fine on Windows 7 x86.

**Comment by Adam-** [comment]
Download ftp://ftp.gnutls.org/gcrypt/gnutls/w32/gnutls-3.4.9-w32.zip, drop the dlls in bin/ over top of the dlls in the inspircd install.

**Comment by Adam-** [comment]
I've updated the Windows release package to contain fixed dlls.
