### ISSUE TITLE
Voice to Override NickServ

### ISSUE THREAD

**Issue by dannymichel** [inspircd/inspircd#1138]
I have InsIRCD 2 and Anope 2 installed. Basically, what i want is voice to override registering. i need for people to be registered to talk in any channel on the server, and when they register, they get auto-voice, but if they aren’t registered, i want to be able to voice them myself so they can talk even if not registered.

**Comment by del6597** [comment]
This doesn't make sense to me. Can you try to reword it and be more specific?  What is "out-voice"? What do you mean you want "voice to override registering"?  Registration happens outside of channels, so having voice shouldn't affect that at all.

**Comment by dannymichel** [comment]
Apologies, I meant auto-voice. 
I think what I may have been looking for is a combination of '/cs levels #channel set autovoice 0' and setting the mode to +m, but the only problem with that is the IRC client just tells the user that 'their message cant be sent to the server' rather than a message like 'you need to register with NickServ using /msg nickserv......xxx'. I know it may be a little off topic, but how would you recommend creating such a notification for unregistered(unvoiced) users?

**Comment by SaberUK** [comment]
You could set an entry message maybe?

**Comment by del6597** [comment]
If you change the mode to +M, does the error message change to say their message was blocked because they aren't registered?

**Comment by dannymichel** [comment]
"You could set an entry message maybe?" how do you recommend doing that?

"If you change the mode to +M, does the error message change to say their message was blocked because they aren't registered?" not if the mode is also set to +m. If just set to +M, it doesn't use the voice moderation. If set to +Mm, the message does not include the nickserv register.

**Comment by GLolol** [comment]
> "You could set an entry message maybe?" how do you recommend doing that?

Use services. `/cs help entrymsg` on Anope.

Looking at the original issue, you can use levels in Anope to set the VOICEME access to 0 (all users who aren't banned). That way, normal users should be able to use `/cs voice` on themselves. Entrymsg or topic should obviously tell them how to do that.

**Comment by SaberUK** [comment]
If you are still having issues with this then please contact the developer of your services package in question:

Anope - irc.teranova.net #anope

Atheme - irc.freenode.net #atheme
