### ISSUE TITLE
Glines placed by filters are not logged

### ISSUE THREAD

**Issue by Robby-** [inspircd/inspircd#1151]
When using the `gline` action, glines placed by filters are not logged like regular glines are.

**Comment by SaberUK** [comment]
This is because the message is sent out in cmd_gline rather than being done when an XLine is actually set. When we rewrite the xline system we should probably move that.

**Comment by attilamolnar** [comment]
The same applies to the `kill` action as reported in #1263

**Comment by Robby-** [comment]
@SaberUK: Closing this manually since #1264 got merged as 6cfa00e862ed9615438c0a1c6faef12f228e46ef.
