### ISSUE TITLE
New apacheauth module

### ISSUE THREAD

**Issue by vccu** [inspircd/inspircd#1152]
Authenticates users against an Apache auth file.

**Comment by vccu** [comment]
https://git.collabora.com/cgit/user/vincent/inspircd/.git/commit/?h=apacheauth

**Comment by SaberUK** [comment]
Hi, can you file a pull request agains the [inspircd-extras](https://github.com/inspircd/inspircd-extras) repository?

**Comment by vccu** [comment]
OK, opened at https://github.com/inspircd/inspircd-extras/pull/75
Closing this one then, thanks.
