### ISSUE TITLE
inspircd script undocumented option with crontab fails

### ISSUE THREAD

**Issue by Robby-** [inspircd/inspircd#1155]
I'm using crontab to have the ircd restart, like so:
`0,10,20,30,40,50 * * * * /home/ircd/insp20-install/inspircd cron --config=/home/ircd/insp20-install/conf/hub-inspircd.conf>/dev/null`

As you can see I'm using the undocumented `--config=` option which works fine with the `start` command, but not with the `cron` command, it results in this error:
```
ERROR: Cannot open config file: /home/ircd/insp20-install/conf/inspircd.conf
Exiting...
```
effectively making it impossible to configure crontab this way.

I'm using this undocumented option because I'm running multiple inspircd instances and it is very useful for this situation.

**Comment by SaberUK** [comment]
Try getting rid of the >/dev/null and seeing if it works then?

**Comment by attilamolnar** [comment]
@SaberUK do you wish to support the undocumented option in master?

**Comment by SaberUK** [comment]
@Robby- Can you test this? https://github.com/SaberUK/inspircd/commit/85b4908a3057d1a377c8f02fd54ca7311c358110

@attilamolnar This is actually caused by a bug which should hopefully be fixed in the commit I just asked @Robby- to test.

**Comment by Robby-** [comment]
@SaberUK: That commit fixes the issue. Thanks!
