### ISSUE TITLE
v2.0.21 build/make warning

### ISSUE THREAD

**Issue by crazycorndog** [inspircd/inspircd#1160]
hi, i got the following warning (yeah i know, it's just a warning) when building release 2.0.21 on ubuntu trusty (14.04LTS):
inspircd/src/modules/m_hideoper.cpp: In member function ‘virtual ModResult ModuleHideOper::OnNumeric(User*, unsigned int, const string&)’:
inspircd/src/modules/m_hideoper.cpp:97:88: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 5 has type ‘size_t {aka unsigned int}’ [-Wformat=]
user->WriteNumeric(252, "%s %lu :operator(s) online", user->nick.c_str(),  opercount);

**Comment by SaberUK** [comment]
@crazycorndog Can you confirm whether applying #1174 fixes this?

(It should, just double checking).

**Comment by crazycorndog** [comment]
yes, looks good, no warning anymore. thank you.
