### ISSUE TITLE
m_chanfilter: Oper override

### ISSUE THREAD

**Issue by Brainscrewer** [inspircd/inspircd#1161]
Currently when chanmode +g is set for certain words, for example `*#*`, IRC Operators are also affected. 

In my opinion IRC Operators should be able to override this if they have enough access as defined in the configuration.

**Comment by B00mX0r** [comment]
This is already implemented in v3.0, as m_chanfilter calls to OnCheckExemption for "filter." Use m_exemptchanops.

**Comment by SadieCat** [comment]
Since commit e2b50c3551 server operators with the `channels/ignore-chanfilter` oper privilege are exempt from channel filters.
