### ISSUE TITLE
Undefined symbol in gnutls

### ISSUE THREAD

**Issue by KeiroD** [inspircd/inspircd#1164]
Hi,

Fresh installation of `inspircd`, v2.0.21.

OS: Ubuntu
Shell: bash
GnuTLS-version: 

```
ircd@boxen:~/inspircd/bin$ gnutls-cli -v
gnutls-cli (GnuTLS) 2.12.23
Packaged by Debian (2.12.23-12ubuntu2.5)
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Nikos Mavrogiannopoulos.
```

This is the following logs:

```
[*] Loading module:     m_serverban.so
[*] Loading module:     m_showwhois.so
[*] Loading module:     m_shun.so
[*] Loading module:     m_sslmodes.so
[*] Loading module:     m_ssl_gnutls.so

[*] Unable to load m_ssl_gnutls.so: /home/ircd/inspircd/modules/m_ssl_gnutls.so: undefined symbol: gnutls_x509_privkey_import
```

What do, Captain? Google™ seems to not know what to do with this particular error, so I've come here to see if anyone might have an idea of how to resolve this.

**Comment by SaberUK** [comment]
You probably built against a different version of the development headers to the library you have installed.

**Comment by KeiroD** [comment]
Hi,

Output of dpkg is as follows:

```
root@boxen:/home/ircd/inspircd/conf# dpkg -s libgnutls-dev
Package: libgnutls-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 2327
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: gnutls26
Version: 2.12.23-12ubuntu2.5
```

This seems to be the latest version?

**Comment by SaberUK** [comment]
What about the library package?

**Comment by KeiroD** [comment]
That outputs the following, if I remember correctly what you're asking for:

```
root@boxen:~$ dpkg -s gnutls-bin
Package: gnutls-bin
Status: install ok installed
Priority: optional
Section: net
Installed-Size: 748
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: foreign
Source: gnutls26 (2.12.23-12ubuntu2.5)
Version: 3.0.11+really2.12.23-12ubuntu2.5
```

I'm pretty sure I had this right, I just still can't get the blasted thing to load gnutls.so... heck, `openssl` works just fine. :/

**Comment by Robby-** [comment]
That is the binary package, you need the _library_ package. On Debian this is called `libgnutlsxx28`, so maybe on Ubuntu it is called `libgnutls`, judging by how `libgnutls-dev` is called in Ubuntu.

**Comment by KeiroD** [comment]
Ah, right.

Forgive me, I just woke up not too long ago.

```
root@boxen:/etc/webmin# dpkg -s libgnutls26
Package: libgnutls26
Status: install ok installed
Priority: standard
Section: libs
Installed-Size: 1072
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: same
Source: gnutls26
Version: 2.12.23-12ubuntu2.5
Replaces: gnutls0, gnutls0.4, gnutls3
```

**Comment by SaberUK** [comment]
I'm not really sure then. Try running `./configure --clean` to do a fresh configure run and then rebuild.

**Comment by KeiroD** [comment]
Alas, that method doesn't work, either.

I'm thinking I may need to do an OS reload to a newer version of Ubuntu to see if this is still an issue or something because this is a weird, weird issue that I've never encountered before until now.

I'll report back once I've done that... after backing up a few things on the server that I'd rather not have to deal with reinstalling. :P

**Comment by SaberUK** [comment]
@KeiroD Did that work?

**Comment by KeiroD** [comment]
Running with `./configure --clean`? No, it didn't. I haven't had the opportunity to try either a. a rebuild of gnutls or b. an OS reload with Ubuntu 15.10 yet but I wanted to answer your question.

**Comment by SaberUK** [comment]
Can you try uninstalling all of the GnuTLS packages and then install libgnutls28-dev and then gnutls-bin?

**Comment by SaberUK** [comment]
Note: You might need to run `./configure -clean` again after doing this to clear the cache.

**Comment by SaberUK** [comment]
@KeiroD Any updates?

**Comment by KeiroD** [comment]
@SaberUK, sorry for the extremely late update.

Works fine on my Pi. Also works fine on another server that I tried installing `libgnutls28` on, after testing to ensure that I was able to reproduce it... and it was indeed reproducible.

**Comment by attilamolnar** [comment]
Closing, please comment if there's still an issue.
