### ISSUE TITLE
lockserv module: ability to specify a custom message and have the commands work remotely

### ISSUE THREAD

**Issue by Robby-** [inspircd/inspircd#1177]
It would be nice if the `LOCKSERV` command accepted an optional custom message, for example:
`LOCKSERV Please use irc.example.tld as this server is getting decommissioned soon.`
Or even via a config option in `modules.conf`. As currently it is needed to hard-code and recompile the module with a custom message.

Another feature I think would be nice to have is if the commands `LOCKSERV` and `UNLOCKSERV` worked remotely as well, although I'm not sure how that would work if the above feature request were to be implemented. As the command syntax would need a change in that case. Maybe it could work like this for example, with a message:
`LOCKSERV server.example.tld This server is scheduled for maintenance, use irc.example.tld.`
Without a message: `LOCKSERV server.example.tld`
And subsequently: `UNLOCKSERV server.example.tld`.
The commands would have to have some logic to determine if a server name was specified or not as the first parameter.

**Comment by SaberUK** [comment]
@Robby- How about this? https://github.com/inspircd/inspircd/compare/master...SaberUK:master+lockserv

**Comment by Robby-** [comment]
I can't actually test it due to not having a master branch server set up yet.

**Comment by attilamolnar** [comment]
Custom reason has been implemented by @SaberUK in #1185. Remote unlock can be implemented via a special rehash flag for example.
