### ISSUE TITLE
No more windows installer

### ISSUE THREAD

**Issue by narucy** [inspircd/inspircd#1180]
Using Windows Installer and copy files to "C:\Program Files (x86)\Inspircd" that is a lot of problem.

Inspircd must run with Administrator level user. Normal user can not run because  "C:\Program Files (x86)\Inspircd\logs" directory can't write. that is not good.

I try normal user running but basically Inspircd must run in "C:\Program Files (x86)\Inspircd" directory, no way to loading modules in other directory.

Finally I found good way to install to Windows, all copying file "C:\Program Files (x86)\Inspircd\**" to "c:\users\xxx\Inspircd" and run. It's work perfectly.

Installer is pretty annoying and confusing in some uses. Inspircd should remove insaller program and just zip package enough!!

**Comment by SaberUK** [comment]
You should change the permissions for the InspIRCd directory to allow you to write to it rather than moving the installation.

@Adam- Would it be possible for us to do this automatically? I know that Steam can do it so we should be able to...

**Comment by attilamolnar** [comment]
We want to keep the Windows installer. #951 is already open about changing the default install path.
