### ISSUE TITLE
Delay Join without m_delayjoin module

### ISSUE THREAD

**Issue by TuSuNaMi** [inspircd/inspircd#1188]
Hello;

My requirements needs delay join without m_delayjoin module. Because this module hide users until they speak. How can I resolve this?

Thanks,
Muharrem

**Comment by SaberUK** [comment]
This is not possible as the entire point of delayjoin is to hide users until they speak.

Please ask questions like this in \#inspircd in the future.

**Comment by attilamolnar** [comment]
Hello. Hiding joins but at the same time showing the user in the member list is something you need client support for, not server support.

**Comment by TuSuNaMi** [comment]
I want wait all users some period than join to autojoin channels this simple I think
