### ISSUE TITLE
ugly output during make j6

### ISSUE THREAD

**Issue by BrickerBrickerOneNine** [inspircd/inspircd#1192]
Everything is looking fine and pretty, then a mess of stuff comes out. Maybe put it at the bottom or format it better so it doesn't look all jumbled. we don't want people to think an error occurred. 

```
        BUILD:      modules/m_sqlauth.cpp
    BUILD:      modules/m_sqloper.cpp
Evaluating perl code for module m_ssl_gnutls.cpp ... (Created and executed /tmp/hMwNAVuo6p)
Locating include directory for package gnutls for module m_ssl_gnutls.cpp... -I/usr/include/p11-kit-1   -DVERSION_GNUTLS="2.12.23" (version 2.12.23)
Evaluating perl code for module m_ssl_gnutls.cpp ... (Created and executed /tmp/Tsn96Pyucy)
Checking version of package openssl is >= 0.9.7... Locating library directory for package gnutls for module m_ssl_gnutls.cpp... Yes (version 1.0.1f)
Locating include directory for package openssl for module m_ssl_openssl.cpp... -lgnutls   (version 2.12.23)
    BUILD:      modules/m_ssl_gnutls.cpp
-DVERSION_OPENSSL="1.0.1f" (version 1.0.1f)
Locating library directory for package openssl for module m_ssl_openssl.cpp... -lssl -lcrypto   (version 1.0.1f)
    BUILD:      modules/m_ssl_openssl.cpp
    BUILD:      modules/m_sslinfo.cpp
```

Edit: fixed formatting

**Comment by BrickerBrickerOneNine** [comment]
the PATHS: section after INSTALL COMPLETE is not formatted like it is during ./configure...

also, it says to start the ircd /fullpath/ and then tells you to remember to configure the inspired.conf and then tells you about sample configs. i think it shouldn't tell you to run before it tells you to use the example config to create the main config. i think what appears to be 3 different steps is really 1 step with sub categories, so perhaps it should say 

"You're almost there. If you have a config for this version, go ahead and place it in your folder and type inspircd start, otherwise head over to /EXAMPLE CONF PATH/ and edit the file to your specifications, be sure to save it as inspired.conf and than issue inspircd start"

not word for word, but maybe something like that.

**Comment by SaberUK** [comment]
Should be cleaner in v3.
