### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by carlosferry** [inspircd/inspircd#1194]
Instead of defining both argv and argc within InspIRCd::InspIRCd(int argc, char** argv), why not simply use an init within ServerConfig::ServerConfig(), such as ServerConfig::ServerConfig() : argc(argc), argv(argv), in configreader.cpp ?

**Comment by attilamolnar** [comment]
The `argv` and `argc` fields are in class `CommandLineConf` so I'm not sure what you mean, can you please illustrate it with actual patch?

**Comment by carlosferry** [comment]
I'm aware of that. However, both argv and argc  are defined at the very end of class InspIRCd (row 398), is there any reason why these two aren't defined on         this->Config = new ServerConfig(argc, argv), instead of this->Config->cmdline.argv = argv (row 388)?

**Comment by Adam-** [comment]
This isn't the correct place for code related questions, use irc.inspircd.org#inspircd.dev for that. If you believe you have a code improvement, open a pull request instead.
