### ISSUE TITLE
m_shun - Add CIDR support

### ISSUE THREAD

**Issue by Robby-** [inspircd/inspircd#1195]
It would be nice if m_shun would have support for CIDR masks as well, like `*!*@2001:DB8::/32`, `*!*someuser@2001:DB8::/32`. Currently one must revert to wildcards to achieve the desired effect, like `*!*@2001:DB8:*`

I'm hoping this can be implemented into the 2.0 branch as this is a feature request that really shouldn't break anything at all, and would enhance the shun module greatly.

**Comment by attilamolnar** [comment]
This has been implemented.
