### ISSUE TITLE
Unicode channel /join

### ISSUE THREAD

**Issue by Doemela** [inspircd/inspircd#1197]
I have a users that can join channels with Unicode Character 'ZERO WIDTH NON-JOINER' (U+200C) an Unicode Character 'RIGHT-TO-LEFT OVERRIDE' (U+202E)

This creates channels that look like other channels with same name because ppl wont see the Unicode behind chan name

InspIRCd 2.0.21

**Comment by SaberUK** [comment]
This is intentional behaviour. If you don't want those chars in your channel names then block them with [m_channnames](https://wiki.inspircd.org/Modules/2.0/channames).

**Comment by Doemela** [comment]
What is the  IRC Control code for U+200C and U+202E ?

**Comment by Doemela** [comment]
Would that be 200 ?

**Comment by Doemela** [comment]
When I do /JOIN #Ctrl+k200 I get #0 Invalid channel name in mIRC but when I add a space between # and Ctrl+k200 /JOIN # Ctrl+k200 I can join that channel 

> Space, bell, and comma will ALWAYS be disallowed in channel names due to the IRC protocol.

**Comment by kaniini** [comment]
It depends on the encoding.
As mentioned on the atheme bug, IRC channel names are considered an arbitrary sequence of bytes.

InspIRCd as @SaberUK mentions supports blocking whitespace or alternative characters using m_channames.

If you feel it is a bug, you should request a relevant standards body (likely the IRCv3 group) to do an editorial clarification stating that channel names aren't arbitrary sequences of bytes.

**Comment by Doemela** [comment]
I understand that but where can I find the "IRC Control codes" of blocking whitespace or alternative characters in https://wiki.inspircd.org/Modules/2.0/channames ? Example only shows (Bold, color, reset, underline, reverse).

**Comment by Doemela** [comment]
@kaniini 

>It depends on the encoding.
As mentioned on the atheme bug, IRC channel names are considered an arbitrary sequence of bytes.

>InspIRCd as @SaberUK mentions supports blocking whitespace or alternative characters using m_channames.

>If you feel it is a bug, you should request a relevant standards body (likely the IRCv3 group) to do an editorial clarification stating that channel names aren't arbitrary sequences of bytes.

Why is it not allowed in a nickname and in channelname it is?

**Comment by Adam-** [comment]
This is not a bug and is the intended behavior. As stated, use m_channames if you want to block specific single-byte characters.

**Comment by attilamolnar** [comment]
There's also m_cban and m_denychans which can be used for blocking wildcard strings in channel names.

**Comment by Doemela** [comment]
@attilamolnar Ty
