### ISSUE TITLE
SASL vhost improvements to consider for 2.2

### ISSUE THREAD

**Issue by Techman-** [inspircd/inspircd#1198]
As it stands in InspIRCd 2.0, services rely on CHGHOST in order to set a user's vhost during SASL authentication, compared to [other IRCds that use SVSLOGIN](https://github.com/grawity/irc-docs/blob/master/server/ts6.txt#L898-L914). It's a separate command that has to be sent from a services server, but this in itself isn't an issue. I mention SVSLOGIN as a potential solution to be discussed further below.

CHGHOST doesn't quite do the job in 2.0 for SASL purposes, for a few reasons. I'll give a case for Anope and a case for Atheme, based on how they behave as of this issue.
## Anope

In Anope, if a user has a vhost tied to their account, it will send `CHGHOST` as soon as it sees the `UID` command from the uplink. This is currently the best way to handle setting vhosts, because sending it before SASL success won't actually stick post-registration if a network has +x as an on-connect umode for that connect class.
## Atheme

In Atheme, [it will send](https://github.com/atheme/atheme/blob/36f1b1a3712058639cac34a2ef51296eb5dfbcb0/modules/protocol/inspircd.c#L721-L728) (ENCAP'd) `CHGHOST` if there's a vhost tied to the user's account. You'll see it during your SASL authentication session, but it won't stick after IRCd registration if you match a connect class that has +x by default. You'll send up with a hashed hostname anyways, which Atheme detects and has to send your vhost _again_, which is a problem because **users could already be in a channel**, which dampens the usability of vhosts as it adds extra cyclehost spam.

Here's some client logs that help show what I'm speaking about:

> 02:41:00 AM    <-->    irc: client capability, enabled: away-notify extended-join account-notify multi-prefix sasl userhost-in-names
> 02:41:00 AM    <-->    You are now logged in as Techman (Techman!Techman@clank.techtronix.net)
> 02:41:00 AM    <-->    techmansworld.com :is now your displayed host
> 02:41:00 AM    <-->    SASL authentication successful
> (...)
> 02:41:03 AM    <-->    allrednc-76oskp.techtronix.net :is now your displayed host
> 02:41:03 AM    <-->    User mode [+ixR] by Techman
> (...)
> 02:41:04 AM    <-->    User mode [-x] by Tetris.AllredNC.org
> 02:41:04 AM    <-->    techmansworld.com :is now your displayed host
## Solutions

I doubt this behavior will be improved upon in 2.0, outside of possibly writing a module that would go into inspircd-extras, hoping that service packages move to support this additional module (even if written by devs that produce vendor mods), so my solutions are more geared towards InspIRCd 2.2 since it isn't in any kind of feature-freeze. I still silently hope that something can be done in 2.0 in the meantime since it technically is an issue, but I digress.
### Solution 1: Handle CHGHOST Better

This solution is probably the easiest, I think. Improve CHGHOST on InspIRCd to actually maintain host changes through user registration, so on connect umodes like +x won't reset the user's displayed host, causing a service daemon to send the vhost again (like Atheme does), or add checks in other modules to not interfere with a vhost if there is one set.

Doesn't require adding anything new in terms of commands, and it actually allows services to reliably send vhosts before sending SASL `D S` and not worry about them. Same thing could apply for CHGIDENT as well, although there could be some situations where you might want a user's ident to remain set to something you configure, like CGI:IRC. Perhaps services could send CHGIDENT and InspIRCd can ignore it when needed, and keep it applied in all other situations.
### Solution 2: SVSLOGIN

We could implement something like SVSLOGIN that Charybdis uses, which allows us to set stuff like vidents and vhosts alike, all in one message. SVSLOGIN could then be translated into the `accountname` metadata and so on, I guess.

---

Part of this issue was me thinking out loud, so I apologize if some things don't make sense; point these out and I can correct/comment.

**Comment by attilamolnar** [comment]
What about using `registered="false"` in the connect block which sets +x on connect? That should work if all registered users using sasl get a vhost from services.

**Comment by Techman-** [comment]
Can you elaborate more, please?

**Comment by SaberUK** [comment]
>This solution is probably the easiest, I think. Improve CHGHOST on InspIRCd to actually maintain host changes through user registration, so on connect umodes like +x won't reset the user's displayed host, causing a service daemon to send the vhost again (like Atheme does), or add checks in other modules to not interfere with a vhost if there is one set.

This has been fixed in 692865acd58c9a475db1fdf4d419188325cd2182. Please reopen if this is still an issue.
