### ISSUE TITLE
MOD: prevent ban removals by hierarchy of +h +o, etc...

### ISSUE THREAD

**Issue by BrickerBrickerOneNine** [inspircd/inspircd#1204]
A module that would prevent a channel half-op +h for example, from removing a ban set by say +q or +o op. This could prevent unwanted behavior set by a channel owner, still allowing halfops to help manage the channel, without undoing something they shouldn't.

**Comment by koaxirc** [comment]
If you cannot trust your halfops to manage without taking ownership, a new module isnt the resolution, changing your halfop's would be.

**Comment by BrickerBrickerOneNine** [comment]
That is the type of bullying behavior young and naive people take. You
can't trust anyone. I mean let's say someone you trust accidentally leaves
their computer unprotected and someone they thought they could trust messes
with them because they were a bad judge of character? Don't make comments
dictating how others should or should not run their channels. That's silly.

**Comment by SaberUK** [comment]
This does seem useful but i'm not sure how easy it would be to implement as as list mode entries are not `Extensible`s.

**Comment by sebastiannielsen** [comment]
Could be done. Since the ban setter's name is in the banlist, it could check the CURRENT status of the bansetter (if he is online) and if it higher than the person trying to remove the ban, it will reject.

This ofcourse means that if the bansetter disconnects or if his rank is lowered, the ban can be removed accordingly.

**Comment by Heufneutje** [comment]
That seems way too wonky and unreliable to be a proper solution. Maybe if it could hook into ChanServ it could work.

**Comment by sebastiannielsen** [comment]
The problem with hooking into chanserv is that services are different, you can run inspircd with a lot of different services packages.
And they are not the same. It could be something that works something like MLOCK that simply reverses the action if its unpermitted, but that would be a module for your favorite services package, not for inspircd.

I also looking on other solutions like saving the status of a nick (which rank a nick DID have Before disconnecting) in a non-persistent database and then using that to determite the required rank to remove a ban, but it can cause a problem if a OP disconnects, the channel leader decides to not have him as OP longer and he reconnects, then the ban will still be "locked" to OP and above. Could be solved by voicing and devoicing the person in question.

Feel free to come with more ideas.
