### ISSUE TITLE
Small modification to the start up inspircd perl script

### ISSUE THREAD

**Issue by ghost** [inspircd/inspircd#1206]
Two things:

Wouldn't it be nice to have an user-friendly output print for the inspircd manager perl script?
I'd recommend something like:

use Term::ANSIColor qw(:constants);
sub show_error(@)
{
my $errorstr = shift;
print BLACK, "[", BLINK BOLD RED, "ERROR", RESET, BLACK, "] ", RESET, $errorstr, "\n";
}

sub show_ok(@)
{
my $okstr = shift;
print BLACK, "[", BLINK BOLD GREEN, "OK", RESET, BLACK, "] ", RESET, $okstr, "\n";
}

Moreover,
I'd use it for the first time within cmd_restart, what about something like:

sub cmd_restart(@)
{
if (getstatus() == 0)
{
show_error("Inspircd is not running; you can't restart the IRCd. Nuf said.");
return 0;
}

cmd_stop();
unlink($pidfile) if (-e $pidfile);
goto &cmd_start;

}

**Comment by Adam-** [comment]
Instead of sending this in as an issue, file a pull request with the change.

**Comment by SaberUK** [comment]
We are unable to use the `Term::ANSIColor` package as it needs to be installed from CPAN which adds an extra step to installing InspIRCd for very little gain.

As the original poster has deleted their GitHub account i'm going to close this.
