### ISSUE TITLE
need some help

### ISSUE THREAD

**Issue by driftypuddle** [inspircd/inspircd#1209]
Hello I need some help

I tried to find a forum but unable to find one for inspircd

so how can I use ascii in nick name like ▀▄▀▄▀▄wнaтnoт▄▀▄▀▄▀ is there a module for this ?

Many Thanks
David

**Comment by Googolplexed** [comment]
For InspIRCd help, join the #inspircd channel on irc.chatspike.net
(You'll want m_nationalchars, but it might take a bit of configuration)

**Comment by driftypuddle** [comment]
After review and read information it may not be good thing to have because got to think of services as well
