### ISSUE TITLE
Change in /stats P

### ISSUE THREAD

**Issue by Yorgosgr** [inspircd/inspircd#1212]
Hello,

I would like to propose a small change to /stats P.
Since me and some other people i guess use mode +H to hide ircop status but still have +h the helper one can /stats P show people that have +h usermode no matter if they have +H or not so that staff that has +h umode are shown

**Comment by del6597** [comment]
You can be a helper (+h) but not an ircop (+o), so why should /stats P show non-ircops?

**Comment by Yorgosgr** [comment]
well yeah so people know who is available for help. kinda like a staff list. Or perhaps a module to be created that shows with a /staff command all the staff the admin wants shown?

**Comment by Yorgosgr** [comment]
actually /staff must show active +h people
