### ISSUE TITLE
Mode change hiding

### ISSUE THREAD

**Issue by Yorgosgr** [inspircd/inspircd#1218]
Hello,

I was going through the inspircd.conf to check something and my eye got caught in this setting:
# hidemodes: If enabled, then the listmodes given will be hidden

```
      # from users below halfop. This is not recommended to be set on +b
      # as it may break some functionality in popular clients such as mIRC.
      hidemodes="eIg"
```

I was thinking since this setting hides the /mode #room +g reply with the channel spamfilter list can we disable people seeing when a +g is set? for example:
/mode #room +g asshole produces this result
- nick sets mode: +g asshole <--- Can this be hidden from users so they dont see that  badword is set? 

I find that it is of little use to hide the list when a user can see the word beeing set

**Comment by TurkDesk** [comment]
kinda good idea, can also apply for other modes like +beI not just +g

**Comment by attilamolnar** [comment]
Any ideas about configuration? Should it be global like now or per channel? What would happen if we allowed hiding any mode change, not only list modes?

**Comment by SadieCat** [comment]
This is possible in v3 with the hidemode module.

https://docs.inspircd.org/3/modules/hidemode/
