### ISSUE TITLE
DNSBL and webchat users: occasional erroneous address shown in the announcement message

### ISSUE THREAD

**Issue by Robby-** [inspircd/inspircd#1229]
Occasionally the ircd will show the IP address of the server where the webchat instance is running on in the ANNOUNCEMENT message when a blacklisted user is connecting:

```
XLINE: Z:line added due to DNSBL match on *@194.187.249.135 to expire on Wed Sep 28 21:37:29 2016: Tor not allowed.
ANNOUNCEMENT: Connecting user ggg!57oz7fquu@<<our own webchat IP address here>> detected as being on a DNS blacklist (tor.dnsbl.sectoor.de) with result 1
```

I had reported this in #717 as well but it turns out the fix provided for that issue did not fix this particular issue where it occasionally shows the wrong address.

InspIRCd version is `2.0.23-2-ge991c29`.

**Comment by SaberUK** [comment]
Speculative fix: https://github.com/inspircd/inspircd/compare/insp20...SaberUK:insp20+ipcache

@Robby- Can you test?

**Comment by Robby-** [comment]
@SaberUK: I've been testing this for over a week now, and today it finally happened again.

**Comment by SaberUK** [comment]
@Robby- Has this been happening recently or have we finally splatted it?

**Comment by Robby-** [comment]
No, this still happens. Yesterday, for example.

**Comment by Robby-** [comment]
Yes, we are running 2.0.25, 758cf50 to be specific. So, 52de083 is included in it.

**Comment by SadieCat** [comment]
@Robby- Have you seen this recently in v3?

**Comment by Robby-** [comment]
We are still on v2 because reasons, so unfortunately I can't say if this is still a thing or not.

**Comment by SadieCat** [comment]
I think this is fixed. If you find that it is not then please comment and I'll reopen.
