### ISSUE TITLE
Channel keys with commas

### ISSUE THREAD

**Issue by AndrioCelos** [inspircd/inspircd#1231]
You can set a channel key (mode `+k`) containing a comma. It seems that, because the comma is used as a delimiter in the `JOIN` command, InspIRCd 2.0.23 won't let users join the channel normally at all.

**Comment by del6597** [comment]
The IRC RFC is very specific about how JOIN messages are to be interpreted and is not specific about channel key validity.  My thought would be to not allow commas in the channel key.  If you were to view a comma in a channel key as a sort of mechanism to keep people out, then you should really just be using +i in the first place.

**Comment by SaberUK** [comment]
Other server implementations strip the comma when setting +k. We should probably do that too.

**Comment by Heufneutje** [comment]
I can imagine setting the channel key with the comma stripped might get confusing if you don't know that the comma in your password was stripped though. I think just rejecting the mode change altogether might be a better solution.

**Comment by SaberUK** [comment]
Fixed in aa78793b3a8003a248d98c700a1f842fe8a92b47.
