### ISSUE TITLE
need helpop for extra modules

### ISSUE THREAD

**Issue by TurkDesk** [inspircd/inspircd#1237]
We do need some way to have helpop content for the modules in inspircd-extras so that when someone does /helpop can see how to use the commands of a module by extras.
Or just add any extra modules help to helpop-full in simpler way i guess.

**Comment by SaberUK** [comment]
Try asking the author of whoever wrote the module in question to provide you with a helpop file.

**Comment by TurkDesk** [comment]
I did not mean for a single module, just in general modules should have this imo.

**Comment by SaberUK** [comment]
We do not support extra modules. Providing documentation for them is the responsibility of the author.

**Comment by attilamolnar** [comment]
Duplicate of #489. For now, extra modules can include `<helpop>` configuration tags that admins can paste into their configs.
