### ISSUE TITLE
One second delay during NOTICE Auth.

### ISSUE THREAD

**Issue by WesleyChannon** [inspircd/inspircd#1242]
Hi there!

I've been running a few concurrent connection benchmarks with some development code I've written my end (a websockets-based IRC client) with inspircd 2.0.x and have noticed a strange 1 second delay between the following connection events when connecting to a client port bound to 127.0.0.1:

:server NOTICE Auth :*** Found your hostname (localhost)
:server NOTICE Auth :Welcome to NETWORK!

This appears to happen regardless of if the 'resolvehostnames' is set to 'no' in the associated connection block configuration.

I'm sending the WEBIRC, PASS, NICK and USER statements (in that order) as soon as the socket is opened. Removing the WEBIRC and PASS statements yields no difference.

Is this 1 second delay by design, or is it an unintended bug of sorts?  I hit the 1 second delay each and every time.  Appears fine if I connect to an internet-facing IP though.

**Comment by Adam-** [comment]
It is intentional. As a client you aren't supposed to assume you are registered until you get an 001.
