### ISSUE TITLE
Configuring inspircd with python-irc

### ISSUE THREAD

**Issue by reyha** [inspircd/inspircd#1244]
I want to connect the python-irc(https://github.com/jaraco/irc) using the Inspircd server while configuring the Zulip's IRC mirror(https://github.com/zulip/zulip/blob/master/bots/irc-mirror.py) . I am currently unable to start the server. I am trying to connect it by using ``python irc-mirror.py --irc-server=127.0.0.1 --channel='#test' --nick-prefix=username``.
Is there some other way to connect to the server?

**Comment by GLolol** [comment]
Are you receiving any *specific* errors?

**Comment by reyha** [comment]
The script is simply not working.  When I debug using pdb, I get this
```
(Pdb) 
> /srv/zulip-venv/local/lib/python2.7/site-packages/irc/connection.py(46)connect()
-> sock.connect(server_address)
(Pdb) 
--Call--
> /usr/lib/python2.7/socket.py(223)meth()
-> def meth(name,self,*args):
(Pdb) 
> /usr/lib/python2.7/socket.py(224)meth()
-> return getattr(self._sock,name)(*args)
(Pdb) 
error: (111, 'Connection refused')
> /usr/lib/python2.7/socket.py(224)meth()
-> return getattr(self._sock,name)(*args)
(Pdb) 
--Return--
> /usr/lib/python2.7/socket.py(224)meth()->None
-> return getattr(self._sock,name)(*args)
(Pdb) 
error: (111, 'Connection refused')
> /srv/zulip-venv/local/lib/python2.7/site-packages/irc/connection.py(46)connect()
-> sock.connect(server_address)
```

**Comment by GLolol** [comment]
What port are you trying to connect to? Connection refused means that no server is present/listening on the port you're trying

**Comment by reyha** [comment]
I am editing the configuration file ``/etc/inspircd/inspircd.conf`` to connect to the port 6667 on the localhost.

**Comment by DjSlash** [comment]
Please use the [wiki](https://wiki.inspircd.org/Installation_From_Source) as a resource for installing and configuring your ircd.

**Comment by attilamolnar** [comment]
@reyha Hello, for support please join us on IRC at irc.inspircd.org #inspircd. This issue tracker is for reporting bugs and requesting features.
