### ISSUE TITLE
module m_filter - adding filtered message

### ISSUE THREAD

**Issue by Gavin-X** [inspircd/inspircd#1247]
i think it would be more useful to ircops to see the msg that's currently being block than the reason why it was blocked.

[09:20:19] -aurora.jhb.za.zairc.net- *** ANNOUNCEMENT: FILTER: Cobra had their message filtered, target was #AdultChat: **Spam/Advertising (See: /RULES (#4)) [ID: 2016061602] [OID: GP]**

The reason should be displayed to the user instead of the ircops. 

Maybe have a setting in the conf to choose to show either reason or msg

**Comment by Gavin-X** [comment]
Suggestion - ServerInstance->SNO->WriteGlobalSno('a', "FILTER: "+user->nick+" had their message filtered, target was "+target+": "+text+" ["+f->reason+"]");

**Comment by SaberUK** [comment]
I'm closing this for the reason mentioned in #1348.

**Comment by Robby-** [comment]
@SaberUK This is still open, it seems you didn't click the right button.

**Comment by SaberUK** [comment]
Oops, fixed~
