### ISSUE TITLE
atheme services [ irc_handle_connect(): connection to uplink established ]

### ISSUE THREAD

**Issue by silkvistor** [inspircd/inspircd#1250]
i have problem with inspircd with atheme services. 

irc_handle_connect(): connection to uplink established

when i try whois services its nickserv No such nick/channel but in map services there..

irc.bla.com (14D)            2 [100.00%] [Up: 1h51m34s]
`-services.bla.com (42F)     0 [ 0.00%] [Up: 7m41s Lag: 1ms]
2 servers and 2 users, average 1.00 users per server
End of /MAP

any idea? thank you.

**Comment by SaberUK** [comment]
Atheme support is located at irc.freenode.net #atheme. You're probably better off asking them.

**Comment by attilamolnar** [comment]
@silkvistor Hello, this issue tracker is for bug reports and feature requests. Support is provided at irc.inspircd.org #inspircd. To troubleshoot this issue, please get some debug logs from inspircd by running `./inspircd start --debug --nofork`.
