### ISSUE TITLE
ldapauth doesn't look up PASS input correctly in 2.0

### ISSUE THREAD

**Issue by rburchell** [inspircd/inspircd#1259]
Note: this issue is for 2.0 only. Above 2.0 have a different issue (#1258).

Basically, ldapauth should fall back to looking up the username and password from the PASS command if a colon is found (PASS <user>:<password>). There is already code for this, but I don't seem to be able to get it working.

I think I understand why. The first lookup (on nick/ident) checks for failure by using LDAP_SUCCESS, but this isn't completely correct. It is possible to get a lookup with 0 results (and thus a LDAP_SUCCESS return value) meaning that a fallback to PASS should be used.

**Comment by Adam-** [comment]
Thanks, fixed in 3f1eb79c7fa82737fda9c9a712724ba2f27651e9.
