### ISSUE TITLE
Send snotice on /filter kill and gline actions

### ISSUE THREAD

**Issue by MuffinMedic** [inspircd/inspircd#1263]
When using a /filter with the block action, a snotice is sent to opers. A snotice should also be sent when /filter is set to kill or gline.

**Comment by ThatOneRoadie** [comment]
[PR#1264](https://github.com/inspircd/inspircd/pull/1264) created for this issue. Cheers!

**Comment by attilamolnar** [comment]
This is tracked in #1151.
