### ISSUE TITLE
WALLOPS without any additional parameters sends a blank message (2.0)

### ISSUE THREAD

**Issue by duckspike** [inspircd/inspircd#1272]
The SNOTICE:
11:02:08 AM From calvin.snoonet.org: [MuffinMedic!Evan@255.255.255.255] WALLOPS 

There's really not much else to this issue other than the fact that "/WALLOPS" seems to work as intended and without any additional parameters.

I've been told that perhaps sending "/WALLOPS :" may allow for this to occur, which does seem like an issue.

**Comment by SaberUK** [comment]
>I've been told that perhaps sending "/WALLOPS :" may allow for this to occur, which does seem like an issue.

This is perfectly normal behaviour. Unlike PRIVMSG/NOTICE the IRC specification does not require that the message parameter of WALLOPS is non-empty.

**Comment by duckspike** [comment]
That's fair. Thank you kindly for the input.
