### ISSUE TITLE
Despite +I (hidechans) /WHO will return a single channel joined to by the user

### ISSUE THREAD

**Issue by duckspike** [inspircd/inspircd#1276]
Example: 
/WHO A_D
[21:51:08] ##channel A_D this.is.a.vhost irc.example.com A_D H* 0 Operator

On networks with hidechans loaded and +I set, /WHOIS will not show the channels that the users are in regardless of whether or not I share any common channels with them. With /WHO, I can see a single channel that they're in, regardless of the mode.

Note: if the chosen channel is +s then the output will show an * for the secret channel instead of the channel name.

InspIRCd 2.0.*

**Comment by MuffinMedic** [comment]
+1

**Comment by SaberUK** [comment]
I can confirm that this problem exists.

**Comment by Adam-** [comment]
Thanks, fixed in 032077534232a4fa97736595bdfcfe3c8b9beb58.
