### ISSUE TITLE
Active ping/pong to avoid DC by inactivity (can it be done?)

### ISSUE THREAD

**Issue by manavortex** [inspircd/inspircd#1278]
Hello, 

my problem is simple. We're running a very small IRC for our online gaming community. Most of our members on iPhone use the app IRCCloud, which will disconnect you after 2 hours of inactivity, unless you enter a subscription module that's not an option for broke teenagers. 

Can I somehow make the server keep them active, so that they don't get DC'd?

Thanks!

**Comment by SaberUK** [comment]
No, and I wouldn't recommend you violate the IRCCloud ToS.

**Comment by manavortex** [comment]
If only that subscription wasn't so ridiculously expensive. >.< 
Thanks for replying though!

**Comment by SaberUK** [comment]
You might want to look into ZNC.

**Comment by manavortex** [comment]
I'm running it for myself, but the notification options don't meet peoples' preferences and I can't seem to get the alert module running on user-base, only globally.

**Comment by attilamolnar** [comment]
Hello,

> Can I somehow make the server keep them active, so that they don't get DC'd?

I don't know how irccloud works but if it is looking for client activity then it is not possible and as pointed out trickery like that is a violation of their ToS and will get the accounts banned. Have you tried looking into alternatives such as https://thelounge.github.io ?
