### ISSUE TITLE
gnutls module update?

### ISSUE THREAD

**Issue by bug** [inspircd/inspircd#1279]
Is there a reason why the gnutls module included in the latest release (2.0.23) is not the one available on both master and insp20 branches? From what I see its last change is from Jun 2016 so prior to the release 2.0.23 tag itself (3 Sep 2016).

According to gnutls's documentation the code of the gnutls module in the release is outdated and broken (it's call to gnutls_certificate_set_x509_key() does not load all the intermediate certificates). On our local ircd this breaks completely SSL clients by not loading our full cert chain.

**Comment by attilamolnar** [comment]
Hello,

> Is there a reason why the gnutls module included in the latest release (2.0.23) is not the one available on both master and insp20 branches? From what I see its last change is from Jun 2016 so prior to the release 2.0.23 tag itself (3 Sep 2016).

The release tarball is generated by github directly from git, and it contains the module at the v2.0.23 tag. This means it contains the latest version of m_ssl_gnutls that is in the insp20 branch as of now.

> According to gnutls's documentation the code of the gnutls module in the release is outdated and broken (it's call to gnutls_certificate_set_x509_key() does not load all the intermediate certificates). On our local ircd this breaks completely SSL clients by not loading our full cert chain.

Can you describe what makes you think the code is broken?

**Comment by bug** [comment]
You're right sorry, the released code is the same as the insp20 branch.

Am i reading wrong https://github.com/inspircd/inspircd/blob/insp20/src/modules/extra/m_ssl_gnutls.cpp#L488 seeing that only the first cert is loaded? According to http://www.hep.by/gnu/gnutls/Core-TLS-API.html#gnutls_005fcertificate_005fset_005fx509_005fkey-1 all certs should be send if needed. On the master branch https://github.com/inspircd/inspircd/blob/master/src/modules/extra/m_ssl_gnutls.cpp#L489 it looks like all certs are loaded.

From what we see in our 2.0.23 installation, our intermediate cert is simply ignored (though present in the CONF/cert.pem file), thus clients fail to verify the cert.

**Comment by attilamolnar** [comment]
Am i reading wrong https://github.com/inspircd/inspircd/blob/insp20/src/modules/extra/m_ssl_gnutls.cpp#L488 seeing that only the first cert is loaded?

In 2.0 the code passes a buffer and the number of elements in the buffer to `gnutls_certificate_set_x509_key()`. The buffer begins with the first element, so it passes the address of the first element to the function.

> From what we see in our 2.0.23 installation, our intermediate cert is simply ignored (though present in the CONF/cert.pem file), thus clients fail to verify the cert.

Please pastebin your certificate file and the output of `echo "" | openssl s_client -showcerts -connect your.server.example.com:port 2>&1 | sed -n -e '/BEGIN\ CERTIFICATE/,/END\ CERTIFICATE/ p'`. What version of GnuTLS are you using?

**Comment by bug** [comment]
The cert file: https://framabin.org/?dc5e37f23d69b0bc#rw568n78wyMdiPk6hi+W9NVNm3lOjxOmMzkQaVUTN0w=

The output of openssl: https://framabin.org/?d49da6bedab4672f#nWoOOjOwEwdc8ZpGsfvxMZrFOIB8VEWWD+MTc1OEchM=

And GnuTLS version:

irc# pkg info gnutls | grep Version
Version        : 3.4.16

Thanks for your time

**Comment by attilamolnar** [comment]
Try to load the cert and the key into gnutls-serv: `gnutls-serv --x509certfile cert.pem --x509keyfile key.pem` then connect to it using the openssl command from my previous comment. Does it show all certs? If yes, is it possible that you have changed the cert file after starting inspircd and not executed `/rehash ssl` to reload it?

**Comment by bug** [comment]
According to the doc https://wiki.inspircd.org/Modules/2.0/ssl_gnutls, the command to reload certs and regenerate DH params is "rehash -ssl". We just tried your "rehash ssl" (no dash) and now all certs are loaded and everything works properly.

So now we look like idiots :-) but thanks a lot.

**Comment by attilamolnar** [comment]
Both commands should do the same in this case, but I'm glad to hear this is resolved.
