### ISSUE TITLE
WebSocket module should check Origin header

### ISSUE THREAD

**Issue by xaquseg** [inspircd/inspircd#1281]
m_websocket doesn't check the Origin header and just blindly accepts connections. This means that any webpage can open a WebSocket connection to the ircd if the module is loaded, which means any page on the web can deploy a spam script that connects without the user's knowledge. Origin needs to be checked against a configurable whitelist, as the WebSocket specification recommends.

**Comment by attilamolnar** [comment]
Yes, this is planned before the final 3.0 release along with other HTTP related enhancements such as HSTS.
