### ISSUE TITLE
Logger not flushing messages until block is filled

### ISSUE THREAD

**Issue by clinew** [inspircd/inspircd#1290]
This results in users not being able to see a message until a large number of messages have been sent.  Culprit appears to be:
```
        if (++writeops % 20 == 0)
        {
                fflush(log);
        }
```
in 'src/logger.cpp', which flushes the log after 20 lines have been written.  Without this code, though, the log only appears to be flushed when the buffer is filled, resulting in a large delay in log messages moving from memory to disk, and partial log messages.

**Comment by SaberUK** [comment]
This only affects master as the log buffering code is non-functional in insp20.

Possible fix: something to the effect of `setvbuf(stdout, NULL, _IONBF, 0);`
