### ISSUE TITLE
protection from ddos flood

### ISSUE THREAD

**Issue by darksis** [inspircd/inspircd#1293]
Hello is have in inspircd protection from ddos flood? it mean like botnet i dont think it not about proxy is something else

**Comment by SaberUK** [comment]
No, you will need something higher level for that. Ask your server provider about whether they provide DDoS protection.

**Comment by clandestinenetworks** [comment]
@darksis I actually use VPNs to do this, a lot of people do, I wrote my own solution https://github.com/clandestinenetworks/Clandestine-DMZ-Configurator
