### ISSUE TITLE
[3.0] Extra colon sent in /MODE replies confuse clients

### ISSUE THREAD

**Issue by GLolol** [inspircd/inspircd#1295]
With InspIRCd 3.0 (git master as of 51ff3d67ed1b6f1594373d3745293ef155a26f44), /MODE numeric replies are sent with a `:` before the last argument. This seems to confuse clients, causing spurious or invalid output:

With HexChat 2.12.4, the raw log is this:
```
<< MODE #test 
>> :insp3.midnight.vpn 324 GL #test :+nt
>> :insp3.midnight.vpn 329 GL #test :1487455404
```

But the IRC output is this:
```
* Channel #test modes: :+nt
* Channel #test created on Wed Dec 31 16:00:00 1969
```

WeeChat handles the timestamp correctly, but displays a spurious leading `:` in the hotlist (i.e. `[14:12] [3] [irc/127.0.0.1] 3:#test(:+nt){2}` instead of `[14:12] [3] [irc/127.0.0.1] 3:#test(+nt){2}`. With InspIRCd 2.0, no colon is sent, and both clients display modes and timestamps fine.

**Comment by DanielOaks** [comment]
Hmm, this is valid RFC1459 framing so clients should be parsing this properly. Is it just HexChat that runs into this issue or are you aware of others as well?

**Comment by GLolol** [comment]
HexChat breaks; WeeChat gets the right TS but formats the modes slightly wrong; irssi works fine for both. I haven't tried/installed any other clients at the moment.

**Comment by SaberUK** [comment]
This is a client bug. You should inform the developers of the clients in question that they need to fix their message parsers.

**Comment by SaberUK** [comment]
@GLolol This has been fixed in the broken clients. See the commit references. ^

**Comment by GLolol** [comment]
Awesome!
