### ISSUE TITLE
Proposal: Implement support for the ACME protocol for automatically obtaining TLS certificates

### ISSUE THREAD

**Issue by SadieCat** [inspircd/inspircd#1296]
This is the protocol implemented by Lets Encrypt which is in the process of becoming an Internet standard.

We could implement this with an embedded HTTP challenge implementation to allow servers to automatically request and renew valid certificates for the server.

Draft RFC: https://ietf-wg-acme.github.io/acme/

**Comment by del6597** [comment]
Sounds like a good idea.  Personally, I've only ever used the DNS challenge for sites since this allows private/internal sites to get a valid cert as well.

**Comment by attilamolnar** [comment]
I think creating and maintaining our own ACME client is too much effort, we could look into bundling one instead, e.g.:

https://github.com/Neilpang/acme.sh
https://github.com/lukas2511/dehydrated

**Comment by SadieCat** [comment]
I think people are pretty used to using their own ACME client nowadays so this doesn't seem necessary anymore.
