### ISSUE TITLE
FYI: 10.12.2 compilation with built-in openssl headers

### ISSUE THREAD

**Issue by working-name** [inspircd/inspircd#1298]
To help clang find the headers for the built-in openssl, I had to add 
`-I/usr/local/opt/openssl/include` to line 40 of main.mk to:
```
CORECXXFLAGS = -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -pipe -Iinclude -I/usr/local/opt/openssl/include -Wall -Wextra -Wfatal-errors -Wno-unused-parameter -Wshadow
```

For incoming google queries: m_ssl_openssl.cpp:48:10: fatal error: 'openssl/ssl.h' file not found
```
Found the linker flags for m_ssl_openssl using pkg-config: -lssl -lcrypto -lz
	BUILD:		modules/m_ssl_openssl.cpp
/Volumes/WorkingOn/Cache/inspircd/src/modules/m_ssl_openssl.cpp:48:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
make[1]: *** [modules/m_ssl_openssl.so] Error 1
```

**Comment by SaberUK** [comment]
You need to install the pkg-config files for OpenSSL.

**Comment by attilamolnar** [comment]
@working-name Let us know whether installing `pkg-config` solved the problem.

**Comment by working-name** [comment]
@attilamolnar Hi there, pkg-config was already installed via brew. Maybe brew doesn't know about Sierra-provided openssl header files?

**Comment by SaberUK** [comment]
@working-name Oh, I thought you were using FreeBSD. If you're using OS X then you'll need to install OpenSSL from Homebrew and then either force link it or set the environment variables that it tells you after building (you can see these using brew info openssl if you've already built).

**Comment by working-name** [comment]
@SaberUK, okay, I see. Thank you!
