### ISSUE TITLE
ldapauth not auth, just lookup?

### ISSUE THREAD

**Issue by allywilson1** [inspircd/inspircd#1303]
With the ldapauth module, it seems it only does a lookup for a valid user, and doesn't do any authentication? 

That is, you can put in any old password, and it is successful?

v2.0.22 r0
Running on server 2012 R2.
LDAP = 2008 R2 mode.

**Comment by allywilson** [comment]
My mistake, this isn't an issue. I configured it incorrectly (misunderstood what the pattern was being used for).
