### ISSUE TITLE
idle time reset on NOTICE

### ISSUE THREAD

**Issue by gangrenejellybean** [inspircd/inspircd#1305]
Filing this report as suggested by Attila Molnar in recent discussion on https://github.com/inspircd/inspircd/issues/438

Currently, inspIRCd resets a client's idle time when they send a NOTICE. This behaviour is not present on any other servers I know of. I can confirm that EFnet/Undernet/freenode don't do this.

Given CTCP replies are sent via notice, a side-effect of this behaviour means that on an inspIRCd server, I can reset someone's idle time merely by pinging them.

Would love to see inspIRCd adopt historical behaviour for NOTICE.

Thanks for your time and consideration.

**Comment by SaberUK** [comment]
Is this something we really need to fix? Idle times on IRC have never been particularly accurate as there are a ton of other cases where an automated script might reset the idle time (e.g. automatically identifying to services using `PRIVMSG NickServ :IDENTIFY ...`, those annoying "I am AFK" scripts, etc). 

I think its also worth noting that whilst other IRC server implementations may act differently how we implement it currently is perfectly fine according to the RFCs as they don't specify how idle times should actually be implemented.

**Comment by Robby-** [comment]
As noted, if this does get "fixed", please make this behavior configurable.

**Comment by gangrenejellybean** [comment]
@saberuk - while those scripts are annoying, I'm not sure such people are the best yardstick to make such decisions against.

I am used to reliable idle times. I consider it bad form that an inactive user running a stock client with no nonsense scripts can have their idle time reset by another user making a CTCP PING or VERSION request.

Please give this further consideration.

**Comment by SaberUK** [comment]
How about a compromise: Sending a CTCP reply doesn't reset your idle time.

**Comment by gangrenejellybean** [comment]
@SaberUK - Yep, that sounds good to me. Thanks!
