### ISSUE TITLE
services/atheme.conf.example

### ISSUE THREAD

**Issue by Casey952** [inspircd/inspircd#1306]
In atheme.conf.example -- Long hand InfoServ requires GroupServ instead of being InfoServ requires InfoServ

`<alias text="INFOSERV"  replace="PRIVMSG $requirement :$2-" requires="GroupServ" uline="yes">`

**Comment by SaberUK** [comment]
That would be my fault. I must have forgotten to edit it when I copied and pasted the aliases when making the new alias files.
