### ISSUE TITLE
(wrong issue tracker?) Wiki logo not suitably scaled for location

### ISSUE THREAD

**Issue by janicez** [inspircd/inspircd#1312]

**Comment by SaberUK** [comment]
I'm not sure why this is happening. It views properly on some pages but not on others. Probably a caching issue?

**Comment by SaberUK** [comment]
I just purged the cache and this seems to be fixed now.

**Comment by SaberUK** [comment]
@janicez Can you confirm that this is no longer an issue?

**Comment by janicez** [comment]
it is no longer an issue
