### ISSUE TITLE
Spoofed vhost by connect block

### ISSUE THREAD

**Issue by Famicoman** [inspircd/inspircd#1313]
I was wondering how feasible it would be to add a way to spoof the host of a user based on the connect block they fall under.

For example, let's suppose I have an ircd with normal client traffic on port 6667, a Tor hidden service that allows client connections on port 7000, and another Tor hidden service that allows only SASL connections on port 7001. So, In my connect blocks, I could have one block for each of these where I specify port allowed, requireaccount for the SASL Tor clients, etc. What I would like to do is overwrite the hosts based on these blocks so the normal clients on 6667 have a host like "standard.myirc.com", the Tor connections on port 7000 have a host like "tor-unverfied.myirc.com", and the Tor SASL clients on port 7001 have a host like "tor-authenticated.myirc.com".

The closest I can think to get to this is to set up a separate ircd instance for each of these three scenarios and enable different prefixes on each instance when specifying half cloaking, so I could get "myirc-", "myirc-tor-unverified-", and "myirc-tor-authenticated" or something similar.

Is there anything I'm missing that I could configure and if not, any technological or philosophical reasons to not implement this feature?

**Comment by genius3000** [comment]
This shouldn't be too hard to implement with a module, using a ``vhost = "thisblock.myirc.net"`` in the connect block config. I might be able to write something for the extras repo today.

**Comment by SaberUK** [comment]
I think m_hostchange might be able to do this... maybe?

**Comment by genius3000** [comment]
Hmmm, missed that one. It should be able to do this, not by connect class exactly but it can mimic them.
Example config has: ``#<hostchange mask="localhost" ports="7000,7001,7005-7007" action="set" value="blahblah.foo">``

So in this case:
```
<hostchange mask="*" ports="6667" action="set" value="standard.myirc.com">
<hostchange mask="*" ports="7000" action="set" value="tor-unverified.myirc.com">
<hostchange mask="*" ports="7001" action="set" value="tor-authenticated.myirc.com">
```

I'm not sure how this module works with m_cloaking, but I would think if you ensure you don't set usermode +x in the specific connect block, it will be fine.

**Comment by genius3000** [comment]
My bad, the above example won't work as I wrote it. You can only have one hostchange tag to a specific mask.
@SaberUK do you think it would be allowed in 2.0 to let m_hostchange use connect block names?

**Comment by Famicoman** [comment]
@genius3000 I also noticed that m_hostchange doesn't seem to let me specify addresses adhering to a certain cidr, for example fc00::/8. I also can't see to specify a specific interface I'm listening on, which appears to work for connect blocks. This would be used by me for other alternative networks that use different address spaces via a tun adapter for virtual networks if I wanted a specific spoofs for connections via dn42 or hyperboria.

Note that I disabled m_cloaking as I imagine this might try to mask the incoming spoofed addresses. Essentially, I would want to use these spoofs to replace m_cloaking. It sounds like I'm requesting something similar to #816.

I'll see about trying [#103](https://github.com/inspircd/inspircd-extras/pull/103)!

**Comment by Adam-** [comment]
There is also #598 which is related

**Comment by Famicoman** [comment]
@genius3000 I tried the module from your pull request and it appears to be doing exactly what I want. I have one connect block for port="7000", another block where allow="fc00::0/8" and a third catch-all block that each have a different vhost associated with them. When I connect to trigger each block, I get the proper spoofed host for each one!

**Comment by genius3000** [comment]
@Famicoman glad to hear it's working as needed!
@Adam- yeah that pull request already takes care of what I was thinking about for in master, nice. :D

**Comment by SadieCat** [comment]
In addition to @genius3000's module you can also limit a `<hostchange>` rule by connect class since commit ea9a72c5a5.
