### ISSUE TITLE
Permchannels should automatically set +P when loading the database if not already set

### ISSUE THREAD

**Issue by SaberUK** [inspircd/inspircd#1317]
Otherwise when the channel empties it will be deleted until the next boot.

I'm not sure if this is a bug we can fix in 2.0 or if it should be deferred to 3.0 for compat reasons.

---

Regardless, i've written a patch for master to fix it: https://github.com/inspircd/inspircd/compare/master...SaberUK:master+autoperm

**Comment by attilamolnar** [comment]
Under what circumstances is it possible that a channel is in the database and not have +P?

**Comment by SaberUK** [comment]
@attilamolnar When people define a permanent channel via defining their own `<permchannels>` tags (we document how to do this in modules.conf.example so I guess that means we support it) rather than just from setting `+P` and loading the generated file.

**Comment by attilamolnar** [comment]
@SaberUK makes sense, I think a doc update + one time log message if the situation is detected is fine for 2.0. For 3.0, push the permchannels mode to the mode change list after all modes. If it's duplicate, it will be dropped harmlessly.

**Comment by attilamolnar** [comment]
For 3.0, calling our mode handler after the other modes should be fine in all cases, even if the permchannels mode is already set.

**Comment by SaberUK** [comment]
@attilamolnar I didn't notice earlier but there is already a warning in the config in 2.0, i'll just add a log message for it.

**Comment by attilamolnar** [comment]
This has been implemented on both insp20 and master, closing.
