### ISSUE TITLE
Local op?

### ISSUE THREAD

**Issue by bonnedav** [inspircd/inspircd#1322]
Is there any way to make an oper who:

- Can only SQUIT or CONNECT locally.
- Can only KILL locally.
- Can send global messages to local server only.

**Comment by SISheogorath** [comment]
Yes, simply define it in your oper classes. As this is a bug tracker and not user support I recommend you to ask in the IRC channel and read the Opera.conf.example file. Anyways it's not recommended to oper anyone you do not trust 100%.

**Comment by Robby-** [comment]
This reminds me of local IRC operators in an IRCnet-style ircd.

**Comment by SaberUK** [comment]
This is not possible. All operators have global privileges.

In future if you have support questions then please ask them at irc.inspircd.org #inspircd instead of here, thanks!~
