### ISSUE TITLE
Connect Class or Ident Auto Join

### ISSUE THREAD

**Issue by TuSuNaMi** [inspircd/inspircd#1323]
Hello,  I want a ask question about auto join. Is this user join to spesific channels connect class or ident. Did inspircd make this?

**Comment by SaberUK** [comment]
If you load `m_conn_join` you can set <connect:autojoin> to a comma delimited list of channels.

**Comment by TuSuNaMi** [comment]
Hello,

I'm added following lines my conf files but do nothing. My version 2.0.20

<connect
   name="Mobil"
   modes="+ixG"
   allow="127.0.0.1"
   resolvehostnames="no"
   timeout="60"
   flood="10"
   pingfreq="120"
   threshold="5"
   sendq="131074"
   recvq="4096"
   globalmax="30"
   localmax="30"
   *autojoin="#Mobil"*
   port="4547">


2017-04-19 18:59 GMT+03:00 Peter Powell <notifications@github.com>:

**Comment by TuSuNaMi** [comment]
I think all webirc or cgihosts use default "Main" class. I see this connections all of them "Main" class.

*** CONNECT: Client connecting on port 4547 (class main): sdfdfdsf!Mobil@

**Comment by SaberUK** [comment]
In 3.0 you can use `<connect webirc="*" autojoin="#channel">` to autojoin all WebIRC clients to a specific channel. This is not possible in 2.0.
