### ISSUE TITLE
GeoIP country redirect

### ISSUE THREAD

**Issue by fragonfour** [inspircd/inspircd#1326]
Is there anyway to redirect countries to another channel for example if I want to redirect US geoip to #US-users, I used /mode # +b G:US#US-users but it didn't work.. 
Is there any special module required for that? GeoIP is installed.. I just want to know about the redirect..

**Comment by SISheogorath** [comment]
This is an issue tracker for software bugs, not a support platform. For further support please visit `#inspircd` on chatspike.

The ban redirect works as designed and doesn't support extbans. If you want to use it in this combination see this extras module: https://github.com/inspircd/inspircd-extras/blob/master/2.0/m_extbanredirect.cpp

**Comment by darksis** [comment]
what is a commands  m_extbanredirect  from irc?
