### ISSUE TITLE
make problem OpenBSD

### ISSUE THREAD

**Issue by layer3** [inspircd/inspircd#1332]
Hi,

./configure runs fine getting the error when trying to execute make (make: no target to make.)

OpenBSD: 6.1

**Comment by SaberUK** [comment]
What version of InspIRCd are you using?

What is the output of `make -v`?

**Comment by layer3** [comment]
V2.0.23 

# make -v
make: unknown option -- v

**Comment by SaberUK** [comment]
Can you pastebin the full output of running configure and then make?

**Comment by layer3** [comment]
https://pastebin.com/9gJ5ZQB1

**Comment by SaberUK** [comment]
Can you try updating to v2.0.24? I'm building an OpenBSD VM now to test this.

**Comment by layer3** [comment]
yeah, I can try 2.0.24 no problem! let you know then!

**Comment by layer3** [comment]
same error

Signing certificate...

Certificate generation complete, copying to config directory... Done.

Symlinking src/modules/m_ssl_openssl.cpp from extra/
SSL certificates found, skipping.

Detecting modules ..................................................................................................................................................
Ok, 146 modules.
Locating include directory for package gnutls for module m_ssl_gnutls.cpp... -I/usr/local/include -I/usr/local/include/p11-kit-1 -I/usr/include -DVERSION_GNUTLS="3.5.10" (version 3.5.10)
Locating library directory for package gnutls for module m_ssl_gnutls.cpp... -L/usr/local/lib -lgnutls (version 3.5.10)
Adding runtime library path to m_ssl_gnutls.cpp ... /usr/local/lib
Checking version of package openssl is >= 0.9.7... Yes (version 1.0.0)
Locating include directory for package openssl for module m_ssl_openssl.cpp... -I/usr/include -DVERSION_OPENSSL="1.0.0" (version 1.0.0)
Locating library directory for package openssl for module m_ssl_openssl.cpp... -L/usr/lib -lssl -lcrypto (version 1.0.0)
Adding runtime library path to m_ssl_openssl.cpp ... /usr/lib
Writing inspircd_config.h
Writing GNUmakefile ...
Writing BSDmakefile ...
Writing inspircd ...
Writing cache file for future ./configures ...


To build your server with these settings, please run 'make' now.
Please note: for SSL support you will need to load required
modules in your config. This configure script has added those modules to the
build process. For more info, please refer to:
http://wiki.inspircd.org/Installation_From_Tarball
*** Remember to edit your configuration files!!! ***


# make
make: no target to make.
#

**Comment by SaberUK** [comment]
I can verify this on v2.0.24. For now installing gmake (`pkg_add gmake`) and running it instead of make is a workaround..

**Comment by layer3** [comment]
yes gmake works! thx

**Comment by SaberUK** [comment]
I'm not sure how we can fix this really. OpenBSD has just straight up removed the Make feature we use for portability between BSD and GNU make.
