### ISSUE TITLE
globalmax localmax configuration values seems to be ignored

### ISSUE THREAD

**Issue by ktorpi** [inspircd/inspircd#1340]
Hello,
For some reasons I need to connect to inspircd server from the same IP address with many clients at the same time. According to my knowledge, the configuration file contains options to configure the number of  clients allowed from the same ip with globalmax and localmax options in the connect section. However, whatever I set, the limit seems to be unchanged (stays 5) and I cannot connect more clients.
I also tried to play with attributes ipv4clone and ipv6clone in cidr, but no success.
Is it a bug, or is there a problem with my configuration?

Please, find attached the config file I've used:
https://gist.github.com/ktorpi/6fc00c2f92d4ad56a19ff9ada15c7972
I'm using InspIRCd 2.0.23 on Windows.

Thank you in advance,
István

**Comment by SISheogorath** [comment]
This is a bug tracker, not a support platform, can you please join #inspircd on irc.inspircd.org

There you should find all the help you need to solve this issue :) Thank you!
