### ISSUE TITLE
DNSBL does not work (Server for Windows)

### ISSUE THREAD

**Issue by EpicNet** [inspircd/inspircd#1344]
InspIRCd 2.0.24
Module **m_dnsbl.so** does not work. The server does not block the connection proxy. Did everything according to instructions and examples. Tell me, what parameters need to be configured in the server configuration so that the protection starts working?

**Comment by SISheogorath** [comment]
Can you file a few more details?

What does your configuration look like? Can you confirm that the IP you used for proxy was blacklisted? Was the IP the IP you saw in on your IRCd as Client-IP?

All details how to configure DNSBL can be found in the example config: https://github.com/inspircd/inspircd/blob/insp20/docs/conf/modules.conf.example#L742-L748

And make sure you don't mix up DNSBL with proxy detection. It's just an IP-Blacklisting.

**Comment by EpicNet** [comment]
Yes, I checked many different proxy addresses that were in the blacklists I listed and they are blocked on other networks. I at least count on the work of this module to block IP, which is in the blacklists.

My configuration for this module is:

<module name="m_dnsbl.so">
<connect
         name="user" port="6667" limit="1000" autojoin="" modes="+x" allow="*" password=""
         timeout="60" pingfreq="180" localmax="3" globalmax="3" maxconnwarn="on"
	 usednsbl="yes" useident="off" requiressl="off"
         fakelag="on" commandrate="1000" threshold="20" allowmotdcolors="false">

<include file="conf/dnsbl.conf">
<dnsbl
        name="rbl.efnetrbl.org" type="record"
        domain="rbl.efnetrbl.org" action="ZLINE"
	reason="BAN => %ip% Check blacklist (rbl.efnetrbl.org)"
	duration="3d" records="1,2,3,4,5"
>
... And about 20 other blacklists, etc.

**Comment by SISheogorath** [comment]
Can you capture some network traffic and check back that the DNS requests are successfully answered?

**Comment by EpicNet** [comment]
Please tell me how to do this and what programs?

**Comment by attilamolnar** [comment]
@EpicNet You can use wireshark to capture traffic and verify that DNS requests are sent from server to the dnsbl and whether there are any replies.

https://www.wireshark.org/

https://www.howtogeek.com/104278/how-to-use-wireshark-to-capture-filter-and-inspect-packets/

**Comment by SaberUK** [comment]
@EpicNet Have you had any success in diagnosing this?

**Comment by EpicNet** [comment]
Alas, no, nothing happened. If you have the opportunity please check this with the same parameters as mine. It is interesting to know whether you will work?

**Comment by SaberUK** [comment]
I've not seen this at all in the almost two years since this issue was filed. If you're still having issues then please ask on IRC.
