### ISSUE TITLE
make zline or gline with pass

### ISSUE THREAD

**Issue by darksis** [inspircd/inspircd#1346]
Hello this possible make zline or gline with a pass it mean if oper set zline about someone and he no want oper else remove it then it to be options zline ip timer reason and pass off oper?

**Comment by Robby-** [comment]
This seems more like an issue with you and your staff. Talk with each other. If needed, lay down the law and tell that nobody else should remove the gline/zline, or to face the consequences. In my opinion, adding a password to/for these commands is excessive.

**Comment by SaberUK** [comment]
No, thats not possible.

**Comment by darksis** [comment]
but also in operlevels is have options to oper make a zline and remove it and this make a some problem in staff
