### ISSUE TITLE
problem with install module geoip in freebsd

### ISSUE THREAD

**Issue by darksis** [inspircd/inspircd#1352]
hello this after i install geoip in freebsd and i get a error /usr/bin/ld: cannot find -lGeoIP

        BUILD:              modules/m_geoip.cpp
An error occured when executing: clang++ -o modules/m_geoip.so -pipe -fPIC -DPIC -pedantic -Woverloaded-virtual -Wshadow -Wformat=2 -Wmissing-format-attribute -Wall -O2 -Iinclude -DMODNAME=m_geoip.so -fPIC -shared -rdynamic /usr/home/asher/inspircd-2.0.24/src/modules/m_geoip.cpp -lGeoIP
/usr/home/asher/inspircd-2.0.24/src/modules/m_geoip.cpp:24:10: fatal error: 'GeoIP.h' file not found
#include <GeoIP.h>
         ^
1 error generated.
*** Error code 1

Stop.
make[1]: stopped in /usr/home/asher/inspircd-2.0.24/build
*** Error code 1

**Comment by SaberUK** [comment]
You haven't installed libGeoIP.

**Comment by darksis** [comment]
i install it
cd /usr/ports/net/GeoIP/ && make install clean
 pkg install GeoIP 
and after i get that
        BUILD:              modules/m_geoip.cpp
An error occured when executing: g++ -o modules/m_geoip.so -pipe -fPIC -DPIC -pe                                                                                                                               dantic -Woverloaded-virtual -Wshadow -Wformat=2 -Wmissing-format-attribute -Wall                                                                                                                                -O2 -g1 -Iinclude -DMODNAME=m_geoip.so -fPIC -shared -rdynamic /usr/home/asher/                                                                                                                               inspircd-2.0.24/src/modules/m_geoip.cpp -lGeoIP
/usr/home/asher/inspircd-2.0.24/src/modules/m_geoip.cpp:24:19: error: GeoIP.h: N                                                                                                                               o such file or directory
/usr/home/asher/inspircd-2.0.24/src/modules/m_geoip.cpp:36: error: ISO C++ forbi                                                                                                                               ds declaration of 'GeoIP' with no type
/usr/home/asher/inspircd-2.0.24/src/modules/m_geoip.cpp:36: error: expected ';'                                                                                                                                before '*' token
/usr/home/asher/inspircd-2.0.24/src/modules/m_geoip.cpp: In member function 'std                                                                                                                               ::string* ModuleGeoIP::SetExt(LocalUser*)':
/usr/home/asher/inspircd-2.0.24/src/modules/m_geoip.cpp:40: error: 'gi' was not                                                                                                                                declared in this scope
/usr/home/asher/inspircd-2.0.24/src/modules/m_geoip.cpp:40: error: 'GeoIP_countr                                                                                                                               y_code_by_addr' was not declared in this scope
/usr/home/asher/inspircd-2.0.24/src/modules/m_geoip.cpp: In constructor 'ModuleG                                                                                                                               eoIP::ModuleGeoIP()':
/usr/home/asher/inspircd-2.0.24/src/modules/m_geoip.cpp:50: error: class 'Module                                                                                                                               GeoIP' does not have any field named 'gi'
/usr/home/asher/inspircd-2.0.24/src/modules/m_geoip.cpp: In member function 'vir                                                                                                                               tual void ModuleGeoIP::init()':
/usr/home/asher/inspircd-2.0.24/src/modules/m_geoip.cpp:56: error: 'gi' was not                                                                                                                                declared in this scope
/usr/home/asher/inspircd-2.0.24/src/modules/m_geoip.cpp:56: error: 'GEOIP_STANDA                                                                                                                               RD' was not declared in this scope
/usr/home/asher/inspircd-2.0.24/src/modules/m_geoip.cpp:56: error: 'GeoIP_new' w                                                                                                                               as not declared in this scope
/usr/home/asher/inspircd-2.0.24/src/modules/m_geoip.cpp: In destructor 'virtual                                                                                                                                ModuleGeoIP::~ModuleGeoIP()':
/usr/home/asher/inspircd-2.0.24/src/modules/m_geoip.cpp:76: error: 'gi' was not                                                                                                                                declared in this scope
/usr/home/asher/inspircd-2.0.24/src/modules/m_geoip.cpp:77: error: 'GeoIP_delete                                                                                                                               ' was not declared in this scope
*** [modules/m_geoip.so] Error code 1

**Comment by SaberUK** [comment]
You need to make sure the headers for libGeoIP are in the system include paths. Ask your operating system maintainer how to do this as it is not an InspIRCd bug.
