### ISSUE TITLE
Windows Installation Error (GeoIP.dll)

### ISSUE THREAD

**Issue by Spy7Dragon** [inspircd/inspircd#1363]
**Description**

The windows installation stops during extraction and outputs "Error opening file for writing: "C:\Program Files (x86)\InspIRCd\GeoIP.dll. This happened on the installer for versions 2.0.16 through 2.0.24.

**Steps to reproduce the issue:**
1. Download InspIRCd-2.0.24.exe
2. Double click installer
3. Hit Run on Security Warning
4. Click Next >
5. Click I Agree
6. Click Next >
7. Click Install
8. Response:

**Describe the results you received:**
Error opening file for writing:

C:\Program Files (x86)\InspIRCd\GeoIP.dll

**Describe the results you expected:**
Next > button becomes active.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `./bin/inspircd --version`:**
Not Installed

**Comment by SaberUK** [comment]
Are you still having this issue on v2.0.25?

**Comment by SaberUK** [comment]
As there has been no response in a few months i'm going to close this now.
