### ISSUE TITLE
WEBIRC does not properly sanitize hostnames passed from the web IRC client

### ISSUE THREAD

**Issue by duckspike** [inspircd/inspircd#1365]
Description: An individual utilizing KiwiIRC NextClient to connect to our IRC has the character "@" in their PTR record. The webirc module does not appear to properly sanitize the record and as a result the user will appear to be connecting from something like `137-59-60-1.dynamic.JOYINTERNET.geocitysolutions@gmail.com`

WHOWAS output:
`was connecting from *@43-227-246-27.dynamic.TENTOTEN.geocitysolutions@gmail.com`

Unfortunately, we don't log the output of the WEBIRC module, so therefore it is not possible to give you this information.

We are running InspIRCd 2.0.24

**Comment by SaberUK** [comment]
This is mainly an issue with your WebIRC gateway but InspIRCd should at the very least be rejecting malformed hostnames sent by WebIRC.

Potential fix for that: https://github.com/inspircd/inspircd/compare/insp20...SaberUK:insp20+cgiirc

**Comment by SaberUK** [comment]
This has been fixed in 5fc4403f621ac93ef8a8c250b30436c0fea8f493. I'll leave this issue open until we decide what we want to do in 3.0 though.

**Comment by SaberUK** [comment]
Proposal: https://github.com/inspircd/inspircd/compare/master...SaberUK:master+dns

**Comment by SaberUK** [comment]
As of 906260c24f7818fb7cf15a0371d760acb1254113 this has been resolved.
