### ISSUE TITLE
Proposal: remove older unused methods from m_cgiirc.

### ISSUE THREAD

**Issue by SaberUK** [inspircd/inspircd#1366]
I'm wondering if we should continue supporting the `pass`, `passfirst` and `identfirst` methods in m_cgiirc for 3.0.

In 2.0 currently the `identfirst` method exists in the code but can't be set in the config. Additionally the `pass` and `passfirst` methods are something that I haven't seen used in a very long time. I don't think modern web clients use them at all.

This would leave us with two methods: `webirc` and `ident` which from what I have seen are still widely used. [A speculative diff of this change is available here.](https://github.com/inspircd/inspircd/compare/master...SaberUK:master+cgiirc)

cc: @dgl @maxleiter @prawnsalad

**Comment by prawnsalad** [comment]
Can confirm, no networks on kiwiirc.com has the IP set via PASS. Only WEBIRC and via the ident in hex form. Further, there has never been any request to support it.

Other clients using the kiwiirc IRC lib such as thelounge also don't support sending the IP via PASS.

**Comment by dgl** [comment]
Supporting just WEBIRC sounds fine to me. CGI:IRC can be set to use either method and I think most other clients only implement WEBIRC now.

**Comment by SaberUK** [comment]
It seems like no web IRC clients actually use these methods as I thought:

- Kiwi IRC (confirmed by prawnsalad)
- The Lounge (uses the Kiwi IRC framework)
- CGI:IRC (confirmed by dgl)
- QWebIRC (confirmed by checking the source code)

**Comment by SaberUK** [comment]
If there's no other clients we need to check i'll merge this on Sunday.

**Comment by SaberUK** [comment]
Implemented in 3cb659afaa644042609bb52dc9c9cbfe92b0ff9f.
