### ISSUE TITLE
Hello i have a question

### ISSUE THREAD

**Issue by darksis** [inspircd/inspircd#1371]
Hello i have a question sorry i open it in here because i have a long time ban without a reason anyway 
i a long time use with inspircd when is version 2.0.0 and my question when all staff in inspircd can write a module block when someone get gline or zline and when he try change ip then he stay with block is have options like it?

**Comment by Heufneutje** [comment]
This is an issue tracker. #inspircd on irc.inspircd.org is for questions.

**Comment by darksis** [comment]
@Heufneutje Are you blind or can not read? i have there ban and i cant ask there the question

**Comment by Heufneutje** [comment]
If you got banned it was probably for good reason considering how rude you currently are. It also doesn't change the fact that this is an issue tracker.

**Comment by Heufneutje** [comment]
That aside I don't really know if what you're asking is even possible. Based on what would you detect that someone changed their IP? Nickname and ident can easily be the same so that doesn't guarantee it's the same person.
