### ISSUE TITLE
inspircd-3.0.0a1 configuration file issue

### ISSUE THREAD

**Issue by carlosferry** [inspircd/inspircd#1400]
Configure perl script isn't working properly. It seems to be that make::common is not found. I fixed this issue by  adding these two lines:

use Cwd;
use lib getcwd();

PS: I know 3.0x series is still beta, yet I thought this might be helpful. 

Thanks

**Comment by SaberUK** [comment]
This has already been fixed in 1d45a7264c01669a046e803d206dd3553fbc5c55. You should update to the latest git master rather than using the v3.0a1 tarball.
