### ISSUE TITLE
[3.0.0] Erroneous colon in RPL_MYINFO/004 numeric

### ISSUE THREAD

**Issue by Herringway** [inspircd/inspircd#1402]
**Steps to reproduce the issue:**
1. Connect to network.

**Describe the results you received:**
`004 Herringway localhost InspIRCd-3.0 :BGHIRSWcdgikorswx ABCDFGIJKLMNOPQRSTYabcefghijklmnopqrstuvwz FIJLYabefghjkloqvw`

**Describe the results you expected:**
`004 Herringway localhost InspIRCd-3.0 BGHIRSWcdgikorswx ABCDFGIJKLMNOPQRSTYabcefghijklmnopqrstuvwz FIJLYabefghjkloqvw`

**Output of `./bin/inspircd --version`:**
InspIRCd-3.0.0-e97d5cf4f

**Comment by SaberUK** [comment]
I can confirm that this is a fault. 

Can you please test this prospective fix to check that it works for you? https://github.com/inspircd/inspircd/compare/master...SaberUK:master+004

**Comment by Herringway** [comment]
the fix moved the colon to the last parameter, but that's acceptable, so it works for me

**Comment by SaberUK** [comment]
>the fix moved the colon to the last parameter

Yeah, that is a valid message as a <trailing> parameter should be treated as equivalent to a <middle> parameter according to the RFC.
