### ISSUE TITLE
[REQUEST] module for shedding users from a server

### ISSUE THREAD

**Issue by emersonveenstra** [inspircd/inspircd#1405]
i think it would be useful to have a module like plexus/oftc-hybrid m_shedding, which disconnects users of a server at a specified rate. This would help with upgrading servers, closing the server and then shedding the users will make the netsplit less disruptive and quicker than just closing and waiting for users to reconnect on their own

**Comment by rburchell** [comment]
Not a bad idea, though (excuse the tangent) I'd personally be more excited by a proper graceful upgrade.

Assuming you can link the same server name with different SIDs multiple times, then you could disable listen ports on the old instance, while starting up a new instance with the same config, and linking it. That could end up automated as a RESTART parameter, even, perhaps: disable listen ports, start new instance with a not-currently-used SID assigned to it by the running instance, and then the old instance would stay running until the user count hit 0 (plus some sort of time boxed threshold as a safety precaution: always kill yourself after a week even if you still have users, or something).

To end users, it would be entirely seamless: they'd stay connected to the old one until they disconnected, to users on the new server, it'd look exactly the same as before.

Complications of course would appear on things like squit, and I guess on PID files and such, but hm...

Another way this could potentially work would be in passing off state and FDs to a new instance entirely, but that's a lot more complex when you throw in external like SQL (what happens to running queries from modules?), DNS (what happens to pending queries?), SSL, etc etc. There's a lot of boxes to check to get that completely correct.

**Comment by linuxdaemon** [comment]
This has been (at least somewhat) implemented in https://github.com/inspircd/inspircd-extras/blob/master/3.0/m_shed_users.cpp
