### ISSUE TITLE
 error: ‘UINT32_MAX’ was not declared in this scope compilation terminated due to -Wfatal-errors.

### ISSUE THREAD

**Issue by AYARCI** [inspircd/inspircd#1415]
Inspircd 3.0.0.a3 installation error for "make -j4"

![inspircd3 0](https://user-images.githubusercontent.com/33767327/32972431-6e63ac78-cc03-11e7-9841-0cb8820f7db7.png)

**Comment by SaberUK** [comment]
Hello,

Can you please provide the output of the following commands:

```sh
uname -a
c++ --version
lsb_release -d
```

**Comment by AYARCI** [comment]
**uname -a**
`Linux host.****.com 2.6.32-696.13.2.el6.x86_64 #1 SMP Thu Oct 5 21:22:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
**lsb_release -a**
`LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.9 (Final)
Release:        6.9
Codename:       Final`
**c++ --version**
c++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by SaberUK** [comment]
If you edit `include/configreader.h` and add `#define __STDC_LIMIT_MACROS 1` on the line after `#pragma once` does this error go away?

If that does not work, does changing `#include <climits>` in `include/inspircd.h` to `#include <limits.h>` fix the problem?

**Comment by AYARCI** [comment]
I applied the changes, but again the same error. :(

**Comment by SaberUK** [comment]
This sounds like you're using a compiler which is too outdated to build InspIRCd. Update and try again.

**Comment by AYARCI** [comment]
Thanks. What do I need to update? Could you give information?

**Comment by SaberUK** [comment]
Either your compiler or your operating system.
