### ISSUE TITLE
XLines loaded from the configuration file should be removed on rehash

### ISSUE THREAD

**Issue by SISheogorath** [inspircd/inspircd#1427]
Currently, it's possible to add xlines by config. The main problem is that when you remove the config but have xlinedb enabled, the xlines persist.

With a flag that allows to "donotpersist", these configs could be added and removed by config files. Right now with enabled xlinedb we can only add entries by config.

**Comment by SaberUK** [comment]
I'm planning on making it so that XLines (or their replacement) which originate from the config file aren't saved to the database. Would that be acceptable?
