### ISSUE TITLE
m_sasl always advertises itself if target isn't set or is *

### ISSUE THREAD

**Issue by B00mX0r** [inspircd/inspircd#1430]
Per https://github.com/inspircd/inspircd/blob/master/src/modules/m_sasl.cpp#L75,L79, m_sasl will advertise itself as an available CAP if the target is set to * or isn't set at all. This is a violation of IRCv3 (see http://ircv3.net/specs/extensions/sasl-3.2.html#advertisement-of-sasl-capability-when-authentication-is-unavaila). Specifically, 
> Servers MUST NOT advertise the sasl capability if the authentication layer is unavailable.

I would propose that either checking for the authentication layer be done differently than seeing if a server is online (i.e. testing for a response to an SASL broadcast), or the "target" parameter of the sasl config tag becoming mandatory and * being illegal.

**Comment by genius3000** [comment]
I'm in favour of making `target` mandatory, therefore '*' is no longer allowed. Though this could still advertise the CAP even if incorrectly set to another (online) server.
