### ISSUE TITLE
Optionally display reasons in expiry messages

### ISSUE THREAD

**Issue by Robby-** [inspircd/inspircd#1434]
It would be nice if expiry messages could optionally contain the reason that was specified when the xline/SHUN/CBAN/R-line/SVSHOLD was originally set.

Currently these messages look like this:
`Removing expired Z-Line 2001:db8::/32 (set by <nick/servername> <seconds> seconds ago)`
What it for example could look like after implementing this and enabling the setting:
`Removing expired Z-Line 2001:db8::/32 (set by <nick/servername> <seconds> seconds ago): <reason>`

**Comment by B00mX0r** [comment]
Would it be possible to have a snomask that would show the expiry reasons? I'm just thinking about bots or opers who wouldn't want those extra lines. I don't know if this is enough of a concern to warrant that, though.

**Comment by Robby-** [comment]
Sounds reasonable to me but then again adding a new snomask for this seems a bit much, also considering snomask characters are limited. I requested this specifically for opers, though. This feature was actually requested by one of my opers.

**Comment by SaberUK** [comment]
I don't really see the point of adding a specific snomask for this. I'll add it to the messages though.

**Comment by Robby-** [comment]
I should note for completeness that this change should not only be done to xlines but also to the expiry messages of other things, like SHUNs, CBANs, R-lines and SVSHOLDs.

**Comment by SaberUK** [comment]
>SHUNs, CBANs, R-lines and SVSHOLDs.

These are also XLines.

**Comment by Robby-** [comment]
For reference, this is what I have been using in the meantime, on 2.0, to get this functionality:
https://gist.github.com/Robby-/af10382f6dd049184af2c7fa2f3036c3
