### ISSUE TITLE
On xline expiry, the setter's name gets replaced by the server's name in snotice messages

### ISSUE THREAD

**Issue by Robby-** [inspircd/inspircd#1435]
**Description**
When xlines expire, depending on some factors, the server's name is shown as the xline setter instead of the actual oper who set it originally, in xline expiry snotice messages.

This issue surfaces on 2 fronts.
* When multiple servers are linked, the remote servers will use the name of the server the oper was on as the setter's name (not tested further than one hop, though). The original server where the xline was set on will, however, still display the actual nickname of the oper who set it, but only if the server wasn't restarted in the meantime (see next point).
* When using `m_xline_db`, the xlines are obviously stored in a db file. However, when writing the xline to the db, each server on the network will write it to the db with its own server name as the setter of the xline. When servers are then subsequently restarted, the expiry messages produced by each server will contain their own name as the setter.

**Steps to reproduce the issue (1/2):**
1. Have linked servers (so no standalone server).
2. Set an xline and wait for the expiry snotice messages.
3. The server where the xline is set on will show the correct nickname in the expiry message.
4. Remote servers will incorrectly show a server name as the setter.

**Steps to reproduce the issue (2/2):**
1. Have linked servers (but a standalone server is also ok for this one).
2. Make sure you loaded `m_xline_db`, then set an xline and restart the server.
3. Wait for the xline expiration snotice message.
4. The server will incorrectly show the server name as the setter and if any other servers are linked and have also been restarted, they also will each show their own server name as the setter).

**Describe the results you received:**
Wrong names of xline setters in expiry messages.

**Describe the results you expected:**
Correct nicknames of xline setters in expiry messages.

**Output of `./bin/inspircd --version`:**
`InspIRCd-2.0.25 rv2.0.25-3-g25c1319`

**Comment by SaberUK** [comment]
Speculative fix: https://github.com/inspircd/inspircd/compare/insp20...SaberUK:insp20+xline

**Comment by SaberUK** [comment]
Any luck with testing that patch?

**Comment by Robby-** [comment]
Sorry, not yet, but most likely this weekend.

**Comment by Robby-** [comment]
I have now tested it and the patch fixes the issue, thanks.

**Comment by SaberUK** [comment]
Fixed in insp20. Thanks for reporting.
