### ISSUE TITLE
m_cgiirc and client IPv6 IP addresses with no reverse DNS

### ISSUE THREAD

**Issue by Robby-** [inspircd/inspircd#1438]
**Description**
Webchat clients using IPv6 that have no reverse DNS on their IP address causes Anope to log a wrong IP address in SASL authentication messages.

**Describe the results you received:**
Anope log: `M_SASL: <our webserver IPv6 IP> (<user IPv6 IP>) identified to account <name> using SASL`

**Describe the results you expected:**
Anope log: `M_SASL: <user IPv6 IP> (<user IPv6 IP>) identified to account <name> using SASL`

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue started occuring in InspIRCd version `2.0.25`.
Caused by commit 5fc4403f621ac93ef8a8c250b30436c0fea8f493
Replacing `find_first_not_of("` with `find_first_not_of(":` fixes the issue, but as discussed on IRC, this is an indirect cause, not the root cause.

**Output of `./bin/inspircd --version`:**
InspIRCd-2.0.25 rv2.0.25-3-g25c1319

**Comment by SaberUK** [comment]
We don't set the `cgiirc_webirc_hostname` when the hostname is invalid which is probably whats causing this.

Speculative fix: https://github.com/inspircd/inspircd/compare/insp20...SaberUK:insp20+cgiirc

**Comment by Robby-** [comment]
The above patch fixes the issue, thank you.
