### ISSUE TITLE
disallow oper access on a linked server

### ISSUE THREAD

**Issue by vlanmx** [inspircd/inspircd#1454]
I would like to change from UnrealRCd to InspIRCd, but there seem to be no option such as `quarantine` that [exists in UnrealRCd](https://www.unrealircd.org/docs/Link_block#options) and permits to disallow /oper access on specific servers linked to hub.

Example: The option is specified on the hub's link block and when a user tries to get /oper on a "quarantined" server, the main hub detects that attempt and kills that user remotely.

I can't find anything relevant in documentation for configuration, maybe I miss something?

My network can't exist without being able to configure some servers this way, so consider it as a possible feature request, if there is no way to do that in InspIRCd.

**Comment by genius3000** [comment]
You're correct in that nothing like `quarantine` exists in InspIRCd. This sounds like a lack of trust in a network's server admins, which is bad in many ways to start with.  
Technically speaking, I don't think this would be difficult to implement as a module. I can't speak for the InspIRCd group, but I would think this feature request might be more suited for the `inspircd-extras` repo.

**Comment by vlanmx** [comment]
Reduced circle/zone of trust is still a good conception that is widely used at some infrastructures, large IRC networks inclusively.
It lacks good realisation in UnrealIRCd, but still exists and is very useful. Although they have reduced its functionality in a new branch, that is not permitting to have a local oper on a quarantined server, which I think is inappropriate logic.

I would create a request for a module, but still not sure whether it is modular or core functionality, because the linking functionality belongs to core.

In addiction to said, there would be 2 ways of implementing it: simple and complex.
Simple way is to create a `quarantine` option without any sub-configuration, that would just check oper attempts on quarantined peers and prevent them.
Complex and appropriate way to make it would involve oper classes to be interchanged and checked between servers, allowing to permit classes that would construct a "local" oper type. Because sometimes we may want to quarantine a server, but allow to use a local oper on it to check snotices, restart it or rehash. Implementing that feature this way is preferable, but may involve more coding.

**Comment by SISheogorath** [comment]
This feature is requested very often and gets always the same answer: If you don't trust a person. Don't give oper privileges.

InspIRCd follows the concept of oper trust. The idea is that a network should act like ONE network. So if I trust someone on Server A I shouldn't untrust him or her on Server B of the same network.

I know, this concept is not perfect from a security perspective and means that when there is on server compromised you have a big problem. But it is way more practical and is better for most IRC networks. For those who really want to have "untrusted" links, they should consider to use anything that is not InspIRCd.

Because when we want to start something like this, we should first of all verify all commands we get from links, otherwise this would be pointless. Right now we trust links and only prevent them from doing complete garbage. But no auditing on these commands.

**Comment by Techman-** [comment]
This feature is implemented in both [Atheme](https://github.com/atheme/atheme/blob/release/7.2/dist/atheme.conf.example#L441) and [Anope](https://github.com/anope/anope/blob/2.0/data/operserv.example.conf#L499-L507) as NOOP.

Piggybacking off of what @SISheogorath has already stated, InspIRCd's whole concept of IRC operatorship is based on trust, and individual servers do verification of commands while remotes basically accept what is broadcast across the network with limited checking. InspIRCd is not an adequate solution if you want more of a "federated" IRC network.

If you are indeed looking for something more towards that, [Charybdis](https://github.com/charybdis-ircd/charybdis#readme) is an apt alternative. You can choose what each server will accept remotely (like whether to accept bans from *.yournetwork.net compared to *.somebody-else.org).

**Comment by SaberUK** [comment]
As mentioned previously it does not make sense with InspIRCd's privilege model. If your system administrator is giving rights to users you don't trust you have a lot bigger issues as they could forge timestamps or do any number of other things to harm your network.

If you can't trust your system administrators then delink their servers.
