### ISSUE TITLE
Decide what commonly used modules to import from inspircd-extras.

### ISSUE THREAD

**Issue by SaberUK** [inspircd/inspircd#1455]
We have lots of useful modules in inspircd-extras and should include the most useful ones with 3.0.

The current list of 2.0 extras modules are:

* [ ] m_accounthost
* [ ] m_antibear
* [ ] m_antibottler
* [ ] m_antirandom
* [ ] m_authy
* [ ] m_autodrop
* [ ] m_autokick
* [ ] m_bannegate
* [x] m_blockhighlight
* [ ] m_changecap
* [ ] m_ciphersuitejoin
* [ ] m_conn_banner
* [ ] m_conn_matchident
* [ ] m_conn_vhost
* [ ] m_custompenalty
* [ ] m_dccblock
* [ ] m_disablemodes
* [ ] m_extbanredirect
* [ ] m_findxline
* [ ] m_flashpolicyd
* [ ] m_forceident
* [ ] m_hash_gnutls
* [ ] m_hideidle
* [ ] m_identmeta
* [ ] m_ircxusernames
* [ ] m_join0
* [ ] m_joinoninvite
* [ ] m_joinpartsno
* [ ] m_joinpartspam
* [ ] m_lusersnoservices
* [ ] m_messagelength
* [ ] m_namedstats
* [ ] m_nickdelay
* [ ] m_nickin001
* [ ] m_nocreate
* [ ] m_nouidnick
* [ ] m_opmoderated
* [ ] m_pretenduser
* [ ] m_privdeaf
* [ ] m_qrcode
* [ ] m_quietban
* [ ] m_require_auth
* [ ] m_requirectcp
* [x] m_rotatelog
* [ ] m_rpg
* [ ] m_slowmode
* [ ] m_solvemsg
* [ ] m_sslstats_gnutls
* [ ] m_stats_unlinked
* [ ] m_svsoper
* [ ] m_timedstaticquit
* [ ] m_topicall
* [ ] m_totp

The following modules have either already been imported or have had their function included:

* m_anticaps
* m_ascii
* m_cap_chghost
* m_capnotify
* m_classban
* m_conn_delayed_join
* m_deferaccept
* m_fullversion
* m_geoipban
* m_invitenotify
* m_ircv3_sts
* m_noctcp_user
* m_nooponcreate
* m_override_umode
* m_rehashsslsignal
* m_regex_re2
* m_replaymsg
* m_sha1

Please respond if you would like a specific module or its behaviour included with 3.0. Include a rationale if possible too.

**Comment by SaberUK** [comment]
A few days ago I proposed to replace m_blockcaps and replace it with m_anticaps from extras.

https://github.com/inspircd/inspircd/pull/473#issuecomment-355735461

**Comment by rburchell** [comment]
It might be worth considering (long term) just ditching extras altogether. The split was never really clear, and I think it's become even less so over time. There's some stuff that is almost certainly useless nowadays (like antibear), but a lot of the more useful stuff like something geoip lookup capabilities for instance I could see being useful in core - if libraries they require are installed, just like the SQL modules.

**Comment by genius3000** [comment]
I'd like to see -extras remain a thing, perhaps renamed to contrib or similar to better differentiate from the "vendor extras". It's nice having a central repo for these "odd-ball" or one-off modules.

As for 2.0-extras I'd like to see in 3.0 core:
- m_antirandom
- m_blockhighlight
- m_findxline
- m_rehashsslsignal

You can also move m_classban and m_ircv3_sts to the already included list.

**Comment by genius3000** [comment]
I'd like to see -extras remain a thing, perhaps renamed to contrib or similar to better differentiate from the "vendor extras". It's nice having a central repo for these "odd-ball" or one-off modules.

As for 2.0-extras I'd like to see in 3.0 core:
- m_antirandom
- m_blockhighlight
- m_findxline
- m_rehashsslsignal

You can also move m_classban and m_ircv3_sts to the already included list.

**Comment by Robby-** [comment]
I also think extras should stay, for the reasons @genius3000 said.

List of modules for including in 3.0:
* m_disablemodes (this should also be renamed to describe it better: m_conn_disablemodes)
* m_findxline (maybe even merge this in the xline system rather than keeping it as a separate module)
* m_privdeaf (though, merging this with m_deaf is more logical I think, maybe even with options for disabling/enabling one or both modes to mimic the current situation where one deaf-module can be loaded but the other is not, but default both to enabled)
* m_rehashsslsignal
* m_require_auth (maybe even merge this in the xline system rather than keeping it as a separate module)
* m_slowmode

**Comment by del6597** [comment]
I would suggest adding m_join0. It's short, sweet, and conforms to the [rfc](https://tools.ietf.org/html/rfc2812#section-3.2.1).

**Comment by GLolol** [comment]
Seconding the following:

- m_rehashsslsignal
- m_blockhighlight
- m_findxline
- m_join0

**Comment by AntiDjin** [comment]
1. m_requirectcp.cpp
2. m_rpg
3. m_quietban

**Comment by SISheogorath** [comment]
* m_geoipban
* m_stats_unlinked
* m_conn_banner
* m_forceident
* m_blockhighlight
* m_noctcp_user

**Comment by Techman-** [comment]
* `m_antirandom` (Unreal bundles something like this now by default and it's highly useful when configured correctly)
* `m_bannegate` (I think this should be a fundamental feature of extended ban types)
* `m_findxline`
* `m_namedstats` (This makes quality of life for opers significantly easier)
* `m_geoipban` (And also, update it to support IPv6!)
* `m_join0` (RFC)
* `m_totp`
* `m_privdeaf`

(I may add later but this is what I can think of right now)

------------
Additionally, I'd like to raise the following questions:
* `m_extbanredirect`: Is this a better way to do ban redirects compared to using `m_banredirect` which crudely accepts only `*!*@host#channel`, since it could support other extended ban types?

**Comment by SaberUK** [comment]
I'm not really a fan of importing the functionality join0. Its from RFC28xx which we generally don't respect unless theres a really good reason to and from what i've seen the majority of use of it seems to be abuse by tricking new users into running it.

**Comment by SaberUK** [comment]
m_rehashsslsignal has been imported in 9da5c8e200833a957d6221ddcaf900cb3b839c13.

**Comment by SaberUK** [comment]
m_anticaps has been imported in 36e6dc7bc8c21db2f8fa63c96b3e3aa23886e056.

**Comment by Cronus89** [comment]
m_antirandom - Been using it for years, on unrealircd and now inspircd.  Catches the dumb bot spammers, very useful.

m_findxline - Searching xlines and able to remove them, no brainer there.  I'd like to be able to search based on time.  i.e. lookup xlines matching *spammer* that were added in the last X days,weeks,months etc

m_stats_unlinked - for lazy opers such as myself, see what servers didnt relink or old servers that should be removed from link blocks

m_requirectcp - I have been using this on a few networks and it has stopped the annoying join spam bots entirely.  I'd like to see it expanded where there were certain criteria needed to fully block, like clients that dont reply to ctcp, dont use cap, etc then block.

**Comment by KoraggKnightWolf** [comment]
In addition to the many listed ones I would like to suggest m_conn_vhost in the modified version of  https://github.com/inspircd/inspircd-extras/pull/130 and the reasoning for it I have elaborated on in this request: https://github.com/inspircd/inspircd-extras/issues/129 (just to spare you guys a long elaboration in here).
 In addition also m_disablemodes as has also been stated by someone.
Good for combatting many forms of spam: m_blockhighlight, m_blockinvite, m_antirandom, m_require_ctcp, m_privdeaf, m_joinpartspam

Thank you for your time and effort in advance and for allowing people to vote on modules to be included in the next major branch.

Regards,

Koragg

**Comment by linuxdaemon** [comment]
I think `m_noctcp_user` could pretty easily be merged with `m_noctcp`  in 3.0
