### ISSUE TITLE
[2.0.25] userhost/userip does not respond when using a nick not in use

### ISSUE THREAD

**Issue by linuxdaemon** [inspircd/inspircd#1456]
When running `USERHOST a_nick_not_in_use`, the server responds like so:
```
<< USERHOST a_nick_not_in_use
>> :dev-ca1.snoonet.org 302 linuxdaemon :
```
Where it should most likely respond with `ERR_NOSUCHNICK`.

However, `USERIP a_nick_not_in_use` does not respond at all.

This behavior seems inconsistent between these two commands and also inconsistent with pretty much every other command that looks up data by nick, which normally use the proper `ERR_NOSUCHNICK` response.

## Version
```
snoonet@dev-ca1:~$ inspircd/bin/inspircd --version

InspIRCd-2.0.25 rv2.0.25-11-g758cf50
```

**Comment by SaberUK** [comment]
The current behaviour is compliant with that of other implementations.

**Comment by SaberUK** [comment]
Because of what I mentioned in my last comment i'm going to close the issue.
