### ISSUE TITLE
Only 1012 of Max Current Global Users and 1004 of Max Current Local Users

### ISSUE THREAD

**Issue by brus37** [inspircd/inspircd#1457]
Hello,

i am using InspIRCd-2.0 with cgiirc access to clients, but it accept only 1012 users connection. The user 1013 can't enter and the server turn very slow and increase the cpu use.
Is it configurable?
Is a cgiirc problem?

**Comment by SaberUK** [comment]
This is most likely a configuration issue not a bug. Your system is probably limited to 1024 max open fds per process and you need to raise the limit. Google for the name of your operating system followed by "raise fd ulimit" to find out how to do this.

Also, this is bug tracker not a support system. For support please visit irc.inspircd.org #inspircd.
