### ISSUE TITLE
E-lines don't work for WebIRC users

### ISSUE THREAD

**Issue by Robby-** [inspircd/inspircd#1465]
**Steps to reproduce the issue:**
1. Set an E-line on an IPv6 range.
2. Set a G-line on the parent IPv6 range.
3. User cannot connect with WebIRC due to G-line.

**Describe the results you received:**
User is G-lined when connecting with WebIRC.

**Describe the results you expected:**
User should be able to connect just fine because of the E-line.

**Output of `./bin/inspircd --version`:**
InspIRCd-2.0.25 rv2.0.25-11-g758cf50

**Comment by SaberUK** [comment]
This is an unfortunate limitation based on how the WebIRC protocol works. There isn't really a lot we can do about this.

**Comment by genius3000** [comment]
Following up on some backlog from #inspircd, this may be fixable and having a quick peek, it looks like `m_cgiirc` doesn't check against E-Lines prior to checking K/G/Z-Lines. I don't have an active test-net with any cgi/web-irc setup but I may be able to set that up in the next few days.  
Initially I would think putting an E-Line check before each `user->CheckLines(true);` should suffice.

**Comment by SaberUK** [comment]
Ah, I thought you meant that you were having problems with WebIRC clients being hit by a G-Line on the gateway IP. Yeah, this should be fixable. I'll post a branch for you to test in a bit.

**Comment by SaberUK** [comment]
>it looks like m_cgiirc doesn't check against E-Lines prior to checking K/G/Z-Lines

ChangeIP calls LocalUser::SetClientIP which should be doing the eline checking.

**Comment by genius3000** [comment]
Correct, I missed that (should've updated that comment with a correction). My later findings (on top of SaberUK's speculative fix) are that between [this ChangeIP and CheckLines](https://github.com/SaberUK/inspircd/blob/c9ec8d8771e4bf4693c76f50bdbcd40eb103abdc/src/modules/m_cgiirc.cpp#L302...L309) the exempt either fails to be set true or is reset.

**Comment by SaberUK** [comment]
This is fixed in insp20 git.
