### ISSUE TITLE
/check command in combination with m_geoip only able to fetch the geoip country code of a webirc, not the real conneciton behind it

### ISSUE THREAD

**Issue by KoraggKnightWolf** [inspircd/inspircd#1470]
**Description**
When using the /check command on a user connecting via a cgi:irc/webirc connection, then the geoip location is not fetched from the actual real host (despite /check finding it) but only from the cgi:irc host. 
This issue is confirmed to occur on InspIRCd 2.0.25

**Steps to reproduce the issue:**
1. Be /oper'ed up on an InspIRCd network (tested on version 2.0.25)
2. Have a user with a properly configured webirc (e.g. KiwiIRC) connect
3. /check the nickname and look at the CHECK meta:geoip_cc - it will be the originiation of the webirc
IP/host NOT of the actual real IP/host of the connected entity.

This appears unintuitive as the /check command can fetch the real IP/host but the issue might be at which point m_geoip tries to fetch the location during the registration process.

Thank you for your time and effort in advance.

Regards,

Koragg

**Comment by SaberUK** [comment]
Fixed in commit fdeccd7.
