### ISSUE TITLE
Why has IOCP been removed? Is there something about solaris that makes it unliked among Insp users?

### ISSUE THREAD

**Issue by janicez** [inspircd/inspircd#1477]
So I've recently gotten back to inspircd after a hiatus generated by ircd-chatd, and I noticed you no longer support IOCP on Solaris. Is this replaced by something else (devpoll maybe)? Or is Solaris no longer a Tier 1 OS?

**Comment by SaberUK** [comment]
Neither Adam nor I have hardware for testing on Solaris and Oracle have fired most of the Solaris development team so it is clear that Solaris is reaching the end of its life. We're not really interested in maintaining a giant pile of code for a dead operating system that is barely used by anyone.

If there are any remaining Solaris users they can continue to use the 2.0 branch where Solaris is still supported.

Note: not all Solaris code has been removed as Solaris derivatives like illumos still exist, However, illumos supports epoll so maintaining a separate socket engine for it is unnecessary.

---

This is an issue tracker. In the future please ask such questions on our IRC channel at irc.chatspike.net #inspircd.
