### ISSUE TITLE
m_ldapauth whitelisting should compare against a user mask.

### ISSUE THREAD

**Issue by SadieCat** [inspircd/inspircd#1478]
Currently LDAP whitelisting works via two methods. For nicks it uses space delimited values in `<ldapauth:allowpattern>` and for CIDR ranges it uses a series of `<ldapwhitelist:mask>` tags.

It would be useful that instead of this it could instead take a list of nick!user@host or nick!user@ip/cidr masks instead.

**Comment by SaberUK** [comment]
We should also do this for m_sqlauth.
