### ISSUE TITLE
Syslog logging

### ISSUE THREAD

**Issue by f0o** [inspircd/inspircd#1486]
systemd and journald do a great job at keeping logs tidy and neat.

It would be nice to have a way to make inspircd log into journald, either by using /dev/log or by using stdout.

Alternatively, native syslog could also be used.

**Comment by SaberUK** [comment]
I have a local branch which implements this (as well as a rewrite of most of logging) but I need to finish it. I'll close this issue when its done.

**Comment by lvenier** [comment]
Hi there,

Is that been implemented in the current v3 branch ?

Rgds

**Comment by SadieCat** [comment]
This has been implemented in git master.
