### ISSUE TITLE
Require TLS for server to server links

### ISSUE THREAD

**Issue by SadieCat** [inspircd/inspircd#1489]
We should mandate that server to server links use TLS to ensure that privacy is not unknowingly being violated by e.g. a channel which is marked as SSL-only leaking conversations via plaintext server links.

Allowing local links to be exempt from this for services would probably be an acceptable exemption as if an attacker has the ability to snoop on local traffic they can probably snoop via other means too.

**Comment by LetUsFsck** [comment]
I always assumed this was a misconfiguration on my part, thanks for bringing it up. I would rate this higher than "minor" for security enhancement. Cheers!

**Comment by SadieCat** [comment]
This has been implemented in master.
