### ISSUE TITLE
Add some kind of opt-in telemetry system.

### ISSUE THREAD

**Issue by SadieCat** [inspircd/inspircd#1490]
We currently don't really have a good way of finding out what people are using so we have to guess based on crawlers. Unfortunately crawlers can't really find every server, can't get every piece of information, and can't ask for consent before collecting data.

It **must** be opt-in in and anonymise data order to preserve user privacy. This might cause some inaccurate results but privacy is non-negotiable. I want to make it **really clear** that privacy is important and that no information would be collected without permission or without a valid use for it. We could allow server operators to customise the specific data points to allow them to share as much data as they feel comfortable sharing.

Information it should NOT collect (non-exhaustive):

- Any kind of personal data about the server administrators (e.g. `<admin:email>` or `<server:name>`).
- Any kind of personal data about users connected to the server.
- Any kind of chat history.

Information it should ideally collect:

- Full InspIRCd version (including distribution label if present).
- Host operating system name and version.
- Compiler name and version.
- List of loaded modules (probably restricted to VF_VENDOR modules only to avoid accidentally making the dataset easy to deanonymise?).
- List of loaded commands (possibly rounded to a few significant figures to protect privacy?).
- The values of certain config values we are interested in (no passwords and probably nothing from a text field).

In the interests of openness i'd like to also make the collected data public so that other IRC developers can use it. The data should be sufficiently anonymised (e.g. "8% of servers run m_foo") that making this information public should not be harmful.

**Comment by KeiroD** [comment]
I'd be willing to set something like this up. As far as e-mails and such... why not make it optional? Some may not mind having their e-mails be public information. Things like that.

The personal data about users and chat history, I definitely agree on not providing but for server ops, I think you should leave the option of how much they want to share up to them.

**Comment by SaberUK** [comment]
>As far as e-mails and such... why not make it optional?

It is not useful information to collect.

**Comment by GLolol** [comment]
This seems like a reasonable proposal - I would also consider stripping the hostname portion of the "Full InspIRCd version" since those values can be traced back to specific networks.

**Comment by SaberUK** [comment]
>I would also consider stripping the hostname portion of the "Full InspIRCd version" 

There is no hostname in the version. I'm not sure what you're referring to but i'm talking about the value of the INSPIRCD_VERSION macro in src/config.h after configure has run.

**Comment by SadieCat** [comment]
Unfortunately I'm not sure this is viable in a way which respects privacy.
