### ISSUE TITLE
Fix bug in module Geoip 

### ISSUE THREAD

**Issue by mircx** [inspircd/inspircd#1492]
Hello Subrek this more message to know the module geoip when install in freeBsd make problem please change it to the geoip from 3
An error occured when executing: clang++ -o modules/m_geoip.so -pipe -fPIC -DPIC -pedantic -Woverloaded-virtual -Wshadow -Wformat=2 -Wmissing-format-attribute -Wall -O2 -Iinclude -DMODNAME=m_geoip.so -fPIC -shared -rdynamic /usr/home/asher/inspircd-2.0.26/src/modules/m_geoip.cpp -lGeoIP
/usr/home/asher/inspircd-2.0.26/src/modules/m_geoip.cpp:24:10: fatal error: 'GeoIP.h' file not found
#include <GeoIP.h>
         ^~~~~~~~~
1 error generated.
*** Error code 1
you no make update to geoip 2.0.26
https://github.com/inspircd/inspircd/commit/8c0426116cdf09e807da12b6b23d977c4a073119
void ReadConfig(ConfigStatus&)
+	void ReadConfig(ConfigStatus&) CXX11_OVERRIDE
 	{
 		ConfigTag* tag = ServerInstance->Config->ConfValue("geoip");
 		extban = tag->getBool("extban");
@@ -106,7 +106,13 @@ class ModuleGeoIP : public Module, public Whois::EventListener
 		return Version("Provides a way to assign users to connect classes by country using GeoIP lookup", VF_OPTCOMMON|VF_VENDOR);
 	}
 
-	ModResult OnCheckBan(User *user, Channel *c, const std::string& mask)
+	void On005Numeric(std::map<std::string, std::string>& tokens) CXX11_OVERRIDE
+	{
+		if (extban)
+			tokens["EXTBAN"].push_back('G');
+	}
+
+	ModResult OnCheckBan(User* user, Channel*, const std::string& mask) CXX11_OVERRIDE
 	{

**Comment by SaberUK** [comment]
This is not a bug. You have been told how to fix your problem.

I recommend that you stop ban evading.
