### ISSUE TITLE
Failed to load module m_halfop.so

### ISSUE THREAD

**Issue by w1bsb** [inspircd/inspircd#1494]
**Description**

**Steps to reproduce the issue:**
1. On server rehash, error is produced that m_halfop.so can't be loaded because it already exists.
**Describe the results you received:**
Thu May 17 11:24:40 2018: ANNOUNCEMENT: Rehashing config file inspircd.conf Caught SIGHUP
Thu May 17 11:24:40 2018: Module m_halfop.so unloaded
Thu May 17 11:24:40 2018: Unable to load m_halfop.so: Mode halfop already exists.
Thu May 17 11:24:40 2018: ANNOUNCEMENT: Failed to load module m_halfop.so: Unable to load m_halfop.so: Mode halfop already exists.
Thu May 17 11:24:40 2018: ANNOUNCEMENT: *** Successfully rehashed server.

**Describe the results you expected:**
m_halfop.so is not loaded, and appears to be deprecated.  I expect not to see this error. I followed the configuration example and loaded m_customprefixes.so and set this line in my config:
<customprefix name="halfop" letter="h" prefix="%" rank="20000" ranktoset="30000">

I also have allowhalfop="yes" in the options section.

**Additional information you deem important (e.g. issue happens only occasionally):**
It might be a configuration issue, but I'm not sure. I made sure m_halfop.so is disabled, customprefix is loaded, and the prefix is defined.   If I disable customprefix/halfop, when my 2nd server tries to link in, I get this error:
CAPAB negotiation failed: Channel modes not matched on these servers. Not loaded here: halfop=%h

So I loaded customprefix and the halfop customprefix and that error goes away, but on rehash, it says can't load halfop.so because its already loaded. I'm stumped.

**Output of `./bin/inspircd --version`:**
InspIRCd-2.0.26 rv2.0.26

**Comment by SaberUK** [comment]
Do you have `<options:allowhalfop>` enabled? This is a legacy setting from 1.x that should not be used in 2.0.

**Comment by w1bsb** [comment]
Thanks @SaberUK that was the problem.  That option was enabled, and removing it has solved the issue. Appreciate your help.
