### ISSUE TITLE
Error when compiling a fresh install of 2.0.26

### ISSUE THREAD

**Issue by sharstine** [inspircd/inspircd#1495]
**Description**
Error when I run "make" on a new install of inspircd-2.0.26.

**Steps to reproduce the issue:**
1. ./configure (go with default options)
2. make

**Describe the results you received:**
An error occured when executing: g++ -o obj/dynamic.o -pipe -fPIC -DPIC -pedantic -Woverloaded-virtual -Wshadow -Wformat=2 -Wmissing-format-attribute -Wall -O2 -g1 -Iinclude -c /home/xxxxxxxx/inspircd-2.0.26/src/dynamic.cpp
/home/xxxxxxxx/inspircd-2.0.26/src/dynamic.cpp: In member function 'void DLLManager::RetrieveLastError()':
/home/xxxxxxxx/inspircd-2.0.26/src/dynamic.cpp:99: error: invalid conversion from 'const char*' to 'char*'
*** Error code 1
Stop in /home/xxxxxxxx/inspircd-2.0.26/build.
*** Error code 1
Stop in /home/xxxxxxxx/inspircd-2.0.26.

See full output: https://pastebin.com/3JkdZ0LX

**Describe the results you expected:**
InspIRCd should compile without error.

**Additional information you deem important (e.g. issue happens only occasionally):**
OS is FreeBSD 7.3-RELEASE-p7.

Output of g++ --version and gcc --version is:
g++ (GCC) 4.2.1 20070719  [FreeBSD]

clang isn't installed on the server I'm using, so that's not an option for me.

**Output of `./bin/inspircd --version`:**
Output of ./inspircd version is: 
InspIRCd version: InspIRCd-2.0.26(r0)

**Comment by SaberUK** [comment]
Fixed in 3cd61d86de6a18a79fdd21952a67b7d1a7f9c517. Thanks for reporting.
