### ISSUE TITLE
Parse error in inspircd.conf with Atheme

### ISSUE THREAD

**Issue by yuljk** [inspircd/inspircd#1496]
**Description**
XML parsing error when starting the inspircd service after adding <chanprotect to inspircd.conf

Hi guys - I've configured Atheme with InspIRCD - however when I attempt to restart the inspircd service I get a parse error as per below

Invalid XML entity name in value of <chanprotect:aprefix> To include an ampersand or quote, use &amp; or &quot; Parse error at /home/inspircd/inspircd-2.0.26/run/conf/inspircd.conf:155:20 (inside tag chanprotect at line 153)
This is the section it is referring to..

<chanprotect
noservices="no" < This line
qprefix="~"
aprefix="&">

**Steps to reproduce the issue:**
1.  Add relevant sections from Atheme documentation to inspircd.conf - service won't start
2. Remove said sections - service starts
3.

**Describe the results you received:**
Service doesn't start

**Describe the results you expected:**
Service should start

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `./bin/inspircd --version`:**

**Comment by SaberUK** [comment]
>aprefix="&"

You should be using `&amp;` not `&;` when using the XML config format.

**Comment by yuljk** [comment]
Many thanks - that has allowed the service to start.

I've tested with Hexchat and /msg NickServ help returns nothing.  Seems Atheme isn't linked properly.

Here's my inspircd.conf

https://pastebin.com/gm5Ca4vS

Many thanks for any help!

**Comment by SaberUK** [comment]
You have probably misconfigured your uplink in atheme. You'd need to ask someone who knows about atheme for that though.

You can get support for atheme at chat.freenode.net #atheme.
