### ISSUE TITLE
Send ban to services

### ISSUE THREAD

**Issue by No-0n3** [inspircd/inspircd#1499]
It would be great if the action "AKILL" could be added to dnsbl module so a custom string that is sent to the bot that handles akill could be sent instead. So services can handle the ban and can be visible through the "AKILL LIST" for easier maintaining.

Will need two extra keys in the "dnsbl"-tag, botname to send to and string to send.

**Comment by SaberUK** [comment]
This would need services integration (i.e. at @anope @atheme) and to be honest i'm not really sure how useful it is. You can get a list of [GKZ]Lines with their respective `/STATS` characters if you want to be able to list them.

**Comment by No-0n3** [comment]
It's more so you can list all bans in one place. It's a function similiar to what HOPM uses when banning.

**Comment by Robby-** [comment]
I think this is a services-only thing, and no code changes to inspircd itself are even required for this. Services should be able to get/see all the bans via regular S2S traffic. However, a module for anope or atheme would have to be coded for them to actually do anything with the bans (like display them nicely in a list, be able to manage them via OperServ, etc.).

**Comment by No-0n3** [comment]
Ok, thx

**Comment by genius3000** [comment]
If interested, I wrote an [Anope module](https://github.com/genius3000/anope-modules/blob/master/m_xlinetoakill.cpp) for X-Line syncing to the AKILL list.  
I was contemplating the original idea here, but services wouldn't like receiving an 'AKILL ADD' command from a server nor a FakeUser that has no services privileges.

**Comment by No-0n3** [comment]
Great, will test it. :)
