### ISSUE TITLE
Configure don't put -DHAS_STRLCPY to GNUmakefile

### ISSUE THREAD

**Issue by p12** [inspircd/inspircd#1503]
**Description**

Hi, I build v2.0.26 on AltLinux and see error.

**Steps to reproduce the issue:**
1. git clone -b insp20 ...
2. cd ....
3. ./configure (default)
4. make

**Describe the results you received:**
compilation error: include/inspstring.h:31:65: error: declaration of ‘size_t strlcpy(char*, const char*, size_t)’ has a different exception specifier
...
/usr/include/string.h:571:15: error: from previous declaration ‘size_t strlcpy(char*, const char*, size_t) throw ()’

**Additional information you deem important (e.g. issue happens only occasionally):**
[pak@cn inspircd-2.0.26]$ gcc -v
Using built-in specs.
COLLECT_GCC=x86_64-alt-linux-gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-alt-linux/5/lto-wrapper
Target: x86_64-alt-linux
Configured with: ../configure --host=x86_64-alt-linux --build=x86_64-alt-linux --target=x86_64-alt-linux --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var/lib --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-dependency-tracking --without-included-gettext --enable-shared --program-suffix=-5 --with-slibdir=/lib64 --with-bugurl=http://bugzilla.altlinux.org --enable-__cxa_atexit --enable-threads=posix --enable-checking=release --with-system-zlib --without-included-gettext --enable-multilib --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --with-arch_32=i586 --with-tune_32=generic --with-multilib-list=m64,m32,mx32 --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,java,ada,go,lto --enable-plugin --enable-java-awt=gtk --with-native-libdir=/usr/lib64/gcj-5 --with-ecj-jar=/usr/share/java/ecj.jar --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-1.5.0.0/jre --enable-libgcj-multifile --disable-libjava-multilib --enable-java-maintainer-mode
Thread model: posix
gcc version 5.3.1 20151207 (ALT Linux 5.3.1-a
[make_gcc5.3_error.txt](https://github.com/inspircd/inspircd/files/2158042/make_gcc5.3_error.txt)
[GNUmakefile.txt](https://github.com/inspircd/inspircd/files/2158054/GNUmakefile.txt)
[.config.cache.txt](https://github.com/inspircd/inspircd/files/2158055/default.config.cache.txt)

lt3) (GCC)

**Comment by SaberUK** [comment]
Can you please see if this patch fixes the issue? https://github.com/SaberUK/inspircd/commit/87fc5dd4e83d456ea6b1ddc71c1852563620d602

**Comment by p12** [comment]
yes, this patch fixes the issue. thanks
