### ISSUE TITLE
Support /foo/i syntax in regex modules

### ISSUE THREAD

**Issue by CorruptMonkey** [inspircd/inspircd#1505]
Currently regular expressions in the PCRE module are case sensitive which makes it difficult to write simplified patterns. As Sadie said on IRC, you would have to do something like `^[Ff][Oo][Oo]$` to make it case insensitive at this time. I believe this should be simplified to something such as `/^foo$/i`.

**Comment by genius3000** [comment]
FYI: `(?i)^foo$` works. I do like the idea of supporting the `/foo/i` syntax though.

**Comment by SadieCat** [comment]
This has been implemented in master with the new regex system.
