### ISSUE TITLE
[Feature Request]: Mode that throttles messages after /joining a channel

### ISSUE THREAD

**Issue by Jigsy1** [inspircd/inspircd#1506]
What with the recent "freenodegate" spam attack - which is still ongoing I believe - would it be possible to include a channel mode which prevents a user from saying anything in a channel unless they've been in it for more than X seconds?

Using +J as an example (since I'm not sure what letters are already in use): /mode #chan +J 120 - means that they need to be in #chan for 120 seconds before they can speak otherwise the message is discarded.

This would most likely require caching the Unix Epoch of the time the user joined a channel then comparing it against the current epoch.

**Comment by SaberUK** [comment]
You want [m_delaymsg](https://github.com/inspircd/inspircd/blob/insp20/docs/conf/modules.conf.example#L707-L713).
