### ISSUE TITLE
Bug in m_httpd and/or m_httpd_stats

### ISSUE THREAD

**Issue by EllisField** [inspircd/inspircd#1507]
There seems to be some bug in the way that the InspIRCd web server returns the data when using `m_httpd_stats`.

On a small server the resulting file size of the XML is `40 KB` but takes 2 minutes to be returned using for example PHP?

`curl` seems to get the file immediately, but PHP takes around 2 minutes, yet much larger XML files are returned immediately when I test whilst hosted on for example apache?

Could it be that the built-in web server is not correctly closing connections or something similar for instance, and PHP is being more strict than say `curl`, or does anyone else have similar experience when using these modules?

Like I say, PHP retrieves much larger files almost instantly, it is just the built in InspIRCd web server I am having issue with.

```
# curl -sI http://inspircdserver:8080/stats | grep -i Content-Length
Content-Length: 41806
```

```
# time curl http://inspircdserver/8080/stats > /dev/null
real	0m0.028s
user	0m0.007s
sys	0m0.011s
```

vs.

```
# time php -r 'file_get_contents("http://inspircdserver:8080/stats");'
...
real    2m0.147s
user    0m0.012s
sys     0m0.012s
```

**Comment by SaberUK** [comment]
I'm guessing that PHP is sending a web request that the module doesn't like and its timing out. Its HTTP parser is pretty temperamental and a replacement is currently being written for it by @edef1c although I think she's waiting for me to visit her again before we finish it.

I'll look into this shortly.
