### ISSUE TITLE
Change OnUserQuit event to allow modify quit message

### ISSUE THREAD

**Issue by iwalkalone69** [inspircd/inspircd#1508]
**Description**

Be able to change quit message as we can do with part messages. This is useful to implement channel mode to hide part and quit messages (+u in some networks).

Maybe it is enough to change OnUserQuit method in src/modules.cpp from:

void            Module::OnUserQuit(User*, **const** std::string&, const std::string&) { DetachEvent(I_OnUserQuit); }

To:

void            Module::OnUserQuit(User*, std::string&, const std::string&) { DetachEvent(I_OnUserQuit); }

Removing const should allow to modify it like it is possible in OnUserPart.

Then, all modules using it must be adapted.

**Comment by iwalkalone69** [comment]
Added a pull request with the changes should be applied:

https://github.com/inspircd/inspircd/pull/1509

**Comment by SaberUK** [comment]
#1629 has now been merged.
