### ISSUE TITLE
Incorrect real ip on ipv6 stack on FreeBSD 11.x

### ISSUE THREAD

**Issue by chrcoluk** [inspircd/inspircd#1511]
**Description**

Was reported to me that my inspircd server instance running on FreeBSD 11.1 has been misbehaving on ipv6 connections, I am the only server on our network running FreeBSD, since its a not so popular OS these days.  I then tested and was able to connect fine on both ipv4 and ipv6 but when whoising myself the reported ip is a incorrect ip in ipv4 format.

Chrysalis is connecting from Chrysalis@0.0.1.36 0.0.1.36

**Steps to reproduce the issue:**
1. Install FreeBSD OS
2. Compile and install Inspircd 2.0
3. Connect over ipv6 and whois yourself

**Describe the results you received:**

Received a mismatched ip in ipv4 format

Chrysalis is connecting from Chrysalis@0.0.1.36 0.0.1.36

**Describe the results you expected:**

On a linux hosted inspircd I got the proper ipv6 as below.

Chrys2 is connecting from Chrysalis@2a02:c7f:4b12:3d11::124 2a02:c7f:4b12:3d11::124

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `./bin/inspircd --version`:**

InspIRCd version: InspIRCd-2.0.25(r0)

**Comment by SaberUK** [comment]
Can you share your `<bind>` config?

**Comment by chrcoluk** [comment]
Not using 4in6

`<bind
      address="87.98.193.109"
      port="6697"
      type="clients"
      ssl="gnutls"
>

<bind address="87.98.193.109" port="6660-6669,7000" type="clients">
<bind address="2001:41d0:4:d223::2:1" port="6660-6669,7000" type="clients">
<bind address="87.98.193.109" port="9999" type="clients" ssl="gnutls">
<bind address="87.98.193.109" port="5555" type="servers">
<bind address="2001:41d0:4:d223::2:1" port="9999,6697" type="clients" ssl="gnutls">
<bind address="&IPVPN;" port="2122" type="servers">

Also variable defined

<define name="IPVPN" value="10.1.34.2">`

**Comment by SaberUK** [comment]
That would be useful as i'm unable to reproduce this.
