### ISSUE TITLE
Connect Blocks Don't Honour CGIIRC IPs

### ISSUE THREAD

**Issue by armouredking** [inspircd/inspircd#1512]
So I've been bashing my head against a brick wall trying to figure this out and the title is about the best I can explain from my analysis.

I am using:

- Inspircd 3.0.0a9
- Atheme 7.2.10-r2
- KiwiIRC Next 18.07.09.1-1

What's happening:

I am attempting to setup the "proper" routing with connect blocks for the CGIIRC module. The inspircd.conf file looks like so:

`<connect name="kiwistart" parent="main" allow="192.168.200.62/32" localmax="250" globalmax="250" limit="150">`
`<connect name="kiwiloaded" parent="main" maxchans="20" webirc="*" limit="1500" motd="kiwimotd">`
`<connect name="main" allow="*" maxchans="35" timeout="10" pingfreq="2m" hardsendq="1M" softsendq="8192" recvq="8K" threshold="10" commandrate="1000" fakelag="on" localmax="3" globalmax="3" resolvehostnames="yes" useident="no" limit="5000" modes="+x">`

Not a lot to see here and it's quite barren but it's the grits to make what happens happen.

Connecting from my KiwiIRC client results in a debug log like this: https://pastebin.com/neE9aF5e

So unrelated, but also an issue, core_dns can only isolate to one IP which makes things rather annoying when trying to specify stuff in config files by hostnames. It won't work, core_dns seems to know all the allowable IPs for a given hostname but only picks the first one and since this doesn't match the connecting IP it throws the error and forces the followup in IP only despite being able to resolve. That means my mask in modules.conf for the CGIIRC section has to be the IP address `192.168.200.62/32` and cannot be `gateway.deoremann.com`, as it won't match and then the CGIIRC info doesn't pass to the server.

The important bit is at the end. Now, my understanding of how this should work is that the first, initial sweep should load class kiwistart which will need the higher limits, as it specifies the IP address of the reverse proxy in front of KiwiIRC explicitly. By the time the second sweep occurs, we should have our user session data and we *should* be using the CGIIRC given IP address instead, so kiwiloaded should be picked, which is similar to main but has slightly different limits and a separate motd. However, as shown, we are not. kiwistart will always be selected because the IRC server says I am connecting from the proxy IP instead of the actual user IP, despite it seemingly knowing what the user IP is.

**Comment by genius3000** [comment]
This looks related to #1229 as it's the failed hostname lookup which keeps the incorrect (webirc) IP address as the hostname. This then let's it match the first connect class again. There's a 'needs to be tested' patch for 2.0 but I see m_cgiirc in 3.0 is a bit different (just requires a little more looking before forward porting the patch).

**Comment by armouredking** [comment]
Does that mean the "unrelated" problem with core_dns is actually related to CGIIRC not working or are they separate issues (since you mention it being in m_cgiirc). Either way I'm willing to be the guinea pig.

**Comment by SaberUK** [comment]
Fixed in 548def58600a5841792504bfdb117c1077482a0d for 2.0; will be merged across to master before the next alpha.
