### ISSUE TITLE
Geoip Modules Need to Update

### ISSUE THREAD

**Issue by MrMaro** [inspircd/inspircd#1521]
I am using geoip module to block user from some country joining my network for security reason. But current geoip module does not work. Pls take a look. 

TQ

**Comment by MrMaro** [comment]
What version of InspIRCd are you using?
- My current version of Inspircd is InspIRCd-2.0.23

What did you expect the module to do?
- I expect the module to block user from some country to connect to my irc network

What did it do?
- Currently the modules does not work, user from the country that i block still can join my irc network

How can we reproduce the issue?
- Geoip need to be updated

**Comment by MrMaro** [comment]
0x17dfa60 m_geoip.so -v-- :Provides a way to assign users to connect classes by country using GeoIP lookup - InspIRCd-2.0.23 r0

<connect deny="*" geoip="TR,RU,HK,CL,IT,VN,CN,VE">

**Comment by SISheogorath** [comment]
What does your config for geoip look like?

**Comment by MrMaro** [comment]
my config: <connect deny="*" geoip="TR,RU,HK,CL,IT,VN,CN,ID,IL,TH,PE,BR,,VE">

**Comment by MrMaro** [comment]
connect deny="*" geoip="TR,RU,HK,CL,VE"

**Comment by SISheogorath** [comment]
Please visit our support channel before we further annoy other people by sending mails out to an bug tracker:

[#inspircd on irc.inspircd.org](https://kiwiirc.com/nextclient/irc.inspircd.org/#inspircd)

**Comment by MrMaro** [comment]
sure TQ

**Comment by SaberUK** [comment]
If the GeoIP module is not blocking people from a specific country you have either misconfigured your connect class, the IP ranges are wrong in your GeoIP database, or the users are connecting using IPv6 which is not supported in 2.0 (3.0 will ship in the next few weeks with IPv6 GeoIP support).

Additionally, you should probably stay in an IRC channel for more than five minutes and actually tell people what you want support with before joining.
