### ISSUE TITLE
How to block Fancy ABC alphabets ansi codes?

### ISSUE THREAD

**Issue by legendskyk** [inspircd/inspircd#1524]
how to block fancy words i mean ansii words?
here is the example:
ⒶⓑⒸⒺⒹⒻ
₳฿₵ɆĐ₣
αв¢є∂f

that type of the words how possible to block it? because spammer use those type of phrase in flooding also abusing.

**Comment by SaberUK** [comment]
This is not possible currently but it will be added in a future release. See #1513 for more details.
