### ISSUE TITLE
User connecting to SSL socket not being marked as using a secure connection

### ISSUE THREAD

**Issue by linuxdaemon** [inspircd/inspircd#1526]
When connecting to an SSL socket, a user is not marked as connecting with a secure connection, despite receiving `[08:58:02] --- *** You are connected to <server> using SSL cipher 'TLS1.2-ECDHE-RSA-AES-128-GCM-AEAD'` when connecting. The client is also sending an SSL client certificate but `m_sslinfo` isn't storing it.

## Versions
`InspIRCd-3.0.0-1ec87c3`

**Comment by SaberUK** [comment]
Fixed in 9574997.
