### ISSUE TITLE
Support UTF-8 custom prefix characters

### ISSUE THREAD

**Issue by spaghetti2514** [inspircd/inspircd#1533]
m_customprefix throws an exception if the length of the given prefix string isn't 1, but clients are supposed to interpret prefix parameters as UTF-8, so custom prefixes should be allowed to be set to multibyte UTF-8 characters.

**Comment by spaghetti2514** [comment]
>RFC 1459 nor RFC 2812

The IETF is old-hat. They don't even have a .horse domain
https://modern.ircdocs.horse/#client-to-server-protocol-structure

**Comment by DanielOaks** [comment]
fwiw using UTF-8 in the protocol in this sort of way is likely to break a fair bit of stuff. while clients _should_ be interpreting messages as UTF-8, doing it with this is something that requires some definite decision on the side of the vendor (Insp devs) and isn't set out anywhere in particular by the horse docs. closest would be https://github.com/ircv3/ircv3-specifications/pull/272 which acks the breaking-older-clients thing.

**Comment by SaberUK** [comment]
Whilst Modern might recommend UTF-8 as mentioned by @DanielOaks this has the potential to break many popular clients which don't handle multibyte UTF-8 characters correctly currently so i'm going to reject this for now.
