### ISSUE TITLE
How to block multi colors spam

### ISSUE THREAD

**Issue by legendskyk** [inspircd/inspircd#1534]
How to block multi colors code in msg? like this screen shot:
![image](https://user-images.githubusercontent.com/42233490/48917578-518ed900-eea9-11e8-81a2-7e4c9230370b.png)

**Comment by SaberUK** [comment]
You have several options for this:

1. Use the blockcolor module and channel mode +c to block messages containing colour codes.
2. Use the stripcolor module and channel mode +S to strip colour codes from messages containing them.
3. Use the filter module to block the messages. You may find the "strip colour" option useful. https://github.com/inspircd/inspircd/blob/insp20/docs/conf/filter.conf.example#L40

This is a bug tracker not a support tracker. If you have any more questions please ask them at irc.inspircd.org #inspircd.
