### ISSUE TITLE
ParamModeBase::OnUnset() is non-virtual but has no implementation

### ISSUE THREAD

**Issue by linuxdaemon** [inspircd/inspircd#1536]
As the title says `ParamModeBase::OnUnset()` is not marked as virtual but also has no actual function. It appears as though it is there to be overriden but due to it not being virtual, that isn't always possible, and often results in warnings about hiding non-virtual functions.

Either `OnUnset()` should be marked virtual or `m_repeat` should stop overriding it.

https://github.com/inspircd/inspircd/blob/3d0d64933da3d37866fadfa042e34a1125315db6/include/parammode.h#L34

https://github.com/inspircd/inspircd/blob/3d0d64933da3d37866fadfa042e34a1125315db6/src/modules/m_repeat.cpp#L130

**Comment by SaberUK** [comment]
OnUnset does actually get called because because of template stuff but it should probably be marked as virtual in the base class anyway just in case someone ever tries to call it on a `ParamModeBase` instance.

**Comment by linuxdaemon** [comment]
If it's marked virtual, that also removes the need for https://github.com/inspircd/inspircd/blob/0b36f9bdc8482284f0801a4a46b2525b32fa09a4/include/parammode.h#L65-L66 as it could just be 
```c++
this->OnUnset(source, chan);
```
