### ISSUE TITLE
Error when compiling a fresh install of 2.0.27

### ISSUE THREAD

**Issue by sharstine** [inspircd/inspircd#1547]
**Description**
Error when I run "make" on a new install of inspircd-2.0.27.

**Steps to reproduce the issue:**
1. ./configure (go with default options, and enable OpenSSL)
2. make

**Describe the results you received:**
        BUILD:              modules/m_testnet.cpp
        BUILD:              modules/m_timedbans.cpp
An error occured when executing: clang++ -o modules/m_timedbans.so -pipe -fPIC -DPIC -pedantic -Woverloaded-virtual -Wshadow -Wformat=2 -Wmissing-format-attribute -Wall -O2 -Iinclude -DMODNAME=m_timedbans.so -fPIC -shared -rdynamic /home/xxxxxxxx/inspircd-2.0.27/src/modules/m_timedbans.cpp
clang++: error: unable to execute command: Killed
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
FreeBSD clang version 6.0.1 (tags/RELEASE_601/final 335540) (based on LLVM 6.0.1)
Target: i386-unknown-freebsd11.2
Thread model: posix
InstalledDir: /usr/bin
clang++: note: diagnostic msg: PLEASE submit a bug report to https://bugs.freebsd.org/submit/ and include the crash backtrace, preprocessed source, and associated run script.
clang++: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /tmp/m_timedbans-8cecda.cpp
clang++: note: diagnostic msg: /tmp/m_timedbans-8cecda.sh
clang++: note: diagnostic msg:

********************
*** Error code 254

Stop.
make[1]: stopped in /home/xxxxxxxx/inspircd-2.0.27/build
*** Error code 1

Stop.
make: stopped in /home/xxxxxxxx/inspircd-2.0.27

**Describe the results you expected:**
InspIRCd should compile without error.

**Additional information you deem important:**
OS is FreeBSD 11.2-STABLE.

Output of `g++ --version`:
g++: Command not found.

Output of `gcc --version`:
gcc (FreeBSD Ports Collection) 4.8.5

Output of `clang --version`:
FreeBSD clang version 6.0.1 (tags/RELEASE_601/final 335540) (based on LLVM 6.0.1)
Target: i386-unknown-freebsd11.2
Thread model: posix
InstalledDir: /usr/bin

Output of `openssl version`:
OpenSSL 1.0.2p-freebsd  14 Aug 2018

Output of `./inspircd --version`:
InspIRCd version: InspIRCd-2.0.27(r0)

**Contents of /tmp/m_timedbans-8cecda.sh:** https://pastebin.com/dpv3ZdrN

**Contents of /tmp/m_timedbans-8cecda.cpp:** Do you really need this file? It's too big for pastebin. If you need it, please let me know the best way to get you this file.

**Comment by genius3000** [comment]
`clang++: error: unable to execute command: Killed`

My first guess with that would be an OOM kill. How much memory does this host have and can you check the kernel/system logs for mention of OOM killing a process?

**Comment by SaberUK** [comment]
Your operating system is killing the compiler because it used too many system resources.

**Comment by sharstine** [comment]
Thank you both for your replies. I'll look into system resources. In the meantime, I was able to complete the build process by running 'make' again (twice) until it eventually finished.
