### ISSUE TITLE
/ZLINE CIDR parsing issue

### ISSUE THREAD

**Issue by lol37** [inspircd/inspircd#1553]
Hello,

Is there someone that could quickly try to reproduce my issue, that is i CAN set a Z:Line on myself using my IP address without CIDR notation as i've set up the insane ban (Alone on my server), i CAN also ban myself using the CIDR notation but STILL using my own IP address (that is followed by /whatevernumber, even > 32) , yet there's no match of my IP address (That is i'm not getting Z:Lined) while z-lining an IP addresses range that contains my IP address.

Branch: inspv3
Thanks for further help.

**Comment by genius3000** [comment]
I find your wording a little difficult to follow. Are you being banned without using CIDR notation? Is insane ban working as expected to your setup? Are you 100% sure your IP as known to the server is what you're Z-lining? Does your IP or host match any E-lines, as that would prevent a Z-line from taking effect?

**Comment by lol37** [comment]
Hi, thanks for reply
By order,
1) Yes.
2) Yes, as i'm getting disconnected when executing /ZLINE on myself (I'm the only one connected on my server, no bots/services)
3) Yes.
4) I've setup none of any E-lines.

**Comment by SaberUK** [comment]
Can you reproduce this on the latest insp3 Git?

**Comment by lol37** [comment]
I've just re-cloned from insp3 repository now everything works, thanks !
