### ISSUE TITLE
[3.0] m_ident randomly prefixing user ident responses with a ~ while it shouldn't

### ISSUE THREAD

**Issue by Robby-** [inspircd/inspircd#1555]
**Description**
`m_ident` is randomly and erroneously prefixing users' ident responses with a `~`, while still sending the `*** Found your ident, '<ident>'` server notice to the client.

**Edit**: I just noticed that in a /WHOIS, the user has a prefixed ident, but in a JOIN, as viewed from another client on the channel, the ident does not have the `~` prefix.

**Steps to reproduce the issue:**
1. Have a system with an ident daemon running on it
2. Have the `m_ident` module loaded in inspircd
3. Keep reconnecting with a client until you notice there's a `~` in your ident even though the ident daemon is running and has responded to the request

**Describe the results you received:**
Got the `*** Found your ident, '<ident>'` notice but there's still a `~` in the ident.

**Describe the results you expected:**
Not have a `~` in the ident.

**Additional information you deem important (e.g. issue happens only occasionally):**
Configuration for the module: `<ident timeout="5" nolookupprefix="yes">`

**Output of `./bin/inspircd --version`:**
`InspIRCd-3.0.0-11cc922`

**Comment by genius3000** [comment]
This looks like the `NoLookupPrefix` is prefixing any user without an active ident lookup happening (whether it was successful or never existed) but still in registration phase (i.e. if CAP negotiation, SASL, etc. is still happening). Ref. https://github.com/inspircd/inspircd/blob/insp3/src/modules/m_ident.cpp#L309...L314
Try changing line 311 to:
`if ((NoLookupPrefix) && (user->ident[0] != '~') && (user->MyClass) && (!user->MyClass->config->getBool("useident", true))`
That'll mimic the `OnUserInit` check for whether to start a lookup, so users with a successful lookup (that haven't changed to a different, non-ident class) won't be prefixed. A better fix could be to leave a SimpleExtItem of 'receivedident' or such and either remove it in `OnUserConnect` or just leave it.

**Comment by Robby-** [comment]
@SaberUK: This fixes the randomness issue but it breaks the `nolookupprefix` setting. Users in connect classes with `useident="no"` do not get their idents prefixed.

**Comment by SaberUK** [comment]
@Robby- Can you check whether this still occurs with the latest insp3 Git?

**Comment by Robby-** [comment]
@SaberUK: The issue no longer occurs, thank you.
