### ISSUE TITLE
[3.0] <options:exemptchanops> is not applied anymore if the exemptchanops module is reloaded

### ISSUE THREAD

**Issue by Robby-** [inspircd/inspircd#1557]
**Description**
The values in `<options:exemptchanops>`  are not applied anymore if the `exemptchanops` module is reloaded. An ircd restart is required to fix this.

**Steps to reproduce the issue:**
Note: We'll use `nonicks` for this.
1. Use the default `<options:exemptchanops>` settings, which contains `nonick:v`, and load the `exemptchanops` module.
2. Be on a channel with channel operator status (+o) and set +N to block nickchanges.
3. You will be able to change nicks since you are +o and +v is the minimum required.
4. `/reloadmodule exemptchanops`
5. Trying to change nicks now will fail because of the channel that has +N set.

**Describe the results you received:**
Unable to change nicknames while `<options:exemptchanops>` is correctly configured (default values) to allow for this, and the `exemptchanops` module is reloaded.

**Describe the results you expected:**
Be able to change nicknames as allowed by default configuration.

**Additional information you deem important (e.g. issue happens only occasionally):**
Setting `+X nonick:v` on the channel works around the issue temporarily, but ultimately a restart is still required to fix it.

**Output of `./bin/inspircd --version`:**
`InspIRCd-3.0.0-0527f85`

**Comment by SaberUK** [comment]
Can you reproduce this on the latest Git?

**Comment by Robby-** [comment]
@SaberUK: The issue has been fixed, I cannot reproduce it anymore, thank you.
