### ISSUE TITLE
[3.0] Hostname-related on-connect notices randomly missing

### ISSUE THREAD

**Issue by Robby-** [inspircd/inspircd#1559]
**Description**
During testing for another issue I noticed I was not always getting the following notices:
`*** Looking up your hostname...`
`*** Found your hostname`

Actually, the `*** Looking up your hostname...` notice never showed up at all, and the `*** Found your hostname` notice seems random if it shows up or not (maybe TTL related?).

**Steps to reproduce the issue:**
1. Connect and watch for these notices (or lack thereof).
2. Keep reconnecting for random results.

**Describe the results you received:**
Notices are missing.

**Describe the results you expected:**
To get these notices on connect, every time.

**Additional information you deem important (e.g. issue happens only occasionally):**
There are no `<dns>` tags configured, thus inspircd falls back to 127.0.0.1, which is fine as there is a resolver running on the server and is working as the hostnames are resolved when connecting to the ircd.

**Output of `./bin/inspircd --version`:**
`InspIRCd-3.0.0-0527f85`

**Comment by SaberUK** [comment]
Fixed in 0a1f9bc.
