### ISSUE TITLE
stop/restart not working while in "run" folder

### ISSUE THREAD

**Issue by kr1pt0ph0b14** [inspircd/inspircd#1571]
**1-** I built and installed InspIRCd-2.0.27(r0) on OpenBSD 6.4 under a regular user account.
It works fine. However, 
when issuing "/home/user/ircd/run/inspircd stop" (and restart), the output reports 'permission denied':

Stopping InspIRCd (pid: 50278)...
**ps: /dev/mem: Permission denied**
InspIRCd Stopped.

It does the job, but just wanted to inform you regarding such error.

**2-** And it seems, instead of typing full path "/home/user/ircd/run/inspircd", when executing inspircd by going inside the "run" folder, and running/stopping it like: 
./inspircd stop/restart, these arguments do not work at all. It always executes the start command instead.

./inspircd stop -> (actually executes ./inspircd start, because it outputs "ports are in use" error)
./inspircd restart -> (actually executes ./inspircd start, because it outputs "ports are in use" error)
so I manually pkill inspircd.

Shortly;
/home/user/ircd/run/inspircd start (starts)
/home/user/ircd/run/inspircd stop (stops)
/home/user/ircd/run/inspircd restart (restarts)

BUT

(in run folder)
any arguments coming after ./inspircd tries starting it. Even it's "stop", "restart", "rehash" or "version".
./inspircd start (starts)
./inspircd stop (tries to start) **The following port(s) failed to bind: Address: Reason: Address already in use**
./inspircd restart (tries to start) **The following port(s) failed to bind: Address: Reason: Address already in use**
./inspircd version (tries to start) **The following port(s) failed to bind: Address: Reason: Address already in use**

**Comment by SaberUK** [comment]
Are you sure you haven't somehow misconfigured your build config and are running the IRCd binary instead of the helper script?

**Comment by SaberUK** [comment]
There has been no response to my request for more information in over a month so i'm going to close this now.
