### ISSUE TITLE
`BUG: sa2cidr(): socket type 0 is unknown!` when checking CIDRs against UNIX socket paths

### ISSUE THREAD

**Issue by linuxdaemon** [inspircd/inspircd#1572]
If a user connects over a unix socket, during connect class assignment MatchCIDR() is called on them, using the unix socket path as their IP. `irc::sockets::MatchCIDR` attempts to convert the IP to an sa https://github.com/inspircd/inspircd/blob/f37590259eeb5cb9634773c000ea8f0fa083683a/src/cidr.cpp#L76 but doesn't check the return value. `aptosa` ends up just setting the sa to 0 when passed a unix socket path, leading to attempting to match the CIDR on a connect class against an sa with `AF_UNSPEC`.

**Comment by SaberUK** [comment]
Should be fixed as of 8bc996bcc1444b33ccfde6ca3588deee0a0459d1.
