### ISSUE TITLE
help in spamfilter

### ISSUE THREAD

**Issue by misterX27** [inspircd/inspircd#1573]
it helps in spamfilter
good morning I am new and I would like to know how I put the spamfilter to refuse the use of a web page

I know this is not real but I would like to deny this web

spamfilter { 
     regex "https://qurl.com/*";
     target { user; channel; };
     action gline;
  reason "stop.. please!!!";
ban-time 10m;
  };

**Comment by KoraggKnightWolf** [comment]
Heya, first of all, this is for actual issues/bugs not for feature requests, best to go to #inspircd on irc.inspircd.org for those. Also /HELPOP spamfilter will show you the exact syntax with explanations, hope that helps! If not feel free to join the support channel and peeps will be glad to help you out :) 

Regards,

Koragg

**Comment by SaberUK** [comment]
Load the [filter module](https://wiki.inspircd.org/Modules/2.0/filter) with the glob provider and add a config tag something like this:

```xml
<keyword
	pattern="https://qurl.com/*"
	reason="stop.. please!!!"
	action="gline"
	duration="10m"
	flags="pn">
```

This is a bug tracker not a support tracker. If you have any more questions then please ask on IRC at irc.inspircd.org #inspircd.
