### ISSUE TITLE
Snotices on IRC about ports being in use while rehashing have tabs in them, making it look weird

### ISSUE THREAD

**Issue by Robby-** [inspircd/inspircd#1578]
**Description**
Snotices on IRC about ports being in use while rehashing have tabs in them, making it look weird. Might be client dependent on how its rendered, though. Using mIRC here.

**Steps to reproduce the issue:**
1. Have some ports in use
2. Start the ircd, observe tab-separated output about ports in use on the console, looking good
3. Go onto IRC and /REHASH, observe what seems to be no spaces in spots where the tab chars are supposed to be, but when you copy paste those snotices somewhere else, e.g. while writing this issue, the tabs appear, maybe its also be client dependent on how its rendered...

**Describe the results you received:**
```
*** 1.Address: [::1]:7200Reason: Address already in use
*** 2.Address: [::1]:7201Reason: Address already in use
```
*Removed the tab characters to make it look like how it appears to me via snotices*

**Describe the results you expected:**
```
*** 1. Address: [::1]:7200   Reason: Address already in use
*** 2. Address: [::1]:7201   Reason: Address already in use
```

**Output of `./bin/inspircd --version`:**
`InspIRCd-3.0.0-318d50b`

**Comment by SaberUK** [comment]
This is a formatting issue in your client.

**Comment by SaberUK** [comment]
As mentioned this is a formatting issue in your client. Please report it to your client maintainer.
