### ISSUE TITLE
Configuration-defined filters do not initially work due to behavioral change in 3.0

### ISSUE THREAD

**Issue by Robby-** [inspircd/inspircd#1581]
**Description**
After (re)starting the server, filters defined in the configuration files (`<keyword>` tags) do not initially get added because the `m_regex_*` modules are loaded later. A simple rehash fixes this. This was not an issue in 2.0 but a behavioral change in 3.0 has introduced this issue. I'm using the default module ordering as provided in the example configuration file.

**Steps to reproduce the issue:**
1. Use a `modules.conf` derived from `modules.conf.example` (thus keeping the default module order), and make sure the `filter` and `regex_glob` modules are loaded
2. Have some `<keyword>` tags defined, in my case at the very bottom of `inspircd.conf`
3. Restart server, get online, `/OPER`, `/STATS s` and observe no filters being present
4. Rehash, `/STATS s`, observe the filters now being present

**Describe the results you received:**
No filters in `/STATS s`.
This was logged:
`FILTER: WARNING: Regex engine 'glob' is not loaded - Filter functionality disabled until this is corrected.`

**Describe the results you expected:**
For it to work as it did in 2.0.

**Output of `./bin/inspircd --version`:**
`InspIRCd-3.0.0-c495b5d`

**Comment by SaberUK** [comment]
Fixed in fa83fac.

**Comment by Robby-** [comment]
Fixed indeed, thank you.
