### ISSUE TITLE
Mutex on LogManager

### ISSUE THREAD

**Issue by carlosferry** [inspircd/inspircd#1584]
Hello,

I have a question, when using m_mysql, does a myqlresult will call OnNotify inside the dispatcher thread?

I am asking this because certain modules that overload OnResult are called inside the dispatcher, am I confused? If so, should not LogManager have a Mutex instead of a bool Lock?

Thanks and keep the hard work!

**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `./bin/inspircd --version`:**

**Comment by SaberUK** [comment]
DispatcherThread uses a thread-safe behaviour internally in one of the base classes.
