### ISSUE TITLE
[3.0] m_noctcp: operoverride setting is missing for umode T

### ISSUE THREAD

**Issue by Robby-** [inspircd/inspircd#1591]
In 3.0, the 2.0 extras module `m_noctcp_user` was merged into `m_noctcp`, however, the `<noctcpuser:operoverride>` setting was not merged along. I would like to request that this still be added, as we are using this setting to allow certain things for opers only.

**Comment by genius3000** [comment]
It would probably be better to add that in as an oper priv, more flexible and I believe has been the method a few other oper-only bools switched to. Probably add a priv for channel override as well.

**Comment by Robby-** [comment]
Even better, more flexibility is always nice, then I can even limit this to specific opers.
