### ISSUE TITLE
Remote user SSL status not synced on user connect.

### ISSUE THREAD

**Issue by genius3000** [inspircd/inspircd#1594]
**Description**
When a SSL user connects to server A, the SSL status/cert isn't being synced to Server B. If you squit/connect the two servers or connect prior to them being linked, the status/cert is synced.

**Steps to reproduce the issue:**
1. Connect with SSL to Server A, already linked to Server B.
2. Note how Server A shows correct SSL status but Server B does not.
3. Squit and re-connect the servers.
4. Note how both servers show the correct status.

**Describe the results you received:**
SSL status/cert is only syncing on server connect.

**Describe the results you expected:**
SSL status/cert sync on user connect.

**Additional information you deem important (e.g. issue happens only occasionally):**
I'd guess this is to do with the IS_LOCAL check in OnPostConnect() of m_sslinfo, but I'm not sure how the syncing is meant to work. Perhaps it's just not syncing on each user connect like expected?

**Output of `./bin/inspircd --version`:**
InspIRCd version: 3.0.0-9b031d4

**Comment by SaberUK** [comment]
Fixed in 62ba7c3.
