### ISSUE TITLE
Feature: Multi-Client Support

### ISSUE THREAD

**Issue by unixtam** [inspircd/inspircd#1595]
I am trying to implement an InspIRCd module for multi-client support, i.e. being able to connect to an InspIRCd network with multiple devices, and having all of these clients share the same presence (including nickname, channels joined, modes etc). I have currently set up the ZNC IRC bouncer as a gateway to the ircd to accomplish this. It works, but kind of feels like overkill if multi-client support is all I'm really using it for.

After taking a look the InspIRCd codebase and came up with two different approaches. I am not sure if either one would be viable and I would like to ask more experienced InspIRCd developers for feedback on this.

### Approach 1) Create a Proxy User Shared by Multiple Clients

In this approach, I would hook `OnUserPreNick` and create a *proxy user* with the desired nick and the password provided in PASS. The actual user or *client user* would keep its nick set to its uuid default. The proxy user would maintain a list of connected client users, to which new clients are added whenever a new user requests the shared nick and provides the correct password. Messages and commands from clients are intercepted and replayed by the proxy by hooking e.g. `OnPreCommand` and `OnUserMessage` (in v3), so that for all intends and purposes, the proxy looks like a regular user. Messages to the proxy are emitted to all connected clients. When a client quits, the proxy remains online until the last client quits, and when the proxy is forced to quit, all clients are disconnected.

One difficulty I have noticed for this approach is that users are kind of tied to their network implementation, e.g. a call to `ServerInstance->Users.AddUser()` takes a file descriptor as an argument, which makes it seemingly difficult to replace by something as abstract as a proxy user. There is precedent for non-standard usage of users in form of the `FakeUser` class, but I am rather unsure about its details.

### Approach 2) Select One Client to Act as Manager

This approach does without introducing artificial users into the system. Instead, the first user to claim a nick will register with the module as the *manager user* and set a password (the one provided via PASS). On subsequent nick requests by other users, the module will look up the nick in the registry and compare passwords. Upon match, the other user will become a *subordinate* to the manager. Similarly to the previous approach, subordinates have their nicks set to their uuid, requests by subordinates are re-routed through the manager, and messages to the manager are emitted to all subordinates as well. When a subordinate quits, it is simply removed from the registry, and when the manager quits, the subordinate next in line becomes the new manager, until the last client disconnects and the nick is removed from the registry.

A problem I perceive with this approach is the handling of joins and modes when the manager disconnects. With a proxy user, these would remain untouched, but when the manager quits or times out, I have to transfer these as quietly as possible to the new manager. I have looked a bit into the channel code, just enough to get a rough idea. Users are assigned memberships which have a `const` user member. So I would have to add a new membership and delete the old one, without loosing messages, without receiving duplicate messages, and without notifying users in the channel that a user has just left and rejoined. It is unclear to me if that can currently be achieved with a module alone in all instances. It would seem undesirable to part/join a channel, lose oper status etc whenever the current manager quits.

----

Your feedback, tips and ideas on making multi-device support in InspIRCd a reality are highly appreciated.

**Comment by genius3000** [comment]
For starters I'll mention to have a look at what @Adam- started in #731. Some of it will be outdated to current 3.0 code but maybe it'll help you somewhat.

**Comment by SaberUK** [comment]
Your best bet is probably to swap the FD in the UserIOHandler for a dummy FD and then handle user input/output using a separate bind type.

**Comment by unixtam** [comment]
@genius3000, thanks, I missed that PR. I searched for "multi-client" and similar terms, but not for "bnc".

@Adam-'s approach involves a single `User` with a list of IO handlers for connected clients. I like this idea because it cleanly distinguishes clients from users and doesn't involve re-routing messages to/from fake users as is the case in the approaches I proposed. Unfortunately, his PR requires sweeping changes to multiple other modules and core code (at least in v1 - the PR hasn't been merged or developed in the past 5 years).

One way to improve upon his approach might be to create a new class `ProxyIOHandler` that derives from `UserIOHandler` and abstracts away the multi-client socket handling. If I could get away with that, it would dramatically reduce the amount of changes required to make this approach work. The changes to `User` would be minimal, and the new `OnUserIOError` hook would not be needed either. Client ping timeouts could be handled by the module via `OnPreCommand` and `OnBackgroundTimer`, replacing Adam-'s second new hook `OnPingTimeout`. Using a different hook/method for initialization, this approach might also be made invisible to the client (as I would like it to be).

How does that sound? Am I missing any obvious problems with this approach?

@SaberUK, thanks for your input. I have two questions:

* If I replaced the file descriptor with a dummy, what would I return to the many `GetFd()` calls throughout the codebase without breaking anything?
* Regarding "using a separate bind type": I'm not following. Could you please elaborate a bit on what you mean by "bind types" and how I would use them? A quick quick web search didn't reveal anything useful, except for *socket types*, but I'm not sure how using different types of sockets would help solve the issue at hand either.

**Comment by unixtam** [comment]
Status: When approaches 1 and 2 turned out to require core code changes, I implemented the approach I described in my previous post. I don't often write C++ code, so I fully expected my plugin to crash and burn when the module was loaded, but it didn't even compile. Apparently, `UserIOHandler& UserIOHandler::operator=(UserIOHandler&&)` has been deleted, although I can't seem to find mention of that in the code.

If you want to take a look, you can find my broken code in files [multiclient.h](https://github.com/unixtam/inspircd/blob/multiclient/include/modules/multiclient.h) and [m_multiclient.cpp](https://github.com/unixtam/inspircd/blob/multiclient/src/modules/m_multiclient.cpp) of the [multiclient branch in unixtam/inspircd](/unixtam/inspircd/tree/multiclient). Grab it while it's up.

Things on my TODO list (besides probably fixing a good amount of segfaults if I get the module to compile): Erase detaching clients on `OnBackgroundTimer` rather than as a side-effect of other loops, and add a custom PING/PONG for clients (also using `OnBackgroundTimer`).

To be honest, though, even if this did work, it feels like one big workaround. A session manager shouldn't have to pose as an IO handler. Adam-'s idea of adding multiple IO handlers to each user is definitely better, but still not ideal. I ended up contemplating faking a connection to the user's socket, but then I might as well just continue to use ZNC. To properly add multi-client support, in my opinion, `User` and `UserIOHandler` would have to be separated, e.g. a `User` that has many `Client`s. A user doesn't have an IP address - that belongs to the client. Also, if code deals with a client connection (e.g. the ssl modules) it should access the client directly, not via a `User` object. If there is an error with a client connection, it shouldn't just quit the user (as it does now), but let some other code further up in the hierarchy decide what to do. Finally, I don't think it should matter to which server of a network a user's client is connected. Achieving this is currently quite impossible, as users are tied to the servers they are connected to. These are just the things I can think of right now.

I realize that IRC was conceived in a time when multi-client support wasn't an issue. I was hoping InspIRCd's modular nature meant I could easily add multi-client support, but that doesn't seem to be the case. Unless any of you have got some ideas, I think I'm going to stick with ZNC or perhaps look into other chat solutions altogether.

**Comment by slingamn** [comment]
Sorry to hijack this ticket, but I was unable to find contact information for @unixtam. We're trying to do something similar on the server side with @oragono, so if you're interested please get in touch :-)
