### ISSUE TITLE
Add a few parameters to the "cgihost" configuration to substitute the real IP address to webgate Mibbit

### ISSUE THREAD

**Issue by EpicNet** [inspircd/inspircd#1614]
There is a problem with getting the real IP address of the user who comes in through the Mibbit webgate, where the IP address is in the realname. This makes a hole in the protection of the server, as the offender can bypass the ban and in this case, the module "m_geoip" incorrectly determines the country, and therefore it is possible erroneous user blocking. Also, many users complain that their real IP address is visible to other users and cannot be hidden using the user mode (+x) or using a personal vhost.

Need to add two parameters to the cgihost configuration:

`subip="$realname"`
Before displaying in the log channel, replace the ip-address of the connection, which will be taken from the real name of the user (if it really is, check its presence XX.XX.XX.XX - showing a clean ip address without resolve host).

`subname="Mibbit User"`
Replace the realname user with the specified text.

Configuration example:
`<cgihost type="webirc" password="" mask="64.62.228.82" subip="$realname" subname="Mibbit User">`

As it was (snomask +c):
> *** CONNECT: Client connecting on port 6699 (class mib): Guest55!8e6ff7da@64.62.228.82 (64.62.228.82) [92-100-209-201.dynamic.avangarddsl.ru]

That is how it should be (snomask +c):
> *** CONNECT: Client connecting on port 6699 (class mib): Guest55!8e6ff7da@92.100.209.201 (92.100.209.201) [Mibbit User]

And only after that the check of the domain zone in the GeoIP should begin, check the IP address for the presence of a proxy, check in the DNSBL databases, set up a personal vhost, hide the IP (+x) and so on ...

Perhaps this can be implemented somehow differently, I leave the solution to this problem at your discretion.

**Comment by SaberUK** [comment]
This seems to be exclusively an issue with Mibbit. Have you considered migrating to a better web client like Kiwi IRC which does not do this?

>There is a problem with getting the real IP address of the user who comes in through the Mibbit webgate, where the IP address is in the realname. 

>the module "m_geoip" incorrectly determines the country,

This is not an issue if you have the cgiirc moduile configured with the ident method for Mibbit (unsure if Mibbit can do the WebIRC protocol).

**Comment by EpicNet** [comment]
We try to leave the choice to the user, what kind of webgate he will use at his discretion in taste and color. Nevertheless, there remains a problem with the definition of the domain zone of the country of the connected user and  hinders checking the presence of an open proxy. 

I would like to get help in solving this problem so that I can manage through the server configuration for individual settings specifically for each individual server.

**Comment by SaberUK** [comment]
>Nevertheless, there remains a problem with the definition of the domain zone of the country of the connected user and hinders checking the presence of an open proxy.

[Please read the cgiirc module documentation.](https://wiki.inspircd.org/Modules/2.0/cgiirc)

**Comment by SaberUK** [comment]
If you have any more issues then please ask in irc.inspircd.org #inspircd. Thanks.
