### ISSUE TITLE
Can't stop a different running inspircd with its script while being in another install directory

### ISSUE THREAD

**Issue by Robby-** [inspircd/inspircd#1621]
**Description**
When having multiple inspircd installation directories, using the script of another inspircd install, especially stopping (starting works fine it seems), while being in a different inspircd install directory will fail. PID file exists, and contains the correct pid. With install directory I mean where the script, bin/, conf/, data/, etc. are located. cd out of that directory, repeat the exact same command, and it works again.

**Steps to reproduce the issue:**
1. cd into one inspircd install directory
2. call the script of another separate inspircd via a /full/path/to/another/inspircd install directory, to stop the ircd, so: `/full/path/to/another/inspircd stop`

**Describe the results you received:**
`InspIRCd is not running. (Or PID File not found)`

**Describe the results you expected:**
```
Stopping InspIRCd (pid: 25236)...
InspIRCd Stopped.
```

**Output of `./bin/inspircd --version`:**
`InspIRCd-3.0.0-e59cb85`

**Comment by NightSommelier** [comment]
I have the same bug on version InspIRCd-3.16.1
