### ISSUE TITLE
Compiling fail on system with old glibc 

### ISSUE THREAD

**Issue by H7-25** [inspircd/inspircd#1630]
Compiling inspircd on debian wheezy fail : 

*************************************
	BUILD:		clientprotocol.cpp
	BUILD:		command_parse.cpp
	BUILD:		commands.cpp
	BUILD:		cidr.cpp
	BUILD:		configparser.cpp
	BUILD:		bancache.cpp
	BUILD:		channels.cpp
	BUILD:		base.cpp
In file included from include/inspircd.h:53:0,
                 from /home/inspircd3/inspircd/src/bancache.cpp:21:
include/convto.h: In function ‘TOut ConvToNum(const string&) [with TOut = char; std::string = std::basic_string<char>]’:
include/convto.h:108:16: error: ‘UINT8_MAX’ was not declared in this scopeIn file included from include/inspircd.h:53:0,
                 from /home/inspircd3/inspircd/src/channels.cpp:26:
include/convto.h: In function ‘TOut ConvToNum(const string&) [with TOut = char; std::string = std::basic_string<char>]’:
include/convto.h:108:16: error: ‘UINT8_MAX’ was not declared in this scope

compilation terminated due to -Wfatal-errors.
compilation terminated due to -Wfatal-errors.
make[1]: *** [obj/bancache.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [obj/channels.o] Error 1
In file included from include/inspircd.h:53:0,
                 from /home/inspircd3/inspircd/src/command_parse.cpp:24:
include/convto.h: In function ‘TOut ConvToNum(const string&) [with TOut = char; std::string = std::basic_string<char>]’:
include/convto.h:108:16: error: ‘UINT8_MAX’ was not declared in this scope
compilation terminated due to -Wfatal-errors.
make[1]: *** [obj/command_parse.o] Error 1
In file included from include/inspircd.h:53:0,
                 from /home/inspircd3/inspircd/src/configparser.cpp:20:
include/convto.h: In function ‘TOut ConvToNum(const string&) [with TOut = char; std::string = std::basic_string<char>]’:
include/convto.h:108:16: error: ‘UINT8_MAX’ was not declared in this scope
compilation terminated due to -Wfatal-errors.
make[1]: *** [obj/configparser.o] Error 1
In file included from include/inspircd.h:53:0,
                 from /home/inspircd3/inspircd/src/cidr.cpp:22:
include/convto.h: In function ‘TOut ConvToNum(const string&) [with TOut = char; std::string = std::basic_string<char>]’:
include/convto.h:108:16: error: ‘UINT8_MAX’ was not declared in this scope
compilation terminated due to -Wfatal-errors.
make[1]: *** [obj/cidr.o] Error 1
In file included from include/inspircd.h:53:0,
                 from /home/inspircd3/inspircd/src/base.cpp:23:
include/convto.h: In function ‘TOut ConvToNum(const string&) [with TOut = char; std::string = std::basic_string<char>]’:
include/convto.h:108:16: error: ‘UINT8_MAX’ was not declared in this scope
compilation terminated due to -Wfatal-errors.
make[1]: *** [obj/base.o] Error 1
In file included from include/inspircd.h:53:0,
                 from /home/inspircd3/inspircd/src/commands.cpp:24:
include/convto.h: In function ‘TOut ConvToNum(const string&) [with TOut = char; std::string = std::basic_string<char>]’:
include/convto.h:108:16: error: ‘UINT8_MAX’ was not declared in this scope
compilation terminated due to -Wfatal-errors.
make[1]: *** [obj/commands.o] Error 1
In file included from include/inspircd.h:53:0,
                 from /home/inspircd3/inspircd/src/clientprotocol.cpp:20:
include/convto.h: In function ‘TOut ConvToNum(const string&) [with TOut = char; std::string = std::basic_string<char>]’:
include/convto.h:108:16: error: ‘UINT8_MAX’ was not declared in this scope
compilation terminated due to -Wfatal-errors.
make[1]: *** [obj/clientprotocol.o] Error 1
make: *** [target] Error 2

**Comment by SaberUK** [comment]
Fixed in 6844ce1.
