### ISSUE TITLE
Mode f trigger type notify as flood

### ISSUE THREAD

**Issue by H7-25** [inspircd/inspircd#1649]
setting a channel +f x:x  trigger type notify as flood and kick users from the channel even if they don't send the message.
To reproduce it set +f 3:5 a channel, access with kiwiirc, enable share when typing, than write in  the input  for a while without send, than send just 1 message.

**Comment by SaberUK** [comment]
This is an unexpected side effect of applying +f to TAGMSGs and i'm not really sure what to do about it.

Maybe we should consider a TAGMSG to be equivalent to 0.1 PRIVMSG/NOTICE?

**Comment by H7-25** [comment]
It's not easy. 
An user who is writing fast or delete and rewrite something so often before send the message can be kicked without he know the reason and this can happen so often.
At the same time a botnet that simulates typing to flood can be really a big problem.
Pheraps a throttling like system instead of kick or ban should be one solution.
