### ISSUE TITLE
Filter module GLINE Bug

### ISSUE THREAD

**Issue by H7-25** [inspircd/inspircd#1650]
Adding a filter of type gline does't apply the gline to correct mask for webirc users:

FILTER: _kiwi6838 (*@127.0.0.1) was G-lined for 1h (expires on Thu May 23 2019 22:10:05) because their message to thom93_ matched ^(.*)?(externalLink\?url)(.*)?$ (Spam Bot)

**Comment by SaberUK** [comment]
>[20:45]  <@H7-25> you  can close the issue , is not the filter module sorry
