### ISSUE TITLE
anticaps message received from an ID 

### ISSUE THREAD

**Issue by H7-25** [inspircd/inspircd#1652]
Setting a channel +B on insp3 if an user match the condition he receive the block notify from an ID :

0xda39a0 Your message exceeded the 70% upper case character threshold for #geeks and was blocked.

**Comment by H7-25** [comment]
Wrong title, the right module is anticaps.

**Comment by SaberUK** [comment]
What mode parameter was being used for the anticaps module?

**Comment by SaberUK** [comment]
Also, what client are you using?

**Comment by H7-25** [comment]
I've checked with kiwiirc, textual and adiirc. This is my anticaps conf :

<module name="anticaps">
<anticaps lowercase="abcdefghijklmnopqrstuvwxyz"
          uppercase="ABCDEFGHIJKLMNOPQRSTUVWXYZ">

like in example.
