### ISSUE TITLE
InspIRCd v3 and onwards does not show full version string

### ISSUE THREAD

**Issue by jesopo** [inspircd/inspircd#1662]
This is mostly as a request for comment on reasoning;

https://github.com/inspircd/inspircd/blob/510f747854b17f64c2f597a4bd5743763fb518f4/make/template/config.h#L22

What is the rationale here? The commenting denotes it's driven by privileged/unprivileged distinction, what's the risk of "unprivileged" users seeing a full semver?

As a user, I've had to point out to network admins that they're running outdated and vulnerable software in the past and this effectively prevents this.

**Comment by SaberUK** [comment]
As I have told you already there is no reason for the average user to know this information. 

Server operators can see the full version if they need it.

**Comment by jesopo** [comment]
You've addressed none of my questions.

**Comment by SISheogorath** [comment]
Okay, let me go for that instead:

> What is the rationale here?

Only provide data required. The version number e.g. 2.0 provides the reasonable view on what features the server provides.

> The commenting denotes it's driven by privileged/unprivileged distinction, what's the risk of "unprivileged" users seeing a full semver?

There is no essential risk here, but as mentioned before, following the "need-to-know" principle it's not required and therefore fine to now show it.

I also want to point out, that InspIRCd is not using SemVer. Just something SemVer-like.

**Comment by jesopo** [comment]
> Only provide data required. The version number e.g. 2.0 provides the reasonable view on what features the server provides.

we don't even get provided by the minor version

> There is no essential risk here, but as mentioned before, following the "need-to-know" principle it's not required and therefore fine to not show it.

I've pointed out a good reason for the full version to be shown - that's why I asked what the risk is. If the reasons **for** including it are not good enough then I would assume there'd have to be good reasons **against** including it. If there's no risk but there's even minor reasons for showing it, why not?
