### ISSUE TITLE
inspircd / atheme

### ISSUE THREAD

**Issue by shahkacak369** [inspircd/inspircd#1665]
helo newbie here.. a few days a go i install inspircd on centos 7.. inspircd 2.0.21 dan atheme service 7.2.6.. when i try use on any irc client.. on startup display like this ..

There are 1 users and 16 invisible on 2 servers
* 18446744073709551602 :operator(s) online
* 2 :channels formed
* I have 2 clients and 1 servers
* Current Local Users: 2  Max: 2
* Current Global Users: 17  Max: 17

(* 18446744073709551602 :operator(s) online )<<-- why operators online display like this..
any body here can help me..

**Comment by SaberUK** [comment]
Your version of Atheme is outdated. Update to the latest version.

**Comment by shahkacak369** [comment]
ok tq saberuk.. :)

**Comment by shahkacak369** [comment]
saberuk can u teach bout user mode for oper on inspircd.. coz i already read at official website inspircd.. but very not detail they explain.. i wanna set mode at oper.conf .. for example /umode +q  for being not able get kick in channel.. or etc..
