### ISSUE TITLE
msgid isn't synced between multiple Send() of message

### ISSUE THREAD

**Issue by linuxdaemon** [inspircd/inspircd#1669]
When the `msgid` tag is added to a `PRIVMSG`, the tag is not set in the MessageDetails the `ClientProtocol::Message` is created from. This means when `OnUserPostMessage` is called for spanningtree and echomessage, `details.tags_out` doesn't have the msgid, meaning a new one gets added by `OnPopulateTags` in `m_ircv3_msgid`. This applies to all outgoing messages it seems, at least to `TAGMSG`, `MODE`, `PRIVMSG`, and `NOTICE`, when echoing the message to the user, sending it out to the other users on the local server, and sending it over spanningtree.

**Comment by SaberUK** [comment]
Another issue: the msgid differs between `extended-join` joins and normal joins.

(Note: the msgid-on-everything patch was reverted for v3.2, working on reintroducing it rn.)
