### ISSUE TITLE
[Feature] CHMODE +g could block part/quit messages

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [inspircd/inspircd#1674]
When we use `CHMODE +g` to prevent some "bad words" from being sent to channel, it could probably also block part/quit messages containing those words.
Some users find that they're unable to send those words to the channel (spam, insults, swearing, etc) and they use them in the part/quit message to achieve the their goal.
IMHO, this would be a good enhancement and very helpful for channel owners, if we think in channels where different languages are spoken at the same time and network admins wouldn't need to add every single word to a spamfilter, e.g.

**Comment by KoraggKnightWolf** [comment]
Definitely a good idea, my guess would be is it hooks into PRIVMSG and NOTICE to act upon those, and could perhaps thus also be changed to hook into PART and QUIT as well.

**Comment by SadieCat** [comment]
This was implemented for part messages, we can't really do it for quit messages because those are global not channel-local.
