### ISSUE TITLE
Unix sockets not recreated on rehash with remove enabled.

### ISSUE THREAD

**Issue by genius3000** [inspircd/inspircd#1681]
When a Unix socket bind tag has `remove` enabled, a rehash will remove the file but not recreate it. It does work great upon startup if there's a dead socket file left behind.  
I'm not very familiar with socket code but having a look, it removes the file but because the listener still exists in `old_ports`, the `new ListenSocket` isn't called which must be doing the file creation. Do we have a safe way of knowing startup vs rehash? Or should we check the `old_ports` list for the socket before removing?

**Comment by SaberUK** [comment]
We should probably move the removal to inside of the ListenSocket constructor.
