### ISSUE TITLE
EXTBAN O no longer works with OPERTYPE with spaces

### ISSUE THREAD

**Issue by shaynejellesma** [inspircd/inspircd#1684]
EXTBAN O not working with OPERTYPE with spaces

The 3.0 upgrade no longer require the use of underscores in the OPERTYPE to translate into spaces. 
This makes the use of EXTBAN O trying to target a specific OPERTYPE ineffective as the EXTBAN cannot have a space.

Opertype excerpt
`<- @time=2019-07-18T16:10:35.493Z :server.name 243 shayne O IRC Operator HWhkos :OP`

The old method to specify the opertype. No longer matches the new opertype with spaces
```
-> server.name MODE #test +e O:IRC_Operator
<- @time=2019-07-18T15:54:15.326Z :shayne!shayne@host MODE #test +e :O:IRC_Operator
```

Cannot set an extban with spaces
```
-> server.name MODE #test +e O:IRC Operator
<- @time=2019-07-18T15:54:22.092Z :shayne!shayne@host MODE #test +e :O:IRC
```

**Version**
InspIRCd version: 3.2.0

**Comment by SaberUK** [comment]
In v3.3.0 you will be able to do `O:Foo_Bar` to match `Foo Bar`.
