### ISSUE TITLE
Hashed Oper Password not possible

### ISSUE THREAD

**Issue by mkapra** [inspircd/inspircd#1692]
**Description**
I am trying to set an oper account on my IRC server. When I try to login as an oper it says "Invalid oper credentials". In the log I found the following error:

`Sat Aug 10 13:43:12 2019: OPER: Failed oper attempt by <myusername>!<username>@127.0.0.1 using login 'test_admin': The following fields did not match: password`

This is my oper config:
```
<module name="m_sha256.so">

<oper name="test_admin"
      password="ecd71870d1963316a97e3ac3408c9835ad8cf0f3c1bc703527c30265534f75ae"
      hash="sha256"
      host="*@127.0.0.1"
      type="NetAdmin">
````

Hashed password is `test123` in this case to try it.

Also I found this in the log to verify the sha256 module gets loaded correctly:
```
Sat Aug 10 13:42:54 2019: New module introduced: m_sha256.so (Module version InspIRCd-2.0.24 r0)
```

EDIT:
Without hashing the password it works perfectly.

**Output of `./bin/inspircd --version`:**
InspIRCd-2.0.24 r0

**Comment by SaberUK** [comment]
You are missing the `m_password_hash.so` module.

https://github.com/inspircd/inspircd/blob/insp20/docs/conf/modules.conf.example#L1365-L1386

**Comment by mkapra** [comment]
@SaberUK Oh, thank you!
