### ISSUE TITLE
Data loss with remote HAProxy connection

### ISSUE THREAD

**Issue by iwalkalone69** [inspircd/inspircd#1694]
**Description**

Sometimes user is not receiving PING so it can't answer with PONG and it gets a Registration timeout. This happens when connections goes through HAProxy and connection has hook haproxy.

PROXY v2 protocol works fine as making some debug messages user gets its real IP even in the failed connections.

I attach a tcpdump capture file to open with Wireshark (https://a.uguu.se/u85GZEedcI5q_irc.dump). It has been captured in the IRC server, so the packets are from HAProxy. Two examples (working and not working clients) can be found with this filter:

`tcp.srcport == 40774 or tcp.dstport == 40774 or tcp.srcport == 40770 or tcp.dstport == 40770`

The connection from port 40770 is working fine and the one from port 40774 is failing.

I've tested with this script:

> #! /usr/bin/expect --
> 
> set timeoutdflt 10
> set servidor [lindex $argv 0];
> set puerto [lindex $argv 1];
> 
> spawn telnet -4 $servidor $puerto
> expect "Connected to"
> send -- "USER A B C D\n"
> send -- "NICK BCDA\n"
> expect -re "PING (.*)\n$"
> send "PONG $expect_out(1,string)"
> expect "Welcome"

It can be executed like:

`./check-inspircd.sh <host> <port>`

Or (if you want to automate):

`watch -n 0.1 ./check-inspircd.sh <host> <port>`

Host and port must go to HAProxy.

As can be seen in the capture file, no error is thrown related to USER and NICK commands.

**Steps to reproduce the issue:**

1. Setup HAProxy to redirect some port to InspIRCd server
2. Setup InspIRCd to get connection from HAproxy with hook haproxy.
3. Connect at least 100 users.
4. Launch the script multiple times or automate with watch and wait for the error.

**Describe the results you received:**
Sometimes clients don't get the PING command

**Describe the results you expected:**
Client should get PING command always if NICK and USER commands are OK.

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue happens randomly. As more users you have connected, more fails you get.

**Output of `./bin/inspircd --version`:**

InspIRCd-3.2.0-2d35c3396

**Comment by iwalkalone69** [comment]
**Additional information**

If I disable the module conn_waitpong, then sometimes user does not receive the numeric 001 (Welcome), so it happens anyway.

**Comment by SaberUK** [comment]
Does this happen without HAProxy in the middle?

**Comment by iwalkalone69** [comment]
Sorry, I forgot it. I haven't been able to reproduce without having HAProxy in the middle. I made some debug messages in my tests and they revealed that NICK and USER do not get parsed in src/command_parse.cpp when registration is not complete.

**Comment by iwalkalone69** [comment]
Adding more information:

conf/inspircd.conf: https://pastebin.com/tTBHTKjd
haproxy.conf: https://pastebin.com/vzeDhdsD

**Comment by SaberUK** [comment]
I suspect ReadProxyAddress in the haproxy module may be consuming too much data. Will look into this tomorrow.

**Comment by SaberUK** [comment]
This was fixed in 78f9c572119aef08c9115ad61caa41e82b41c98a.
