### ISSUE TITLE
Redirection Idiocy

### ISSUE THREAD

**Issue by clem16** [inspircd/inspircd#1695]
**Description**

**Steps to reproduce the issue:**

1. Google anything related to inspircd
2. Google anything relating remotely to inspircd
3. Google anything remotely resembling anything inspircd related.

**Describe the results you received:**

So, I go to setup inspircd.

As most normal people do, I simply google for the specific document page i'm looking for, and with proper indexing. I should be taken right to it. But no matter what google link I click on, i'm taken to the default document page, which is less than helpful.

When I click on a google link, I expect to be taken to the page I clicked on that has been indexed by google. Not redirected to the default https://docs.inspircd.org/...
I mean, I get it. someone is super proud of all the work they put into a pretty little docs landing page, however it's essentially useless.

When I click on a link of something, I don't want to be redirected to the same stupid landing page. I want to see what I clicked on.

Can someone explain to me why this is going on?

The result is, i'm having to turn to tutorials that are not official and piece crap together that's from people blogs and other tutorials that are not official documentation because the official documentation is essentially useless.

I'm seriously looking at other projects simply because of this one simple stupid problem.

Fix basic site functionality, remove ALL link redirection.

**Describe the results you expected:**

To get to the link I actually click on, and not be redirected to a useless landing page.

**Additional information you deem important (e.g. issue happens only occasionally):**

All the time.

**Comment by SaberUK** [comment]
The old documentation site at wiki.inspircd.org was shut down because it was full of old incorrect information. For many pages it will redirect to the relevant new page but due to the sheer size of the old site not everything was redirected. There are no redirects on the new docs.inspircd.org site.

If you have *specific* support questions you can ask them at irc.inspircd.org #inspircd although i'd recommend dropping your hostile attitude. Nobody will be willing to volunteer their time unpaid to help someone who is being hostile towards them and you'll most likely end up being banned.

**Comment by clem16** [comment]
Thank your for the response.
I don't intend to come off as being hostile. 
I'm just frustrated, and was wondering what was going on.

I have not stopped by the channel to ask questions (partly because I was trying to cool down) and, usually I google around until I can find the answer instead of bothering people asking simple questions that have likely been asked many times before. However, this time all my searching kept leading me to the exact same landing page. Which is incredibly frustrating when your in research mode and your train of thought keeps getting disrupted and derailed by once again landing on the exact same page even tho you clicked a different link, and having to go back and reword the search query, or find an alternative link.

There may be no redirects on the new docs.inspircd.org however there is a huge amount that's still indexed in google.

Thanks for clarifying what what was happening.

As for specifics on what I was actually trying to do. I was actually trying setup a small lab environment to learn how to link two irc servers. Why, because I'm curious and wanted to see how it was done.

Thanks again.
