### ISSUE TITLE
Can't remove a silence different than *!*@*

### ISSUE THREAD

**Issue by iwalkalone69** [inspircd/inspircd#1697]
**Description**

If you add a silence different than mask *!*@*, when you try to remove adding a - character, it tries to remove *!*@* silence and throws an error that this silence is not found.

**Steps to reproduce the issue:**

1. /quote SILENCE +user1234!\*@\* p
2. /quote SILENCE -user1234!\*@\* p

**Describe the results you received:**

*!*@* p :The SILENCE entry you specified could not be found

**Describe the results you expected:**

SILENCE -user1234!\*@\* :p

**Output of `./bin/inspircd --version`:**

InspIRCd-3.3.0-c6d3a2cec

**Comment by SaberUK** [comment]
Fixed in #1698.
