### ISSUE TITLE
IRC原理？IRC接口？

### ISSUE THREAD

**Issue by askunix** [inspircd/inspircd#1699]
啥是IRC，Windows下写一个聊天室（单聊，群聊），怎么使用相关接口

**Comment by SISheogorath** [comment]
@askunix There is no UI or web interface for InspIRCd itself. You either need to use a client of your choice.

By the way, we speak english on our issue tracker, this makes it easier for everyone to read and understand questions.

**Comment by askunix** [comment]
IRC is very simple. I wrote a GUI with QT C++, which supports single chat, group chat, group announcement, and can leave the mailbox if needed.
