### ISSUE TITLE
Use wildcard in /whois command

### ISSUE THREAD

**Issue by CuloArdido** [inspircd/inspircd#1700]
Recently I discovered that in a chat that I enter from time to time they changed their servers to InspIRCd-3 and when trying to make a `/whois *foo*` always appears "no such nick" when before showed all the nicks containing foo. Would it be possible to implement that functionality or is something that already exists but can be configured after installing?

**Comment by SaberUK** [comment]
This is not functionality which exists in v3. Whilst it is in RFC 1459 I don't think any modern IRC server implementation supports this.

If you have adequate oper privileges you can do `/WHO *foo* n`.
