### ISSUE TITLE
"Bad file descriptor" error when connecting to server from a client.

### ISSUE THREAD

**Issue by IoIxDButStronger** [inspircd/inspircd#1701]
**Description**

I installed Inspircd through the .deb file provided in releases. When I try to connect to the IRC server that is running via Inspircd, using ircii, I get the following error:

`*** Unable to connect to port 6667 of server irc.ioi-xd.net (proxy
+irc.ioi-xd.net:6667): connect: Bad file descriptor`

It's worth noting that I have to run this through root because that's where I installed it first, and no matter what user I install it through now, even after purging the installation through `apt-get purge`, it still gets installed in `/usr/sbin/inspircd` and I can't run it as a non root user because for some reason the config file cannot be found unless I run it as root.

It's worth noting that I tried other irc clients. Kiwi IRC times out after ten seconds and IRCCloud doesn't connect either, (although it doesn't give an error). 

**Steps to reproduce the issue:**

1. Set up InspiRCd through the .deb file provided in the releases page
2. Set it up through root by accident, spend an hour trying to migrate to a non root user, give up when you find out that `--runasroot` exists
3. Connect through an IRC client.
4. Profit

**Config file:**

https://pastebin.com/raw/s5iSXTQJ

**Output of `/usr/sbin/inspircd --version`:**

InspIRCd-3.3.0-9d4dadba8

**Comment by SaberUK** [comment]
It looks like you're using a firewall on irc.ioi-xd.net. Try enabling access on port 6667?

**Comment by SaberUK** [comment]
No response in over a month so i'm assuming this is fixed; closing...
