### ISSUE TITLE
Voiced users can set +v other users

### ISSUE THREAD

**Issue by H7-25** [inspircd/inspircd#1706]
Voiced users can set +v other users using /mode #channel +v nick

**Comment by SaberUK** [comment]
Are you sure you don't have oper override set up?

**Comment by H7-25** [comment]
I've try with a normal user, i' running current insp3 git

**Comment by SaberUK** [comment]
This is a doc issue, fixed in 216470adcf8786a5a2d9b50097bb59d65962a744.
