### ISSUE TITLE
Improper mode on users in channels when connecting with BNC/ZNC

### ISSUE THREAD

**Issue by teqnodude** [inspircd/inspircd#1709]
When using Inspircd 3.x and you are connecting with BNC/ZNC then at first join all users show their proper modes in channels ie those who are voiced, opped etc but once joined and you close the irc client and reconnect with your BNC/ZNC then if you were previously opped you look like deopped or voiced. I have tested this multiple times in test environments and in production and same problem occurs not just for me but for other people as well. This only occur with Inspircd 3.x and not 2.x so clearly the problem must lie with the 3.x versions of Inspircd.

**Comment by SaberUK** [comment]
This is a bug in ZNC's mode handling. It's fixed in ZNC git.

https://github.com/znc/znc/commit/95369455fcbc95f8064253b1e72c8b9bc83b6e98

See also: https://github.com/inspircd/inspircd/issues/1636#issuecomment-490224949
