### ISSUE TITLE
batch response with labeled-response contain label on all batch lines

### ISSUE THREAD

**Issue by kylef** [inspircd/inspircd#1710]
**Description**

The labeled-response specification (https://ircv3.net/specs/extensions/labeled-response) states that the start of a batch MUST be tagged with the draft/label tag. In InspIRCd (testnet) I am currently seeing the behaviour that all the batch contains the labelled response which is contary to the example in IRCv3 labeled-response specification:

> If a response consists of more than one message, and the batch capability is > enabled, a batch MUST be used to group them into a single logical response. >The start of the batch MUST be tagged with the draft/label tag.

Example from spec:

> ```
> Client: @label=mGhe5V7RTV WHOIS nick
> Server: @label=mGhe5V7RTV :irc.example.com BATCH +NMzYSq45x labeled-response
> Server: @batch=NMzYSq45x :irc.example.com 311 client nick ~ident host * :Name
> ...
> Server: @batch=NMzYSq45x :irc.example.com 318 client nick :End of /WHOIS list.
> Server: :irc.example.com BATCH -NMzYSq45x
> ```

**Steps to reproduce the issue:**

1. Connect to testnet for InspIRCd
2. Enabled the `batch` and `draft/labeled-response-0.2` capabilities
3. Complete Registration
4. Perform a WHOIS request with a label.

**Describe the results you received:**

```
$ gnutls-cli testnet.inspircd.org -p 6697
CAP LS
:testnet.inspircd.org CAP * LS :account-notify account-tag away-notify batch cap-notify chghost draft/labeled-response-0.2 draft/setname echo-message extended-join invite-notify message-tags multi-prefix sasl server-time tls userhost-in-names
CAP REQ :batch draft/labeled-response-0.2 message-tags
:testnet.inspircd.org CAP * ACK :batch draft/labeled-response-0.2 message-tags
CAP END

NICK kylef
USER a b c d
...

@draft/label=abcdefg WHOIS kylef
@draft/label=abcdefg :testnet.inspircd.org BATCH +1 :draft/labeled-response
@draft/label=abcdefg;batch=1 :testnet.inspircd.org 311 kylef kylef a ... * :d
@draft/label=abcdefg;batch=1 :testnet.inspircd.org 378 kylef kylef :is connecting from ...
@draft/label=abcdefg;batch=1 :testnet.inspircd.org 312 kylef kylef testnet.inspircd.org :InspIRCd test server
@draft/label=abcdefg;batch=1 :testnet.inspircd.org 379 kylef kylef :is using modes +
@draft/label=abcdefg;batch=1 :testnet.inspircd.org 671 kylef kylef :is using a secure connection
@draft/label=abcdefg;batch=1 :testnet.inspircd.org 317 kylef kylef 19 1569160841 :seconds idle, signon time
@draft/label=abcdefg;batch=1 :testnet.inspircd.org 318 kylef kylef :End of /WHOIS list.
@draft/label=abcdefg :testnet.inspircd.org BATCH :-1
```

**Describe the results you expected:**

The label is only present on first line of the batch, to match the example in draft/labeled-response specification.

```
@draft/label=abcdefg WHOIS kylef
@draft/label=abcdefg :testnet.inspircd.org BATCH +1 :draft/labeled-response
@batch=1 :testnet.inspircd.org 311 kylef kylef a ... * :d
@batch=1 :testnet.inspircd.org 378 kylef kylef :is connecting from ...
@batch=1 :testnet.inspircd.org 312 kylef kylef testnet.inspircd.org :InspIRCd test server
@batch=1 :testnet.inspircd.org 379 kylef kylef :is using modes +
@batch=1 :testnet.inspircd.org 671 kylef kylef :is using a secure connection
@batch=1 :testnet.inspircd.org 317 kylef kylef 19 1569160841 :seconds idle, signon time
@batch=1 :testnet.inspircd.org 318 kylef kylef :End of /WHOIS list.
:testnet.inspircd.org BATCH :-1
```

**Output of `./bin/inspircd --version`:**

Not my instance, but:

```
VERSION
:testnet.inspircd.org 351 kylef InspIRCd-3. testnet.inspircd.org :
:testnet.inspircd.org 005 kylef ACCEPT=30 AWAYLEN=200 CALLERID=g CASEMAPPING=ascii CHANLIMIT=#:20 CHANMODES=Zbegw,k,FHJdfjl,BCDMNOPRScimnprstuz CHANNELLEN=64 CHANTYPES=# ELIST=CMNTU ESILENCE=CcdiNnPpTtx EXCEPTS=e EXTBAN=,BCNORSUacjmrsz :are supported by this server
:testnet.inspircd.org 005 kylef HOSTLEN=64 KEYLEN=32 KICKLEN=255 LINELEN=512 MAXLIST=begw:100 MAXTARGETS=20 MODES=20 MONITOR=30 NAMESX NETWORK=InspIRCd-TestNet NICKLEN=30 OVERRIDE PREFIX=(qaohv)~&@%+ :are supported by this server
:testnet.inspircd.org 005 kylef SAFELIST SILENCE=32 STATUSMSG=~&@%+ TOPICLEN=307 UHNAMES USERIP USERLEN=10 VBANLIST WATCH=30 WHOX :are supported by this server
```

**Comment by SaberUK** [comment]
Note: this only applies to the testnet. The ircv3_labeledresponse module has not been merged into the insp3 branch yet as it represents a WIP specification.

I honestly think the spec is badly designed and complicates both client and server implementations as well as making the feature completely worthless for handling multi-line messages without batch support.

**Comment by kylef** [comment]
Perhaps that feedback would be better shared and updated in the draft/labeled-response specification? As far as I can tell from https://github.com/ircv3/ircv3-specifications/pull/378 / https://github.com/ircv3/ircv3-specifications/pull/378#issuecomment-501213223 InspIRCd has ratified the spec, yet has a different implementation.

Having different implementations doesn't make it easier for client implementations at all.

**Comment by SaberUK** [comment]
>Perhaps that feedback would be better shared and updated in the draft/labeled-response specification?

I've tried and failed to get the spec changed to match sane behaviour already.

>InspIRCd has ratified the spec

We have not. The module is not in the inspircd/inspircd Git repository and only exists in my private fork.

I'll update my implementation to match the (imo worthless) spec whenever I merge it into inspircd/inspircd after it gets ratified by IRCv3.

**Comment by SadieCat** [comment]
This is fixed, i'll push it to testnet later.
