### ISSUE TITLE
CGIIRC not adding the correct host?

### ISSUE THREAD

**Issue by DarkTexas** [inspircd/inspircd#1713]
Some Users who are connecting via a CGIIRC are not having their real IP/Host in the Connect/Disconnect/Whois information.

The IP is the Users's real IP and does NOT match the Hostname (chat.icq-chat.com in our case).
This is not happening for all connects via CGIIRC.

**Steps to reproduce the issue:**

1. Connect to the Network via a Webchat<->CGIIRC 
2. The IP/Hostmask will not match sometimes at connecting users

**Describe the results you received:**

CONNECT: Client connecting on port 6667 (class main): Anna!Anna@chat.icq-chat.com (8.xxx.x.xx7*) [[23/F/U]]

[18:46:52] Anna is Anna@arb.clm.oli7au.IP * [23/F/U]
[18:46:52] Anna is connecting from Anna@chat.icq-chat.com 8.xxx.x.xx7*
[18:46:52] Anna on #Germany

**Describe the results you expected:**

CONNECT: Client connecting on port 6667 (class main): Werwoelfin26!Werwoelfin@xxxx.dip0.t-ipconnect.de (79.xxx.xxx.xx) [[U/F/U]]

[18:50:45] Werwoelfin26 is Werwoelfin@172.m75.g60md3.IP * [U/F/U]
[18:50:45] Werwoelfin26 is connecting from Werwoelfin@xxxx.dip0.t-ipconnect.de 79.xxx.xxx.xx

^ here the IP matches the Host and "chat.icq-chat.com" is not shown

**Additional information you deem important (e.g. issue happens only occasionally):**

issue happens only occasionally

**Output of `./bin/inspircd --version`:**

InspIRCd version: 3.3.0

**Comment by jlu5** [comment]
I think I can confirm similar behaviour on 3.3.0.

Basically, if a user connects with an IP that fails a FCrDNS check, the hostname of the WebIRC gateway is assigned instead of the raw IP. Clients with proper FCrDNS or no rDNS at all connect with a correct mask.

**Comment by DarkTexas** [comment]
This seems to affect xlines as well as it's setting those xlines on the host and lines the half network if not being carefull, kinda a server-breaking issue.

**Comment by DarkTexas** [comment]
Possible way around this:
Setting **resolvehostnames="no"** in all connect classes helped us, temporary.

**Comment by SaberUK** [comment]
You need to disable DNS lookups for your WebIRC gateway.
