### ISSUE TITLE
extempchanops also for +E (repeat)

### ISSUE THREAD

**Issue by H7-25** [inspircd/inspircd#1714]
extempchanops should need an option also to override repeat flood module (+E)

**Comment by genius3000** [comment]
There is an exemption in m_repeat: repeat . https://docs.inspircd.org/3/modules/repeat/#exemptions I see it's not referenced in the m_exemptchanops docs though.

**Comment by H7-25** [comment]
Fine, so just extempchanops docs and helpop example, needs to be updated
