### ISSUE TITLE
User can not join all channel (+b) 

### ISSUE THREAD

**Issue by gorut** [inspircd/inspircd#1718]
I have a problem with my users, every time they connect or go online on my server, they can't join all channels, even messages are banned + b

guess what settings should be corrected for the problem huh

** Anda tidak bisa bergabung di saluran #hijaben karena anda telah dilarang (mode +b)

**Comment by SaberUK** [comment]
Try unbanning them?

This is a bug tracker not a support system. In the future please ask for support on IRC.
