### ISSUE TITLE
/SILENCE not correctly removing

### ISSUE THREAD

**Issue by DarkTexas** [inspircd/inspircd#1719]
**Steps to reproduce the issue:**

1. Type /silence +help (help will get added to the silence list)
2. Type /silence (to list the silence list)
3. Type /silence -help to remove the invalid entry (it will not get removed)

**Describe the results you received:**

[10:44:09] *!*@* CciNnPpTt The SILENCE entry you specified could not be found

same seems to be happen with e.g. help!*@ and help*

**Describe the results you expected:**

Should have removed it from the list.

**Output of `./bin/inspircd --version`:**

InspIRCd 3.3.0

**Comment by SaberUK** [comment]
This is fixed in insp3 git already. 

https://github.com/inspircd/inspircd/commit/e566a2d666f6f54eeab364794145e3b0999383ed
