### ISSUE TITLE
DNSBL module look skip webirc users check

### ISSUE THREAD

**Issue by H7-25** [inspircd/inspircd#1721]
If an users connect to irc using a webirc client it look he is skipped from dnsbl check

**Steps to reproduce the issue:**

1.  Connect your network  using a proxy or a vpn present on dronebl using a webirc client
2. Connect your network  using a proxy or a vpn present on dronebl using any other client

Using a webirc client i can connect to the network, using any other client i get zlined 

I think DNSBL module should check and zline webirc connection too if a proxy is used

inspircd3@webirc:~/ircd/bin$ ./inspircd --version

InspIRCd-3.3.0-685dfe016

**Comment by SaberUK** [comment]
DNSBL lookups *are* done for WebIRC users. You need to disable DNSBL lookups for the gateway to avoid issues as it won't run a DNSBL check if one is already in progress.

I've updated the docs to make this more clear.

**Comment by genius3000** [comment]
I just ran a quick test for my suspicion. Having `usednsbl="no"` in the WebIRC class will still cause the DNSBL check not to execute. When `OnSetUserIP()` is called the current class is still the WebIRC one. Same issue occurs for hostname lookup, skipping it in the WebIRC class causes it not to lookup the hostname of the real IP either.

**Comment by SaberUK** [comment]
@genius3000 Ah, i'll change the event to be fired after the class change.

**Comment by SaberUK** [comment]
Just pushed a fix, does that work for you?

**Comment by genius3000** [comment]
I won't be able to test until tonight, but will let you know. Thanks.

**Comment by genius3000** [comment]
@SaberUK I can confirm that the fix works.  

For reference:  
Connect class for my WebIRC gateway has
```
usednsbl="no"
resolvehostnames="no"
```
Connect class for users has those both set to "yes". Both DNSBL and hostname lookups are being executed on the real IP address of connecting WebIRC clients now.

**Comment by SaberUK** [comment]
Thanks for testing! 👍
