### ISSUE TITLE
I have a problem with core_hostname_lookup.cpp

### ISSUE THREAD

**Issue by pasmax2** [inspircd/inspircd#1723]
inspircd.git.3/src/coremods/core_hostname_lookup.cpp: In member function ‘virtual void UserResolver::OnLookupComplete(const DNS::Query*)’:
inspircd.git.3/src/coremods/core_hostname_lookup.cpp:77:16: error: ‘user’ was not declared in this scope
    HandleError(user, "Could not resolve your hostname: No " + this->manager->GetTypeStr(this->question.type) + " records found");
                ^
compilation terminated due to -Wfatal-errors.
real.mk:122: recipe for target 'modules/core_hostname_lookup.so' failed
make[1]: *** [modules/core_hostname_lookup.so] Error 1
GNUmakefile:161: recipe for target 'target' failed
make: *** [target] Error 2

inspircd 3

**Comment by SaberUK** [comment]
Thanks for reporting, the Git diff viewer I use is incredibly broken and I thought something was staged when I committed to it when it actually wasn't.

**Comment by SaberUK** [comment]
Fixed in bed84ae.
