### ISSUE TITLE
Requirement of replaced library

### ISSUE THREAD

**Issue by mdziczkowski** [inspircd/inspircd#1725]
I wanted to report that InspIRCd require a library named **libmariadbclient18** with has been replaced with the library named **libmariadb3** (unfortunatelly, even if the **libmariadb3** library is installed, I'm unable to intall the InspIRCd debian file (*.deb).

Please fix it asap. Thanks

**Comment by rctgamer3** [comment]
This has still not been fixed yet. libmariadbclient18 is unavailable in Debian 10 Buster.

**Comment by SadieCat** [comment]
Sorry for the late reply. This is fixed with our new packages.
