### ISSUE TITLE
v2 +k chmode does not strip comma (,) from channel keys

### ISSUE THREAD

**Issue by KoraggKnightWolf** [inspircd/inspircd#1727]
**Description**

When setting channel mode +k on a channel on InspIRCd 2, a comma (,) is NOT stripped from the key. Thisi s problematic because when joining multiple channels with a key, the list of keys is seperated by a comma, and InspIRCd 3 strips commas appropriately.

**Steps to reproduce the issue:**

1. Setup an InspIRCd 2 (important NOT InspIRCd 3) server
2. Join an empty, non registered and non permanent channel, example #Channel to gain ops (or gain them in other means e.g. via SAMODE)
3. Use /mode #Channel +k ,test 
4. Observe how mode +k ,test is set WITHOUT stripping the comma (,)

**Describe the results you received:**

The comma (,) is NOT stripped from the channel key upon setting the +k channel mode.

**Describe the results you expected:**

The comma (,) should be stripped from all channel keys because when joining multiple channels with keys, the list of keys is seperated via comma (,)

This is limited to InspIRCd 2 networks as InspIRCd 3 ones strip the comma (,) appropriately. This also happens regardless of where the comma is, so a key in the form of ,test or te,st or test, (comma at the beginning, in the middle, and at the end respectively) all will be set when they should not be.

**Output of `./bin/inspircd --version`:**

InspIRCd version: InspIRCd-2.0.27(r0)

(Side note: compared to git for v2 reveals tha 2.0.28 did not have any changes to the +k channel mode for roughly 7 years, so the latest v2 version would not have a fix for this either)

**Comment by SaberUK** [comment]
v2 is only receiving security fixes so this won't be changed. Sorry.
