### ISSUE TITLE
Possibly add "Wants=network-online.target" to service file

### ISSUE THREAD

**Issue by cbiedl** [inspircd/inspircd#1729]
As I've learned, systemd is a bit complicated if a service should not be started before the network is fully configured - like inspircd when there are hard-coded addresses the daemon should bind to while the related interfaces are not configured yet.

According to the systemd documentation (fast-forward to "How do I make sure that my service starts after the network is really online?") at

    https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/

the service file should contain the following two lines:

    After=network-online.target
    Wants=network-online.target

while the inspircd service file as seen at

    https://github.com/inspircd/inspircd/blob/insp3/make/template/inspircd.service

only has the first. Although I haven't experienced a problem from that, it might be better to play safe and add the other line as well.

So treat this as a suggestion, not as a feature request.

Regards

**Comment by cbiedl** [comment]
Small correction, currently there is
    After=network.target
while systemd suggest using "network-online.target". Again, it's probably wiser to follow that recommendation.

**Comment by SaberUK** [comment]
InspIRCd v3 has `<bind:free>` ([docs link](https://docs.inspircd.org/3/configuration/#ltbindgt)) to allow you to bind to addresses before the network comes up but if you file a pull request i'd have no objections to merging it.
