### ISSUE TITLE
Server Links over Unix Domain Sockets

### ISSUE THREAD

**Issue by shaggie76** [inspircd/inspircd#1730]
We typically operate InspIRCd in a hub & spoke topology on a single server to leverage multiple cores -- with 5 spokes this fills out a hex-core server nicely and lets us scale to over 100K connections by balancing users across 5 processes.

Historically we just used loopback connections for these (binding to localhost to conceal the link ports) however when researching using Unix Domain Sockets to reduce the pain of haproxy in https://github.com/inspircd/inspircd/issues/1726 it occurred to me that using UDS for localhost links might be a nice performance win.

Unfortunately I found https://github.com/inspircd/inspircd/issues/904 which suggests that 5 years ago nobody thought links over UDS was worthwhile.

I had hope when I saw https://github.com/inspircd/inspircd/issues/1479 (a few years after the initial UDS discussion) so I tested the latest code but evidently links are still limited to TCP.

So I'd like to renew the call for UDS links citing the performance benefits of running a "network" on a single multi-core server.

**Comment by SaberUK** [comment]
UNIX sockets for server linking should work on non-Windows. You need to set the `<link:ipaddr>` field to the socket path.

**Comment by shaggie76** [comment]
The log suggested that without a port specified it would not work and the code seems to support that?

src\modules\m_spanningtree\utils.cpp(211):			ServerInstance->Logs->Log(MODNAME, LOG_DEFAULT, "Ignoring a link block without a port.");

Looking at the source I don't see it parsing a path tag at all?

For the hub I have

`<bind path="/home/glen/InspIRCd0/run/bind.sock" type="clients">`

But a spoke can't 

`<link name="irc0.warframe.com" path="/home/glen/InspIRCd0/run/bind.sock" ,,,`

**Comment by shaggie76** [comment]
Specifying a UDS in the "ipaddr" field (and adding a bogus port number) doesn't work (as I would expect)

Thu Nov 14 2019 12:25:27 m_spanningtree: Could not resolve IP associated with Link 'irc2.warframe.com': Domain not found

**Comment by SaberUK** [comment]
Hm, i'll look into this.

**Comment by genius3000** [comment]
I've got some WIP on this and the 'no port' link blocks. For now though you should be able to specify link blocks with both `ipaddr` and `allowmask` to the UDS path, a valid (but bogus) port just to satisfy that one check, and of course the name and passwords. Then make sure your corresponding bind is set for servers. I initially was just testing with netcat and getting a connection started; just ran a test with two servers and successfully connected them via UDS.

**Comment by shaggie76** [comment]
Looking through the rawio logs I found:

```
Fri Nov 15 2019 10:24:10 SOCKET: Accepting connection on socket /home/glen/InspIRCd0/run/link.sock fd 10
Fri Nov 15 2019 10:24:10 SOCKET: BUG: sa2cidr(): socket type 0 is unknown!
Fri Nov 15 2019 10:24:10 SOCKET: BUG: sa2cidr(): socket type 0 is unknown!
Fri Nov 15 2019 10:24:10 SOCKET: BUG: sa2cidr(): socket type 0 is unknown!
Fri Nov 15 2019 10:24:10 SOCKET: BUG: sa2cidr(): socket type 0 is unknown!
Fri Nov 15 2019 10:24:10 SOCKET: BUG: sa2cidr(): socket type 0 is unknown!
Fri Nov 15 2019 10:24:10 SOCKET: Refusing connection on /home/glen/InspIRCd0/run/link.sock - Connection refused by module
```

I'll try to figure out where that's going wrong -- we haven't reset out inspircd.conf in 5 years of upgrades so maybe there's something we failed to upgrade that is necessary for UDS.

**Comment by shaggie76** [comment]
I got it working with allowmask="*" for some reason (maybe my system has something different?). I will try to clean this up and roll out for production this weekend.

**Comment by shaggie76** [comment]
So for posterity, like genius3000 said, you need to hack the link directive: specify the UDS path in the ipaddr tag, set allowmask="*", and specify a bogus port:

hub:
`<bind path="/path/to/hub/link.sock" type="servers">`

spoke:
`<link name="irc0" ipaddr="/path/to/hub/link.sock" allowmask="*" port="1" sendpass=".." recvpass="..">`

Sadly I deployed this to our production servers just now and at a load of 50K users I'm not seeing any improvement to CPU load per spoke (I'm assuming the %CPU column includes kernel time which is where I'd expect to see the gains).
