### ISSUE TITLE
Inspircd 3.4.0 Turkish Nickname Support ( NationalChars )

### ISSUE THREAD

**Issue by AnaxArxes** [inspircd/inspircd#1735]
hello I would like to get support for Turkish.

ircd.log:
m_nationalchars: loadtables () called for missing file: ../locales/tr_TR.iso88599
 
Unable to read the configuration for m_nationalchars.so: The locale file failed to load. Check your log file for more information.

modules.conf

nationalchars file="tr_TR.iso88599" casemapping="tr_TR.iso88599_braces"

what should I do ?

**Comment by SaberUK** [comment]
You need to configure it with a path to a casemapping file. See [the docs](https://docs.inspircd.org/3/modules/nationalchars/#configuration) and locales/README.txt for more information.

This is a bug tracker not a support system. If you have any more questions please ask them at irc.inspircd.org #inspircd.
