### ISSUE TITLE
Error modes

### ISSUE THREAD

**Issue by arianshack** [inspircd/inspircd#1737]
I have a problem with InspIRCd 3.4, install everything correctly and confs, but when the user connects does not activate the +x, also happens the same with ssl, only works if you activate it manually /mode nick +x / +z, I do not know what can be, here I leave as I have the connection section, Greetings and I hope someone can help me.
<connect 
        name="main"
	allow="*"
	localmax="40"
	globalmax="40"
	modes="+xT"
	limit="5000">

**Comment by SaberUK** [comment]
You've probably not loaded the conn_umodes module.

This is a bug tracker. If you have any more issues then please ask in irc.inspircd.org #inspircd. Thanks.
