### ISSUE TITLE
Automatically generate the authors list in /INFO from git history.

### ISSUE THREAD

**Issue by SadieCat** [inspircd/inspircd#1740]
This would be useful as it would mean we wouldn't need to keep manually updating it.

**Comment by SaberUK** [comment]
Recent contributors: git log --since='2 years ago' --format='%aN' | sort --ignore-case --unique

Past contributors: git log --after='2 years ago' --format='%aN' | sort --ignore-case --unique

**Comment by SadieCat** [comment]
Instead of this we now have `docs/AUTHORS.txt`.
