### ISSUE TITLE
Broken .deb package

### ISSUE THREAD

**Issue by Ascrod** [inspircd/inspircd#1743]
Steps to reproduce:
1) Spin up a fresh VM with Ubuntu Server 18.04.3 LTS
2) Download and install `inspircd_3.4.0-1_amd64.deb` with dpkg
3) `apt -f install` to install dependencies and finish installation
4) `service inspircd restart`
5) `journalctl -xe`

Results:
Inspircd fails to start with this error: "Unknown parameter '--logfile'"

Fix:
`/lib/systemd/system/inspircd.service` and `/etc/init.d/inspircd` need to be updated to remove the nonexistent `--logfile` parameter.

**Comment by Adam-** [comment]
[inspircd_3.4.0-1_amd64.deb.zip](https://github.com/inspircd/inspircd/files/4023719/inspircd_3.4.0-1_amd64.deb.zip)

Can you test this package and see if there are any more issues?

**Comment by Ascrod** [comment]
After putting a basic config file in `/etc/inspircd`, the service starts without any further issues. Thanks!

**Comment by Adam-** [comment]
Okay I've updated the download.
