### ISSUE TITLE
Linking issue with m_nationalchars

### ISSUE THREAD

**Issue by Eyecu** [inspircd/inspircd#1744]
When trying to link servers with m_nationalchars module loaded I get the following error 

Mon Jan 06 2020 07:34:21 LINK: Connection to 'hub.koach.com' failed with error: CAPAB negotiation failed: Modules incorrectly matched on these servers. Not loaded here: m_nationalchars.so=/home/hub/inspircd-3.4.0/locales/bynets/cs3-utf8 Not loaded there: m_nationalchars.so=/home/chat1/inspircd-3.4.0/locales/bynets/cs3-utf8

problem is too unless you use the full path for the nationalchars file it gives an error loading the module. IE i can't just use bynets/cs3-utf8 even though the module descriptions says relative path is based from ../locales

**Comment by SadieCat** [comment]
You need to set <nationalchars:casemapping> to the name of the casemapping you're using.

**Comment by SadieCat** [comment]
Ah, I see the issue! Will fix shortly.
