### ISSUE TITLE
Add more codepage files for use with the codepage module

### ISSUE THREAD

**Issue by SadieCat** [inspircd/inspircd#1746]
A replacement for the nationalchars module was added in 3dd446d.

The only interesting codepage file which is currently available is latin1. We should add more codepage files for it and then delete the nationalchars ones.

**Comment by EpicNet** [comment]
Tell me, if it’s possible how to make a configuration file so that can add all the “**Russian**” characters for use in aliases, as well as any additional new characters from the **UTF-8** encoding table ???

```
абвгдеёжзийклмнопрстуфхцчшщъыьэюя
АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ
!?:'-"(~)*.
```

**Comment by SadieCat** [comment]
This module is currently for 8-bit encodings only, which for Russian would be [KOI8-R](https://en.wikipedia.org/wiki/KOI8-R#Character_set). It can not be used with UTF-8 yet.

**Comment by EpicNet** [comment]
Can you create a ready-made file "koi8-r.conf" for using Russian characters and add it to the IRCD release update, as well as send me the file by e-mail?

**Comment by SadieCat** [comment]
More codepages will be added in time but its not a priority for now.

**Comment by sadiepowell** [comment]
It didn't get forgotten but I haven't had time to work on it yet because its tricky with how InspIRCd handles stuff internally. The nationalchars module tried it but it was very broken and caused lots of internal issues which is why it was removed.
