### ISSUE TITLE
Channel::WriteNotice() has some modules sending a notice from each server.

### ISSUE THREAD

**Issue by genius3000** [inspircd/inspircd#1749]
The changes in commit 687778b that send the message to other servers via ProtocolInterface doesn't work well for some modules. A few modules using Channel::WriteNotice already have each server sending the message, sending them via PI just duplicates it per server.

Known modules (not currently definitive):
1. m_joinflood - mode has to keep an internal state per server.
2. m_knock - does this really need to route to all servers?

I see in the same commit that spanningtree's fjoin got switched to creating the message but we probably don't want to have that in more places than necessary. So I'm thinking of two possibilities:
- Have Channel::WriteNotice take a bool 'remote', default to false. Send via PI only if true.
or
- Create Channel::WriteRemoteNotice and that sends via PI only (this matches User:: WriteRemoteNotice) or send both local and remote to simplify the calling end.  

I'm currently on mobile and haven't had a ton of time to check this 100% but wanted to get this posted before I forget and to discuss the best route.

**Comment by SadieCat** [comment]
I agree re using WriteRemoteNotice for global notices.

>m_joinflood - mode has to keep an internal state per server.



>m_knock - does this really need to route to all servers?

Why wouldn't it need to go to all servers? If it only sent to the local server then people on other servers wouldn't know about the knock.

**Comment by genius3000** [comment]
With m_knock I meant the command is routed/broadcast to all servers, which is why it worked when only sending a message to local users. Switching that to sending to remote users too, does the command really need to be broadcast anymore?

**Comment by SadieCat** [comment]
Ah, I see. I missed the routing function in the command handler when I looked at it earlier.

**Comment by SadieCat** [comment]
I think this is fixed now.
