### ISSUE TITLE
Sending +k with prior key results in no response

### ISSUE THREAD

**Issue by kylef** [inspircd/inspircd#1750]
**Description**

Setting `+k` mode with same key does not return a response.

**Steps to reproduce the issue:**

Join a channel; set a channel key; set the same channel key again.

```
$ gnutls-cli testnet.inspircd.org -p 6697
C: NICK me
C: USER a b c d
...
S: :testnet.inspircd.org 002 me :Your host is testnet.inspircd.org, running version InspIRCd-3
S: :testnet.inspircd.org 003 me :This server was created 11:17:30 Feb 02 2020
...
C: JOIN #foo
...
C: MODE #foo +k sekret
S: :me!a@<redacted> MODE #foo +k :sekret
C: MODE #foo +k sekret
```

**Describe the results you received:**

Nothing.

**Describe the results you expected:**

I'd expect a key set error defined in RFC1459:

> 467     ERR_KEYSET
> "<channel> :Channel key already set"

**Comment by SadieCat** [comment]
Is this behavour defined somewhere? I just checked hybrid, charybdis, unreal, and ngircd and none of them seem to send ERR_KEYSET.

**Comment by kylef** [comment]
I was looking at the permitted responses in the mode command in RFC1459 (i'm testing client side behaviours) in https://tools.ietf.org/html/rfc1459#section-4.2.3.2 which shows `ERR_KEYSET` as a response. The definition of ERR_KEYSET is what I showed above and shows an example message of "Channel key already set", I can't think of another case than sending same key twice to get a message stating the key was already set.
