### ISSUE TITLE
Proxied WebSocket + connectban problems

### ISSUE THREAD

**Issue by LunaSquee** [inspircd/inspircd#1752]
**Description**

A proxied WebSocket + connectban module results in the proxy server getting Z-Lined when the connection threshold is reached, instead of the real IP of the client. (Circumvented temporarily with an E-Line)

**Steps to reproduce the issue:**

1. Proxy Insp's websocket with something like nginx and enable connectban
2. Create multiple connections in rapid succession, ensuring that the server does actually get the client's real IP address (look at logs, or host name of the IRC user if doing a full connection)
3. Observe how the proxy server's IP address gets put into the Z-Line list (/stats Z)

**Describe the results you expected:**
The client's real IP address should get added to the Z-Line list instead of the proxy server's.

**Additional information you deem important (e.g. issue happens only occasionally):**
Another thing that I noticed that may or may not be related, is that when your proxy server is 127.0.0.1, creating too many connections will ban absolutely everyone on your network for some reason.

**Output of `./bin/inspircd --version`:**
InspIRCd-3.5.0

**Comment by LunaSquee** [comment]
While on the topic of websocket, is there a way to make the +z mode work with websocket connection?

**Comment by SadieCat** [comment]
+z will work with WebSocket connections if you use TLS between your proxy and InspIRCd.

**Comment by LunaSquee** [comment]
> +z will work with WebSocket connections if you use TLS between your proxy and InspIRCd.

It doesn't seem to be the case for me, I set `ssl="openssl"` on the `<bind>` and the proxy addresses it via `https://` but +z still doesn't work

**Comment by LunaSquee** [comment]
> +z still blocks me from joining

`/whois` does not mention I'm connected securely either

**Comment by SadieCat** [comment]
Can you see if this fixes your connectban issues:https://github.com/inspircd/inspircd/compare/insp3...SadieCat:insp3+fix-connectban

**Comment by LunaSquee** [comment]
Nope, it is still banning local address

**Comment by SadieCat** [comment]
Does this happen on the latest insp3 Git?

**Comment by SadieCat** [comment]
This should be fixed in insp3 git. Please reopen if you're still having issues.
