### ISSUE TITLE
SAMODE - Server should set the mode, not IRCop !

### ISSUE THREAD

**Issue by amganq** [inspircd/inspircd#1754]
Hello,

On the new InspIRCd (version 3), after I log in to the server and Oper myself ("/oper ...") I get the IRC Operator status.

If I want to be able to freely change modes, if I am not a channel operator, I use SAMODE.

But, when issuing "/samode #channel +o Me" for example, it says that I opped myself.
It should HIDE the originating IRCop user who issued the command, and it should say, like in other IRC Servers (undernet's ircu or unrealircd) something like this:

"irc.example.com (my server's hostname) sets mode +o..." --- effectively this mode change is coming from the server itself (for the outside viewers).

How can we reproduce this in InspIRCd ?

Thank you.

**Comment by SadieCat** [comment]
InspIRCd works this way by design. The main reason AFAIK that other IRCds set it from the server is that it used to be common for client bots to be used to manage channel access and they would break when an oper used SAMODE. However, its not 1998 anymore and we have have services which can handle this.

**Comment by SadieCat** [comment]
If you have any more issues then please ask in irc.inspircd.org #inspircd. Thanks.

**Comment by amganq** [comment]
OK. I understand this. But I am managing a small network and I don't know if I'll use services.
If I get the source and compile InspIRCd by source, what must I edit in the .cpp file ? (and which .cpp file) to leave the "server sets mode +o" not the user... ?
Thanks.
