### ISSUE TITLE
WebSocket 403 error

### ISSUE THREAD

**Issue by Lerian715** [inspircd/inspircd#1758]
Hi,  
I'm trying to connect inspircd with kiwi web client via websocket. I have already enabled `websocket` by:  
**modules.conf**  
```
<module name="websocket">
<wsorigin allow="http://localhost:8080/">
```
**inspircd.conf**  
```
<bind address="" port="7002" hook="websocket">
```
but I'm getting **403**. Should I authenticate or somethink?  
I know, you do not develop KiwiIRC but maybe someone has experience with it so here is my config:  
**static/config.json**
```
{
	"windowTitle": "Kiwi IRC - The web IRC client",
	"startupScreen": "customServer",
	"kiwiServer": "http://localhost:8080/webirc/websocket/",
	"restricted": false,
	"theme": "default",
	"themes": [
		{ "name": "Default", "url": "static/themes/default" },
		{ "name": "Dark", "url": "static/themes/dark" }
	],
	"startupOptions" : {
		"server": "localhost",
		"port": 7002,
		"tls": false,
		"direct": true,
		"channel": "#guests",
		"nick": "_user?"
	}
}
```

**Comment by SadieCat** [comment]
You need to whitelist the origin of your KiwiIRC instance.

https://docs.inspircd.org/3/modules/websocket/#ltwsorigingt

If you have any more issues then please ask in irc.inspircd.org #inspircd. Thanks.

**Comment by SadieCat** [comment]
Sorry, just noticed my previous now-deleted comment was wrong. You're specifying a path in your wsorigin tag. Delete that and it should work.

If you have any more issues then please ask in irc.inspircd.org #inspircd. Thanks.
