### ISSUE TITLE
Problem with inspircd in LAN

### ISSUE THREAD

**Issue by CasvalDOT** [inspircd/inspircd#1760]
**Description**

I'm try to use a raspberry pi with kali linux distro as small server for a irc server. I've installed inspircd via official repos using the command:

`apt install inspircd`

I've change the configuration enabling some modules, and then start the service via the following command:

`systemctl start inspircd`

I've check the status and the result show me the loaded modules:
```
m_password_hash.so
m_sha256.so
m_md5.so
m_permchannels.so
m_conn_join.so
m_securelist.so
m_sslinfo.so
m_sslmodes.so
```
No errors occured, but when try to connect from the same machine or another pc into LAN, i get the following error:

```
Irssi: Connection to 192.168.66.104 established
i*** Looking up your hostname...
Could not resolve your hostname: Domain not found; using your IP address (192.168.66.100) instead.
23:31 -!- ERROR Closing link: (434AAAAAF@192.168.66.100) [Registration timeout]
23:31 -!- Irssi: Connection lost to 192.168.66.104
```
The ip 192.168.66.104 is my irc server, instead 192.168.66.100 is the ip machine of the irc client.

What is the problem? I'm supposed that is a misunderstanding of the configuration file. The file is reported below:

```
<define name="DOMAIN" value="test.io">
<define name="ADMIN_NAME" value="test">
<define name="ADMIN_NICK" value="TEST">
<define name="ADMIN_EMAIL" value="test@localhost">

<server name="irc.&DOMAIN;"
        description="Local IRC Server"
        network="Localnet">

<admin name="ADMIN_NAME"
       nick="ADMIN_NICK"
       email="ADMIN_EMAIL">

<bind replace="true" port="6667" type="clients">

<power diepass="3456" restartpass="7890" pause="2">

<connect name="6bone"
         deny="3ffe::0/32"
         reason="The 6bone address space is deprecated">

<cloak mode="full" key="TESTESTTESTTSTSTTSTSTSTTSTSTSTSTTSTSTTS" prefix="cloaked-">

<connect allow="*"
	useident="no"
	port="6667"
	 password="test"
	 maxchans="10"
	 commandrate="2"
         timeout="60"
         flood="20"
         threshold="1"
         pingfreq="120"
         sendq="262144"
         recvq="8192"
         localmax="3"
         resolvehostnames="yes"
         globalmax="3">

<class name="Shutdown"
       commands="DIE RESTART REHASH LOADMODULE UNLOADMODULE RELOAD">
<class name="ServerLink"
       commands="CONNECT SQUIT RCONNECT MKPASSWD MKSHA256">
<class name="BanControl"
       commands="KILL GLINE KLINE ZLINE QLINE ELINE">
<class name="OperChat"
       commands="WALLOPS GLOBOPS SETIDLE SPYLIST SPYNAMES">
<class name="HostCloak"
       commands="SETHOST SETIDENT SETNAME CHGHOST CHGIDENT">

<type name="NetAdmin"
      classes="OperChat BanControl HostCloak Shutdown ServerLink"
      host="netadmin.omega.org.za">
<type name="GlobalOp"
      classes="OperChat BanControl HostCloak ServerLink"
      host="ircop.omega.org.za">
<type name="Helper"
      classes="HostCloak"
      host="helper.omega.org.za">
<oper name="root"
      password="12345"
      host="*@localhost"
      type="NetAdmin">

<files motd="/etc/inspircd/inspircd.motd"
       rules="/etc/inspircd/inspircd.rules">

<channels users="20"
          opers="60">

<dns
#	server="127.0.0.1"
	timeout="5">

<pid file="/var/run/inspircd/inspircd.pid">

<options prefixquit="Quit: "
         noservices="no"
         qaprefixes="no"
         deprotectself="no"
         deprotectothers="no"
         flatlinks="no"
         hideulines="no"
         syntaxhints="no"
         cyclehosts="yes"
         ircumsgprefix="no"
         announcets="yes"
         disablehmac="no"
         hostintopic="yes"
         quietbursts="yes"
         pingwarning="15"
         allowhalfop="yes"
	 exemptchanops="">

<security hidewhois=""
          userstats="Pu"
          customversion=""
          hidesplits="no"
          hidebans="no"
          operspywhois="no"
          hidemodes="eI"
          maxtargets="20">

<performance
             maxwho="128"
             softlimit="1024"
             somaxconn="128"
             netbuffersize="10240">

<whowas groupsize="10"
        maxgroups="100000"
        maxkeep="3d">

<timesync enable="no" master="no">

<badnick nick="ChanServ" reason="Reserved For Services">
<badnick nick="NickServ" reason="Reserved For Services">
<badnick nick="OperServ" reason="Reserved For Services">
<badnick nick="MemoServ" reason="Reserved For Services">

<module name="alias">
<module name="chghost">
<module name="customprefix">
<module name="globops">
<module name="hidechans">
<module name="hidechans">
<module name="svshold">
<module name="spanningtree">
<module name="showwhois">
<module name="services_account">
<module name="cloaking">
<module name="conn_umodes">
<module name="password_hash">
<module name="sha256">
<module name="md5">
<module name="permchannels">
<module name="conn_join">
<module name="securelist">
#<module name="ssl_gnutls">
<module name="sslinfo">
<module name="sslmodes">
```

**NOTE!**
I've try to set in connection tag  `resolvehostnames="no"` with a similar result:
```
23:46 -!- Irssi: Connecting to 192.168.66.104 [192.168.66.104] port 6667
23:46 -!- Irssi: Connection to 192.168.66.104 established
23:47 -!- ERROR Closing link: (434AAAAAB@192.168.66.100) [Registration timeout]
23:47 -!- Irssi: Connection lost to 192.168.66.104
```

If instead i uncomment the following line in tag dns:`server="127.0.0.1"`, the result is:

`Could not resolve your hostname: Request timed out`

**NOTE 2.**

I'm try to connect using irssi client and the folowing command:
`/connect 192.168.66.104 6667 test MYNICK`

What's wrong with my conf?

**Output of `./bin/inspircd --version`:**
InspIRCd-3.4.0

**Comment by genius3000** [comment]
So, I was close to saying this looks like a weird client issue; registration timeout means your client is matched to the connect class but fails to send USER and/or NICK within the set 60 seconds. **But then** I spotted that you have `commandrate="2"` which according to the [example conf notes](https://github.com/inspircd/inspircd/blob/insp3/docs/conf/inspircd.conf.example#L430) would equate to 0.12 commands (lines) in 60 seconds. _Note: at least I think my math and understanding is correct on that._
Try bumping that to the example conf's default of 1000 (one line per second) and see what happens.

To mention a few other minor things:
- You have the module `hidechans` declared twice.
- `bind:replace` is only used with a unix socket bind.
- Those hostname resolution failures are normal. A private IP address won't resolve to anything unless you use a local resolver and configure it to have a rDNS. With no DNS server specified, InspIRCd uses the system default from resolv.conf.

I'll also mention a reminder that this is an issue tracker (bugs and feature requests) not a support forum; support is handled at #inspircd on irc.inspircd.org. Please direct any future support requests there.

**Comment by CasvalDOT** [comment]
Thank for your feedback. The problem was the value of commandrate. Setting it at 1000 as you say now works. I've also set the option `resolvehostname` with `no` value. I also apologize for have use the wrong communication channel Next time I will contact you using the appropriate channels.
