### ISSUE TITLE
[*] Unable to load m_ldap.so: The specified module was not found.

### ISSUE THREAD

**Issue by tsk7mde** [inspircd/inspircd#1766]
Hello everybody,
I want to use the "LDAP" module under Windows Server 2019. 
It should be possible to log in users with the Active Directory. 
Unfortunately I cannot load the module. Can someone help me? 

Unfortunately I can not find another version that contains the module m_ldap.so for Windows. 
The file that is in the setup does not seem to work.

Grüße

Thomas

**Comment by SadieCat** [comment]
I don't think the LDAP module is included with our Windows builds as it has third-party dependencies. You'll need to build from source if you want to use that.

If you have any more issues then please ask in irc.inspircd.org #inspircd. Thanks.

**Comment by tsk7mde** [comment]
README! (From the SRC Download!)
Building from source on Windows is generally not recommended but [a guide is available](https://github.com/inspircd/inspircd/blob/master/win/README.txt) if you wish to do this.
