### ISSUE TITLE
libgmp-10.dll not Working under Windows

### ISSUE THREAD

**Issue by tsk7mde** [inspircd/inspircd#1767]
Hello everybody,

as soon as I run the module "ssl_gnutls" the server no longer starts.
The libgmp-10.dll file is not suitable for Windows.
I had to change the date manually to fix the problem. 
Can the setup not be updated ???

Version 3.5

**Comment by genius3000** [comment]
We'll have to check for this issue once we get the Windows binary builds setup.

**Comment by SadieCat** [comment]
A Windows binary package with fixed modules will be available in the next release (on the 29th).
