### ISSUE TITLE
channel voice / op -- You must specify a parameter for the voice mode

### ISSUE THREAD

**Issue by Casey952** [inspircd/inspircd#1777]
**Description**

On mIRC when you voice devoice and op deop yourself or another user when using the mIRC control function it says:

```
#Casey v * You must specify a parameter for the voice mode. Syntax: <nick>.
#Casey o * You must specify a parameter for the op mode. Syntax: <nick>.
```
This does not happen on InspIRCd 2

**Steps to reproduce the issue:**

1. mIRC when you are a channel op
2. right click on yourself or another person in the list of users in the channel.
3. Control -> voice / op - to voice and op the user.

And same for devoice / deop

**Describe the results you received:**

You get a message saying:

```
#Casey v * You must specify a parameter for the voice mode. Syntax: <nick>.
#Casey o * You must specify a parameter for the op mode. Syntax: <nick>.
```

It does give you the voice and op modes and removes them.

When you voice and op using /mode #channel + nick -- it does not get this message.

**Describe the results you expected:**

To not have this message come up saying this.

**Additional information you deem important (e.g. issue happens only occasionally):**

Does not get this message on InspIRCd 2.
customprefix is loaded
mIRC 7.59

**Output of `./bin/inspircd --version`:**
InspIRCd-3.6.0

**Comment by SadieCat** [comment]
This is a bug in mIRC.  It's sending a bunch of prefix mode changes without any values.

Please report it at https://forums.mirc.com/ubbthreads.php/forums/8/1/bug-reports so Khaled can fix it. Thanks.

**Comment by Casey952** [comment]
mIRC are saying this is an ircd bug:

> That is a bug by the ircd which rejects a command which has been accepted for years. The outbound command comes from the popups.ini command:
> 
> .Voice:/mode # +vvv $$1 $2 $3
> 
> Since only 1 nick is highlighted, the $2 and $3 are null. The 2nd and 3rd 'v' mode should be ignored in the absence of a 2nd and 3rd nick. To placate an ircd which doesn't accept a voice command which has been valid for decades, the line in popups.ini would need to be replaced with:
> 
> .Voice:/mode # + $+ $str(v,$0) $$1 $2 $3
> 
> This replacement changes the command to have the v replicated to match the number of nicks following it. You could even replace append $4 $5 $6 depending on how many mode commands can be stacked together at the networks you use.


mIRC debug:

```
server.name MODE #channel +vvv nick
<- @time=2020-05-02T23:53:53.126Z :server.name 696 nick #channel v * :You must specify a parameter for the voice mode. Syntax: <nick>.
```

**Comment by SadieCat** [comment]
It might have been accepted for years but its still invalid.
