### ISSUE TITLE
/inspircd/modules/m_mysql.so is not a module (no ABI symbol)

### ISSUE THREAD

**Issue by jcoelh0** [inspircd/inspircd#1778]
**Description**

I'm trying to connect a database to my inspIRCd servers and I'm not able.
I downloaded the dependencies and configured it in the docker file correctly but it says that this extra module is not a module. 

**Steps to reproduce the issue:**

1. Download the right dependencies. 
2. Run extra module mysql (just like in the docs) 
3. Run server

**Describe the results you received:**
Unable to load m_mysql.so: /inspircd/modules/m_mysql.so is not a module (no ABI symbol)

**Describe the results you expected:**
inspircd/modules/m_mysql.so loaded successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**
Docker file config:
RUN ./configure --enable-extras m_mysql.cpp
RUN apk add --no-cache mariadb-dev

**Output of `./bin/inspircd --version`:**
Version 3

**Comment by SadieCat** [comment]
As you're running it in Docker I wonder if this is an issue with musl's libdl being to spec but effectively broken.

**Comment by jcoelh0** [comment]
I executed this command:
`docker exec inspircd_inspircd1_1 nm -g /inspircd/modules/m_mysql.so | grep inspircd`
and it didn't output anything.

**Comment by SadieCat** [comment]
This should be fixed in insp3 git.
