### ISSUE TITLE
RPL_WHOREPLY (352) second param picks channel when one is not applicable

### ISSUE THREAD

**Issue by jesopo** [inspircd/inspircd#1781]
a `WHO <nick>` has a somewhat debated second parameter - some pick the first "visible" channel, some just give `*`. i think the latter is better and i think it's reasonable given irc2 does it too

servers that give `*`
- ircnet (**irc2**)
- irc.unrealircd.org (**unrealircd**)
- alphachat (**charybdis**)
- darwin (**oragono**)
- team-irc.irccloud.com (**prattle**)
- irc.w3.org (**ngircd**)

servers that give first visible channel
- freenode (**ircd-seven**)
- irc.tilde.chat (**inspircd**)
- undernet (**ircu**)
- rizon (**plexus**)

**Comment by SadieCat** [comment]
I've looked back in Git history and I can't really see why we do this.

@Adam- Why does Plexus do this? Do you know where this behaviour originated?

**Comment by SadieCat** [comment]
@jesopo Do you know if any clients depend on this behaviour?

**Comment by SadieCat** [comment]
Ah, i've found where its from. It seems to be from the WHOX spec.

https://github.com/quakenet/snircd/blob/master/doc/readme.who#L91

**Comment by SadieCat** [comment]
I think I'm going to leave this as-is.
