### ISSUE TITLE
Unable to get SSL functional

### ISSUE THREAD

**Issue by shir0tetsuo** [inspircd/inspircd#1783]
**Description**

Hello.

I am running a Clockworkpi Gameshell (armhf) trying to run inspircd from a source build. I've obtained certificates from letsencrypt, but for the life of me I cannot get this to work.

I have tried many different variations of configurations both with openSSL and with gnutls.

**Steps to reproduce the issue:**

1. Obtain SSL stuff from letsencrypt
2. Ensure the module was enabled before building inspircd.
3. Apply the following configuration to inspircd.conf:

`<bind
      address="*"
      port="6697"
      type="clients"
      ssl="openssl"`

      `# defer: When this is non-zero, connections will not be handed over to
      # the daemon from the operating system before data is ready.
      # In Linux, the value indicates the time period we'll wait for a
      # connection to come up with data. Don't set it too low!
      # In BSD the value is ignored; only zero and non-zero is possible.
      defer="0"

      # free: When this is enabled the listener will be created regardless of
      # whether the interface that provides the bind address is available. This
      # is useful for if you are starting InspIRCd on boot when the server may
      # not have brought the network interfaces up yet.
      free="no">`

    `<sslprofile name="Clients"
            provider="openssl"
            cafile="/cert/fullchain.pem"
            certfile="/cert/fullchain.pem"
            ciphers="DEFAULT"
            compression="no"
            dhfile="/cert/dhparam-2048.pem"
            ecdhcurve="prime256v1"
            hash="sha256"
            keyfile="/cert/privkey.pem"
            renegotiation="no"
            requestclientcert="yes"
            tlsv1="no"
            tlsv11="yes"
            tlsv12="yes">`

`<module name="ssl_openssl">`

**Describe the results you received:**

`Stopping InspIRCd (pid: 21631)...
InspIRCd Stopped.
InspIRCd - Internet Relay Chat Daemon
See /INFO for contributors & authors

InspIRCd Process ID: 22015

Loading core modules ....................
[*] Loading module:     m_ssl_openssl.so
InspIRCd is now running as 'shadownet.irc.shadowsword.tk'[444] with 1048576 max open sockets`

openssl s_client localhost:6697

`CONNECTED(00000003)
3069788176:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record         /ssl3_record.c:332:
   ---
    no peer certificate available
    ---
    No client certificate CA names sent
    ---
    SSL handshake has read 5 bytes and written 283 bytes
    Verification: OK
    ---
    New, (NONE), Cipher is (NONE)
    Secure Renegotiation IS NOT supported
    Compression: NONE
    Expansion: NONE
    No ALPN negotiated
    Early data was not sent
    Verify return code: 0 (ok)

**Describe the results you expected:**

Normal SSL enabled connection

**Additional information you deem important (e.g. issue happens only occasionally):**

In irssi, /connect -SSL localhost produces:

`18:15 -!- Irssi: warning SSL handshake failed: wrong version number
18:15 -!- Irssi: Connection lost to localhost`

**Output of `./bin/inspircd --version`:**
InspIRCd-3.6.0-fdf0e13dd

**Comment by SadieCat** [comment]
As [the ssl_openssl docs](https://docs.inspircd.org/3/modules/ssl_openssl/) say, <bind:ssl> MUST match the value you have specified in <sslprofile:name>. You have it set to "openssl" which only works if you have a legacy `<openssl>` tag defined.

If you have any more issues then please ask in irc.inspircd.org #inspircd. Thanks.

**Comment by shir0tetsuo** [comment]
Thankyou for your swift reply. Yes I see this now and I will attempt to implement this correction.
