### ISSUE TITLE
WebSocket connection failed: Error during WebSocket handshake: Unexpected response code: 503

### ISSUE THREAD

**Issue by pixelfoundry-dev** [inspircd/inspircd#1787]
**Description**

**Steps to reproduce the issue:**

1. create droplet centos 8 on digitalocean
2. install requirements: mariadb, postgress, sqlite
3. install inspircd 3.6.0 via rpm `rpm -i "https://github.com/inspircd/inspircd/releases/download/v3.6.0/inspircd-3.6.0-2.el8.x86_64.rpm"`
4. enable websocket port in `/etc/inspircd/inspicd.conf` => `<bind address="" port="7002" type="clients" hook="websocket">`
5. enable websocket module in `/etc/inspircd/modules.conf` => `<module name="websocket"><wsorigin allow="*">`
6. start inspircd:
```
InspIRCd - Internet Relay Chat Daemon
See /INFO for contributors & authors

InspIRCd Process ID: 17124

Loading core modules ....................
[*] Loading module:     m_websocket.so
InspIRCd is now running as 'penguin.omega.example.org'[422] with 262144 max open sockets
```
7. connect with kiwiirc webclient:
```
"startupOptions" : {
        "server": "xxx.xxx.xxx.xxx",
        "port": 7002,
        "tls": false,
        "direct": true,
        "channel": "#omega",
        "nick": ""
    }
```

**Describe the results you received:**
```
WebSocket connection to 'ws://xxx.xxx.xxx.xxx:7002/' failed: Error during WebSocket handshake: Unexpected response code: 503
```

**Describe the results you expected:**
connection to inspircd with success

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `./bin/inspircd --version`:**
3.6.0

**Comment by SadieCat** [comment]
You do not have the sha1 module loaded. This is required for using the websocket module.

**Comment by pixelfoundry-dev** [comment]
@SadieCat that was the problem, thank you very much
