### ISSUE TITLE
Loading / unloading monitor module does not update support for connected clients

### ISSUE THREAD

**Issue by kylef** [inspircd/inspircd#1788]
I noticed that the behaviour of loading and unloading modules which provide capabilities are updating clients with `cap-notify`. Although for modules which use isupport to indicate support are not updating clients when the respective module is loaded or unloaded for example with monitor.

When loading the monitor module (such as by adding `<module name="monitor">` to config and then rehashing inspircd, via `pkill -HUP inspircd`), no support lines informing connecting clients that monitor is available are sent. I was thinking I'd see something along the lines of:

```
:my.server 005 foo MONITOR=30 :are supported by this server
```

The client must reconnect to be aware that MONITOR has been supported.

---

The removal of the monitor module doesn't remove monitor from the support for existing clients. Such as via:

```
:my.server 005 foo -MONITOR :are supported by this server
```

A session can look like the following:

```
:my.server 001 foo :Welcome to the x IRC Network foo!~a@172.16.1.101
:my.server 002 foo :Your host is x, running version InspIRCd-3
:my.server 003 foo :This server was created 15:06:13 Jul 01 2020
:my.server 004 foo my.server InspIRCd-3 BHILRSWdhiorswx CFIJKLMOPQRSYabcefhijklmnopqrstvw :FIJLYabefhjkloqvw
:my.server 005 foo AWAYLEN=200 CASEMAPPING=rfc1459 CHANLIMIT=#:20 CHANMODES=IYbew,k,FJLfjl,CKMOPQRScimnprst CHANNELLEN=32 CHANTYPES=# ELIST=CMNTU EXCEPTS=e EXTBAN=,COQRSUcjm HOSTLEN=64 INVEX=I KEYLEN=32 :are supported by this server
:my.server 005 foo KICKLEN=255 LINELEN=512 MAXLIST=Ibew:100 MAXTARGETS=20 MODES=20 MONITOR=30 NAMESX NETWORK=x NICKLEN=16 PREFIX=(qaohv)~&@%+ SAFELIST STATUSMSG=~&@%+ TOPICLEN=307 :are supported by this server
:my.server 005 foo UHNAMES USERIP USERLEN=10 USERMODES=,,s,BHILRSWdhiorwx WATCH=30 WHOX :are supported by this server
:my.server 251 foo :There are 0 users and 0 invisible on 1 servers

...
MONITOR L
:my.server 733 foo :End of MONITOR list

// in background, an oper removes the module:
MONITOR L
:my.server 421 foo MONITOR :Unknown command
```

**Comment by SadieCat** [comment]
We do not support removing ISUPPORT values like this currently because although the spec does say that is a thing barely any clients actually support it and will instead parse it as a token called `-MONITOR`.

I have plans to change this for v4 although I wonder if there is anything we can do in the meanwhile to mitigate this.

**Comment by jwheare** [comment]
Is there anything actively harmful about a client interpreting it as a token -MONITOR. Seems like that’s basically a noop.

**Comment by SadieCat** [comment]
No, not really. Which is why I want to change this for v4.

**Comment by Techman** [comment]
What if the server force-sent the ISUPPORT data again on module load/unload?

**Comment by SadieCat** [comment]
Git master now sends an ISUPPORT diff. I'll add workarounds for the v3 branch where possible.
