### ISSUE TITLE
Missing error or echo-message for sending server mask messages

### ISSUE THREAD

**Issue by kylef** [inspircd/inspircd#1790]
I've tried out various cases with server mask PRIVMSG/NOTICE alongside echo-message and I do not seem to get any replies from InspIRCd 3.6:

```
C: PRIVMSG $ hi
C: PRIVMSG $*.example.com :hi
```

In the case where I shouldn't have permission to do so, there is no error. In the case it works there seems to be no echo-message (while echo-message is enabled).

unrealircd returns following error:

```
S: :irc1.unrealircd.org 481 foo :Permission Denied- You do not have the correct IRC operator privileges
```

Some others return 401, although it may be because they just don't support server mask messages.

oragono:

```
S: :oragono.test 401 kyle $ :No such nick
:oragono.test 401 kyle $*.example.com :No such nick
```

ircd-seven:

```
S: :adams.freenode.net 401 kyle $*.example.com :No such nick/channel
```

**Comment by SadieCat** [comment]
>Some others return 401, although it may be because they just don't support server mask messages.

I don't know about oragono but charybdis' mass-messaging prefix is `$$` not `$`.

I'll look into this now.
