### ISSUE TITLE
m_openssl 'renegotiation' false positive breaks server linking with OpenSSL ≤ 1.1.1a and TLSv1.3

### ISSUE THREAD

**Issue by digitalcircuit** [inspircd/inspircd#1791]
**Description**

On Ubuntu 18.04's version of OpenSSL, InspIRCd incorrectly detects TLSv1.3's normal negotiation flow as an attempted renegotiation, breaking server-to-server linking with the default configuration.

Specifically, the [`ssl_openssl` module's check for `SSL_CB_HANDSHAKE_START`](https://github.com/inspircd/inspircd/blob/6d3e316234f47468cd15bc9bdff66e2a76fa4cd6/src/modules/extra/m_ssl_openssl.cpp#L672-L683 ) gets triggered during TLSv1.3 negotiation on a very narrow range of OpenSSL versions - [1.1.1 and 1.1.1a, but not after 1.1.1b - OpenSSL fixed this fairly quickly](https://github.com/openssl/openssl/issues/8069 ) in [an upstream commit on January 22nd, 2019](https://github.com/openssl/openssl/commit/4af5836b55442f31795eff6c8c81ea7a1b8cf94b ).

Unfortunately, Ubuntu 18.04 LTS, which is still supported for three more years, has the **unfixed** version of OpenSSL, as [confirmed by downloading the source and checking the changelog and affected code itself](https://packages.ubuntu.com/source/bionic-updates/openssl ) - the following is NOT applied:

`openssl-1.1.1/ssl/statem/statem.c`
```diff
-        if (cb != NULL)
-            cb(s, SSL_CB_HANDSHAKE_START, 1);
+        if (cb != NULL) {
+            if (SSL_IS_FIRST_HANDSHAKE(s) || !SSL_IS_TLS13(s))
+                cb(s, SSL_CB_HANDSHAKE_START, 1);
+        }
```

**Steps to reproduce the issue:**

1.  Set up two InspIRCd nodes on Ubuntu 18.04 LTS
2.  Make use of the default `<sslprofile>` connection via `ssl_openssl`
3.  Ensure TLSv1.3 is *not* disabled (currently there's no way to disable it in InspIRCd)
4.  Attempt to link the two servers together

**Describe the results you received:**

Error message of `Renegotiation is not allowed`.

**Describe the results you expected:**

InspIRCd should allow linking, disregarding the `SSL_CB_HANDSHAKE_START` messages when TLSv1.3 is in use and OpenSSL is not fixed.

**Additional information you deem important (e.g. issue happens only occasionally):**

I'm not sure of a reliable way to determine at compile-time whether or not OpenSSL will behave badly.

This affects many projects using OpenSSL, not just InspIRCd:
* [nginx wound up removing the `SSL_CB_HANDSHAKE_START` detection](https://forum.nginx.org/read.php?29,281348,281348 )
* node.js and haproxy were impacted as well, as per the OpenSSL bug report

Workaround: disable the `renegotiation` blocking by setting `renegotiation="yes"` in an `<sslprofile>`.

**Output of `./bin/inspircd --version`:**

```
InspIRCd version: 3.7.0
```

**Comment by SadieCat** [comment]
You can work around this already by using a custom SSL profile for linking that allows renegotiation.

https://docs.inspircd.org/3/modules/ssl_openssl/#ltsslprofilegt

If you have defined an SSL profile tag the `<openssl>` tag will need to be migrated to a SSL profile. You can do this by replacing `<openssl ` with `<sslprofile name="examplenamehere" provider="openssl" ` and then replacing all cases where `<bind:ssl>` and `<link:ssl>` are set to `openssl` with `examplenamehere`.

**Comment by github-sys-admin** [comment]
having some interesting problems with x448 with both openssl and gnutls `OpenSSL 1.1.1n  15 Mar 2022
` I can at least get it to kinda work with openssl, still stuck with dhparams so I think that's why it's married to this cipher `TLSv1.3-TLS_AES_256_GCM_SHA384` but whatever the case I'd like to use ecdhe-ecdsa-chacha20-poly1305 because it's cool and I apparently cant which sucks. 

something else potentially kinda dangerous is that if I switch it to use gnutls it recognizes the certificate as prime256v1 :S and it will also negotiate the `TLS1.3-ECDHE-RSA-AES-256-GCM-AEAD` cipher 

should hash="sha512" work? I haven't figured that out yet I don't think it does though and that module is loaded.

**Comment by github-sys-admin** [comment]
but yeah thats what i'll get 
```
19:14:08  ▬▬ │    - subject `EMAIL=no-reply@clandestine.network,CN=am.nl.eu.clandestine.network,OU=N/A,O=clandestine,L=N/A,ST=N/A,C=NA', issuer
             │ `EMAIL=no-reply@clandestine.network,CN=59e57a656595,OU=N/A,O=clandestine,L=N/A,ST=N/A,C=NA', serial 0x01, EdDSA (Ed448) key 456 bits, signed using
             │ EdDSA-Ed448, activated `2022-05-13 00:09:51 UTC', expires `2032-05-10 00:09:51 UTC', pin-sha256="H1NCaSpTZml+5DNHsn3TZP39Cv3gPBd0Zm+h6RhEec0="
19:14:08  ▬▬ │  - certificate[2] info:
19:14:08  ▬▬ │    - subject `EMAIL=no-reply@clandestine.network,CN=59e57a656595,OU=N/A,O=clandestine,L=N/A,ST=N/A,C=NA', issuer
             │ `EMAIL=no-reply@clandestine.network,CN=59e57a656595,OU=N/A,O=clandestine,L=N/A,ST=N/A,C=NA', serial 0x38d372804c55ab215fa7fd18ac7534e20e809942, EdDSA (Ed448)
             │ key 456 bits, signed using EdDSA-Ed448, activated `2022-05-13 00:09:04 UTC', expires `2032-05-10 00:09:04 UTC',
             │ pin-sha256="GIuDZjixUt0VixnlKz9aj6gyDvgYYP71ul4D3WRZ8ZQ="
19:14:08  ▬▬ │ gnutls: peer's certificate is trusted
...
19:14:13  ▬▬ │ am.nl.eu.clandestine.network: *** You are connected to am.nl.eu.clandestine.network using TLS (SSL) cipher 'TLSv1.3-TLS_AES_256_GCM_SHA384'
```

**Comment by github-sys-admin** [comment]
with gnutls: (and weechat instead of irssi)

I see, so the client (other client) was detecting it wrong as prime256v1 I notice with weechat though its only sending the server cert and not the full chain: 

```
19:17:53  ▬▬ │ gnutls: receiving 1 certificate
19:17:53  ▬▬ │  - certificate[1] info:
19:17:53  ▬▬ │    - subject `EMAIL=no-reply@clandestine.network,CN=am.nl.eu.clandestine.network,OU=N/A,O=clandestine,L=N/A,ST=N/A,C=NA', issuer
             │ `EMAIL=no-reply@clandestine.network,CN=59e57a656595,OU=N/A,O=clandestine,L=N/A,ST=N/A,C=NA', serial 0x01, EdDSA (Ed448) key 456 bits, signed using
             │ EdDSA-Ed448, activated `2022-05-13 00:09:51 UTC', expires `2032-05-10 00:09:51 UTC', pin-sha256="H1NCaSpTZml+5DNHsn3TZP39Cv3gPBd0Zm+h6RhEec0="
19:17:53  ▬▬ │ gnutls: peer's certificate is trusted
...
19:17:58  ▬▬ │ am.nl.eu.clandestine.network: *** You are connected to am.nl.eu.clandestine.network using TLS (SSL) cipher 'TLS1.3-ECDHE-RSA-AES-256-GCM-AEAD'
```



I actually managed to get gnutls to work right (I think) using this cipher string 
```19:42:35  ▬▬ │ am.nl.eu.clandestine.network: *** You are connected to am.nl.eu.clandestine.network using TLS (SSL) cipher 'TLS1.3-ECDHE-RSA-CHACHA20-POLY1305-AEAD'```
```

19:42:35  ▬▬ │ am.nl.eu.clandestine.network: *** You are connected to am.nl.eu.clandestine.network using TLS (SSL) cipher 'TLS1.3-ECDHE-RSA-CHACHA20-POLY1305-AEAD'

```

**Comment by SadieCat** [comment]
Please open a new issue instead of adding unrelated things to other peoples issues.
