### ISSUE TITLE
"Cannot assign requested address"

### ISSUE THREAD

**Issue by davekimble2** [inspircd/inspircd#1794]
**Description**
On Ubuntu-20.04 Inspircd-2.0.25 doesn't load - "Cannot assign requested address"

**Steps to reproduce the issue:**

1.  $ sudo apt install inspircd
2.  $ ~/inspircd-2.0.25/run/inspircd start
3.

**Describe the results you received:**
Inspire Internet Relay Chat Server, compiled on Aug  5 2020 at 08:23:46
(C) InspIRCd Development Team.

Developers:
	Brain, FrostyCoolSlug, w00t, Om, Special, peavey
	aquanight, psychon, dz, danieldg, jackmcbarn
	Attila

Others:			See /INFO Output
InspIRCd Process ID: 239312

Loading core commands.....................................................

WARNING: Not all your client ports could be bound -- 
starting anyway with 0 of 1 client ports bound.

The following port(s) failed to bind:

1.	Address: xxx.181.86.189:6697 	Reason: Cannot assign requested address

Hint: Try using a public IP instead of blank or *
InspIRCd is now running as 'irc.davekimble.net'[1DK] with 1024 max open sockets

**Describe the results you expected:**
inspircd running OK

**Additional information you deem important (e.g. issue happens only occasionally):**
the port being used, as reported by gufw, is 38536 and changes each time the server is started.
Port 6697 is NOT being used by anything.
Starting it as root doesn't make any difference.
I don't know why a server needs to know what its public IP address is, but it is not blank or *.
**Output of `./bin/inspircd --version`:**
bash: ./bin/inspircd: No such file or directory

**Comment by genius3000** [comment]
As this is for a fairly old version of the 2.0 branch which itself will be EOL soon enough (dist packages are usually quite old) and this is a support request, please do as the issue template stated:
```
The GitHub issue tracker is for bug reports ONLY. General support can be found at the following locations:

Docs: https://docs.inspircd.org
IRC: irc.inspircd.org #inspircd
```

To help you out a bit first, the error you're receiving means that InspIRCd **cannot** bind to that requested IP address/port. Ensure nothing else is currently listening on that port **and** ensure the address you specified is accessible by the system (`ss -tln | grep 6697` and `ip a`). You could change the specified address to blank or '*' to bind to all available addresses on the specified ports.

I'd also recommend ditching the apt installed version and installing from our GH Releases, the latest 3.x version.
Please use IRC for any further support, thanks.
