### ISSUE TITLE
WEBSOCK don't work

### ISSUE THREAD

**Issue by dumber-Chatteurs** [inspircd/inspircd#1795]
i'm on 3.7 inspircd version

when i want configure websock it's don't work

modules.conf
enable : 

<module name="sha1"> 
<module name="websocket">
<wsorigin allow="*">

inspirc.conf
<bind address="" port="7002" type="clients" hook="websocket">

in kiwi

 "startupOptions" : {
                "server": "irc.chatteurs.fr",
                "port": 7002,
                "tls": true, 
                "direct":true,
                "channel": "#Hall",
                "nick": "kiwi?",
}

have this error

Firefox ne peut établir de connexion avec le serveur à l’adresse wss://irc.chatteurs.fr:7002/.

(Firefox can't connext with wss://..)

i'm search many time, i'm testing many config but never work

**Comment by SadieCat** [comment]
I'm guessing you've misconfigured your SSL listener. Make sure that you have hook="websocket" and ssl="the name of a ssl profile" in your bind tag

This is a bug tracker not a support system. If you have any more issues then please ask in irc.inspircd.org #inspircd. Thanks.
