### ISSUE TITLE
SANICK sends error messages to the target

### ISSUE THREAD

**Issue by AndrioCelos** [inspircd/inspircd#1797]
**Description**

When the `SANICK` command is used to change another user's nickname, and the nickname change can't be completed for certain reasons, error messages such as `ERR_NICKNAMEINUSE` are sent to the target rather than the user initiating the command.

This only happens if the following line is reached, and not for all error conditions. For example, specifying an invalid nickname does not produce this issue.

https://github.com/inspircd/inspircd/blob/5cb71b751a62c4aeadced5311c84d92dfe62db20/src/modules/m_sanick.cpp#L72

**Steps to reproduce the issue:**

1. Connect two clients. Client A must have access to `SANICK`.
2. From client A, attempt to change client B's nickname to client A's nickname.

**Describe the results you received:**

Client B received: `@time=2020-09-22T04:53:53.000Z :Andrea-PC.test.andriocelos.net 433 Corvus Andrio :Nickname is already in use.`
Client A received: `@time=2020-09-22T04:53:53.000Z :Andrea-PC.test.andriocelos.net NOTICE Andrio :*** ANNOUNCEMENT: Andrio failed SANICK (from Corvus to Andrio)`

**Describe the results you expected:**

Client B should not receive any messages. Client A may receive `ERR_NICKNAMEINUSE`. However, it may need to be wrapped in a `NOTICE` to avoid confusing client software.

**Output of `./bin/inspircd --version`:**

```
InspIRCd - Internet Relay Chat Daemon
See /INFO for contributors & authors


InspIRCd-3.5.0
```

**Comment by slingamn** [comment]
We're trying to figure out the correct behavior here (https://github.com/oragono/oragono/issues/1277). Currently, we send exactly the same error responses to SANICK that we would to NICK, e.g.,

```
@label=nick NICK root
@label=nick;time=2020-09-22T11:07:52.597Z :oragono.test ACK
@label=sanick SANICK baz qux
@time=2020-09-22T11:08:42.517Z;label=sanick :oragono.test 433 root qux :Nickname is already in use
```

However, we got a report that this led to incorrect client behavior, because a client assumed that `433 ERR_NICKNAMEINUSE` is only sent in response to `NICK`. I'm not totally convinced by this argument but I thought I'd ask around to see what the best response is.

**Comment by slingamn** [comment]
Following a suggestion from @jwheare, I drafted something that uses standard replies for this:

```
SANICK baz root
:oragono.test FAIL SANICK NICKNAME_IN_USE root :Nickname is already in use
SANICK baz netcat
:oragono.test FAIL SANICK NICKNAME_RESERVED netcat :Nickname is reserved by a different account
SANICK baz :
:oragono.test FAIL SANICK NICKNAME_INVALID * :No nickname given
SANICK baz *
:oragono.test FAIL SANICK NICKNAME_INVALID * :Erroneous nickname
SANICK baz ! 
:oragono.test FAIL SANICK NICKNAME_INVALID ! :Erroneous nickname
SANICK baz baz
:oragono.test NOTE SANICK NOOP baz :Client already had the desired nickname
SANICK netcat qux
:oragono.test FAIL SANICK UNKNOWN_ERROR qux :You must use your account name as your nickname
SANICK baz qux
:baz!~user@localhost NICK qux
```

(The `UNKNOWN_ERROR` is an implementation-specific thing we do.)

Thoughts?

**Comment by jwheare** [comment]
Don't know if I would *recommend* this as such, it's an option but probably not well supported by clients. Not really many good options other than NOTICE or UNKNOWN_ERROR for non-standard stuff like this.

**Comment by SadieCat** [comment]
We have a vendor cap to enable opting-in to standard replies (inspircd.org/standard-replies) instead of notices so this would be an okay idea.

**Comment by slingamn** [comment]
Cool! Yeah, let me know if you have any feedback on those verbs / codes / parameters.

**Comment by slingamn** [comment]
One more for completeness (replacing an earlier use of `401 ERR_NOSUCHNICK`, so that all error responses are using standard replies):

```
SANICK bar qux
:oragono.test FAIL SANICK NO_SUCH_NICKNAME bar :No such nick
```

**Comment by SadieCat** [comment]
It seems like fixing this will require some breaking changes. I added a workaround for this for v3.
