### ISSUE TITLE
/clearcache missing in inspircdv3

### ISSUE THREAD

**Issue by chotaire** [inspircd/inspircd#1801]
**/clearcache missing in inspircdv3**

The command /clearcache seems to be missing in inspircdv3 and I couldn't find an alternative to clear DNS cache. Bringing back this command would be very useful for obvious reasons, since DNS cache keeps lasting forever (like a day?) and seems to ignore DNS zone TTLS from what was my experience with inspircd v2.

**Comment by SadieCat** [comment]
In v3 cached DNS results are expired after five minutes (or the TTL if that is shorter). The DNS cache is also cleared whenever the server is rehashed. Is this not good enough?

**Comment by chotaire** [comment]
Yep, both the new behaviour plus /rehash resetting DNS cache is more than good enough. I am closing this ticket because this does not need to be improved. @SadieCat maybe add a line to documentation or config samples so that people coming from v2 know what's up?
