### ISSUE TITLE
Not registered

### ISSUE THREAD

**Issue by KiteFlyKid** [inspircd/inspircd#1805]
**Description**

Hello! 
My inspired server is deployed in Ubuntu 18.04. When I send command （JOIN,PRIVMSG）to the irc server. It turns out to be "not registered" 

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/45324156/95760185-4a5f5700-0cdd-11eb-9b9b-75c0793a4f47.png)

**Describe the results you expected:**
So what should I do to let my command be accepted

**Additional information you deem important (e.g. issue happens only occasionally):**
I install INSOIRCD by apt get and I don't know the version exactly

**Comment by SadieCat** [comment]
You can't send JOIN/PRIVMSG until you have fully connected to a server.

If you have any more issues then please ask in irc.inspircd.org #inspircd. Thanks.
