### ISSUE TITLE
SSL23_GET_SERVER_HELLO:unknown protocol

### ISSUE THREAD

**Issue by rivierejordan** [inspircd/inspircd#1807]
Hi,

I configure all my SSL file with InspiRCD but I get this error: 
`Connection failed ((336031996) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol`

Here is my configuration
```

<bind
      address=""
      port="6697"
      type="clients"
      ssl="openssl"
      defer="0"
      free="no">

<sslprofile name="Clients"
            provider="openssl"
            certfile="fullchain.pem"
            crlfile=""
            ciphers="DEFAULT"
            compression="no"
            dhfile="ssl-dhparams.pem"
            ecdhcurve="prime256v1"
            hash="sha256"
            keyfile="privkey.pem"
            renegotiation="no"
            requestclientcert="yes"
            tlsv1="no"
            tlsv11="no"
            tlsv12="yes">

```

**Comment by SadieCat** [comment]
You have <sslprofile:name> set to "Clients" but have <bind:ssl> set to "openssl". You should use the name of the SSL profile in the bind tag if using an SSL profile.

If you have any more issues then please ask in irc.inspircd.org #inspircd. Thanks.
