### ISSUE TITLE
add a text var to hidebans similar to hidekills

### ISSUE THREAD

**Issue by DarkTexas** [inspircd/inspircd#1832]
Currently it's possible to configure the inspircd.conf with the hidekills="" feature, which hides the /kill message from other users and lets the user replace the kill message with a static text. 

There should be a option for bans (hidebans) as well to have a pre-defined text so the user doesn't have to modify the core module xline.so

**Comment by SadieCat** [comment]
This was implemented in f8614ea98581fb303abc36c792be6ba60b3c8b42.
