### ISSUE TITLE
UDP port stays bound when core_dns module unloaded

### ISSUE THREAD

**Issue by clinew** [inspircd/inspircd#1838]
A system audit shows that InspIRCd listens on a random UDP port.  As I recall from discussing this last year, this port is used for DNS and could be changed in v3 by unloading the `core_dns` module.  I unloaded the module, but the port remains bound.

**Steps to reproduce the issue:**

1. Find the bound UDP port with `netstat -lpn`
2. Unload the `core_dns` module with (from `irssi`) `/quote unloadmodule core_dns`
3. Find that the UDP port is still bound

**Describe the results you received:**
UDP port remained bound despite unloading of module (which is to my knowledge) using it.

**Describe the results you expected:**
UDP port would be unbound when the module is unloaded.

**Additional information you deem important (e.g. issue happens only occasionally):**
None.

**Output of `./bin/inspircd --version`:**
InspIRCd-3.8.1

**Comment by SadieCat** [comment]
Fixed in da7cba6.
