### ISSUE TITLE
Allow unloading of core modules at start-up

### ISSUE THREAD

**Issue by clinew** [inspircd/inspircd#1839]
Description: Allow unloading of core modules at start-up.  Or, really, a blacklist for core modules which will not be loaded at start-up.

Problem: I will forget to remove the `core_dns` module if I have to manually do so after every program execution.

Rationale: Allows administrators to maintain a consistent server configuration across multiple executions without manual intervention.

**Comment by SadieCat** [comment]
I'm not really interested in allowing this. Core modules implement important functionality and removing them may cause serious issues with InspIRCd ability to run. This is why `<security:allowcoreunload>` defaults to `no` in v3 and support for unloading core modules has been removed entirely in master.

What issue are you encountering that requires you to unload core_dns?

**Comment by clinew** [comment]
I don't need any DNS functionality (ex: reverse-DNS look-ups) and want to keep all unneeded ports closed (the `core_dns` module listens to a random high-numbered UDP port).

**Comment by SadieCat** [comment]
It's not actually harmful that it does that. You can just use a firewall if you're that worried.

**Comment by SadieCat** [comment]
I just pushed a commit that allows disabling DNS lookups entirely. Can you see if it solves your issue?

**Comment by clinew** [comment]
Works for me, thank you!
