### ISSUE TITLE
Missing header files in sources

### ISSUE THREAD

**Issue by mdziczkowski** [inspircd/inspircd#1840]
### Needed Informations:

**OS**: Linux (lubuntu, version: 20.10)
**InspIRCd version**: 3.8.1

### Steps to reproduce the issue:

0. set the CFLAGS and CPPFLAGS to: `-O3`
1. download and unpack the sources (I had choosen the zip file)
2. run: `configure`
3. run:  `make`
4. see error

### Describe the results you received:

**[NOTE]:** _All path's were truncated and replaced by (without quota marks): "PATH" for security reasons_

`Execution of 'pg_config --includedir' succeeded: /usr/include/postgresql`

`Execution of 'pg_config --libdir' succeeded: /usr/lib/x86_64-linux-gnu`

	`BUILD:		modules/m_pgsql.cpp`

`[PATH]/inspircd/src/modules/m_pgsql.cpp:42:10: fatal error: libpq-fe.h: No such file or directory`

  ` 42 | #include <libpq-fe.h>`

  `    |          ^~~~~~~~~~~~`

`compilation terminated.`

`make[1]: *** [real.mk:736: modules/m_pgsql.so] Error 1`

`make[1]: *** Waiting for unfinished jobs....`

`make: *** [GNUmakefile:172: target] Error 2`

### Describe the results you expected:

Sucess of `make`

**Comment by Robby-** [comment]
It seems that your system does not have the `libpq-dev` package installed, which is required for compiling this module.

**Comment by SadieCat** [comment]
As @Robby- said this is a system package header not an InspIRCd header.

**Comment by elazarza** [comment]
sudo apt-get install libpq-dev
fixed that for me
