### ISSUE TITLE
m_connectban: Add allow list specifically for this module

### ISSUE THREAD

**Issue by Kufat** [inspircd/inspircd#1841]
**Description**

Add config options for m_connectban to allow specified CIDR ranges to be exempt from normal connectban limits.

**Why this would be useful**

Whenever IRCCloud goes down for a minute or two and comes back up, my server is flooded with reconnects. Then IRCCloud's IP gets z-lined. Then I manually remove the z-line...and we get flooded with reconnects again.

I could E-line IRCCloud, but that would be overly broad and would allow individual users whose uid/sids have been G-lined to get on the server. Temporarily E-lining an IP manually when this happens works, but requires that an oper happen to be paying attention at the time (or that an unaffected user is able to get the attention of an oper.)

This would be a narrowly-tailored exclusion that only applies to m_connectban, which would avoid any side effects.

**Comment by Robby-** [comment]
Sounds reasonable, however, maybe this is best implemented as a new option to the `<connect>` tags, so these ranges can be exempted in that way and this option can then also be included by default in `conf/providers/irccloud.conf.example`?

For example `<connect:connectbanexempt="yes">` which defaults to no if this is not set.

**Comment by SadieCat** [comment]
For IRCCloud I'd recommend banning their IPv4 ranges and only allowing IPv6 connections as IPv6 IRCCloud users have their own IPv6.

**Comment by SadieCat** [comment]
I just pushed a commit. Does this solve your problem?

**Comment by Kufat** [comment]
@SadieCat It should! Thank you very much.

You pushed that commit while I was writing an answer to your suggestion about IPv6. So I'll give you the short version: 

We've been seeing some connectivity issues that've been causing IRCCloud to lose all IPv6 connections to our network at times. Since we're hosted on AWS, the problems affect users across different servers on different continents, and non-IRCCloud IPv6 users are unaffected when we see these mass connection drops, I'm inclined to think that the problem is on (or at least closer to) IRCCloud's end. So, if we blocked their v4 IPs we'd leave our IRCCloud users with no way to connect when these connectivity blips happened.
