### ISSUE TITLE
OJOIN prefix issue

### ISSUE THREAD

**Issue by gokturkyilmaz** [inspircd/inspircd#1842]
Not sure if should I report this or not. But, I have some words about the OJOIN module.

When I removed the prefix '**!**' from: `<ojoin prefix = "!" notice = "yes" op = "yes">` I leaved it empty. Because we do not use any prefix characters.

When I OJOIN'ed a channel, it gives me **@**, that's perfect! But when I leave the channel, others can still see '**!**' front on my nickname. Like;

[10:32] * !Gokturk (Gokturk@staff.hybridirc.com) has left #testchan

And when I reloaded the OJOIN module without any changes. It gives me automatically '**!**' back.

I am using InspIRCd-3.6.0.

Thanks.

**Comment by SadieCat** [comment]
Those users need to run `/VERSION` to update their clients cache of user prefixes.
