### ISSUE TITLE
Messages from SSL client are not always handled when available (inspircd v2)

### ISSUE THREAD

**Issue by dloser** [inspircd/inspircd#1848]
**Description**

In certain cases messages from an SSL client are not handled until a later message is send by the client. Multiple message can be "buffered" this way and once in this state there is no way to have all sent messages processed.

Seen with inspircd version 2.0.27 from Debian buster, using epoll and gnutls.

I'm aware that "v2 is dead" and don't expect a fix there, but I figured it could be useful to have some reference to this issue somewhere.

**Cause of issue**

Events for the connection are edge triggered (`EPOLLET`) and `m_ssl_gnutls` uses `gnutls_record_recv` which will only read a single SSL packet (even if multiple are available). So the following sequence can happen:

1. Multiple packets arrive before the next call to `epoll_wait`.
2. `epoll_wait` is called and returns an event.
3. `gnutls_record_recv` is used which reads the first packet only.
4. `gnutls_record_check_pending` is checked, which returns 0 because it only returns >0 when there is more data left from the first packet, not when there are other packets available.
5. Next calls to `epoll_wait` do not return an event because `EPOLLET` is set and no new packets have arrived since the last call. (Without `EPOLLET` it would return an event as long as there is data available.)
6. A new packet arrives.
7. `epoll_wait` is called and returns an event.
8. Only the second packet from step 1 is read.
9. Etc.

The actual bug seems to be that `EPOLLET` is set. This happens because `m_ssl_gnutls` sets the event mask with `FD_WANT_POLL_READ` (which would prevent `EPOLLET`) _before_ the socket has been added to the epoll interest list. After that the socket is added, but with `EPOLLET` set, which will never be removed.

This has been fixed in inspircd v3 in commit fb7acf3, which adds the socket before triggering `OnAccept` (where `m_ssl_gnutls` sets `FD_WANT_POLL_READ`).

**Steps to reproduce the issue:**

1. Connect to server using SSL.
2. Send `USER` and `NICK` commands.
3. Wait for `PING` from server.
4. Send `PONG`.
5. Wait for `001` response from server.
6. In quick succession send multiple message, but as separate writes/packets. For example: `write("MODE nick +B\r\n"); write("JOIN #channel\r\n");` and not `write("MODE nick +B\r\nJOIN #channel\r\n");`
7. A second later send another message. For example a `QUIT`.

**Describe the results you received:**

After step 6 you get all expected messages from when you connect including a response to the `MODE` command, but no `JOIN` on the channel.

After step 7, channel is joined, but `QUIT` is not processed until yet another message is sent.

**Describe the results you expected:**

After step 6 you get all expected messages from when you connect as well as responses to both the `MODE` and `JOIN` commands.

After step 7 the server processes the `QUIT` command and terminates the connection.

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue can be quite hard to reproduce. I've only seen it "randomly" for a client that is connecting locally to the server (i.e. via loopback interface).

**Output of `./bin/inspircd --version`:**

InspIRCd-2.0.27 r0

**Comment by Adam-** [comment]
Although 1.2 is EOL, I would note that if you do have to use it for some reason, you may be able to work around this by using the poll or select socket engines, which do not support edge-triggered notifications.
