### ISSUE TITLE
InspIRCd silently ignores invalid +k keys

### ISSUE THREAD

**Issue by ProgVal** [inspircd/inspircd#1850]
**Description**

if a client sends a message "MODE #chan +k :passphrase with spaces" (which is illegal per RFC2812), InspIRCd ignores it entirely.

The RFC doesn't say what to do with it, but other implementations I have checked either send an error or truncate/change it:

* Oragono sends ERR_INVALIDMODEPARAM ([with an invalid syntax](https://github.com/oragono/oragono/issues/1563) though)
* Charybdis drops spaces
* Unreal truncates on the first space

**Steps to reproduce the issue:**

1. `JOIN #chan`
2. `MODE #chan +k :passphrase with spaces`

**Describe the results you received:**

Nothing happens

**Describe the results you expected:**

Something should happen, eg. ERR_INVALIDMODEPARAM

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `./bin/inspircd --version`:**

```
InspIRCd - Internet Relay Chat Daemon
See /INFO for contributors & authors


InspIRCd-3.8.1
```

**Comment by SadieCat** [comment]
This is because IsModeParamValid returns false for mode parameters that begin with : or that contain a space.

I'll make it send an error instead.
