### ISSUE TITLE
v3.9 install problem

### ISSUE THREAD

**Issue by TuSuNaMi** [inspircd/inspircd#1852]
Hello,

I given error install v3.9 to my centos 6.10 (32bit) following error. How can I solve this? thanks.

[user@irc inspircd-3.9.0]$ ./configure
Bareword found where operator expected at /home/user/inspircd-3.9.0/make/configure.pm line 240, near "s/(?:^m_|\.cpp$)//gr"
Compilation failed in require at ./configure line 46.
BEGIN failed--compilation aborted at ./configure line 46.

**Comment by SadieCat** [comment]
Can you tell us the output of `perl --version`?

**Comment by TuSuNaMi** [comment]
Sure here;

This is perl, v5.10.1 (*) built for i386-linux-thread-multi
Copyright 1987-2009, Larry Wall

**Comment by SadieCat** [comment]
I guess we're using some features from a Perl version which is too new. Try making this change to `make/configure.pm`:

```diff
-        return $module =~ s/(?:^m_|\.cpp$)//gr;
+        $module =~ s/(?:^m_|\.cpp$)//g;
+        return $module;
```

Please consider updating your system though. That version of CentOS is EOL and is not getting any more security updates so we'll be dropping support for it in a future release.

**Comment by TuSuNaMi** [comment]
thanks, it worked. my special requirements needs old centos version. long time i never think change this.

last question i have old 2.0.x config how can i convert to 3.x version? thank you

**Comment by thesamesam** [comment]
https://docs.inspircd.org/3/breaking-changes/ may help
