### ISSUE TITLE
WHOX always uses fuzzy match visibility logic

### ISSUE THREAD

**Issue by ilbelkyr** [inspircd/inspircd#1853]
**Description**

When using `WHO nick` to get the WHO output for a given individual nick, this will succeed even if you are normally unable to see the target user; this is on purpose AFAIK, as you could use `WHOIS` or similar instead anyway.

When using any form of WHOX (such as `WHO nick %na`), it will require you to be able to see the target user to get any output, even if just a single nick was specified.

https://github.com/inspircd/inspircd/blob/85a4184ab473c407fb07cc46d73de70d2897157e/src/coremods/core_who.cpp#L80-L81

This code unconditionally sets the `fuzzy_match` flag if there was more than one parameter given, presumably since WHOX allows for flags that affect matching (e.g. `WHO something a` will look up people by account), thus making it not a simple case of looking up info by nick. This is also done if there's just a list of fields and no such flags specified, though.

**Steps to reproduce the issue:**

1. Connect as an unprivileged user.
2. Assume a second connection (nick `test` in this example) not sharing any channels with you; user mode `+i` is set
3. Run `WHO test`
4. Run `WHO test %uhn`

**Describe the results you received:**

`WHO test` returns normal output; `WHO test %uhn` does not give a result (beyond the end-of-list numeric)

**Describe the results you expected:**

Both `WHO test` and `WHO test %uhn` seem like they should return output for the user on the nick `test`.

**InspIRCd version:**

Can't get it via the command line as requested, but `VERSION` says `InspIRCd-3.8.1-e984d6435`

**Comment by SadieCat** [comment]
Fixed in 85d94c6.
