### ISSUE TITLE
maxmind false/positive?

### ISSUE THREAD

**Issue by TuSuNaMi** [inspircd/inspircd#1854]
Hello,

I use v3.9 version at ubuntu 64 bit machine and the free maxmind registration on the connect I give following error (debug log); 

_Sat Mar 06 2021 11:24:04 CONNECTCLASS: The unnamed-5 connect class is suitable for 97KAAAAAB (97KAAAAAB!97KAAAAAB@185.114.xx.xx)
Sat Mar 06 2021 11:24:04 USERS: QuitUser: 97KAAAAAB=97KAAAAAB '*** ATTENTION!!! *** Proxy Suspect Please Contact Us [admin at sohbetodam.org] Thank you'
Sat Mar 06 2021 11:24:04 USEROUTPUT: C[97KAAAAAB] O ERROR :Closing link: (97KAAAAAB@185.114.xx.xx) [*** ATTENTION!!! *** Proxy Suspect Please Contact Us [admin at sohbetodam.org] Thank you]_

my config here;

`<connect deny="*" country="SA,BH,CH,IN,PK,BR,AU" reason="*** ATTENTION!!! *** Proxy Suspect Please Contact Us [admin at sohbetodam.org] Thank you">`
This IP not include this countries i checked with mmdblookup 

`<module` name="m_cgiirc.so">
<cgiirc opernotice="no">
<cgihost type="webirc" password="xxxxxxxx!" `mask="185.114.xx.xx">`

**Comment by SadieCat** [comment]
Are you sure the database hadn't been updated on disk inbetween the server loading it and you checking mmdblookup? We don't do anything special to the info we just pull it directly from the lookup API.

**Comment by SadieCat** [comment]
I'd guess you don't actually have the geoclass module loaded?

Also, `<connect:country>` is space delimited not comma delimited.

**Comment by TuSuNaMi** [comment]
yes I'm sure. can i solve this problem with e-line? 
yes i tried both with comma and without comma result is same.

**Comment by SadieCat** [comment]
geo_maxmind != geoclass

They're two different modules and both are required.

**Comment by TuSuNaMi** [comment]
hello yes its solved with loading geoclass module thank you.
