### ISSUE TITLE
'stdout' and 'stderr' as a <log> method

### ISSUE THREAD

**Issue by rburchell** [inspircd/inspircd#1860]
**Description**

In some circumstances, for example, when running as a part of some larger infrastructure with centralized logging, or in a container, or as a systemd service, or perhaps where the filesystem is immutable for some reason (you get the idea), it can be useful to have logging *not* be forced to be directed to a file.

Unfortunately, it looks like the only way this is possible right now is via `--debug`, which is of course not really what we want.

I think that allowing a <log> tag to use method="stdout/stderr" would be a pretty reasonable solution for this problem. I haven't thought about this too deeply, but I'm thinking it could work something like this:

```
// when loading configuration...
if (nofork)
    if (debug) {
        // create two 'fake' log tags, warnings and above to stderr, everything below to stdout.
        // presumably, all config-based log tags that are going to console can be ignored in this case, too.
    }
} else {
    // check all log tags, and treat any that are in stderr/stdout mode as a warning (or an error),
    // since stderr/stdout are going to be closed in this case.
}

// create log streams as appropriate ...
```

**Why this would be useful**

I think I already covered this.

**Comment by SadieCat** [comment]
I'd be open to adding this but for now could you add a file log type that logs to /dev/stdout or /dev/stderr?

**Comment by rburchell** [comment]
Hmm, yeah, that might work since they aren't closed. Though, I suppose that exposes another problem with my plan: right now, a log gets all output >= its level. This would mean that if I had one logger going to stdout for "boring" stuff, and warnings going to stderr, nothing would stop the stdout logger *also* getting those.

That's inconvenient, but I guess I can at least live with everything on stdout for now...

**Comment by rburchell** [comment]
After trying it a bit, another small request: it'd also be good to be able to suppress the addition of TIMESTR for this, since timestamping is generally happening by whatever is hoovering up the logs anyway.

**Comment by SadieCat** [comment]
This has been implemented in git master.
