### ISSUE TITLE
Private Networks

### ISSUE THREAD

**Issue by WolfTown0907** [inspircd/inspircd#1866]
**Description**
I run an IRC Network for a medium sized business, with each building having its own server, and they are all part of the same network. It would be a good idea to create a utility to add networks to a fresh install so that I can provision IRC clients with the network preinstalled.

**Why this would be useful**

It would permit IT admins to quickly provision IRC clients.

**Comment by SadieCat** [comment]
Clients all do their own thing so there's no single way to preconfigure them. You'll need to look into how the client your employees use works and then write a script to automatically generate configs for it.

**Comment by SadieCat** [comment]
Closing this as there's not really anything we can do regarding this.
