### ISSUE TITLE
Elines overreaching over webirc connections

### ISSUE THREAD

**Issue by CoryChaplin** [inspircd/inspircd#1871]
**Description**

When using an reverse dns on a webirc proxy, all the webirc users connecting through the proxy will benefit from any eline that affects the proxy's rdns (in my case *.europnet.org).
Adding _resolvehostnames="no"_ to the connect class bypasses the issue.

**Steps to reproduce the issue:**

1. Add an rdns to the server hosting the webirc proxy
2. Add an eline matching that host
3. Connect a webirc user
4. Gline the user

**Describe the results you received:**
The gline doesn't apply because the user is protected by eline (exempt is also visible in /check).

**Describe the results you expected:**
The user should be glined.

**Output of `./bin/inspircd --version`:**
InspIRCd-3.8.1

**Comment by CoryChaplin** [comment]
Todo: check against master

**Comment by DrummingAway** [comment]
no patches yet available for this bug?

**Comment by SadieCat** [comment]
@CoryChaplin Does this fix your issue? https://github.com/inspircd/inspircd/compare/insp3...SadieCat:insp3+host

**Comment by DrummingAway** [comment]
### **Great thank you very much for everthing.**

**Comment by SadieCat** [comment]
I've committed that fix. Thanks for reporting, please poke me in #inspircd.dev if it's still an issue.
