### ISSUE TITLE
LUSERS should exempt secret channels from RPL_LUSERCHANNELS

### ISSUE THREAD

**Issue by SadieCat** [inspircd/inspircd#1873]
Having secret channels in RPL_LUSERCHANNELS exposes their existence.

We should instead make it not include these channels.

**Comment by SadieCat** [comment]
Whilst this is technically a bug there's software which relies on it (e.g. the netsplit.de tracker bot) so we need to consider how to not break it when fixing this.

**Comment by examknow** [comment]
maybe this should be configurable
