### ISSUE TITLE
[v4] Shuffle modules between contrib and main

### ISSUE THREAD

**Issue by SadieCat** [inspircd/inspircd#1874]
As with v3 we should demote unuseful modules and promote useful modules.

Some quick proposals:

## Demotions

- [x] censor &mdash; not very useful, basically just a poor version of the filter module.
- [x] clones &mdash; not very useful.
- [x] lockserv &mdash; not very useful.
- [x] modenotice &mdash; only existed for v2 compat.
- [x] regex_tre &mdash; old regex library nobody really uses anymore, added for unreal compat but unreal has dropped it.
- [x] userip &mdash; duplicates the behaviour of the check command in a less useful way

## Promotions

- [ ] joinpartspam &mdash; useful for antispam
- [ ] shed_users &mdash; useful for dealing with server migrations
- [ ] tgchange &mdash; useful for antispam
---

Note: this doesn't include modules which are having their behaviour rolled into other modules (like fakelist)

**Comment by SadieCat** [comment]
I've demoted the modules in this list. Will look into importing the others after I tag a1 tomorrow.

**Comment by Techman** [comment]
I'd like to argue that m_censor still has some use - as a badwords filter. Some networks may wish to have some kind of opt-in word filter available for channels. Using the global spam filter would be too much.

This may be considered "basic" functionality, at least in terms of IRCds that consider themselves featureful. Bumping it to contrib would also mean that it loses official support. Not that I think that you wouldn't help someone if they were to run into a bug, of course.

**Comment by SadieCat** [comment]
Added modenotice to contrib which was removed earlier in v4 development.

@Techman The censor module is so trivial to avoid it's not really effective for that. If people want to use "bad words" they're gonna do that regardless of whether you try to stop them or not and the censor module isn't anywhere near enough for avoiding that.

**Comment by SadieCat** [comment]
I should also look into client support for MONITOR to see if its feasible to kick the watch module into contrib too. I suspect it's not possible right now but I haven't checked clients to be sure.

**Comment by SadieCat** [comment]
I'm thinking about moving [userip](https://docs.inspircd.org/3/modules/userip/) to inspircd-contrib. Its a non-standard extension, only Unreal and us implement it, and it duplicates the behaviour of `/CHECK` in a much less useful way.
