### ISSUE TITLE
Sync channel list mode limits across servers

### ISSUE THREAD

**Issue by bigfoot547** [inspircd/inspircd#1877]
**Description**
Sync `<maxlist>` configuration values across servers.
Below is an IRC log of a discussion about the issue.
```
<bigfoot> ChanServ bans on channels set RESTRICTED override maxlist
...
<~Sadie> bigfoot: if you open an issue i can look into getting a way for services to enforce limits
...
<~Sadie> i dont think we sync the list limit currently so that'd need to be fixed
<bigfoot> how would it be synced? in the CAPABs?
<~Sadie> channel metadata probably
```
Note that this feature, if implemented, would not *prevent* services from overfilling list modes, but rather notify the server of the limits. It is up to the services themselves to respect the limits.

**Why this would be useful**
Services servers, for example, do not know the `<maxlist>` values in the IRCd's configuration, meaning that services are in the dark about how many bans are allowed to be set on a channel at once.

As an example (specific to atheme), when a channel is set RESTRICTED, ChanServ kickbans users who join who aren't on the access list. In the event that a large number of unauthorized users attempt to join the channel, ChanServ would add a large number of +b modes, potentially exceeding the IRCd's limit.

**Comment by SadieCat** [comment]
Implemented in commit 722c63ad53dea99829cf010786354e21016aadef.
