### ISSUE TITLE
[v4] errors when running make on Debian 10

### ISSUE THREAD

**Issue by shaynejellesma** [inspircd/inspircd#1878]
**Description**
Getting errors during make when trying to compile v4.0.0a1 on Debian 10.

**Steps to reproduce the issue:**

1. a fresh git clone and checkout tags/v4.0.0a1
2. ./configure --prefix=/home/ircd/inspircd --development
3. make

**Describe the results you received:**
https://pastebin.com/WusZHqg5

**Describe the results you expected:**
To successfully compile

**Additional information you deem important (e.g. issue happens only occasionally):**
Debian: 10.9 | GCC: 8.3.0 (Debian 8.3.0-6) | OpenSSL: 1.1.1d | GnuTLS: gnutls-cli 3.6.7 | Perl: v5.28.1
Have also tried using "export LDFLAGS='-lstdc++fs'" recommendation from the irc channel.
I am able to compile v3.10.0 on this server

**Output of `./bin/inspircd --version`:**
n/a

**Comment by SadieCat** [comment]
Can you also pastebin the output of `apt-cache policy libstdc++-8-dev` (replace the 8 with an asterisk if it gives an error).

**Comment by shaynejellesma** [comment]
# apt-cache policy libstdc++-8-dev
libstdc++-8-dev:
  Installed: 8.3.0-6
  Candidate: 8.3.0-6
  Version table:
 *** 8.3.0-6 500
        500 http://mirror.internode.on.net/pub/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by SadieCat** [comment]
Does this branch fix your issue?

https://github.com/SadieCat/inspircd/tree/master%2Bfs (`git clone --branch master+fs https://github.com/SadieCat/inspircd.git`)

**Comment by SadieCat** [comment]
This should be fixed in git. Thanks for reporting.
