### ISSUE TITLE
ircv3_sts module won't work if TLS connections are proxied

### ISSUE THREAD

**Issue by russss** [inspircd/inspircd#1911]
**Description**

The ircv3_sts module helpfully prevents you from enabling STS for an insecure port. However, this prevents STS being enabled if inbound connections are proxied to the port (as is the case if you're using the haproxy module).

**Steps to reproduce the issue:**
1. Configure the ircv3_sts module to use a non-TLS port.

**Describe the results you received:**
Fails to start with `Unable to read the configuration for m_ircv3_sts.so: <sts:port> must be a TLS port`

**Describe the results you expected:**
Not the above :)

I'm not sure if there's ever a useful case for having a proxy _without_ using the haproxy module, so perhaps it could check if the port has TLS _or_ the haproxy hook enabled.

**Output of `./bin/inspircd --version`:**
`InspIRCd-3.10.0`

**Comment by SadieCat** [comment]
This is a known issue. STS requires the server name sent via SNI which is currently only available via the `SSLIOHook` class. We need to add the server name field to the `ssl_info` class but it would require adding interning to the modules that create `ssl_cert` objects to avoid having tons of duplicate string copies and I'm not sure how to do that without a ton of duplicate code just yet.

**Comment by SadieCat** [comment]
This should work now if you add `hookssl="yes"` to your `<bind>` tag.
