### ISSUE TITLE
DNS resolution failure when connecting using haproxy module

### ISSUE THREAD

**Issue by russss** [inspircd/inspircd#1914]
**Description**

When using the haproxy module with inbound proxy connections over TCP (I can't use unix sockets in this case), it appears that there's a race condition in reverse DNS resolution which results in the hostmask containing the IP rather than the hostname.

I think inspircd first tries to resolve the address of the proxy, then when the PROXY header is read, it kicks off another resolution attempt using the IP address from the header. The first resolution attempt (which returns NXDOMAIN) is reliably returning after the second in my case, so I'm guessing it's deleting the correct hostname.

**Steps to reproduce the issue:**
Described above.

**Describe the results you received:**
```
*** Looking up your ident...
*** Looking up your hostname...
*** Looking up your ident...
*** Looking up your hostname...
*** Found your hostname (id-30.tooting.irccloud.com) -- cached
*** Could not resolve your hostname: Domain not found; using your IP address (2001:67c:2f08:4::1e) instead.
[...]
Your hostmask: sid30@2001:67c:2f08:4::1e
```

(Note that the IP address in the "Could not resolve your hostname" response is the correct address from the PROXY header, but I'm guessing that's been overwritten by the haproxy module after the DNS request started.)

**Describe the results you expected:**
The hostmask should include the DNS name rather than the IP address.

**Output of `./bin/inspircd --version`:**
`InspIRCd-3.10.0`

**Comment by SadieCat** [comment]
I thought I'd fixed this already but apparently I only did it for the dnsbl module.

I'll commit a fix for this today. Until then you can add a connect class for your gateway address that has `resolvehostnames="no" set to work around this.

**Comment by SadieCat** [comment]
I didn't get a response from you on IRC so I'm going to commit my second fix for this as I'm pretty sure it should fix it. Poke me on IRC if it still happens afterwards though.
