### ISSUE TITLE
[m_codepage] Problem work

### ISSUE THREAD

**Issue by NightSommelier** [inspircd/inspircd#1934]
**Description**

 I'm not sure, but it seems to me that the codepage module is not working correctly.
I am using windows-1251 symbols.

When I try to change my nickname, it writes: **Erroneous Nickname**

**Steps to reproduce the issue:**

1. Activate module `<module name="codepage">`
2. Added into inspircd `<include file="codepages/windows-1251.conf">`

**Config codepages/windows-1251.conf:**

```C#
<codepage name="windows-1251" charset="windows-1251">

<cpchars begin="128" end="153" front="yes">
<cpchars begin="160" end="175" front="yes">
<cpchars begin="224" end="233" front="yes">
<cpchars begin="240" end="245" front="yes">
<cpchars begin="178" end="179" front="yes">
<cpchars index="156" front="yes">
<cpchars index="236" front="yes">
<cpchars index="158" front="yes">
<cpchars index="238" front="yes">
<cpchars index="159" front="yes">
<cpchars index="239" front="yes">
<cpchars index="165" front="yes">
<cpchars index="180" front="yes">

<cpchars index="96">
<cpchars index="45">
<cpchars begin="48" end="57">
<cpchars begin="123" end="125" front="yes">
<cpchars index="91" front="yes">
<cpchars index="93" front="yes">
<cpchars index="95" front="yes">
```

**Output of `./bin/inspircd --version`:**

InspIRCd version: 3.11.0

**Comment by SadieCat** [comment]
What client are you using? Is it configured to use the right codepage in its text encoding setting?

**Comment by SadieCat** [comment]
If you have any more questions then please ask in irc.inspircd.org #inspircd. Thanks.
