### ISSUE TITLE
request SNI support

### ISSUE THREAD

**Issue by devicefr** [inspircd/inspircd#1939]
Hi,

It's possible to add SNI ssl support, so people can point two or more domains with ssl on port 6697 or whatever.

thanks.

**Comment by SadieCat** [comment]
You can already do this if you specify multiple domains in your certificate. 

https://certbot.eff.org/faq#can-i-get-a-certificate-for-multiple-domain-names-san-certificates

Is this not what you want?

**Comment by devicefr** [comment]
Hi Sadie,

I'm not pretty sure that this is what I need, what I refer is "Server Name Indication", so I can point two or more certs to one SERVER o IP address. So I can have irc.example1.org, irc.example2.org, irc.example3.org point to 192.124.21.23.

https://en.wikipedia.org/wiki/Server_Name_Indication

thanks for reply..

**Comment by SadieCat** [comment]
This is what a SAN certificate is for. You list all of your domains as alternate names when requesting your certificate. SNI is typically used for hosting multiple servers behind one IP address not this.

**Comment by SadieCat** [comment]
If you have any more questions then please ask in irc.inspircd.org #inspircd. Thanks.
