### ISSUE TITLE
Making Insp4 named "acting" extbans more consistent with each other

### ISSUE THREAD

**Issue by progval** [inspircd/inspircd#1940]
**Description**

Looking at https://docs.inspircd.org/3/extended-bans/#acting , I see five name patterns:

* `no*` (noctcp, nonick, nokick, nonotice)
* `block*` (blockinvite, blockcaps, blockcolors)
* `stripX` (stripcolors)
* name of what is banned/blocked (partmsg)
* verb (mute)

As this is going to be a feature exposed to user, I think they should be made more consistent with each other to provide a nicer interface. Obviously we can't use a single pattern (because blockcolors != stripcolors), but it would be nice to reduce the number.

I propose the fourth pattern (name of what is banned), `+b X` means "ban X", so "+b noctcp:*" or "+b blockinvite:*" makes them double negatives. Here is a [quote from Syzop](https://bugs.unrealircd.org/view.php?id=5991#c22157):

>  What I always try to keep in mind when adding an extban is using the following logic:
> "for +b, i am banning.... [something]"
> So ~join, as i am banning joins
> So ~account, as i am banning an account
> And so on.. channel, security-group, operclass, realname, etc.

Note that Insp's "matching" extbans already follow this "rule", in a way.

This means the following renames:

* `noctcp` -> `ctcp`
* `nonick` -> `nick`
* `nokick` -> `kick`
* `nonotice` -> `notice`
* `blockinvite` -> `invite`
* `blockcaps` -> `caps`
* `blockcolors` -> `colors` ?
* `stripcolors` -> ???
* `partmsg` -> unchanged
* `mute` -> ???

**Why this would be useful**

1. This will make Insp itself more consistent.
2. Makes the names shorter.
3. Finally, it would make Insp more consistent with Unreal. (even if you're not interested in this, I hope the other two points are enough to convince you)

What do you think?

**Comment by SadieCat** [comment]
As I've said on IRC I'm honestly not too interested in this. The names we use match the names of the modes they are associated with and I'm more concerned with internal consistency than consistency with some implementation that someone wrote after ours.

**Comment by progval** [comment]
> The names we use match the names of the modes they are associated with and I'm more concerned with internal consistency

Then rename these modes as well. It will improve Insp's internal consistency as well.

**Comment by SadieCat** [comment]
That would break compatibility with v3.

**Comment by progval** [comment]
> That would break compatibility with v3

How? Mode names are never exposed to users, right?

> external services such as Anope which rely on names to identify modes.

Ah, that's annoying. What use do services have for identifying modes?

**Comment by SadieCat** [comment]
>How? Mode names are never exposed to users, right?

Mode names are exposed to users (via the namedmodes module)

>Ah, that's annoying. What use do services have for identifying modes?

Services needs to know what modes do so they can set them and know if users should be allowed to set them (i.e. you don't want a user to be able to add themselves at a higher rank to the autoop list).

**Comment by progval** [comment]
> Mode names are exposed to users via the namedmodes module.

Oh, I didn't know you already implemented this!

> Services needs to know what modes do so they can set them and know if users should be allowed to set them (i.e. you don't want a user to be able to add themselves at a higher rank to the autoop list).

I see. Won't Insp4 have breaking changes that require updates to Anope and Atheme anyway?

**Comment by SadieCat** [comment]
>I see. Won't Insp4 have breaking changes that require updates to Anope and Atheme anyway?

The previous major version's S2S protocol is always supported by major new releases (1.2 on 2.0, 2.0 on 3.0, etc) so no.

**Comment by progval** [comment]
What about a temporary "translation" step in the implementation of the S2S protocol, then?

**Comment by SadieCat** [comment]
I'm sorry but no. The effort required to actually implement this along with how much it will break is simply not worth the reward of maybe having some things named similar to Unreal.
