### ISSUE TITLE
<execfiles> for showfile module

### ISSUE THREAD

**Issue by richardg867** [inspircd/inspircd#1941]
**Description**

My network is migrating from a many-years-old InspIRCd 2 setup with an `<execfiles>` block to load the `/RULES` file from a web server. With InspIRCd 3 replacing `/RULES` with the `showfile` module, InspIRCd's ability to handle remote loading of this file was removed, since showfile can only read local files.

**Why this would be useful**

Consistency. The ability to load `/MOTD` and `/OPERMOTD` remotely has always been there, and the replacement of `/RULES` with `showfile` was a regression in this department.

**Comment by genius3000** [comment]
According to [https://docs.inspircd.org/3/modules/showfile](showfile's documentation) you can still use `execfiles` with it. The key=value in an execfiles tag becomes the key you use as a "file", or it should default to the command name; so `<execfiles rules="foo bar"> and <showfile name="rules" ...>` should work. If that fails, try adding the `file="rules"` to the showfile tag. I'm sure I've seen this done already in v3.

**Comment by richardg867** [comment]
I completely missed the `showfile` module's documentation. Thanks for clarifying.
