### ISSUE TITLE
InspIRCd doesn’t even contact configured LDAP

### ISSUE THREAD

**Issue by Al2Klimov** [inspircd/inspircd#1942]
**Description**

**Steps to reproduce the issue:**

1. On an Ubuntu 20.04 box setup InspIRCd. Make sure users can connect and text.
2. Add this config:

```
<module name="ldapauth">
<ldapauth baserdn="dc=nodomain"
          attribute="cn"
          server="ldap://127.0.0.1"
          killreason="nice try"
          searchscope="subtree"
          binddn="cn=admin,dc=nodomain"
          bindauth="123456"
          verbose="yes"
          userfield="no" >
```

**Describe the results you received:**

Server kicks me out w/ "nice try" w/o even contacting LDAP. (Wireshark is your friend.)

**Describe the results you expected:**

Server lets me connect and text.

**Additional information you deem important (e.g. issue happens only occasionally):**

See comments under https://serverfault.com/questions/1083163/inspircd-doesn-t-even-contact-configured-ldap

**Output of `./bin/inspircd --version`:**

I've compiled a fresh master just to be sure.

**Comment by progval** [comment]
Are you sure wireshark was listening on the right interface? (probably `lo`)

**Comment by genius3000** [comment]
Where did you get your configuration information from? Both our example configs and docs.inspircd.org show correct examples. You need to enable the extras module m_ldap and configure it, then configure m_ldapauth to use the `dbid` assigned in the m_ldap configuration.

Also, please note: `master` branch is v4, or pre-release; `insp3` branch is v3 or current and is what the docs site is based on.

**Comment by Al2Klimov** [comment]
Congrats, @genius3000. You’ve just won a bounty of 50 reputation: https://serverfault.com/questions/1083163/inspircd-doesn-t-even-contact-configured-ldap
