### ISSUE TITLE
`/INFO invalid.server` returns no reply

### ISSUE THREAD

**Issue by progval** [inspircd/inspircd#1943]
**Description**

The `/INFO` command takes an optional argument, which is a server (or a nick on the target server) from which to get the info.

Refs:

* https://datatracker.ietf.org/doc/html/rfc1459#section-4.3.8
* https://datatracker.ietf.org/doc/html/rfc2812#section-3.4.10
* https://modern.ircdocs.horse/#rplendofinfo-374

When given an invalid server name / unused nick, I would expect it to return ERR_NOSUCHSERVER, as do other servers I tested (unless they ignore the parameter entirely)

**Steps to reproduce the issue:**

1. Connect a client to any server
2. Send `/INFO invalidserver`

**Describe the results you received:**

Nothing happens

**Describe the results you expected:**

Should reply with ERR_NOSUCHSERVER

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `./bin/inspircd --version`:**

I tried with `InspIRCd-4.0.0-8de48c3ad` and `InspIRCd-3.10.0-3d6365989`

**Comment by SadieCat** [comment]
We should probably remove the multi-server routing of INFO. It's almost always going to be the same value on each server and there's no reason to actually fetch it for other servers other than to attempt a really shitty DoS attack.

**Comment by SadieCat** [comment]
I checked Anope and Atheme quickly and neither of them seem to implement INFO making it even more useless.
