### ISSUE TITLE
Crash with "Reference allocate on the stack!" on the latest master

### ISSUE THREAD

**Issue by progval** [inspircd/inspircd#1944]
**Description**

**Steps to reproduce the issue:**

1. Checkout the latest master (2ec53e10ee5325df12586c72471efabb07cb9d70)
2. Create a config file with this content:
   ```
   <bind address="0.0.0.0" port="46033" type="clients">                                     
   <server name="My.Little.Server" description="testnet" id="000" network="testnet">        
   ```
2. Run `inspircd --nofork --config insp.conf`

**Describe the results you received:**

```
InspIRCd - Internet Relay Chat Daemon
See /INFO for contributors & authors

InspIRCd Process ID: 571682
Reference allocate on the stack!
```

then stops

**Describe the results you expected:**

This is what I got on 047473426bc6e60185c2576ec3f585b9e62d5072:

```
InspIRCd - Internet Relay Chat Daemon
See /INFO for contributors & authors

InspIRCd Process ID: 575331

Loading core modules ....................
InspIRCd is now running as 'My.Little.Server'[000] with 1048576 max open sockets
```

then keeps running

**Additional information you deem important (e.g. issue happens only occasionally):**

Debian 11
GCC 10.2.1

**Output of `./bin/inspircd --version`:**

```
InspIRCd-4.0.0-2ec53e10e
```

**Comment by SadieCat** [comment]
Fixed, thanks for reporting! 👍
