### ISSUE TITLE
v3.11 .0 on Ubuntu m_httpd loads, but 404 is displayed

### ISSUE THREAD

**Issue by un-fuf-a-doo** [inspircd/inspircd#1947]
**Description**

I'm new to hosting my own IRCd, but not to IRC. I believe I have everything configured properly, and I even have my own wildcard certificate. Testing secure connections to the default port 6697 works without issue. When configuring the httpd module, I am using the same <sslprofile>, but every attempt to load my server in a browser fails with a 404, after prompting for which client certificate to use. Do I need another <sslprofile> specifically for the httpd module? Or am I just way way off on what the httpd module is for?

**Steps to reproduce the issue:**

1. Configure a basic InspIRCd on Ubuntu 20
2. Enable httpd and ssl_openssl
3. Configure a <bind> for each using the same <sslprofile>
4. Connections to the IRCd ssl port work, Connections to IRCd httpd 404.

**Describe the results you received:**

1. Connections to the ssl port connect without issue
2. Connections to the httpd port present 404 errors

**Describe the results you expected:**

1. I expected to see a minimal web irc connection to my server

**Additional information you deem important (e.g. issue happens only occasionally):**

OS: Ubuntu Server 20.10

```
<module name="ssl_openssl">
<bind address="192.168.122.170" port="6697" type="clients" sslprofile="Clients" defer="0" free="no">
<module name="httpd">
<bind address="192.168.122.170" port="8097" type="httpd" sslprofile="Clients">
<httpd timeout="20">

<sslprofile name="Clients"
            provider="openssl"
            cafile="certs/cacert.pem"
            certfile="certs/cert.pem"
            ciphers="DEFAULT"
            compression="no"
            dhfile="certs/dhparam.pem"
            hash="sha256"
            keyfile="certs/cert.key"
            renegotiation="no"
            requestclientcert="yes"
            tlsv1="no"
            tlsv11="no"
            tlsv12="yes">
```

**Output of `./bin/inspircd --version`:**

```
/usr/lib/inspircd/bin/inspircd --version
InspIRCd-3.11.0
```

7h4Nk - Y0u

**Comment by SadieCat** [comment]
The httpd module just provides a HTTP server for other modules like [httpd_config](https://docs.inspircd.org/3/modules/httpd_stats/) (`/config`) or [httpd_stats](https://docs.inspircd.org/3/modules/httpd_stats/) (`/stats`). It doesn't actually provide anything by itself.

What are you actually trying to do? If you're trying to connect to IRC via WebSockets then you want the [websocket](https://docs.inspircd.org/3/modules/websocket/) module instead.

**Comment by un-fuf-a-doo** [comment]
Hey thanks for replying. I was hoping that Inspircd had a built in web to irc interface. 
I think I misread what that module is for completely.

**Comment by SadieCat** [comment]
You probably want to look into [KiwiIRC](https://github.com/kiwiirc/kiwiirc) which provides a client that can connect to InspIRCd via WebSockets.

**Comment by un-fuf-a-doo** [comment]
Thank-you!   Closing this out.
