### ISSUE TITLE
Change directory on Linux after compilation

### ISSUE THREAD

**Issue by leandroluiz** [inspircd/inspircd#1958]
Hi everyone,

First of all, thanks for your work. I was wondering if there's some way to change the directory where the main binary look for the conf file, after compilation.

I compiled a new version today in a directory and moved to another but it won't run because the binary was looking for the conf file in the location where it was compiled.

Thanks!

**Comment by progval** [comment]
You can use the `--config` option to specify the location of the config file.

**Comment by leandroluiz** [comment]
> You can use the `--config` option to specify the location of the config file.

oh! cool! Sorry for that. Thanks for your help.
