### ISSUE TITLE
[v4] Infinite loop of METADATA bouncing between two servers upon services account login

### ISSUE THREAD

**Issue by AndrioCelos** [inspircd/inspircd#1962]
**Description**

When I link two InspIRCd v4.0.0a7 servers and services, connect to one and identify to a services account, it results in `METADATA` messages bouncing back and forth between the two servers and repeated 'authenticated' messages on the client until I disconnect.

When this was discovered, I was connecting to the leaf server, but the issue occurs whichever server I connect to.

Some other actions that produce `METADATA` messages, such as joining a channel that would have a mode lock set, also cause the issue.

**Steps to reproduce the issue:**

1. Link two InspIRCd 4 servers and a services server.
2. Connect a client to either server and identify to a services account.

**Describe the results you received:**

Debug output is at https://gist.github.com/AndrioCelos/cac78c42a013617a3db236bdbd3507e0.

**Describe the results you expected:**

The server receiving a `METADATA` message should not echo it back to the sender.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `./bin/inspircd --version`:**
InspIRCd-4.0.0-28513865c

**Comment by SadieCat** [comment]
This should be fixed in `master`. Can you confirm?

**Comment by AndrioCelos** [comment]
> This should be fixed in `master`. Can you confirm?

Yes, the above setup seems to be working fine now.
