### ISSUE TITLE
Permchannel mode not write permchanneldb file

### ISSUE THREAD

**Issue by sdemingo** [inspircd/inspircd#1965]
When I set +P mode on a channel, it's is not write in the permchannels.conf file. The mode is set in the channel but when I restart the service it disappears. The service reads permchannels.conf well beacause if I write a channel definition, it's is loaded when start the service. 

I load the module in inspircd.conf:

```
<module name="permchannels">
<permchanneldb filename="/etc/inspircd/permchannels.conf"
                listmodes="yes"
                saveperiod="5s">
<include file="/etc/inspircd/permchannels.conf">
```
I test the with relative path and absolute path but I have the same results. The permissions of permchannels.conf are 644 to "irc" user. I'm using inspircd 3.8.1-2 on Debian 11 installed with apt from the official repositories.

**Comment by sdemingo** [comment]
The user "irc" has 770 mode on the config directory. 

When I active +P mode these are the log messages:

```
Feb 26 12:12:58 trastero audit[10044]: AVC apparmor="DENIED" operation="mknod" profile="/usr/sbin/inspircd" name="/etc/inspircd/permchannels.conf.tmp" pid=10044 comm="inspircd" requested_mask="c" denied_mask="c" fsuid=39 ouid=39
Feb 26 12:12:58 trastero kernel: audit: type=1400 audit(1645877578.094:26): apparmor="DENIED" operation="mknod" profile="/usr/sbin/inspircd" name="/etc/inspircd/permchannels.conf.tmp" pid=10044 comm="inspircd" requested_mask="c" denied_mask="c" fsuid=39 ouid=39
Feb 26 12:13:23 trastero audit[10044]: AVC apparmor="DENIED" operation="mknod" profile="/usr/sbin/inspircd" name="/etc/inspircd/permchannels.conf.tmp" pid=10044 comm="inspircd" requested_mask="c" denied_mask="c" fsuid=39 ouid=39
Feb 26 12:13:23 trastero kernel: audit: type=1400 audit(1645877603.002:27): apparmor="DENIED" operation="mknod" profile="/usr/sbin/inspircd" name="/etc/inspircd/permchannels.conf.tmp" pid=10044 comm="inspircd" requested_mask="c" denied_mask="c" fsuid=39 ouid=39
```

**Comment by SadieCat** [comment]
AppArmor is denying write access to the config directory.  Debian ship their own AppArmor profile instead of using ours so they'll need to fix this. Please report this issue to the Debian package maintainer.

Alternately, we have our own .deb packages on the downloads page which you can download from the releases page.

**Comment by sdemingo** [comment]
Ok, now it's working with your .deb package. Thank you for you help!
