### ISSUE TITLE
IRCv3 ACCOUNT does not get sent for oneself

### ISSUE THREAD

**Issue by KoraggKnightWolf** [inspircd/inspircd#1974]
**Description**

It appears that IRCv3 ACCOUNT RAW is NOT sent for one's own connection, whether SASL is done during or post-registration. CHGHOST however is sent, and after discussion on IRC, I am opening this issue here so it does not get lost.

**Steps to reproduce the issue:**

1. use SASL auth with a custom vhost on the services end to in theory trigger ACCOUNT (for logging in) as well as CHGHOST (for having the vhost applied)
2. observe in client rawlog/debug etc window/buffer that even though CHGHOST is correctly sent by the server, ACCOUNT is not, even when receiving the 900 and 903 numerics when SASL authentication is successful.
3.

**Describe the results you received:**

ACCOUNT is not sent, however CHGHOST is (when account has a services-sided vhost)

**Describe the results you expected:**

ACCOUNT should also be sent as one's own "account status" is changing upon successful SASL authentication.

**Additional information you deem important (e.g. issue happens only occasionally):**

This also is the result on other IRCd's with a similar feature set to Insp, e.g. Unreal, and seems to occur with Anope as well as Atheme. 
Interestingly if oneself is user A, and another entity is user B, and both can log in and out of account C, then this happens: A sees B logging in and out of C, and B sees A logging in and out of C.
BUT A never sees themselves logging in and out of C, and B never sees themselves logging in and out of C either.

**Output of `./bin/inspircd --version`:**

Not possible as I do not have shell/vps access. However server creation date is Feb 01 2022.

**Comment by progval** [comment]
Relevant bit of [spec](https://ircv3.net/specs/extensions/account-notify):

> When enabled, clients will get the ACCOUNT message to designate the account name changes for clients on common channels with them, **including themselves.**

**Comment by KoraggKnightWolf** [comment]
Thank you for looking into the specification, in this specific instance I am not in any channels yet (during-connection SASL auth), but even in that case I should receive an ACCOUNT for myself, as I also get a CHGHOST for myself right? 
Regardless, Insp (and Unreal for that matter) are then "violating" the spec as they never send it for oneself.

**Comment by progval** [comment]
oh, I guess the spec is ambiguous then

**Comment by SadieCat** [comment]
We /should/ be sending it according to the code but for some reason we're not.
