### ISSUE TITLE
[Documentation] I cannot find documentation on the S2S protocol

### ISSUE THREAD

**Issue by satmd** [inspircd/inspircd#1975]
We just had a person looking for documentation of our s2s protocol.

I searched our site and our code but came back empty handed.

I think we should consider publishing documentation for the s2s protocol. Certainly for InspIRCd v4.x and probably also for v3.x.

**Comment by SadieCat** [comment]
I'm working on it but its a big task.

https://github.com/inspircd/inspircd-docs/issues/10
