### ISSUE TITLE
Virus detected when downloading

### ISSUE THREAD

**Issue by prichardso30** [inspircd/inspircd#1980]
Downloading InspIRCd-3.13.0.exe from the official site, results in the install being blocked due to malware:
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fSabsik.FL.A!ml&threatid=2147780195

**Comment by SadieCat** [comment]
What antivirus are you using? This is almost certainly a false positive as a lot of antivirus software flags IRC software as malware even if it is not.

https://www.virustotal.com/gui/url/c74a24324da88bb67af49d414ec88f5ac95f7253e3d308055602224646a27e4e?nocache=1 reports nothing

**Comment by prichardso30** [comment]
Interesting.  Yeah I thought it was weird, have never seen it before.  

Both chrome, and Windows security blocked it - which I thought was weird - never usually both blocking.

**Comment by SadieCat** [comment]
Google seems to suggest that it is flagging it as some sort of IRC trojan which makes sense. They're probably looking for some vague IRC-related strings in the binary which we are hitting.

We had this issue last time we provided Windows releases. I'll try to get it delisted but unfortunately antivirus vendors do have a habit of not caring if their crappy products hit legitimate software.

**Comment by prichardso30** [comment]
No problems :) 

I didn’t think it was an issue, but raised it just in case.  

Thanks thanks for following it up @SadieCat

**Comment by SadieCat** [comment]
I have filed a report with Microsoft which is currently pending.

**Comment by prichardso30** [comment]
Thank you. The support and quick response are amazing!

**Comment by SadieCat** [comment]
I haven't had a response from Microsoft yet but I updated our installer scripts to match the latest CMake release (e985f7ecc398b6f442b73478a9c0cf076c5c513a) and uploaded a new package (InspIRCd-3.13.0r2.exe) with this change to the downloads page. Can you confirm if this still triggers your antivirus?

**Comment by prichardso30** [comment]
Howdy, that seems to have fixed it :)
thank you

**Comment by SadieCat** [comment]
Nice, thanks for checking.
