### ISSUE TITLE
Error while building from source in termux 

### ISSUE THREAD

**Issue by jakbin** [inspircd/inspircd#1986]
I got this error .

![Screenshot_20220604-235624_Termux.jpg](https://user-images.githubusercontent.com/65591973/172050957-29895b81-a3fc-46d2-b6a3-cd470dfe346d.jpg)

**Steps to reproduce the issue:**

1. I downloaded inpircd v3.13.0.zip file from repo.
2. Then I run './configure'
3. Then I run 'make -j2 install'
4. Then I got that error.

**Describe the results you received:**
Nothing 

**Describe the results you expected:**
How to fix this .

**Comment by jakbin** [comment]
I fix issue by changing this code at line 55 

```diff
- #for (int fd = getdtablesize() - 1; fd >= 3; --fd) {
 + #for (int fd = sysconf(_SC_OPEN_MAX) - 1; fd >= 3; --fd) {
```

**Comment by SadieCat** [comment]
>I fix issue by changing this code at line 55

This is unfortunately not a portable change as it breaks non-Linux systems. I guess we could use `getrlimit(RLIMIT_NOFILE)` here though which would be portable.

>But it is not working properly.

That seems like a bug in the Termux version of Perl? `start` is defined in the same way as other functions.

Try running it directly with the executable in the bin directory instead.

**Comment by jakbin** [comment]
This new commit solve problem for termux ??

**Comment by SadieCat** [comment]
The most recent commit should solve the compilation issue yeah.

**Comment by jakbin** [comment]
I built it successfully. But he can't create inspircd.conf file in conf directory .

![20220609_054732.jpg](https://user-images.githubusercontent.com/65591973/172738471-5a1b7ed5-b8d8-4b48-809b-275168966c22.jpg)

**Comment by SadieCat** [comment]
You need to create your own config file. See the examples directory and https://docs.inspircd.org/3/configuration/.

**Comment by jakbin** [comment]
Thanks brother , it's working fine now.

**Comment by SadieCat** [comment]
If you have any more issues then please ask in irc.inspircd.org #inspircd. Thanks. :)
