### ISSUE TITLE
Strange behavior when trying to connect to inspircd container via websockets

### ISSUE THREAD

**Issue by Falco-K** [inspircd/inspircd#1987]
I am currently trying to connect to the inspircd docker container via localhost for testing purposes. It seems to work if I connect via the browser (e.g. via https://websocketking.com/ or https://jsfiddle.net/69cvLhkq/), resulting in default NOTICE messages as soon as I connect. However, if I try it via my local applications, I get a variety of errors:

### Using Dart:
```
var channel = IOWebSocketChannel.connect(Uri.parse('ws://localhost:8080'));

channel.stream.listen((message) {
  print(message);
});
```
results in the error "Connection to 'http://localhost:8080#' was not upgraded to websocket".

### Using Python:
```
import asyncio
import websockets

async def test():
    async with websockets.connect("ws://localhost:8080") as websocket:
        await websocket.recv()

asyncio.run(test())
```
results in the error "websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 400".

### My custom config extension:
```
<module name="sha1">
<module name="websocket">
<wsorigin allow="*">

<bind address="0.0.0.0"
      port="8080"
      type="clients"
      free="no"
      defer="5s"
      hook="websocket">
```

Most likely I am doing something obvious wrong, but I can't seem to find the cause. Maybe someone has an idea what might be wrong? Any help is appreciated.

**Steps to reproduce the issue:**

1. Run the latest Inspircd docker container with `docker run --name inspircd -p 8080:8080 -v <path to config shown above>:/inspircd/conf.d/ inspircd/inspircd-docker`
2. Run the Dart or Python program above

**Describe the results you received:**
Various error messages regarding a failed websocket connection, depending on the libraries used to connect to the container.

**Describe the results you expected:**
NOTICE messages, like I get by connecting via the browser.

**Output of `./bin/inspircd --version`:**
InspIRCd-3.13.0

**Comment by SadieCat** [comment]
If you check your server log it should give you a reason why. You might need to enable debug logging though like this:

```
<log method="file"
     type="USERS"
     level="debug"
     target="users.log"
     flush="1">
```

**Comment by SadieCat** [comment]
Implementations are supposed to normalise their headers before sending them and existing web browsers do this already afaik. Regardless though I'll look into making it match headers insensitively before the next release.

**Comment by SadieCat** [comment]
This should be fixed in insp3 git now. Can you test?

**Comment by Falco-K** [comment]
Yes, works fine for me now! Thanks a lot for the quick fix!
