### ISSUE TITLE
/who #chan x%nfchu

### ISSUE THREAD

**Issue by entropy311** [inspircd/inspircd#1989]
/who #chan x%nfchu

This command only lists the HIGHEST mode a nickname has on a channel.

Make this return ALL channel modes a nickname has (not only @) like all other IRCds have.

**Comment by SadieCat** [comment]
InspIRCd does this but only if your client has requested the `multi-prefix` IRCv3 capacity. Do you have [the namesx module](https://docs.inspircd.org/3/modules/namesx) loaded?
