### ISSUE TITLE
Interaction between Z-lines, E-lines, and cgiirc produces unexpected result

### ISSUE THREAD

**Issue by Kufat** [inspircd/inspircd#1992]
**Description**

Background:
Due to a history of abuse, my network bans VPNs, shell providers, AWS, etc. by default, with specific users' shells and bouncers receiving e-lines. We also make use of a Lounge instance, which is hosted on an IP that would otherwise be banned due to the above. We therefore have an e-line for the host. 

Issue:
By e-lining the cgiirc host (name and IP, one e-line each), it appears we've given everyone connecting from that host an exemption from Z-lines and possibly all other X-lines, rather than just allowing the initial connection. I've removed both the z-line and e-line as a stopgap, but I'd prefer to have a better solution.

**Steps to reproduce the issue:**

1. E-line a cgiirc host
2. Z-line an underlying IP
3. Connect, via cgiirc, from the underlying IP

**Describe the results you received:**
Connection is allowed.

**Describe the results you expected:**
I was expecting the connection to be disallowed.

**Additional information you deem important (e.g. issue happens only occasionally):**

I'm assuming this is WAD but I think there might need to be a code change in order to produce the desired behavior.

**Output of `./bin/inspircd --version`:**

InspIRCd-3.13.0

**Comment by genius3000** [comment]
Check/try a couple diagnostics:
1) (with your usual E-lines set on host) run /check <nick> on a client connected through said host. Look for the `exempt` flag. Also check the cgiirc metadata (`real...` iirc) compared to the currently set real host and IP.
2) Remove the two E-lines and add just one for *@IP to rule out at least the hostname as the hold up here. Connect a client and repeat the above to check.

**Comment by SadieCat** [comment]
I've investigated this and I can't seem to reproduce it at all.

**Comment by Kufat** [comment]
Ah well. Thanks for looking into it!

**Comment by SadieCat** [comment]
Other people (@gokturkyilmaz) are also reporting this so lets keep the issue open for a bit longer. :)

**Comment by SadieCat** [comment]
I think d82607052564d27aa0d75219f574c47bbf6eb06b should have fixed this.
