### ISSUE TITLE
Z-Lines in webirc are ineffective

### ISSUE THREAD

**Issue by gokturkyilmaz** [inspircd/inspircd#2000]
I think I found a bug in 3.14.0. I've tested it on different servers and it's still the same.
 
Z-Lines doesn't effect to webirc users IF server IP addresses (kiwiirc's IP's or local servers) are on inspircd's exception list.
 
When a user connects to server via webirc, e.g. KiwiIRC; and when the user is Z-Lined. The user is still able to re-connect with the same IP  after being Z-Lined.

**Comment by SadieCat** [comment]
Duplicate of #1992.
