### ISSUE TITLE
WHO command may omit results if delayjoin or other modules are loaded

### ISSUE THREAD

**Issue by shaggie76** [inspircd/inspircd#2001]
**Description**

The way /WHO handles mods may result in it randomly omitting results depending on the order the channels the target user is in, even when not doing a channel-focused query.

1) If Bob is in two channels #D and #A
2) Alice is in #A with Bob
3) #D has delayjoin set and Bob has never spoken in #D
4) If Alice issues a "/who Bob n%nu" command she may get no results
5) The workaround for this case can be /who Bob nd%nu however there may be other modules with problems (eg: m_auditorium is probably also likely to cause problems).

As best I can tell from the code the reason for this is in core_who.cpp CommandWho::SendWhoLine where the first thing it does is
```
	if (!memb)
		memb = GetFirstVisibleChannel(source, user);
```
IE: if you aren't doing a channel-focused /WHO it turns it into one whether you like it or not. If it happens to pick a channel that happens to be using m_delayjoin or m_auditorium the OnWhoLine callback may return MOD_RES_DENY inappropriately.

There's plenty of cases in this code flow that handle null nemb because that's a perfectly natural state and if I comment out the GetFirstVisibleChannel default everything works I would expect. I'm not sure what it was trying to do with that code but I'm not quite convinced it's what you want.

**Output of `./bin/inspircd --version`:**

InspIRCd-3.14.0

**Bonus performance suggestion***

In core_who.cpp CommandWho::WhoUsers the compiler can't short-circuit the evaluation of can_see_normally and so will check all those clauses even if data.fuzzy_match is false. 
```
		bool can_see_normally = user == source || source->SharesChannelWith(user) || !user->IsModeSet(invisiblemode);
		if (data.fuzzy_match && !can_see_normally && !source_has_users_auspex)
			continue;
```
I only mention this because at times our server has over 100K users in it and we're issuing more /who queries now.

**Comment by SadieCat** [comment]
This branch should fix this, can you test?

https://github.com/inspircd/inspircd/compare/insp3...SadieCat:insp3+who

**Comment by shaggie76** [comment]
I'm sorry but that's a lot more changes than I'm comfortable deploying to a live production environment right now. Our users were screaming mad about this because it was breaking part of our game, I theorized why, tried a 2-line hack, users stopped yelling at us, so I felt like the polite thing to do would be to report it. Thank you though.

**Comment by SadieCat** [comment]
Fixed in insp3 git.
