### ISSUE TITLE
/amsg and /ame - blockamsg module problem

### ISSUE THREAD

**Issue by netkrd** [inspircd/inspircd#2007]
**Description**
Opers can use /amsg or /ame commands, but it still gives notice in #Logs channel and status window

**Steps to reproduce the issue:**

1. 
2.
3.

**Describe the results you received:**

**Describe the results you expected:**
Opers and channel ops should be exempt and not get notice for them

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `./bin/inspircd --version`:**
InspIRCd version: 3.14.0

**Comment by SadieCat** [comment]
The blockamsg module does not have any exemptions for opers. Are you sure you're not confusing your client echoing the message locally with it being visible by other users?

**Comment by netkrd** [comment]
I tried again, yes i am sure of it, it warns but sometimes it appears on all channels on the server, sometimes it only appears on one channel.

Note:All privs are active in the opers.conf file 

> The blockamsg module does not have any exemptions for opers. Are you sure you're not confusing your client echoing the message locally with it being visible by other users?

**Comment by SadieCat** [comment]
Yeah, thats how blockamsg works. It can only detect that a user is sending a mass-message after it has seen the second message.

**Comment by SadieCat** [comment]
I've added an oper priv to exempt opers which I think is what you were asking for? Please say if that's not what you wanted.

**Comment by netkrd** [comment]
Yes i want exemption.
Actually all modules need to be exempted from oper.
Thanks.

> I've added an oper priv to exempt opers which I think is what you were asking for? Please say if that's not what you wanted.

**Comment by netkrd** [comment]
I tested it and it worked fine.
Thanks again.
