### ISSUE TITLE
Convert the hostchange module to a cloak method

### ISSUE THREAD

**Issue by SadieCat** [inspircd/inspircd#2025]
**Description**

Now we have modular cloaking we should convert [the hostchange module](https://docs.inspircd.org/4/modules/hostchange/) to be a cloaking method.

**Why this would be useful**

This would allow it to integrate with services better, would allow users to remove their cloaks, would allow opers to `/CHECK` users better, etc.

**Comment by SadieCat** [comment]
Working on this over here: https://github.com/inspircd/inspircd/compare/master...SadieCat:inspircd:master+static-cloak

I'm curious as to what hostchange actions people actually use. `set` does not seem particularly useful. Do people even use it?

**Comment by siniStar7** [comment]
Yes, it is used!

I can verify that we use it on [IRC4Fun](https://irc4fun.net) set gateway cloaks/vhosts, similar to libera.chat.  It'd be nice if it could be configurable to _not_ allow being unset, or overridden by a Services vhost. (_But it works fine for our uses even with the users being able to unset or override it via Services_) 

This functionality does come in useful in situations where you would like to cloak certain bots or services that are unable to IDENTIFY to NickServ and gain their own cloak/vhost. (e.g. Notifico)

**Comment by SadieCat** [comment]
I'm thinking it might be a good idea to keep hostchange as-is for v4 and also add three new modules that do the same things as it but that are integrated into the cloak system which people can then migrate to. Splitting them up me

- `cloak_account` (equivalent of the addaccount action).
- `cloak_nick` (equivalent of the addnick action).
- `cloak_static` (equivalent of the set action).
