### ISSUE TITLE
Improve sqlauth module to support the 'registered user' mode (+r) and additional guest nicknames

### ISSUE THREAD

**Issue by SPiRiT369** [inspircd/inspircd#2030]
**Description**
Currently, sqlauth module allows authenticating users, and allows guests to join only with a given nick pattern (e.g. allowpattern="Guest-*").
I think it can be usefull to let guests use any un-registered nickname, as well as add the +r (registered) user mode to users that are registered and authentication successfully with their password.

**My suggestion is:**
Add the following functionality to sqlauth module:
- When sqlauth is enabled, SQL query will be performed for any connection.
- If the nickname is registered (i.e. the query returned data) and the user provided the correct password, the user will get the +r mode to be marked as a registered user. (Obviously, if the user provided a wrong password, the connection will be rejected)
- If the nickname is not registered (i.e. the query returned nothing) - the user will be allowed to connect as long as his nickname matches the "allowpattern" value.
- The "allowpattern" value can be set to "*" to allow any nickname.

Once a registered user gets the +r mode, he can join channels having the +R (registered users only) mode.
Also the +M channel mode (services_account module) will allow channel ops to moderate guests in their channels.

**Why this would be useful**
- It gives server operators a better way to manage user accounts
- Allows accounting without using third-party tools (except for the registration part...)
- Provides better guest users experience when SQLAuth is enabled (they can choose any nick, as long as it's not registered)

This feature can be very useful for me, and I believe/hope for others too.

<3

**Comment by SadieCat** [comment]
I've implemented support for multiple sqlauth exemptions. 

What is your use case for marking the user as `+r`? This is typically for services accounts and in fact user mode +r is deprecated in master as it doesn't actually mark a user as being logged into a registered account just that they are using a nickname which is part of their group. What actually marks a user as being logged into a registered account is having the accountname/accountnicks/accountid metadata set on them.

**Comment by SPiRiT369** [comment]
The idea (and what I am willing to implement) is to let all users use ANY nickname (as I mentioned) as long as it's registered. Whoever wants to reserve their nick will register it (using a simple html page I'll create). And to prevent trolls I hoped to use the +r mode so channels can be limited to registered users only. But from your comment I understand that this is not a standard way to work with :/

Adding multiple sqlauth exemptions is great (many thanks!) but still I wish I could let guests choose any nickname they want as long as it is not registered (i.e. the sqlauth query returns no data).

I do not want to use 3rd party service, and allowing any guest nick as I mentioned is more friendly for regular (non tech) users in my opinion.

If you think it is possible to implement it somehow, I think it can be very useful (not just for me). If not then I'll try to think about using the feature you've added. (Thanks again for that <3)

**Comment by SPiRiT369** [comment]
Hi Sadie,
Since this is not a practical request, my suggestion can be canceled. Can you cancel it, or should I do that?
