### ISSUE TITLE
<chanhistory:maxduration> is not parsed as a duration

### ISSUE THREAD

**Issue by AndrioCelos** [inspircd/inspircd#2032]
**Description**

The `maxduration` argument for the `chanhistory` module configuration tag seems to be being parsed as a simple number instead of a duration. 

https://github.com/inspircd/inspircd/blob/f8614ea98581fb303abc36c792be6ba60b3c8b42/src/modules/m_chanhistory.cpp#L233

**Steps to reproduce the issue:**

1. Configure InspIRCd to enable the chanhistory module with the configuration from modules.conf.example.
2. Start InspIRCd.

**Describe the results you received:**

The value of `4w` in the example config resulted in an error message:

```
Wed Apr 19 2023 13:47:03 CONFIG: The value of <chanhistory:maxduration> at /home/andrea/apps/inspircd/run/conf/modules.conf:423:2 (4w) is contains an invalid magnitude specifier (w); using the default (2419200) instead.
```

**Describe the results you expected:**

The tag should be parsed with no errors and the specified duration should be respected.

**Additional information you deem important (e.g. issue happens only occasionally):**

This issue is only relevant to InspIRCd 4 because it relates to an alpha feature.

**Output of `./bin/inspircd --version`:**

InspIRCd-4.0.0-a20

**Comment by SadieCat** [comment]
Good catch, fixed.
