### ISSUE TITLE
Plaintext channel-key instead of hashed value when set in presence of other ops.

### ISSUE THREAD

**Issue by gokturkyilmaz** [inspircd/inspircd#2036]
When you set a channel key (+k) while other users are present in the channel and you are an operator, the key is visible in plaintext rather than being displayed as a hashed value.

**Comment by SadieCat** [comment]
This is as intended? Members of a channel and opers with channels/auspex can see the channel key.

**Comment by gokturkyilmaz** [comment]
> This is as intended? Members of a channel and opers with channels/auspex can see the channel key.

Yes but I think it shouldn't be seen _(should be masked/hashed somehow)_ by regular users who are not opped, if there's is an user in the channel.
