### ISSUE TITLE
bug inspircd version 4 in freebsd 13.2

### ISSUE THREAD

**Issue by mark4638** [inspircd/inspircd#2044]
hello there i will try run inspircd-4.0.0a21 in freebsd 13.2 and i get error i will run from home the inspircd without install a module geo_maxmind  this run ok but with a module i get error i happy to know how i can run it with this a module thanks to help
Found the libmaxminddb compiler flags for geo_maxmind using pkg-config: -I/usr/l ocal/include
Found the libmaxminddb linker flags for geo_maxmind using pkg-config: -L/usr/loc al/lib -lmaxminddb
BUILD: modules/m_geo_maxmind.cpp
In file included from /usr/home/asher/inspircd-4.0.0a21/src/modules/m_geo_maxmin d.cpp:34:
In file included from /usr/home/asher/inspircd-4.0.0a21/include/inspircd.h:51:
In file included from /usr/include/c++/v1/sstream:184:
In file included from /usr/include/c++/v1/istream:163:
In file included from /usr/include/c++/v1/ostream:139:
In file included from /usr/include/c++/v1/ios:214:
/usr/include/c++/v1/__locale:676:16: fatal error: use of undeclared identifier ' isascii'
return isascii(__c) ? (__tab_[static_cast<int>(__c)] & __m) !=0 : false;
^
1 error generated.
gmake[1]: *** [real.mk:478: modules/m_geo_maxmind.so] Error 1
gmake: *** [GNUmakefile:210: target] Error 2

**Comment by SadieCat** [comment]
This is not a bug in InspIRCd. Your system C++ library is broken.

**Comment by RhodiumToad** [comment]
For the record, it's not a bug in the system headers, but rather a bug in libmaxminddb, which is defining _POSIX_C_SOURCE in an inappropriate place. I have reported it to them here: https://github.com/maxmind/libmaxminddb/issues/318

(It's not clear that it is even legal to define _POSIX_C_SOURCE in C++ code, but that's not the main point.)
