### ISSUE TITLE
Sadie stop to flood my network

### ISSUE THREAD

**Issue by bmt1234** [inspircd/inspircd#2046]
listen well little boy Sadie if you keep flooding me with all your clones on my server I will enter no with 10000000000 clones it's easier if what you thought then I'm asking you to stop flooding my server with clones and I also don't want to use a hundred thousand botnetans so please let me go

**Comment by SadieCat** [comment]
I think you might be in the wrong place. InspIRCd is software used to run IRC servers not an IRC spam source and neither InspIRCd nor any contributor to the InspIRCd project are responsible for the current IRC-wide spam attack.
