### ISSUE TITLE
Services module does not remove user mode r correctly in v4

### ISSUE THREAD

**Issue by AndrioCelos** [inspircd/inspircd#2050]
**Description**

The `services` module does not remove user mode `r` from users who change nickname.

**Steps to reproduce the issue:**

1. Identify to a services account matching your current nickname (so services sets `+r` on you).
2. Change your nickname.

**Describe the results you received:**

If the new nickname is equal to the old nickname (different capitalisation), the server sets `-r` on the user, then Anope immediately sets `+r` again.
If the new nickname is different from the old nickname, no mode change occurs.

**Describe the results you expected:**

If the new nickname is equal to the old nickname (different capitalisation), no mode change should occur.
If the new nickname is different from the old nickname, the server should set `-r` on the user.

**Additional information you deem important (e.g. issue happens only occasionally):**

This issue applies only to InspIRCd v4 when `services:disablemodes` is set to `no`.

Seems to be the result of a missing `!` in the following line.

https://github.com/inspircd/inspircd/blob/3854c3f8e329fbdf7ff155c9a9c749dae56badbd/src/modules/m_services.cpp#L316

**Output of `./bin/inspircd --version`:**

```
InspIRCd-4.0.0-788bcd29c
```

**Comment by SadieCat** [comment]
Oops, I'll fix that shortly.
