### ISSUE TITLE
RPL_ISUPPORT CHANLIMIT does not show the correct value

### ISSUE THREAD

**Issue by GTAXL** [inspircd/inspircd#2052]
**Description**
The CHANLIMIT= param in the RPL_ISUPPORT numeric always displays 20 even if you change the maximum channels in the connect block or oper block. However you can join more than 20 channels (if configured) so the advertising CHANLIMIT is just incorrect.

**Steps to reproduce the issue:**

1. Configure a value like connect maxchans="200" or type maxchans="400"
2. Observe the CHANLIMIT parameter stay at 20, indicating the network only allows you to be in 20 channels when this is false.
3. Oper up to an oper class with even more channels than the globally configured one. Do a /VERSION and notice it still stays at 20 channels.
4. Join more than 20 channels and notice you are able to join more than what the RPL_ISUPPORT advertises.

**Describe the results you expected:**
The CHANLIMIT should advertise the correctly configured maximum channel value for the user's connect class, and update when someone opers up as well if the oper has a type class with a different configured maxchans value.

**Output of `./bin/inspircd --version`:**
InspIRCd-3.15.0-debian

**Comment by SadieCat** [comment]
This is a known issue in v3. The isupport list is global and can't be updated based on your connect class which makes it hard to show the true value there. This has been fixed in v4.
