### ISSUE TITLE
inspircd doesnt build with m_log_syslog module on FreeBSD

### ISSUE THREAD

**Issue by driesmp** [inspircd/inspircd#2053]
[inspircd-3.16.1_1.log.txt](https://github.com/inspircd/inspircd/files/12175829/inspircd-3.16.1_1.log.txt)

When trying to build inspircd with m_log_syslog module enabled on FreeBSD the build fails in a clean build environment.

**Comment by genius3000** [comment]
That module doesn't exist in v3, it's new to v4 (master branch). I'm not sure if you're attempting with some form of a backport but that error reads to me like the file does not exist, or is otherwise unreadable.

**Comment by driesmp** [comment]
Oh wow, derp. Indeed you are right. Thanks
