### ISSUE TITLE
how ip detected in aliases

### ISSUE THREAD

**Issue by legendskyk** [inspircd/inspircd#2068]
I want to add a command in alias.conf like
!e nickname then alias auto add nickname*!*@fullipaddress as:

+e nickname*!*@F44B8C.6B47B7.DD8AC5.9A4B46 in the channel?

is that possible?

**Comment by SadieCat** [comment]
The user IP address is not currently available in aliases. I'll add it for the next release.

**Comment by SadieCat** [comment]
Implemented. As of the next release you will be able to use $address for the IP address.
