### ISSUE TITLE
Eline nick should be work and also +U mode msg should show to room #ExtBanU

### ISSUE THREAD

**Issue by legendskyk** [inspircd/inspircd#2069]
Hello

My room traffic mostly from Pakistan and one of spammer get Pakistani IPs for spam, I want to shun ips and allow only those users which known and i want if i put their nick with ips in eline then server allow them to chat kindly make a feature like that asap.

and other function i want when i put my room +U or i put any ip u:*!*@IP or any nick u:nick then that user or ip msg should show to ExtbanU room instead of show operators kinly modify the m_opmoderated.cpp module.

**Comment by legendskyk** [comment]
seems everyone is busy?

**Comment by SadieCat** [comment]
E-lines are only for exempting from things that might ban you from the server not channel level restrictions.

Showing messages in a different channel has the risk of allowing operators to snoop on messages which is something that we explicitly do not support for privacy reasons.
