### ISSUE TITLE
[slibtool] [clang] make: No targets specified and no makefile found. Stop.

### ISSUE THREAD

**Issue by clinew** [inspircd/inspircd#2070]
**Description**

I got a bug report where a user is not able to build `inspircd` with the clang compiler.

Looking at the logs shows that the `CXX` environment variable appears to be set to `clang++` and the `find_compilers()` method in `make/configure.pm` shows `clang++` in the list of compilers.  Based on looking at the code, I don't see why `clang++` isn't found.  Any ideas what might be going wrong here?

**Steps to reproduce the issue:**

1. Currently unknown :(
2.
3.

**Describe the results you received:**
Build failure.

**Describe the results you expected:**
Build success.

**Additional information you deem important (e.g. issue happens only occasionally):**
Bug report: https://bugs.gentoo.org/show_bug.cgi?id=919508

**Output of `./bin/inspircd --version`:**
N/A since build fails, but source is `3.16.1`.

**Comment by SadieCat** [comment]
The way it checks if the compiler exists is by trying to execute it. It should output something if you're using INSPIRCD_VERBOSE=1 but it doesn't seem to be doing that for some reason? Weird.

**Comment by satmd** [comment]
There's a proposed solution in https://github.com/inspircd/inspircd/pull/2071
