### ISSUE TITLE
restrictchans - Send reason the user cannot create a channel

### ISSUE THREAD

**Issue by GTAXL** [inspircd/inspircd#2084]
I have the module restrictchans loaded with allowregistered="yes". So pretty much to make it so only registered users can create new channels.

When a regular user attempts to join a channel they get the following:
* Cannot join #test (You are banned).

This is misleading and confusing. I think it would make it clearer to use something along the lines of
"You must be registered before you can create new channels."

I just tested it with allowregistered="no" as well, reloaded the module and it results in the same You are banned.

I was going to say in that case something like "Only administrators are allowed to create new channels." but I see you have the allow channel option, so something like "You are not allowed to create new channels." instead of the misleading "You are banned".

I think this makes more sense than just You are banned. If they need to register their nick, let them know. If even registered users are restricted, let them know.

**Comment by genius3000** [comment]
I think your client is ignoring the reason supplied with the numeric, instead showing a generic message. The module sends [numeric 474](https://defs.ircdocs.horse/defs/numerics#err-bannedfromchan-474) with a reason of `You are not allowed to create new channels.`

Granted that's still not as descriptive as you're asking and there's pros and cons to being less vs. more descriptive (spam/bot protection, etc.)  
Maybe adding an optional NOTICE with a configurable message would be the best option here.

**Comment by GTAXL** [comment]
Here's how UnrealIRCd does it

`*errmsg = "%s :You must be logged in to create new channels", channel->name;`

So it uses a server notice, not a channel ban. Technically the user isn't "banned" from the channel. No ban exists, it's a new channel. They just need to register their nick. It's also off putting; a new user will think why am I banned from all these channels? I'm going to find a new network.

**Comment by SadieCat** [comment]
We use this numeric like this in several places with different messages. The message parameter isn't superfluous information and shouldn't be just hidden like that.  You should ask the developer of your client to stop hiding it.

**Comment by GTAXL** [comment]
Ok, so it's a client bug then? I would love to file a bug report with the client developer, however Hexchat just recently was discontinued. It's still a very popular client though.

I also just tested this functionality on the latest version of mIRC. It shows,

#test unable to join channel (address is banned)

I'd venture to say mIRC is a major client too. This bug that is in multiple IRC clients, may of been the reason the UnrealIRCd guys may of chosen to use a server notice instead.

Even if the existing method on InspIRCd did work, I do think it should say something different if you are just restricting it to registered users.
