### ISSUE TITLE
Handle connection registration bursts sent by clients

### ISSUE THREAD

**Issue by emersion** [inspircd/inspircd#2086]
**Description**
Clients want to minimize the number of roundtrips used to connect to an IRC server, especially on flaky connections such as mobile phones/hotspots. To this end, some clients (including gamja) send multiple commands in a single burst without waiting for the server reply. It doesn't seem like inspircd handles this.

Not really a bug per se, just a compatibility issue with some clients.

**Steps to reproduce the issue:**

1. Point gamja to `wss://testnet.inspircd.org:8097`
2. Fill the login form with any non-empty username and password

**Describe the results you received:**

gamja sends the following in a single burst:

```
AUTHENTICATE PLAIN
AUTHENTICATE <base64>
CAP END
```

inspircd processes the first command by sending `AUTHENTICATE +`, but then "skips" the second command and directly processes the third command by sending `RPL_WELCOME`. Later on, inspircd aborts the second command with `ERR_SASLABORTED`.

**Describe the results you expected:**

inspircd waits for the `AUTHENTICATE` command to complete before processing the rest.

**Comment by SadieCat** [comment]
InspIRCd doesn't process AUTHENTICATE requests itself it forwards them to services. As a client you have to wait until SASL is done before sending `CAP END`.

This is what it looks like from the server:

```
USERINPUT:      C[597AAAACU] I CAP LS 302
USEROUTPUT:     C[597AAAACU] O :testnet.inspircd.org CAP * LS :account-notify account-tag away-notify batch cap-notify chghost draft/no-implicit-names echo-message extended-join extended-monitor inspircd.org/poison inspircd.org/stats-tags invite-notify labeled-response message-tags multi-prefix sasl=ANONYMOUS,EXTERNAL,PLAIN server-time setname standard-replies sts=duration=2592000 tls userhost-in-names 
USERINPUT:      C[597AAAACU] I NICK aaa
USERINPUT:      C[597AAAACU] I USER aaa 0 * aaa
USERINPUT:      C[597AAAACU] I CAP REQ :account-notify away-notify batch chghost echo-message extended-join extended-monitor invite-notify labeled-response message-tags multi-prefix sasl server-time setname
USEROUTPUT:     C[597AAAACU] O @time=2024-03-01T14:05:44.101Z :testnet.inspircd.org CAP aaa ACK :account-notify away-notify batch chghost echo-message extended-join extended-monitor invite-notify labeled-response message-tags multi-prefix sasl server-time setname
USERINPUT:      C[597AAAACU] I AUTHENTICATE PLAIN
m_spanningtree: S[21]        O :597 ENCAP 00B SASL 597AAAACU * H 2a01:e0a:71:60c0:848b:cfb8:e3ab:884 2a01:e0a:71:60c0:848b:cfb8:e3ab:884 S
m_spanningtree: S[21]        O :597 ENCAP 00B SASL 597AAAACU * S PLAIN
USERINPUT:      C[597AAAACU] I AUTHENTICATE <removed>
USERINPUT:      C[597AAAACU] I CAP END
m_spanningtree: S[21]        I :00B ENCAP 597 SASL 00BAAAAAG 597AAAACU C +
USEROUTPUT:     C[597AAAACU] O @time=2024-03-01T14:05:44.102Z AUTHENTICATE :+
USEROUTPUT:     C[597AAAACU] O @time=2024-03-01T14:05:45.053Z :testnet.inspircd.org 001 aaa :Welcome to the InspIRCd Testnet IRC Network aaa!~aaa@<removed>
<motd spam here>
USEROUTPUT:     C[597AAAACU] O @time=2024-03-01T14:05:45.053Z :testnet.inspircd.org 906 aaa :SASL authentication aborted
```

The [SASL specification](https://ircv3.net/specs/extensions/sasl-3.1) says:

> The AUTHENTICATE command MUST be used before registration is complete and with the sasl capability enabled. To enforce the former, it is RECOMMENDED to only send CAP END when the SASL exchange is completed or needs to be aborted. Clients SHOULD be prepared for timeouts at all times during the SASL authentication.


> If the client completes registration (with CAP END, NICK, USER and any other necessary messages) while the SASL authentication is still in progress, the server SHOULD abort it and send a 906 numeric, then register the client without authentication.

---

I suspect that you may find the same behaviour on other IRC servers that have to talk to a remote server for authentication.

**Comment by emersion** [comment]
Right, I understand your point of view, but I don't want to give up latency because of one implementation. Oh well, I will just document that my clients are incompatible with inspircd. Thanks for taking the time to reply!

**Comment by SadieCat** [comment]
Given that we're following the spec its probably how every implementation that has to talk to a services server (i.e. everything other than Ergo) works but okay. 🤷‍♀️

**Comment by progval** [comment]
Couldn't there be an IRCv3 capability to advertise the server supports this?

**Comment by emersion** [comment]
I believe this was fixed in https://github.com/inspircd/inspircd/commit/4931b94e96c1f1a490c6fa44bf9e727dad82ab00.
