### ISSUE TITLE
Small issues with example configs

### ISSUE THREAD

**Issue by ItsOnlyBinary** [inspircd/inspircd#2099]
While using the example config's to recreate new up to date config's for my server I found a few small issues I've noted below.
---

This talks about multiple ports and the example below, but there is no example for multiple ports below
https://github.com/inspircd/inspircd/blob/58d775b2b1888a279d494c9f3d1043212139aa19/docs/conf/inspircd.example.conf#L127-L129

Would be nice if the comment included where this path is relative to.
https://github.com/inspircd/inspircd/blob/58d775b2b1888a279d494c9f3d1043212139aa19/docs/conf/inspircd.example.conf#L172-L173

Seems this module was replaced with anticaps, so should be removed from here?
https://github.com/inspircd/inspircd/blob/58d775b2b1888a279d494c9f3d1043212139aa19/docs/conf/inspircd.example.conf#L681-L682

Should be fully commented out like the rest of the config?
https://github.com/inspircd/inspircd/blob/58d775b2b1888a279d494c9f3d1043212139aa19/docs/conf/modules.example.conf#L1842-L1857

**Comment by SadieCat** [comment]
I've fixed all but the passforward one. I'm going to go through the module config and enable some stuff by default at some point so there's no point touching that right now.

**Comment by ItsOnlyBinary** [comment]
typo'ed: directory

https://github.com/inspircd/inspircd/blob/2b6dcdee3f61eaa51e61880e0c27a77c700ff775/docs/conf/inspircd.example.conf#L173

**Comment by ItsOnlyBinary** [comment]
I do like the idea of enabling recommended modules by default, would make barrier of entry much easier.  Its taken me many hours to go through the configs for my server.

Although alphabetical order is nice, maybe also consider grouping the modules in some fashion so related modules are together.
