### ISSUE TITLE
irssi fails to connect to InspIRCd v4 without the cap module loaded

### ISSUE THREAD

**Issue by anthonyryan1** [inspircd/inspircd#2103]
This is a a cross-reference to the irssi issue found herer: https://github.com/irssi/irssi/issues/1531

**Description**

It looks like irssi sends a deliberately invalid JOIN command to solicit a response from InspIRCd following CAP LS in an effort to differentiate the absence of IRCv3 client capabilities from a server that's not responding.

It looks like their code worked for InspIRCd 3.x, but after 4.x irssi it causes irssi to hang during connections.

The JOIN hack can be found here: https://github.com/irssi/irssi/blob/0697e3eaf14ab5c0d6529d883475f327bad59e73/src/irc/core/irc-servers.c#L313-L319

**Steps to reproduce the issue:**

1. Have an InspIRCd v3.x server
    * Without the cap module enabled
    * Connect to it with irssi
3. Upgrade InspIRCd to v4.2.0

**Describe the results you received:**

irssi users are suddenly unable to connect.

Can be mitigated by loading the [[cap]] module.

**Describe the results you expected:**

irssi to continue working. 

**Additional information you deem important (e.g. issue happens only occasionally):**

As an outsider to both projects, it looks at face value to me like this bug lies in irssi. But perhaps the inspircd team can suggest a better avenue for them to detect the absence of cap support across all supported inspircd versions?

**Output of `./bin/inspircd --version`:**

InspIRCd-4.2.0

**Comment by SadieCat** [comment]
This is irssi's bug imo. They're relying on the server accepting an empty `<trailing>` parameter in a place where it is not valid.

That said, it would probably be more helpful if we sent `ERR_NOTREGISTERED` here regardless of the parameter count. I'll look into changing that.

**Comment by SadieCat** [comment]
FWIW the correct behaviour would be for irssi to just send the full connection burst at once. If the server doesn't support capability negotiation it will end connection registration but if it does the server will respond with a capability list which can then be handled.
