### ISSUE TITLE
Unable to load m_ssl_openssl.so

### ISSUE THREAD

**Issue by slimture** [inspircd/inspircd#2105]
**Description**

Trying to start inspircd after building from source on freeBSD 14.1-RELEASE-p3 with  gmake (--version GNU Make 4.4.1).

Compiler:
 Binary:  c++
 Name:    Clang
 Version: 18.1

**Steps to reproduce the issue:**

1. Downloaded https://github.com/inspircd/inspircd/archive/refs/tags/v4.3.0.tar.gz
2. ./configure --enable-extras ssl_openssl --enable-extras ssl_gnutls
3. gmake install
4. Didn't receive any errors while building
5. Tried above 5 times and started over from scratch with new folders and deleted old folder with build files.

**Describe the results you received:**
Loading module:     m_ssl_openssl.so

[*] Unable to load m_ssl_openssl.so: /usr/home/*hidden*/insptest/run/modules/m_ssl_openssl.so: Undefined symbol "_ZN3fmt3v107vformatENS0_17basic_string_viewIcEENS0_17basic_format_argsINS0_20basic_format_contextINS0_8appenderEcEEEE"

**Describe the results you expected:**
That the server would start...

**Output of `./bin/inspircd --version`:**
InspIRCd-4.3.0

**Comment by SadieCat** [comment]
Would it be possible for you to test:

- If you `freebsd-update fetch && freebsd-update fetch install && pkg update && pkg upgrade`, reboot, delete the build directory, and then run `make install` does it work?
- If you GCC and run `export CXX=g++` and then rerun configure does it work?

I don't think this is an InspIRCd issue. I think this might be an issue with either the FreeBSD compiler or {fmt}.

**Comment by SadieCat** [comment]
Also can you check whether `/usr/local/fmt` exists?

**Comment by slimture** [comment]
> Would it be possible for you to test:
> 
> * If you `freebsd-update fetch && freebsd-update fetch install && pkg update && pkg upgrade`, reboot, delete the build directory, and then run `make install` does it work?
> * If you GCC and run `export CXX=g++` and then rerun configure does it work?
> 
> I don't think this is an InspIRCd issue. I think this might be an issue with either the FreeBSD compiler or {fmt}.

Tried with your first bullet-point. Didn't work.

/usr/local/include/fmt exists and contains:

/usr/local/include/fmt # ls
args.h		color.h		core.h		format.h	ostream.h	ranges.h	xchar.h
chrono.h	compile.h	format-inl.h	os.h		printf.h	std.h

**Comment by SadieCat** [comment]
Would it be possible for you to provide the output of:

```sh
echo "cppflags: $CPPFLAGS"
echo "cxxflags: $CXXFLAGS"
echo "ldflags: $LDFLAGS"
```

I suspect you may be getting a conflict between your system {fmt} headers and the InspIRCd-vendored {fmt} headers.

**Comment by slimture** [comment]
> Would it be possible for you to provide the output of:
> 
> ```shell
> echo "cppflags: $CPPFLAGS"
> echo "cxxflags: $CXXFLAGS"
> echo "ldflags: $LDFLAGS"
> ```
> 
> I suspect you may be getting a conflict between your system {fmt} headers and the InspIRCd-vendored {fmt} headers.

```
echo "cppflags: $CPPFLAGS"
CPPFLAGS: Undefined variable.

echo "cxxflags: $CXXFLAGS"
CXXFLAGS: Undefined variable.

echo "ldflags: $LDFLAGS"
LDFLAGS: Undefined `variable.
```

**Comment by SadieCat** [comment]
Does the error go away if you use this branch?

https://github.com/SadieCat/inspircd/archive/refs/heads/insp4+test.tar.gz

**Comment by slimture** [comment]
> Does the error go away if you use this branch?
> 
> https://github.com/SadieCat/inspircd/archive/refs/heads/insp4+test.tar.gz

Yes!

**Comment by SadieCat** [comment]
It seems like our fmtlib is conflicting with your system fmtlib. I'll see if I can find a better solution for this than manually patching it.

**Comment by slimture** [comment]
> It seems like our fmtlib is conflicting with your system fmtlib. I'll see if I can find a better solution for this than manually patching it.

But it's not just affecting my freebsd-system right? Thanks for your help!

**Comment by SadieCat** [comment]
Its not just your system yeah.

Does this also fix the problem? https://github.com/SadieCat/inspircd/archive/refs/heads/insp4+test2.tar.gz

**Comment by slimture** [comment]
> Its not just your system yeah.
> 
> Does this also fix the problem? https://github.com/SadieCat/inspircd/archive/refs/heads/insp4+test2.tar.gz

Yes it does. With both openssl and gnutls.

**Comment by SadieCat** [comment]
Thanks for testing! :)
