### ISSUE TITLE
Allow private addresses to bypass TLS requirement

### ISSUE THREAD

**Issue by LaserEyess** [inspircd/inspircd#2114]
**Description**

Inspircd 4 requires non-local connections to use TLS, which is a good idea, but excludes some valid and secure usecases. The [stated intent](https://docs.inspircd.org/4/overview/#tls) of this restriction is:

> At least one TLS module must now be enabled at build time and servers which link over the public internet must now be linked via TLS.

I think this is a good idea and promotes good security in default configurations, but it doesn't capture all usecases. For example, we link multiple servers via Wireguard, a VPN, and have no need for TLS encryption on top of the already very secure wireguard protocol. 

Therefore, my request is that ipv4 private addresses and ipv6 ULA s from this check.

**Why this would be useful**

My personal usecase is to skip double encryption, which I think is wasteful. But it also gives more flexibility when setting up an internal network of IRC servers, since it doesn't require setting up certs as well as DNS for what is really only internal connections. 

I believe this also is consistent with the intent of requiring public facing connections to be encrypted.

**Comment by SadieCat** [comment]
I considered this when I made the change but the problem is we can't tell what those private addresses are actually being used for and it is reasonably common for those addresses to be used in cases where snooping is actually a concern (e.g. corporate LANs where users snooping on unencrypted traffic is actually a concern).

Double encryption isn't particularly wasteful, I doubt it'd even be 1% of the CPU/memory usage of your IRC server. You can just use the same certs as for client connections or just give it a self-signed certificate that expires in 10 years and specify a cert fingerprint in the link block.

**Comment by LaserEyess** [comment]
I would imagine that a corporate LAN has exactly the resources and security infra needed to manage DNS + a CA + cert distribution. I don't have those resources, and I would just like to encrypt internet-facing traffic only. 

As for how to detect this, on Linux you can check the interface type and if it's `tun`, `tap`, `wireguard`, etc., you can assume it's a secure connection.

**Comment by SadieCat** [comment]
>I would imagine that a corporate LAN has exactly the resources and security infra needed to manage DNS + a CA + cert distribution. I don't have those resources, and I would just like to encrypt internet-facing traffic only.

Doing this is not much harder than distributing configs for your network already. You can just generate a key and cert with `openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 3650 -nodes -subj "/CN=irc.yourdomain.com"` and then put the fingerprint (`openssl x509 -fingerprint -noout -in cert.pem`) in your link config.

**Comment by LaserEyess** [comment]
The problem is `irc.mydomain.com` points to my *external* ip address, not to my wireguard IP address. Does inspircd let you just ignore cert domain? I guess it's a static IP, so I could use that instead? But now I'm asking, what's the point? This isn't giving me any security benefit, it's just extra configuration and management on my end.

Or I would have to open a brand new port on my server and route the connection over the internet, something which is strictly less secure than routing over wireguard.

**Comment by SadieCat** [comment]
>The problem is irc.mydomain.com points to my external ip address, not to my wireguard IP address. Does inspircd let you just ignore cert domain? I guess it's a static IP, so I could use that instead?

It doesn't have to match a real DNS hostname you can just use your server name. Using a certificate fingerprint in the link block moves security from the CA system to your server config.

> But now I'm asking, what's the point? This isn't giving me any security benefit, it's just extra configuration and management on my end.

Unfortunately compromises have to be made and your use case is very niche vs the risk from exposing chat over users. People have died from having their IRC comms snooped before. If this alternative really bothers you that much you can just edit the source to remove the `capab->remotesa.is_local()` check in the spanningtree module.
