### ISSUE TITLE
Fails to install, maybe incompatible CPU architecture

### ISSUE THREAD

**Issue by jckirton** [inspircd/inspircd#2123]
**Description**

When trying to install the current version of InspIRCd on an Ubuntu 22.04.1 server, it fails, quoting missing dependencies.

**Steps to reproduce the issue:**

Follow ubuntu install guide until running "sudo apt-get install ./inspircd_4.3.0.ubuntu24.04.1_amd64.deb"

**Describe the results you received:**

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'inspircd:amd64' instead of './inspircd_4.3.0.ubuntu24.04.1_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 inspircd:amd64 : Depends: libargon2-1:amd64 (>= 0~20171227) but it is not installable
                  Depends: libc6:amd64 (>= 2.38) but it is not installable
                  Depends: libgcc-s1:amd64 (>= 3.3.1) but it is not installable
                  Depends: libgnutls30t64:amd64 (>= 3.8.2) but it is not installable
                  Depends: libldap2:amd64 (>= 2.6.2) but it is not installable
                  Depends: libmysqlclient21:amd64 (>= 8.0.22) but it is not installable
                  Depends: libpcre2-8-0:amd64 (>= 10.22) but it is not installable
                  Depends: libpq5:amd64 (>= 9.1~) but it is not installable
                  Depends: libpsl5t64:amd64 (>= 0.16.0) but it is not installable
                  Depends: libre2-10:amd64 (>= 20160901) but it is not installable
                  Depends: libsqlite3-0:amd64 (>= 3.5.9) but it is not installable
                  Depends: libstdc++6:amd64 (>= 13.1) but it is not installable
                  Depends: libio-socket-ssl-perl:amd64 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Describe the results you expected:**

Not the above.

**Additional information you deem important (e.g. issue happens only occasionally):**

It is a Ubuntu 24.04.1 server, ARM architecture

**Output of `./bin/inspircd --version`:**

**Comment by SadieCat** [comment]
>It is a Ubuntu 24.04.1 server, ARM architecture

You are trying to install an x86-64 package on AArch64. The packages are only built for x86_64 currently as I do not have any AArch64 hardware to build them on.

If you want to build your own packages you can with [the package builder](https://github.com/inspircd/package-builder).

Once you've installed the dependencies you can build a package for just your system with `INSPIRCD_PACKAGES=deb INSPIRCD_DEB_PLATFORMS=ubuntu-24-04 INSPIRCD_VERSION=4.3.0  ./build.sh`
