### ISSUE TITLE
Suggestion about geoban module

### ISSUE THREAD

**Issue by z0ugl4** [inspircd/inspircd#2134]
### Description

Hello there,

I want to make a small suggestion for inspircd v4, specifically if geoban module has been loaded then have the option to hide the country for ircops or any custom class.

Example:

        <connect name="Custom"
         allow="*"
         commandrate="1000"
         fakelag="on"
         globalmax="3"
         hardsendq="1M"
         limit="5000"
         localmax="3"
         maxchans="30"
         maxconnwarn="no"
         pingfreq="2m"
         recvq="8K"
         hidecountry="on/off">
         
### Why this would be useful?

I think it would be useful to someone who wants to hide country (as an extra privacy option for ircops or any custom class).

**Comment by SadieCat** [comment]
Why would you want to hide it? Its only shown in WHOIS if you have the geoban module loaded and I'm not sure why you'd want the geoban module loaded but not allow people to see the location of users as it makes it hard to know what country to ban.

**Comment by z0ugl4** [comment]
I agree with you from one side, it's useful module and gives you the ability to block users from any country. From other side, it's just an extra option. For example opers can set +H and hide oline status. I mean with the logic that if they want, they could also hide the country they are connecting from. Besides that, I can see and other reasons why it would be useful.

In any case, I'm not saying for myself, it's easy to hide the real country I'm connecting from with other ways, it's simply a suggestion.

**Comment by SadieCat** [comment]
I'm happy to add new features but features for the sake of features without an actual use case and with no users that want it is not something I want to maintain.
