### ISSUE TITLE
RPL_Created showing (re)start date not creation date.

### ISSUE THREAD

**Issue by rwills32** [inspircd/inspircd#2142]
### Description

On a server restart the ircd displays the creation date inspircd has been (re)started.  RPL_Created is showing the time of the instance the ircd is (re)started not and not that of the date when it was compiled.

### Steps to reproduce the issue

Restart the ircd to change the creation date.

### Describe the results you received

Newer date of when the ircd was created.  For example on my server I created the server in June 2024 on the last release of 3.17.1 so I expected it to send RPL_Created as "This server was created 14:14:14 June 28 2024" but instead it shows the restart date of This server was created 14:01:35 Dec 22 2024.  

### Describe the results you expected

Creation date of when the ircd was compiled I.e "This server was created 14:14:14 June 28 2024.  This helps new users to a network get a better feel of if a server has been created for a longer period of time and not something that has just been spawned up recently, if a user needs to know the uptime of a server after the creation date and if it's important to users is available via '/stats u' anyway.

To use another ircd as example connecting to a IRCu server losangeles.ca.us.undernet.org is presented as "This server was created Mon Nov 15 2021 at 08:04:09 PST" yet '/stats u' presents *** Server Up 87 days, 16:53:26 therefore the rpl_created is not showing the time the server instance was (re)started but when it was actually compiled.

### InspIRCd version

Inspircd-3.17.0

**Comment by SadieCat** [comment]
This is intentional behaviour.

https://modern.ircdocs.horse/#rplcreated-003

Using the compilation time doesn't make sense imo as it breaks reproducible builds and doesn't provide any useful information as because of InspIRCd's modularity would just show the time that core_info is compiled.

**Comment by rwills32** [comment]
The link you shared states it can be either restart or creation date, however rfc2812 states creation date as most other major ircds also follow the creation date including unrealircd (also being modular).  I'm not familiar with the ircds you've listed.

I see no issue with listing when core_info was compiled and if people need to go further and know when a server was restarted then /stats u provides this.  The argument for "using the compile time " for conncting clients could arguably be said the same for when the time the server was last restarted.  Its part of the nuneric 003 that Knowing when the server was last created and one of the things I look at when invited to new networks as it gives an indication if it's a newly popped up network or got themsleves established. 

Has the issue been rested against reproducible builds to see if the creation date would effect it, a build time value should be the same as a restart date value and aslong as it isnt future tense and has a date regardless of what it is? Why isn't reproducible builds based on the version rather than time/date or have I misunderstood you on that?

**Comment by SadieCat** [comment]
> The link you shared states it can be either restart or creation date, however rfc2812 states creation date as most other major ircds also follow the creation date including unrealircd (also being modular). I'm not familiar with the ircds you've listed.

Yeah, and we use the start date as per the Modern IRC spec. InspIRCd was written from scratch and has some design decisions which are different to that of all of the irc2 derivatives like Unreal.

> one of the things I along with many look at when invited to new networks as it gives an indication if it's a newly popped up network or got themselves established.

You are mistakenly relying on this information for that purpose. If the compile tome was used there it

1. Wouldn't actually show anything because a lot of InspIRCd users use packages so it would show the time the packaged version was compiled

2. Would change whenever a network rebuilds their server from scratch after an update or whenever core_info is updated.

> Why isn't reproducible builds based on the version rather than time/date or have I misunderstood you on that?

The way that information is embedded into the server means that when the server is recompiled in a clean environment the date would change making the binary different. This would make the build non-reproducible.

**Comment by rwills32** [comment]
Ok, I understand what the design of inspircd core and packages a bit more now and the future its heading for and I respect that, however a ircd that takes rpl_create date and manipulates it to the (re)start date isn't true in the value's it presents.  Further more inspircd should maybe just tweak the 003 sent to clients as "This server was last restarted on.... " rather than using "This server was last created on..." which no longer represents what the rfc states it should be irrespective of modern vs old specs.

**Comment by SadieCat** [comment]
> however a ircd that takes rpl_create date and manipulates it to the (re)start date isn't true in the value's it presents

To be clear, it has *never* in any IRC server been the date that the server was actually created. As far as I know in all irc2 based servers it is the date that the configure script was run or when it was most recently compiled. From a quick check servers of the official UnrealIRCd network has a date in 2024, DALnet has a date of 2022, and IRCnet has a date of 2021. All of these networks are at least two decades old if not older.

**Comment by rwills32** [comment]
> Quote reply

Exactly! The creation time (i.e when it was compiled) but you've tried to prove it was always the restart time for "newer" rfc.  
Just for reference taken from IRCNet to back up ircd's do in fact use the creation/compile date. 
```
*** Your host is tngnet.ircnet.io, running version 2.11.2p3+0PNv1.06
*** This server was created Sun Apr 16 2023 at 19:34:05 CEST

*** Server Up 118 days, 7:15:25
*** u End of STATS report
```

If what you say that IRCds use the restart time then that should be saying "This server was created Monday, 2 September 2024..." with an uptime of only 118 days.  I can restart our newly created unrealircd and copy/paste it won't show the restart date either .

Needless to say after your approach our network team agreed and completed our migration off of inspircd and anope as we feel that.  I'm done trying to prove something that is unique to inspircd and does exist on other ircd's, further comments (which should of been obvious from the closure of this) isn't necessary.
