### ISSUE TITLE
OP-Moderated +m

### ISSUE THREAD

**Issue by deathspawn** [inspircd/inspircd#226]
Was looking for this sort of thing, so like, when you set +m, instead of the messages being blocked, they get sent to ops and above. Could even make it so you can set a certain mode (or rank number for custom modes) and anyone of that value or higher can see messages.

Can be useful in places used mainly for updates and let people sit in the room and watch updates go by without distractions and still be able to use bot commands. Or in channels where you want to make it so other users cannot see a private issue but you still want to see what that issue is. Like a private help channel.

**Comment by Juliaria08** [comment]
> +z is already `m_sslmodes`.

Then the op  mod can be +Z?

**Comment by SadieCat** [comment]
This module has been committed to inspircd-contrib, you can install it with `./modulemanager install m_opmoderated` or by placing the source file in the src/modules directory.

https://github.com/inspircd/inspircd-contrib/blob/master/3.0/m_opmoderated.cpp

**Comment by Juliaria08** [comment]
> ./modulemanager install m_opmoderated

So i need to manualy recompile insp?
