### ISSUE TITLE
Keep unregistered users from a banned mask out of a channel but not registered ones

### ISSUE THREAD

**Issue by Robby-** [inspircd/inspircd#247]
This is a feature request to be able to ban masks/ranges from an ISP (or even an entire ISP) on a channel, but still allowing registered users from that ISP in. However, registered users that get banned by channel ops should still stay banned. The current extbans do not allow for such a thing.

Imagine the following situation:
Some user: Lamer (~blah@4424-adsl.isp.com)
This user is being annoying, always changing IP addresses to get around bans etc but does not register with services.
So, I set a ban on *!*@*-adsl.isp.com but this keeps everyone matching out which is not desirable. So I want to add an exception for registered users that match that banmask, I'd do this via +e but that would again allow everyone matching to get in and even do banwalking when they get banned. The current 'R' extban is not in any way useful in this case. An exception on R:\* is for example not acceptable as nobody would be able to get banned anymore.

It would be very handy if we could set broad channel bans like the above, but still allowing registered users in AND still keep the ability to ban individual users via their hostmask regardless of being registered or not.

I was thinking of something like:
Assume 'J' would be the extban responsible for allowing matching registered users in (keep in mind individual users still must be able to get banned).
Set a ban on *!*@*-adsl.isp.com
and then set an exception on J:*!*@*-adsl.isp.com
But make J: only work when there's a ban with the exact same mask and not some other that would also match it.

**Comment by voidzero** [comment]
It appears that this no longer works. I'm trying to ban `U:*!*@*#channel` and users still get through.

**Comment by voidzero** [comment]
a ban of type `*!*@*` with an exempt of `R:*` also doesn't work for me.

**Comment by Robby-** [comment]
You're using this functionality wrong. You can't combine the `U:` extban with the redirect extban, like you are trying to do. They only work by themselves, so like `U:*!*@some.bogus.host.example.tld` and `*!*@some.bogus.host.example.tld#somechannel`. As for the `R:` extban, it only takes services account names, such as registered nicknames, for example: `R:voidzero`.

**Comment by voidzero** [comment]
Thanks @Robby- for responding.

What I was hoping to do, is redirect unregistered/unidentified users to what I call a lobby - a channel with auditorium mode - where the topic tells them to register or identify to nickserv, after which they can join the main chatroom. So: redirect unregistered users, allow registered users.

This is the most user-friendly way I could think of for our visitors. The thing is, we are getting massive spam floods from some idiot who keeps rejoining with different IPs, it's hard to keep him out, he always manages to slip messages through. So I figured that the registration requirement will at least help to slow him down - we can then ban accounts he has made. But in cour case many visitors use webchat, and are not tech savvy. Getting "you are banned" without further explanation really confuses things too much.. these people for the most part only join to partake in a conversation during a live radio show.

**Comment by voidzero** [comment]
Correction: `ban *!*@*#somechannel` and exempting `R:*` does work. I encountered another bug where joining a group with a new nickname, and then trying to join, does not lift the ban (user has to reconnect and identify to the nick again), but other than that, this seems to work after all.
