### ISSUE TITLE
[2.0.7] Permission Denied - Oper type NetAdmin does not have access to set user mode s

### ISSUE THREAD

**Issue by helloall** [inspircd/inspircd#257]
I am using Windows 7 and trying to configure inspircd  and everything in startup.log seems to be fine. The first lines of the log are the modules that are loaded. The last line: "Thu Jul 12 22:12:14 2012: Startup complete as 'irc.test.info'[996], 24000 max open sockets" and I have no errors.
I am trying to oper up with the command "/oper username password" and I get the following error:
- irc.test.info sets mode: +o
- irc.test.info sets mode: -x

globalop.chatspike.net is now your displayed host

You are now a NetAdmin 

Permission Denied - Oper type NetAdmin does not have access to set user mode s

My oper config is this:

```
<class name="Everything" commands="*" privs="*" usermodes="*" chanmodes="*">

<type name="NetAdmin" classes="Everything" vhost="globalop.chatspike.net" modes="+s +cCqQ">

<oper name="Brain" password="s3cret" host="*" type="NetAdmin">
```

We are running the m_opermodes.so module which is required. 
I think I don't have the privileges  to see server notices, although in my config I use usermodes="*" etc. So what am I doing wrong?

**Comment by Luffy** [comment]
Hello! I'm currently using manjaro and connecting to InspIRCd via HexChat and I still got this problem.. 
`[22:22:25] --- #lobby :You must have channel op access or above to set channel mode o`
I also tried the editing opers.conf just like @helloall did with a new class but no chance. Any suggestions? Currently running InspIRCd-2.0.25.

**Comment by SaberUK** [comment]
This is a bug tracker. For support please visit irc.inspircd.org #inspircd.
