### ISSUE TITLE
Add some hardening

### ISSUE THREAD

**Issue by DrWhax** [inspircd/inspircd#286]
Hi,

I added and tested some extra hardening flags to achieve a safer inspircd build: https://github.com/DrWhax/patches/commit/5da2f8e113de201b67604881d6adc470652243db
The above patch is for GNUmakefile, this will achieve:

./checksec.sh --file inspircd 
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH      FILE
Partial RELRO   Canary found      NX enabled    No PIE          No RPATH   No RUNPATH   inspircd

I tested this at a: Linux vks18708 2.6.32-042stab059.7 #1 SMP Tue Jul 24 19:12:01 MSK 2012 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 12.04 machine.

Build fine with openssl or gnutls as option.

Unfortunately -fPIE and -pie failed, this is due to external libraries like gnutls and openssl who don't come with pie support on most distro's.

I think it would be really nice if we can work towards a safer binary for inspircd for *BSD and linux!

**Comment by SaberUK** [comment]
>To be honest, it'd be a somewhat better solution to respect the CXXFLAGS environmental variable, 

This has since been implemented. The build system will now pick up your custom build flags from CPPFLAGS/CXXFLAGS/LDFLAGS in the environment which you can  use if you want to use extra hardening.
