### ISSUE TITLE
Support WHOX

### ISSUE THREAD

**Issue by DasBrain** [inspircd/inspircd#31]
It would be nice if InspIRCd would support WHOX. It is an enchantment for the /who command.

WHOX is supported on many different IRCds and is a useful enchantment.
Basically the client can ask only for the informations it needs. 

The benefits are:
- Possible traffic reducing, because not all fields might be requested and therefore sended.
- Possibility to add extra fields in extended who queries like the accountname.

For more information read:
http://hg.quakenet.org/snircd/file/37c9c7460603/doc/readme.who
Please note that all known IRCds that support whox add WHOX in the 005 nummeric. This is not mentioned in the documentation above.

Implementation Notes:
It is required that each module can add new flags and fields. This is especially required for m_services_account.

If I have the time I will try to implement this.

**Comment by JeDa** [comment]
4 years and still WHOX is not on InspIRCd...

**Comment by Adam-** [comment]
I do have an old pull request open for this, #810

**Comment by jwheare** [comment]
Docs moved to https://github.com/quakenet/snircd/blob/master/doc/readme.who

**Comment by Shawn-Smith** [comment]
Any chance on getting this implemented? The ircv3 spec specifically calls for this in account-notify,

**Comment by SaberUK** [comment]
WHOX support has been implemented in 227484c6c068eee8251cc4f13a0676bd8b2ecc8d.
