### ISSUE TITLE
WebSocket support in m_httpd

### ISSUE THREAD

**Issue by SaberUK** [inspircd/inspircd#351]
It would be nice if we had [WebSocket](http://en.wikipedia.org/wiki/WebSocket) support in `m_httpd`. Someone requested support for a module for WebSocket connections to an IRC server (similar to `m_xmlsocket` for old versions of Adobe Flash) and implementing it using `m_httpd` would probably be the best way to go about it.

**Comment by attilamolnar** [comment]
This has been implemented.

**Comment by kklouzal** [comment]
Is there any provided documentation for configuration?

**Comment by SaberUK** [comment]
Read conf/examples/modules.conf.example.

**Comment by kklouzal** [comment]
I just read through the entire thing, not a single mention of WebSocket. m_httpd module doesn't mention anything about it either. I can only assume enabling m_httpd will enable WebSocket based connections? I ONLY need WebSocket connections though, no statistics or any of those things the module provides.

**Comment by SISheogorath** [comment]
How about: https://github.com/inspircd/inspircd/blob/master/docs/conf/modules.conf.example#L2022-L2027

**Comment by kklouzal** [comment]
Ahh it's here in the one provided on GitHub but not in the files provided from the installer. Thank you very much!

**Comment by SISheogorath** [comment]
Websocket is only available in alpha.

**Comment by kklouzal** [comment]
Unfortunately this distribution does not include visual studio project files or use something like CMake.. 👎
