### ISSUE TITLE
No connect to LDAP Server?!

### ISSUE THREAD

**Issue by offlinehoster** [inspircd/inspircd#428]
I have a brandnew compiled version of inspircd.
The LDAP settings should be fine and is matching to your example config..
Is there a LDAP attribute which one is needed or?!

I see connects to the ldap server in my ldap.log but there is no query with a username or anything else...the ldap server is available and he is working fine...i can access with all my user credentials by using apache directory studio...

Any ideas? Maybe a Problm with wildcard certificates?

Wed Feb 20 23:55:46 2013: ANNOUNCEMENT: LDAP server has gone away - reconnecting...

**Comment by mbenalaya** [comment]
Dear einajh,

I have the same problem. 
Could you please explain how can to configure the LDAP server certificate on inspircd ?

Thanks in advance

**Comment by SaberUK** [comment]
@mbenalaya You might be better off asking in our support channel at irc.inspircd.org #inspircd.

**Comment by mbenalaya** [comment]
@SaberUK I tried but nobody answer.

**Comment by ijaxon** [comment]
Hey! If you're on Ubuntu makes sure you have an entry for your ldap servers cert.

/etc/apparmor.d/usr.sbin.inspircd 

  # needed for ldapauth
  /etc/ldap/ldap.conf r,
  # Needed to see the ldap server's certificate. File owned by irc:ssl-cert
  /etc/ldap/ITSNAME** r,
  /etc/ssl/IRCTLSCERTS** r,
