### ISSUE TITLE
ctcp version - idle changeing problem

### ISSUE THREAD

**Issue by huntitus** [inspircd/inspircd#438]
Hy,
We are found some problem with the ctcp version. If someone send the "version" command, after the client answer the client idle time is changing.

Thank You for the help/answers or bugfix.
Regards.: huntitus /DumaNet/

**Comment by gangrenejellybean** [comment]
I realise this is an old bug report, but I also consider this behaviour to be broken.

I'm not aware of any other ircd other than inspircd that resets idle time when a client sends a NOTICE. EFnet, Undernet and Freenode certainly don't have this behaviour.

Can the historical behaviour of NOTICE be restored?

**Comment by attilamolnar** [comment]
@gangrenejellybean

>I'm not aware of any other ircd other than inspircd that resets idle time when a client sends a NOTICE. EFnet, Undernet and Freenode certainly don't have this behaviour.

If this is indeed true we should look into changing the behavior on NOTICE, please open an issue about idle time reset on NOTICE so it can be tracked.

**Comment by Robby-** [comment]
This is true also for IRCnet's ircd and derivatives. I disliked this behavior at first but I've grown used to it. If this were to be "fixed" in InspIRCd, it should be configurable.
