### ISSUE TITLE
[Proposal/Feature] Allow invisibility for normal users

### ISSUE THREAD

**Issue by BlacklightShining** [inspircd/inspircd#441]
Frankly, usermode `i` seems pretty useless to me; I never use `WHO` myself and don't know anyone who even knows such a command exists. What would be more useful is a mode that would make `WATCH`, `WHOIS`, `ISON`, etc. behave as if the target user doesn't exist, unless the two users share a common channel.

**Comment by SaberUK** [comment]
I don't think its impossible to implement this in a waythat isn't trivially bypassable by doing `NICK target` to check if it exists, sorry.
