### ISSUE TITLE
[SUGGESTION]: Add 'shun' option in /filter actions

### ISSUE THREAD

**Issue by westor7** [inspircd/inspircd#483]
Hello,

I wanna suggest to add the SHUN option tin actions of filter so if filter triggers with shun action then an shun will be add to the users host.

e.g: /quote filter _testt_ shun \* :testt filter

[15:43:25] -> Server: filter _testt_ shun \* :testt filter
[15:43:29] -darkness2.chatnet.gr- **\* Invalid filter type 'shun'. Supported types are 'gline', 'none', 'block', 'silent' and 'kill'.
- Thanks!

**Comment by cehib** [comment]
@attilamolnar hi you closed my issue 1158 but i come here and there is no solution pls help ?

**Comment by Heufneutje** [comment]
It was closed because it was a duplicate of this issue. There's no need to track the same issue multiple times. It's marked to be implemented in InspIRCd 2.2.

**Comment by cehib** [comment]
nearly 3 years open and not fixed, thats why i open new ticket

ty anyway will go back to unreal for now

**Comment by SaberUK** [comment]
Opening new tickets will not make it get added faster. We only have a limited amount of resources and can't add every feature at once.
