### ISSUE TITLE
Log rotation

### ISSUE THREAD

**Issue by HelixSpiral** [inspircd/inspircd#496]
I noticed that there doesn't seem to be an option for log rotation. It'd be nice if there was a basic implementation to rotate logs on a daily or weekly basis.

Eg:

```
<log method="file" type="OPER" level="default" target="logs/opers.log" rotate="daily">
```

If rotation is set it would rename `opers.log` to `opers-day.month.year.log` or something.

**Comment by SaberUK** [comment]
@Shawn-Smith You might want to check out inspircd/inspircd-extras#67.

**Comment by SadieCat** [comment]
v3 ships a logrotate config as of the latest release.
