### ISSUE TITLE
Overhaul of channel-based flood settings.

### ISSUE THREAD

**Issue by Shawn-Smith** [inspircd/inspircd#499]
Instead of having many different modes to handle different types of flood settings it would be nice if we could consolidate all of this under one mode, +f.

I was thinking if we changed this to a list mode then we could have other modules that, if they wanted to, could add features to the +f mode using the syntax:
`+f [flood-type]:[[function]:lines:seconds]`
Where `[flood-type]` is the type of flood protection (message, nick, ctcp, etc) and `[function]` would be kick/mute/ban/block, etc

So we could do something like:
`m_flood` would provide the +f channel mode and do nothing else (the other modules would require `m_flood` to be loaded).

`m_messageflood` would provide: `+f message:[kick:lines:seconds]`
`m_nickflood` would provide: `+f nick:[kick:nick-changes:seconds]`
`m_blockcaps` would provide: `+f caps:[block:percentage:minimum-length]`
(They would all provide other functions besides the ones I added in the examples above, I put their default behavior in the examples.)

And so on and so forth.

Current modules that I *think* could be implemented into the +f mode:
* m_nickflood (+F)
* m_blockcaps (+B)
* m_joinflood (+j)

This would free up 3 modes entirely that could then be used for other purposes

Current modules that I *think* could add functionality to +f and enhance their current state
* m_blockcolor (+c, block color only if it is over a limit)
* m_knock (+K, block knocks if it is over a limit)
* m_noctcp (+C, block CTCPs only if over a limit)

For these modes, perhaps we could do something like: `+f color:[setmode:lines:seconds]`
and the module would then set the mode that is related to the `color` setting (in this case, it's +c) if there are more than so many lines in so many seconds with color in them.

**Comment by attilamolnar** [comment]
This doesn't worth the effort.

**Comment by BlacklightShining** [comment]
Whoa, whoa, whoa. Two and a half years, and then _this?_ You're not even going to leave it open in case someone else wants to implement it?

**Comment by SaberUK** [comment]
This isn't something which is trivial to implement and would break a ton of things. Not worth the effort especially considering that named modes are the future and will be standardised with IRCv3.

**Comment by attilamolnar** [comment]
Even if you ignore the breakage and effort required, implementing this would be a step backwards because this hides modes behind magic strings, modes which are now exposed to clients directly.
