### ISSUE TITLE
Doesn't work in Windows 8

### ISSUE THREAD

**Issue by narucy** [inspircd/inspircd#505]
Every firewall setting off, also setting file just same windows 7 PC, I can connect with irc://[::1] but Windows 8, I can't connect. also I don't know how to enable ipv4 connect in windows inspircd. Please tell me conf file example. (I understand pretty tough work Windows/Posix OS compatible source code writing architecture, Still dod you went to support Windows computer?)

**Comment by ManicSec** [comment]
aaa
