### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NGTmeaty** [inspircd/inspircd#525]
[1;32mInspire Internet Relay Chat Server[0m, compiled on May  6 2013 at 15:33:56
[1;32m(C) InspIRCd Development Team.[0m

Developers:
[1;32m Brain, FrostyCoolSlug, w00t, Om, Special, peavey
    aquanight, psychon, dz, danieldg, jackmcbarn[0m

Others:         [1;32mSee /INFO Output[0m
InspIRCd Process ID: [1;32m32747[0m
Could not read "conf/op.conf" for include at /usr/home/mmoempire/inspircd/inspircd-2.0.12/run/conf/inspircd.conf:118:29 (inside tag include at line 118)

It doesnt load conf/op.conf i renamed opers to op.
please help

**Comment by mattford** [comment]
2 years later but I thought I'd comment since I'm here. This happens if you run the binary directly from the bin file instead of using ./inspircd start in the root directory

**Comment by Spyneur** [comment]
Thanks you mattfordn very helpful ;)
