### ISSUE TITLE
PID file handling "broken" regarding setuid handling

### ISSUE THREAD

**Issue by abustany** [inspircd/inspircd#566]
When setting up InsIRCd to run as another user, it apparently does not try to write the PID file before setuid'ing. This means that I can't configure it to write a PID file to /var/run for example, and still have it running as a non-root user...

**Comment by SaberUK** [comment]
I'm not really sure if theres any option here other than to disallow the user from changing `<pid:file>` after startup. Does anyone have any ideas?
