### ISSUE TITLE
Write log messages to an SQL database

### ISSUE THREAD

**Issue by androos** [inspircd/inspircd#610]
You can read in the wiki under log configuration:
"method: What sort of backend to log to. Currently "file" works out-of-box, and you need to load m_sqllog and a SQL provider module for a "sql" method. "

So I want to use the sql method but the sqllog module is not available in inspircd 2.0.

So logging to database is impossible in 2.0? 
Is there planed anything to make it possible in future versions?

**Comment by HNJAMeindersma** [comment]
Any updates on this matter @attilamolnar?

**Comment by SaberUK** [comment]
There is not a SQL logging system for 2.0 currently as the logging system does not support module-provided loggers. I've got a local branch with a logging cleanup and it will hopefully be included with the 3.0 release.

**Comment by SadieCat** [comment]
This has been implemented in git master.
