### ISSUE TITLE
can't make install owned by root

### ISSUE THREAD

**Issue by Nowaker** [inspircd/inspircd#697]
> Error: You must specify a non-root UID for the server
> 
> If you are making a package, please specify using ./configure --uid

I am making a package inspircd-git for Arch Linux. I already use --uid. It doesn't work.

```
./configure \
  --enable-extras=m_geoip.cpp \
  --enable-extras=m_ldapauth.cpp \
  --enable-extras=m_ldapoper.cpp \
  --enable-extras=m_mysql.cpp \
  --enable-extras=m_pgsql.cpp \
  --enable-extras=m_regex_pcre.cpp \
  --enable-extras=m_regex_posix.cpp \
  --enable-extras=m_regex_tre.cpp \
  --enable-extras=m_sqlite3.cpp

./configure \
  --uid=0 \
  --prefix=/usr/lib/inspircd \
  --binary-dir=/usr/bin \
  --module-dir=/usr/lib/inspircd/modules \
  --config-dir=/etc/inspircd \
  --data-dir=/var/lib/inspircd \
  --log-dir=/var/log/inspircd \
  --enable-gnutls \
  --enable-openssl \
  --enable-epoll

make DESTDIR="$pkgdir" INSTUID=0 install
```

I tried various ways. --uid=root or --uid=0. With or without INSTUID. When I don't set INSTUID, /usr/lib/inspircd is owned by my user UID instead of root.

**Comment by kuz-sysadmin** [comment]
> Alternately, you can edit INSTUID in the makefile.

and if i were to edit the UID, what exactly would i even set it to?

**Comment by SadieCat** [comment]
This issue is over six years old. If you want to build as root you can should pass `--uid root` to configure to specify the user to run as and then run make install.

If you have any more questions then please ask in irc.inspircd.org #inspircd. Thanks.
