### ISSUE TITLE
Auditorium does not show joined user to ops after they quit: changing host

### ISSUE THREAD

**Issue by md-5** [inspircd/inspircd#745]

**Comment by genius3000** [comment]
I was going to create a new issue, then found this one still open.

To add to the issue, the cyclehosts quit line is also sent back to the user cycling, when able to see in an auditorium channel.
This causes varying issues in different clients. ZNC doesn't seem to do much other than say "<*status> You quit [Changing host]", didn't notice any other issues from it. Quassel takes the quit line more seriously and sets all active channel buffers inactive, really screwing up channel messages.

I'm not sure if this is okay to fix in 2.0 yet, but hopefully for sure in 3.0.
Having a look at the cyclehosts code, is there any need to send the quit line to the exceptions list, when a join can't be sent after that?
Seeing that "/names" is a workaround to fix the channel nicklist, could there be a check added to not send the quit line to the cycling user at least?

Thanks to @attilamolnar for seeing the convo in #quassel and mentioning that it's likely an issue with an auditorium channel.

**Comment by attilamolnar** [comment]
@genius3000 I've fixed that issue, it will be in the next 2.0 release.

**Comment by genius3000** [comment]
Perfect, thank you!

**Comment by SaberUK** [comment]
This should be fixed in the v3 branch afaik.
