### ISSUE TITLE
MONITOR module to replace WATCH

### ISSUE THREAD

**Issue by Shawn-Smith** [inspircd/inspircd#748]
`MONITOR` is part of the IRCv3.2 spec. It's intended to replace the `WATCH` protocol eventually. I think we should aim to have `MONITOR` support in 2.2, and possibly backport it to 2.0 since it is a fairly useful feature.

Link to the `MONITOR` spec: http://ircv3.org/specification/monitor-3.2

**Comment by attilamolnar** [comment]
A module supporting MONITOR might be added, however it will not replace WATCH for the foreseeable future. WATCH is widespread while MONITOR is less so. Recently ircd-ratbox has stopped supporting MONITOR:

    r28669 | androsyn | 2015-09-29 11:04:13 -0400 (Tue, 29 Sep 2015) | 1 line
    remove monitor, nobody really uses it, rebuild automake to reflect its removal as well

**Comment by attilamolnar** [comment]
MONITOR support has been implemented.
