### ISSUE TITLE
Logging Event Types Inconsistent With Documentation (hardcoded to "snomask")

### ISSUE THREAD

**Issue by scub** [inspircd/inspircd#749]
## Reproduction

The following directives when placed within inspircd's configuration should split client connect/disconnects into a secondary log.

E.g. https://github.com/inspircd/inspircd/blob/master/docs/conf/inspircd.conf.example#L835

```
<log type="USERS" level="default" target="/var/log/ircd/connection.log">
<log type="* -USERS -USERINPUT -USEROUTPUT" level="default" target="/var/log/ircd/inspircd.log">
```

Managed to trace the issue to the event type being hardcoded with the value of "snomask", within snomask.cpp for all effected types.
https://github.com/inspircd/inspircd/blob/master/src/snomasks.cpp#L130

It would appear that the scaffolding for this functionality was already put into place using the desc parameter passed to Snomask::Send(), but looking at the desc (event type) assigned to the individual snomasks there is still a disconnect between the documentation and the presented types.

Log Events Effected: USERS (CONNECT QUIT) KILL OPER XLINE

**Comment by SaberUK** [comment]
Fixed in 8faa6ac.
