### ISSUE TITLE
Cloacking module suggestion

### ISSUE THREAD

**Issue by H7-25** [inspircd/inspircd#752]
Actualy m_cloacking module using half mode, in many don't give the ability to the chanop to ban  a subnet when user ip resolve an host . 
Modifing LastTwoDomainParts function , moving if (dots >= 3) to if (dots >= 4), should reduce the number of this case .

Example : 

host233-49-dynamic.33-79-r.retail.telecomitalia.it    real host
SimosNap-ktdadk.retail.telecomitalia.it    clocked host with actual function 
SimosNap-ktdadk.33-79-r.retail.telecomitalia.it  moving dots limit to 4

Shorter hostnames will be not affected by this modify : 

ppp-180-72.27-151.libero.it

will be always : 

SimosNap-7b2aj8.27-151.libero.it

**Comment by SaberUK** [comment]
This has been implemented in #1353.
