### ISSUE TITLE
Channel mode to limit joins to a class

### ISSUE THREAD

**Issue by ghost** [inspircd/inspircd#790]
Hi

On our network our webchat users are placed in to their own class `webchat-users` for example. 

We are looking for a module that adds a channel mode where only users in this class can join the channel. 

Classes the channel mode allows could just be set in the `inspircd.conf` ...

If someone could help out, we'd be willing to test it etc. straight away.

Thanks

Steve

**Comment by attilamolnar** [comment]
This is being implemented by @johanna-a in #1150.

**Comment by attilamolnar** [comment]
Support for this has been merged, thanks to @johanna-a for her work on this.
