### ISSUE TITLE
m_cgiirc should not use resolved hostname if DNS is disabled

### ISSUE THREAD

**Issue by hifi** [inspircd/inspircd#795]
When DNS resolving is disabled in server config, m_cgiirc still uses the hostname field of a WEBIRC connecting user which causes all WEBIRC users to have hostname resolved and all regular users not.

**Comment by SaberUK** [comment]
This is no longer an issue as m_cgiirc *always* does a DNS lookup now because of faulty gateways sending invalid hostnames.
