### ISSUE TITLE
Removal of usermode +s as the SNOMASK mode

### ISSUE THREAD

**Issue by Shawn-Smith** [inspircd/inspircd#798]
Basically, in short, I would like to see server notices handled in a WATCH/MONITOR-type fashion.

So intead of `+s +xyz` we would have something like: `SNOMASK + remoteconnections,localconnections,localkills,remotekills`

Some command syntax:
`SNOMASK LISTFULL` - List all the SNOMASKS that the server supports
`SNOMASK LISTCURRENT` - List all the SNOMASKS you currently have enabled
`SNOMASK + one[,two,...N]` - Add SNOMASKS to your list
`SNOMASK - one[,two,...N]` - Remove SNOMASKS from your list

`LISTFULL` should give a description of what the SNOMASK does, eg:
````
remoteconnections - Be notified when a connection is established on a remote server
localconnections - Be notified when a connection is established on a local server
localkills....etc
````

With this format we could also 'alias' things, like `connections` could be aliased to both `remoteconnections` and `localconnections` and `kills` could be both `localkills` and `remotekills`

This is just some stuff I've pulled off the top of my head to get the ball rolling so to speak, and to get others to put forth some ideas on this.

Edit :: Reason for moving away from +s is when setting modes you set-over what is currently there. So doing: `+s localkills remotekills` and then wanting to update it later you can't just send `+s localconnections`, you have to send them all.

This poses a problem in the event of not being able to fit them all on one line. With the /SNOMASK command we would not have this problem.

**Comment by attilamolnar** [comment]
I'll consider this when implementing #943.
