### ISSUE TITLE
Extban negating (~ char)

### ISSUE THREAD

**Issue by HelixSpiral** [inspircd/inspircd#800]
I was wondering if it would be possible to negate Extbans similar to charybdis.

For example, we currently have `R:<account>` to match registered users and `U:<nick!user@host>` to match unregistered users.

This would have been cleaner if we had a negate character that allowed us to do something like `~R:*` to match all unregistered users.

Wanting this also partially ties into issue #730, so it might be possible to make `~R:*#somechan` the equivalent of the charybdis `$~a$#somechan`

**Comment by SadieCat** [comment]
This was implemented in dac5288954.
