### ISSUE TITLE
Extended JOIN message not sent when reconnecting user over host change.

### ISSUE THREAD

**Issue by Shizmob** [inspircd/inspircd#821]
When a client connects and successfully negotiates the [extended-join](http://ircv3.org/extensions/extended-join-3.1) capability, all `JOIN` messages to be sent by the server should follow the `extended-join` format of having three parameters: the joined channel(s), the user's account name or an asterisk (`*`), and the user's GECOS.

However, when a user host is changed and the server emits fake `QUIT`/`JOIN` messages to the other clients to allow them to update their internal state, the emitted `JOIN` message is always in plain format, not the extended format:

```
[<redacted>!<redacted>@<redacted>] JOIN ['#<redacted>', '*', '<redacted>']       
[<redacted>!<redacted>@<redacted>] ACCOUNT ['<redacted>']                             
[<redacted>!<redacted>@<redacted>] QUIT ['Changing host']                             
[<redacted>!<redacted>@<redacted>] JOIN ['#<redacted>']         
```

This is in violation of the specification.

**Comment by SaberUK** [comment]
This has now been implemented in the latest 3.0 alpha.
