### ISSUE TITLE
maxquit="0" shows IRC operators regular quit messages but not 'system' (XLine etc.) quit messages

### ISSUE THREAD

**Issue by UselessOper** [inspircd/inspircd#843]
**Regular quit:**

`21:25 *** QUIT: Client exiting: nickname!Male@0.0.0.0 (0.0.0.0) [Quit: lightIRC.com Flash IRC Client]`

**XLine quit:**

`21:20 *** QUIT: Client exiting: nickname!Female@0.0.0.0 (0.0.0.0) []`

**Comment by SaberUK** [comment]
Having looked into the code changes in QuitUser I think that this is fixed in v3. Please respond if this is not the case.
