### ISSUE TITLE
Module to report to opers on channel flood

### ISSUE THREAD

**Issue by theredv** [inspircd/inspircd#858]
Is there an existing module for this? It was default on charybdis.

How it works:
a user floods X lines in N seconds in a channel without operator status and a snotice is sent to all logged in opers.

This is crucial for irc.snoonet.org and would be a great addition

**Comment by SadieCat** [comment]
This was already implemented by someone in contrib. It seems a bit niche to add to the core though.

https://github.com/inspircd/inspircd-contrib/blob/master/3/m_globalmessageflood.cpp
