### ISSUE TITLE
Geoip City AutoJoin

### ISSUE THREAD

**Issue by TuSuNaMi** [inspircd/inspircd#863]
Hello;

I need some module sample if user from Berlin autojoin user to #berlin channel

This is possible

**Comment by SaberUK** [comment]
From what I can see this is not possible with any current open source GeoIP database (GeoIPCity is closed source).

**Comment by SaberUK** [comment]
As there hasn't been any suggestions as to how we could feasibly implement this i'm going to close this issue.
