### ISSUE TITLE
Filter out snomasks for OPER classes.

### ISSUE THREAD

**Issue by Foxboron** [inspircd/inspircd#877]
Currently its either all the snomasks or no snomasks. It would be great to have a new field in the oper `class` block to decide on what snomasks the class can use. To further refine on the information someone receives.

```
<class name="HelloWorld" 
...
chanmodes="*"
snomasks="qkKL">
```

Trying to make an IRC server be as anonymous as possible, but not being able to see link messages when linking leafs, because you want to skip the `cCqQ` masks is annoying.

**Comment by SadieCat** [comment]
Implemented in 6fcbfc0.
