### ISSUE TITLE
Ignore running as root if user is specified in config

### ISSUE THREAD

**Issue by Hello71** [inspircd/inspircd#888]
currently I need to use --runasroot or caps jiggering to have inspircd run as root then drop privileges later.

I need to do this because I want my SSL keys in a central location (/etc/ssl/private) which is only readable by root instead of copying them and making them only readable by inspircd or creating yet another group or using ACLs.

using --runasroot prints an unnecessary large warning and delays startup by 20 seconds for no reason in particular.

**Comment by SadieCat** [comment]
Since v3.5.0 the `--runasroot` option has been a binary switch to allow running as root with no 20 second delay.
