### ISSUE TITLE
Link over unix sockets

### ISSUE THREAD

**Issue by md-5** [inspircd/inspircd#904]
https://github.com/atheme/atheme/issues/307#issuecomment-51672437
https://github.com/atheme/atheme/issues/265#issuecomment-50989086

**Comment by mpotier** [comment]
One use case for this:
  1. You want to have ircd running locally and not exposed to the outside (listening on a UNIX socket)
  1. You have a web client (such as qwebirc) running on the same machine that connects to ircd through the socket

I really wish it were implemented now.

**Comment by attilamolnar** [comment]
@mpotier InspIRCd will have native websocket support instead which will hopefully remove the need for server side gateways like the one required for qwebirc.
