### ISSUE TITLE
bans are open to anyone..

### ISSUE THREAD

**Issue by TurkDesk** [inspircd/inspircd#915]
hide banlist for people not being in the channel by /mode #chan b to get list.. this should not be done with inspircd.conf hidemodes as affect globaly, but should be done in source to affect only people not being in the channel.. the same thing may go with +e +g +I i could not test out..

**Comment by TurkDesk** [comment]
@ShutterQuick the patch should not block opers i think if you can work around that ?

**Comment by Mikaela** [comment]
:-1: as other IRCds allow seeing the ban list from outside and if you or someone you are helping on support channel of network are/is banned, it helps a lot by seeing what ban you mask and who set it so they could be contacted for additional details.

**Comment by NikosPapakonstantinou** [comment]
@Mikaela :+1:
Btw opers can override that setting by default so the patch should handle that case imho.

**Comment by attilamolnar** [comment]
The hidelist module provides this feature.
