### ISSUE TITLE
GeoIP deny doesn't match

### ISSUE THREAD

**Issue by SISheogorath** [inspircd/inspircd#920]
Hi,

got a little bug, geoip did not denied the IP from an User connecting via WebIRC (using cgi). The changed host is not recognized by it. 

<connect deny="*" geoip="TH,TJ,TK,TL,TM,TN,TO,TR,TT,TV,TW,TZ,UA,UG,UM,UY,UZ,VA,VC,VE,VG,VI,VN,VU,WF,WS,YE,YT,ZA,ZM,ZW" reason="You are not allowed to connect from that country!">

\* [Gast55883] is connected from Turkey (TR)

There is no <connect allow> before the deny block. and the IP is not recognized in Stats G so it simply doesn't trigger on IP change. (whois result by m_geoipban).

Greets
Sheo

**Comment by PeLLw** [comment]
Hello everyone

I want to ask if they can help why does not the GEOIP.
It does not work at all. All it installed no errors, but nothing works geoip.

I hope you can answer, thank you very much.

**Comment by SISheogorath** [comment]
Out dated and patch ported to master
