### ISSUE TITLE
m_nationalchars's handling of paths is very inconvenient

### ISSUE THREAD

**Issue by eevee** [inspircd/inspircd#938]
It prepends `../locales/` to whatever I give as a file path.  But when inspircd is [installed system-wide](https://github.com/inspircd/inspircd/blob/0c9a94ea9285d1094c031d0c4ed06326b99cf890/configure#L117), that's relative to `/etc/inspircd`, so it's looking in `/etc/locales`, which is nonsense.

I can give an absolute path, but then I'm sending `CASEMAPPING=/etc/inspircd/locales/foo` back to clients in ISUPPORT, which is also nonsense.

**Comment by attilamolnar** [comment]
This was partially addressed by @SaberUK in #1058, and we have decided to deprecate m_nationalchars in 2.2. See #1062 for more information.
