### ISSUE TITLE
m_securelist exemption for authenticated users

### ISSUE THREAD

**Issue by Shawn-Smith** [inspircd/inspircd#942]
It's a bit annoying for legitimate users to be forced to wait so many seconds seconds before listing, I think there should be an option for those that have authenticated with NickServ to bypass the wait time in listing.

**Comment by GLolol** [comment]
+1

**Comment by SaberUK** [comment]
Speculative untested patch: https://github.com/inspircd/inspircd/compare/master...SaberUK:master+securelist-exempt-registered

**Comment by SaberUK** [comment]
Implemented in 39b51a7c11e384603102c01de1c46c28e7699046.
