### ISSUE TITLE
OpenSSL Read Error Issue

### ISSUE THREAD

**Issue by jdonovan1013** [inspircd/inspircd#962]
After implementing openssl on my instance of inspircd I am unable to connect via IRC client. The debug log provides  the following at each connection attempt:

Mon Jan  5 12:03:11 2015: classbase::~ @0x7fff56046ab0
Mon Jan  5 12:03:11 2015: New file descriptor: 19
Mon Jan  5 12:03:11 2015: Error on FD 19 - 'Read Error'
Mon Jan  5 12:03:11 2015: QuitUser: 136AAAAAA=136AAAAAA 'Read Error'
Mon Jan  5 12:03:11 2015: DoWrite on errored or closed socket
Mon Jan  5 12:03:11 2015: Remove file descriptor: 19
Mon Jan  5 12:03:11 2015: Deleting 9LocalUser @0xd6bcfe0

There does not appear to be any documentation of this error.

**Comment by SaberUK** [comment]
Can you pastebin your configuration files? I think you might be connecting using SSL on a non SSL port (or vice versa).

**Comment by jdonovan1013** [comment]
Listening and connecting on port 6697. Is that not the correct SSL port?

**Comment by SaberUK** [comment]
Ports do not magically support SSL just by loading the SSL module (you need to set `ssl="openssl"` in the bind tag). This is why I asked you to pastebin your configuration files.

**Comment by jdonovan1013** [comment]
Right, see below:
From config file:

<bind
     address="REDACTED"
   
      port="6697"

      type="clients"

      ssl="openssl"
>


From modules.conf 

<openssl certfile="cert.pem" keyfile="key.pem" dhfile="dhparams.pem" sslv3="false" ciphers="HIGH:MEDIUM" compression="false">


Let me know if you any other portions of the configs, I'll have to check them for anything confidential.

**Comment by jdonovan1013** [comment]
This got left out of the last post for some reason:

<
openssl certfile="cert.pem" keyfile="key.pem" dhfile="dhparams.pem" sslv3="false" ciphers="HIGH:MEDIUM" compression="false"
>

**Comment by SaberUK** [comment]
What client are you trying to connect with?

**Comment by jdonovan1013** [comment]
mIRC

**Comment by SaberUK** [comment]
I'm honestly not sure what is wrong. What version of InspIRCd are you using?

**Comment by jdonovan1013** [comment]
InspIRCd-2.0.18(r0)

It's definitely an odd problem. The server works fine without SSL, it's only when I bind the port using openssl.

Take a look at these logs if you don't mind. One of them says that the server should still work, but maybe they're part of the problem. I get these logs when I start the IRCd:

Mon Jan  5 12:39:15 2015: m_ssl_openssl.so: Can't read CA list from /opt/inspircd/run/conf/ca.pem. This is only a problem if you want to verify client certificates, otherwise it's safe to ignore this message. Error: No such file or directory

Mon Jan  5 12:39:15 2015: SSL error: 3154:error:02001002:system library:fopen:No such file or directory:bss_file.c:122:fopen('/opt/inspircd/run/conf/ca.pem','r')

Mon Jan  5 12:39:15 2015: SSL error: 3154:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:125:

Mon Jan  5 12:39:15 2015: SSL error: 3154:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:279:

**Comment by SaberUK** [comment]
Can you try starting with ./inspircd debug (you might need to install gdb) and then pastebinning the *full* log of the server startup.

**Comment by jdonovan1013** [comment]
http://pastebin.com/TAcCWJ2B

**Comment by SaberUK** [comment]
Can you try pastebinning the output of `openssl s_client -connect IPADDRESS:PORT` from the computer you are trying to connect *from*?

**Comment by jdonovan1013** [comment]
I am attempting to connect from a Windows client, so that command will not work I think. However, I did test a couple of other things:
I entered the port and address in a web browser. This yielded some information and other text followed by (Registration Timeout). I was able to view the server's certificate.

I was able to telnet to the address and port.

On the IRC server, I executed the command locally. This yielded a good deal of information about the server and certificate, followed by another Registration Timeout. See below for a portion of the output:

SSL handshake has read 1433 bytes and written 331 bytes
---
New, TLSv1/SSLv3, Cipher is DHE-RSA-AES256-SHA
Server public key is 1024 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : DHE-RSA-AES256-SHA
    Session-ID:
    Session-ID-ctx:
    Master-Key: Redacted
    Key-Arg   : None
    Krb5 Principal: None
    Start Time: 1420483831
    Timeout   : 300 (sec)
    Verify return code: 18 (self signed certificate)
---
There were no errors generated by any of these tests. The attempts are reflected in the logs only as Registration Timeouts; there is no mention of the "Read Errors".

**Comment by jdonovan1013** [comment]
I've just discovered that the server is functional when I connect via a different IRC client. Looks like the issue is client-side.

**Comment by attilamolnar** [comment]
@jdonovan1013 Hello,

The configuration you pasted is wrong. Consider this (from the [m_ssl_openssl wiki page](https://wiki.inspircd.org/Modules/2.0/ssl_openssl):

>  `<openssl:customcontextoptions> - Allows custom context options to be set if true. This is required for the following options to have any effect.`

Otherwise the `sslv3` and `compression` options don't work.

Did you resolve the original issue?
