### ISSUE TITLE
m_timedbans: Duplicate timed ban handling

### ISSUE THREAD

**Issue by Renegade334** [inspircd/inspircd#964]
Currently, if a user attempts to set a timed ban on a channel where the mask is already banned:
* m_timedbans still attempts to process the +b
* because the duplicate ban is not added, `ServerInstance->Modes->GetLastParse()` is empty
* the /TBAN command prints "Invalid ban mask" and fails

What should happen:
* if there is already a matching ban on the specified mask in the given channel, m_timedbans should not process the +b mode, but should still add the timed ban to `TimedBanList`
* if a matching *timed* ban already exists, it should simply update the expiry time of the existing timed ban

**Comment by attilamolnar** [comment]
It is too late to change this behavior in 2.0 and m_timedbans is being deprecated in 2.2 in favor of a generic timed modes module. I wish we could update the "Invalid ban mask" error message at least, but bots may depend on that as well. The best we can do is update the help text in 2.0.

**Comment by attilamolnar** [comment]
I tried to see this for myself and realized the issue only applies to 2.2, and not 2.0 (which has no GetLastParse() check). For 2.2 this should be fixed (of course) in the simplest way possible since m_timedbans is only provided for compatibility in 2.2.

**Comment by Renegade334** [comment]
Would you suggest something simpler? I can't think of anything more reductive than iterating over the channel's banlist for a match.

**Comment by attilamolnar** [comment]
What do you think about `-b+b <mask> <mask>` ?

**Comment by Renegade334** [comment]
Did consider it originally, but then the timed ban list would need to be iterated over in all cases anyway, so the reduction in complexity isn't dramatic.

**Comment by attilamolnar** [comment]
The latest commits to m_timedbans merged in from insp20 should have resolved this. Reopen if you find that it still exists.
