### ISSUE TITLE
JOIN command can fail to join password-protected channels when joining multiple channels at once

### ISSUE THREAD

**Issue by aleth** [inspircd/inspircd#965]
It appears inspircd is happy with

JOIN #ch1 pwd1
JOIN #ch1,#ch2 ,pwd2

but not with

JOIN #ch1,#ch2,#ch3 ,,pwd3

in which case the password-protected channel fails to be joined (server responds with 475 : Cannot join channel (Incorrect channel key)).

**Comment by attilamolnar** [comment]
Can you clarify which channels are the password protected ones in all of these cases?

**Comment by clokep** [comment]
@attilamolnar The numbers correspond, e.g. pwd3 goes with #ch3, pwd2 goes with #ch2.

**Comment by ShutterQuick** [comment]
@clokep 
> It appears inspircd is happy with
>
> JOIN #ch1 pwd1
> JOIN #ch1,#ch2 ,pwd2

Oh? Could you explain a bit closer, in terms of exact input you give, actual output, and expected output? A couple of examples would be neat. It seems to behave like expected to me.

> -> JOIN #Chan1,#Chan2 ,a
> <- :User2!a@localhost JOIN :#Chan1
> <- :server 353 User2 = #Chan1 :@User1 User2 
> <- :server 366 User2 #Chan1 :End of /NAMES list.
> <- :server 475 User2 #Chan2 :Cannot join channel (Incorrect channel key)

Just order the channels so you list those needing a key first. Like:
> -> JOIN #Chan2,#Chan3,#Chan1 a,b
> <- :User2!a@localhost JOIN :#Chan2
> <- :server 353 User2 = #Chan2 :@User1 User2 
> <- :server 366 User2 #Chan2 :End of /NAMES list.
> <- :User2!a@localhost JOIN :#Chan3
> <- :server 353 User2 = #Chan3 :@User1 User2 
> <- :server 366 User2 #Chan3 :End of /NAMES list.
> <- :User2!a@localhost JOIN :#Chan1
> <- :server 353 User2 = #Chan1 :@User1 User2 
> <- :server 366 User2 #Chan1 :End of /NAMES list.

Charybdis and Unreal behaves the same way.

**Comment by aleth** [comment]
@ShutterQuick 

>Oh? Could you explain a bit closer, in terms of exact input you give, actual output, and expected output? A couple of examples would be neat. It seems to behave like expected to me.

The expected behaviour is for the password-protected channel to be successfully joined, regardless of the order of channels in the command. You seem to be able to reproduce the issue even with a single non-protected channel before the password-protected one.

> Just order the channels so you list those needing a key first. Like:

This is indeed the workaround I have just landed. It should, however, not be necessary.
The RFC spec is quite clear for the JOIN syntax, and does not require password-protected channels to be listed first.

> Charybdis and Unreal behaves the same way.

That's hardly a good reason not to follow the spec.

**Comment by aleth** [comment]
For what it's worth, on irc.mozilla.org:

-> JOIN #abcd,#efgh ,key
<- :aleth JOIN :#abcd
<- :server 353 aleth = #abcd :@aleth
<- :server 366 aleth #abcd :End of /NAMES list.
-> MODE #abcd
<- :aleth JOIN :#efgh
<- :server 333 aleth #efgh ...
<- :server 353 ...
<- :server 366 ...
-> MODE #efgh

-> JOIN #ch1,#ch2,#efgh ,,key
<- :aleth JOIN :#ch1
<- :server 353 aleth = #ch1 :@aleth
<- :server 366 aleth #ch1 :End of /NAMES list.
-> MODE #ch1
<- :aleth JOIN :#ch2
<- :server 353 aleth = #ch2 :@aleth
<- :server 366 aleth #ch2 :End of /NAMES list.
-> MODE #ch2
<- :server 475 aleth #efgh :Cannot join channel (Incorrect channel key)

**Comment by attilamolnar** [comment]
Just confirmed that you can't leave out keys on other ircds as well, the join fails in that case.

Using your example on another ircd implementation:
`JOIN #ch1,#ch2,#ch3 ,,pwd3` fails, no channels joined
`JOIN #ch1,#ch2,#ch3 pwd1,,pwd3` joins only `#ch1`
`JOIN #ch1,#ch2,#ch3 pwd1,pwd2,pwd3` joins all three.

**Comment by ShutterQuick** [comment]
@aleth 
I'm not so sure the RFC is so clear.

1459
> Command: JOIN
> Parameters: <channel>{,<channel>} [<key>{,<key>}]

I interpret that as it being invalid to separate blank passwords.
If not I think it would say
> [[key]{,[key]}]

Moreover, the only example I see 1459 give for joining passworded channels and non-passworded channels at the same time is
> JOIN #foo,&bar fubar

**Comment by aleth** [comment]
@ShutterQuick 

I was looking at RFC2812 (http://tools.ietf.org/html/rfc2812#section-3.2.1)
>   Command: JOIN
>   Parameters: ( <channel> *( "," <channel> ) [ <key> *( "," <key> ) ] )
>               / "0"

I take your point - the question is whether <key> can be an empty string. Since there can be channels without passwords, I assumed the answer was obviously "yes", but from the discussion here it seems it's not obvious at all ;)

**Comment by Heufneutje** [comment]
Large parts of RFC2812 aren't really implemented in most modern IRCds. It's mainly RFC1459 IRC developers look at as far as I'm aware.

**Comment by attilamolnar** [comment]
@aleth Can't you fix this client side by sending JOINs where the keyless channels are the last ones? That would work on all/most server implementations. I'm not really in favor of changing behavior to mismatch other servers for no real gain.

**Comment by aleth** [comment]
@attilamolnar Yes, I've already fixed it like that in the client code -- as you point out, we have to do this anyway due to the other servers out there.

**Comment by attilamolnar** [comment]
@aleth Great, thanks for your input on this.
