### ISSUE TITLE
DNS server discovery in /etc/resolv.conf ignores the IPv6 nameserver

### ISSUE THREAD

**Issue by Robby-** [inspircd/inspircd#973]
DNS server discovery in /etc/resolv.conf seems to ignore IPv6 entries such as `nameserver ::1`.

From the log:
`<dns:server> set to '127.0.0.1' as first resolver in /etc/resolv.conf.`

/etc/resolv.conf contents:
`nameserver ::1`
`nameserver 127.0.0.1`

**Comment by SaberUK** [comment]
Possible fix: https://github.com/SaberUK/inspircd/compare/insp20...insp20%2Bipv6-nameserver

**Comment by Robby-** [comment]
Tested and working.
