### ISSUE TITLE
Z-line and insane parse null and zero subnet masks improperly.

### ISSUE THREAD

**Issue by ThatOneRoadie** [inspircd/inspircd#977]
Ver 2.0.18

Insane checks failing on 0 subnet masks:
Expected behavior: Adding a Z-line for 0.0.0.0/0, with an insane configuration of anything less than 100% (in this example, insane is set to 1%), should prevent the Z-line from passing, as it should fail the insane check.

Actual Behavior: Adding a Z-line for 0.0.0.0/0 passes insane after T-line matches the Z-line against 100% of the network.

Z-line parsing improperly:
Expected behavior: Adding a Z-line for "1.2.3.4/" should fail out because of an invalid CIDR mask, and be rejected.

Actual Behavior: Adding Z-line for "1.2.3.4/" passes properly, and is treated as "1.2.3.4/0", matching all users. Related: the resulting Z-line is never checked against insane (no T-line log), and so can match all users.

Oper Logs and insane config line: https://ghostbin.com/paste/sg6dv

**Comment by SaberUK** [comment]
I think the 0.0.0.0/0 issue is because we call `Match` instead of `InspIRCd::MatchCIDR` in the `*MatchesEveryone` functions.

I'm not sure about the second issue. I would guess we aren't doing enough validation before setting the Z-Line.

**Comment by attilamolnar** [comment]
> I think the 0.0.0.0/0 issue is because we call InspIRCd::Match instead of InspIRCd::MatchCIDR in the *MatchesEveryone functions.

Are you going to take a look at this or should I?

**Comment by Adam-** [comment]
"1.2.3.4/" masks no longer match everyone as of 6aaf7047297b739377e7d509cb914f32447fb281.

**Comment by SaberUK** [comment]
>I think the 0.0.0.0/0 issue is because we call InspIRCd::Match instead of InspIRCd::MatchCIDR in the *MatchesEveryone functions.

This has been fixed as of 1bdf114d37a2932138196d3438eddd30bf9d73a2. Please reply if you are still having issues and i'll reopen the issue.
