### ISSUE TITLE
Merge m_muteban and m_nopartmsg

### ISSUE THREAD

**Issue by Googolplexed** [inspircd/inspircd#979]
As brought up in https://github.com/shalture/shalture/issues/45, m_muteban and m_nopartmsg seem like they are less than useful independantly

+p/m_nopartmsg would probably have to be kept as a dummy mode to preserve linking compatibility, but otherwise I don't see any issues with rolling the functionality into m_muteban ?

**Comment by SaberUK** [comment]
I'm not so sure about this. We don't restrict normally banned users from having a part message so it would be inconsistent to do so with this module.

I propose that we extract `<security:restrictbannedusers>` from the core into a module and then make it filter part messages which would replace m_nopartmsg.

**Comment by MandL27** [comment]
That sounds like a better idea. In unreal at least, bans are effectively channel shuns.

**Comment by SaberUK** [comment]
This is basically what i'm proposing (untested): https://github.com/SaberUK/inspircd/compare/inspircd:master...SaberUK:master%2Brestrictbannedusers

**Comment by MandL27** [comment]
I'm no dev, but I say go for it. Seems like it'd be more user-friendly this way.

**Comment by Googolplexed** [comment]
As mentioned in IRC last night, I agree with SaberUK's reasoning

**Comment by B00mX0r** [comment]
Does that code solve for ignoring part messages on mute bans as well as normal bans? It doesn't look like it from what I can see. Also, as an FYI, the header date is 2014 instead of 2015.

**Comment by attilamolnar** [comment]
> As brought up in shalture/shalture#45, m_muteban and m_nopartmsg seem like they are less than useful independantly

What about using m_muteban with `<options fixedpart="">`?

**Comment by Googolplexed** [comment]
When in that configuration, m_nopartmsg becomes worthless anyway, as its job is effectively being done in the core for everyone.

**Comment by attilamolnar** [comment]
Sorry for being ambiguous, I meant fixedpart with a non-empty message (updated previous post). In that case, if m_muteban clears the part messages of mutebanned users it will also clear the fixedpart message which is not the case with the current m_muteban

**Comment by B00mX0r** [comment]
The current m_muteban doesn't do anything to part messages.

**Comment by antoligy** [comment]
Technically all modules used to silence any part of what a user may choose to do should be merged with this logic?

Would it make more sense to introduce unified cmodes where multiple modules can subscribe to them?

**Comment by KeiroD** [comment]
@antoligy *personally*, I would agree with introducing unified cmodes where multiple modules can subscribe to them.

Setting it up that way further extends the modularity that is Inspircd.
