### ISSUE TITLE
SQL in utf-8

### ISSUE THREAD

**Issue by flopraden** [inspircd/inspircd#980]
Hi, 

I loaded the nationalchar for utf-8 and utf-8 sqlauth isn't working since the MySQL connection wasn't configured for utf-8

Here the patch to add an option for character-set.
It may be interessant to put it for others SQL drivers

-- 
Best
```
--- a/src/modules/extra/m_mysql.cpp
+++ b/src/modules/extra/m_mysql.cpp
@@ -255,6 +255,12 @@ class SQLConnection : public SQLProvider
                bool rv = mysql_real_connect(connection, host.c_str(), user.c_str(), pass.c_str(), dbname.c_str(), port, NULL, 0);
                if (!rv)
                        return rv;
+               // enable character-set settings
+               std::string characterset;
+               if (config->readString("characterset", characterset))
+               {
+                 mysql_set_character_set(connection,characterset.c_str());
+               }
                std::string initquery;
                if (config->readString("initialquery", initquery))
                {
```

**Comment by SaberUK** [comment]
Can you file a pull request?

**Comment by ShutterQuick** [comment]
Also it might be a bat idea to ignore the result of mysql_set_character_set()
At the very least log a warning on failure

**Comment by flopraden** [comment]
Hi, 

I've done it and add a line to report error on mysql_set_character_set.

-- 
Best

**Comment by flopraden** [comment]
close in https://github.com/inspircd/inspircd/pull/981
