### ISSUE TITLE
m_xline_db and m_permchannels: Improper location verification of data directory

### ISSUE THREAD

**Issue by B00mX0r** [inspircd/inspircd#982]
m_xline_db and m_permchannels both use the data directory for their databases. However, they're unable to distinguish whether or not InspIRCd was started via "./inspircd start" or "./bin/inspircd". As a result, if InspIRCd is started via "./bin/inspircd", it'll try and use "bin/data" rather than "./data", which results in this:

*** ANNOUNCEMENT: database: cannot create new db: No such file or directory (2)

Ubuntu 14.04.1, InspIRCd 2.0.19 (latest code in insp20 branch).

**Comment by SaberUK** [comment]
This has been fixed in master. Unfortunately you'll need to specify an absolute path in insp20 though.

**Comment by B00mX0r** [comment]
Thanks
