### ISSUE TITLE
[2.0] Occasional 401 on /PRIVMSG ~#chan

### ISSUE THREAD

**Issue by B00mX0r** [inspircd/inspircd#987]
When doing /PRIVMSG ~#chan, the server will sometimes return a 401 (Channel not found) for "~#chan". I'm able to replicate this behavior on my network, a different public network, and the latest insp20 source (with chanprotect loaded of course). Oddly enough, it's as though it only happens for certain users on certain channels. On a channel I created for testing this with two users, the bug didn't occur. When I created another one, it happened for one user but not the other. It still happened just for this one user after reconnecting.

It's a really weird bug. I have no idea what's causing it, so I can't give you more than what I've observed. Be careful when trying to find it, since I can assure you that it's not a "worksforme" (I looked into it because somebody reported it on a different network's #help channel). Note that debug showed nothing.

**Comment by Renegade334** [comment]
* ~ is a valid channel prefix on some networks.
* ~ may have special relevance to clients, bouncers etc. (for example, ZNC will probably intercept this)

**Comment by SaberUK** [comment]
Can you provide the following information:

1. InspIRCd version
2. Client name and version
3. The channel name which the user was trying to PRIVMSG.
4. The value of the STATUSMSG token your server is sending to clients.

P.S. This is unrelated to the problem but you probably want to use customprefix instead of chanprotect/halfop as the latter has been removed in the master branch.

**Comment by attilamolnar** [comment]
@B00mX0r Please supply a /MODULES list from an affected server

**Comment by B00mX0r** [comment]
http://pastebin.com/PjYKSvB1

**Comment by attilamolnar** [comment]
You said you successfully reproduced this on some channels but not on others, what channel names were you trying exactly? You also mentioned this issue occuring on a public network, which one is that? I'd like to see this happening. Thanks.

**Comment by B00mX0r** [comment]
The channel I experienced it on was #b00mx0r. The public network was irc.tl (where Renegade is). I haven't responded yet because I was waiting to ask the user who reported it in #help which channel they were on.

**Comment by Renegade334** [comment]
inspircd never sends the text "Channel not found" with a 401 numeric. That applies both to insp20 and master.

A possible source might be [ZNC's partyline](https://github.com/znc/znc/blob/f47e8465efa4e1cd948b9caae93ac401b4355df8/modules/partyline.cpp#L466) which does intercept all PRIVMSGs to targets starting with a ~ character.

**Comment by Renegade334** [comment]
> 401 (Channel not found)

Is that 401 message verbatim?

I would suggest that a possible source might be [ZNC's partyline](https://github.com/znc/znc/blob/f47e8465efa4e1cd948b9caae93ac401b4355df8/modules/partyline.cpp#L466) which does intercept all PRIVMSGs to targets starting with a ~ character. That would explain why the same command has different effects for different users.

**Comment by SaberUK** [comment]
@B00mX0r Can you verify whether you are using ZNC?

**Comment by attilamolnar** [comment]
Please reopen once confirmed this occurs in the scenario described by @SaberUK.
