### ISSUE TITLE
Inspircd & kiwiIRC work together?

### ISSUE THREAD

**Issue by Chrysweel** [inspircd/inspircd#996]
Hello.

I do not know where to put this issue, but I am crazy this problem. I put it here to see if anyone else has tried.

I have inspircd and irc client kiwiIRC (https://github.com/prawnsalad/KiwiIRC/)

But I have a problem.
Some users are connected even after you close the browser.

I have inspircd and KiwiIRC with config by default.

I think that problem is : inspircd not throw the user disconnection event or kiwiIRC not collect that event to close the connection.

Has anyone tried inspircd and kiwiIRC together?

Thanks by advance.

**Comment by Mikaela** [comment]
I have only used kiwiirc.com instance without issues (except that the confirmation message didn't appear for some reason and the bot connected and disconnected immediately, but I was given the manual code).

I am not sure which has the issue, but @prawnsalad might still be interested.

**Comment by Chrysweel** [comment]
Yes @Mikaela I opened a issue in project KiwiIRC . https://github.com/prawnsalad/KiwiIRC/issues/671

I dont know where is the problem ! :_(

**Comment by Sheogorath-SI** [comment]
I don't think it's anything about inspircd because it doesn't handle kiwiirc in another way then any other connection. You should checkout what browsers these users sure using and then check why connection does not expire in kiwiirc

**Comment by SaberUK** [comment]
It should be supported (it's no different to any other client) but without logs we can't say either way. It's probably a KiwiIRC misconfiguration/bug though rather than an InspIRCd one.

**Comment by attilamolnar** [comment]
Hello, as pointed out by previous commenters, this is likely not an inspircd issue. If you believe it is an inspircd issue please reopen and attach debug logs of inspircd.

**Comment by Chrysweel** [comment]
Ok thanks ! I'll do it if necessary.
